### ISSUE TITLE
Configurable products with different child prices were marked as discounted products

### ISSUE THREAD

**Issue by henkvalk** [Smile-SA/elasticsuite#2823] opened 2023-01-17 16:52 UTC
### Preconditions

Magento Version : 1.4.5-p1 CE

ElasticSuite Version : 1.10.12.1

Environment : developer

Third party modules : 

### Steps to reproduce

1. create configurable product
2. add sizes with different prices
3. 

### Expected result

1. only products that have a discount

### Actual result

1. discounted products and the configurable products with different prices

**Comment by romainruaud** [comment] 2023-01-17 16:54
Hi,

this one is a duplicate of #866 

There is a workaround in PR https://github.com/Smile-SA/elasticsuite/pull/2677/

Regards

**Closed by romainruaud** 2023-01-17 16:54 UTC

**Comment by lukutisz** [comment] 2023-02-09 12:23
In Magento 2.4.5-p1 and ElasticSuite 2.10.12

This workaround is not working https://github.com/Smile-SA/elasticsuite/pull/2677 , I am getting errors:

`Type Error occurred when creating object: Smile\ElasticsuiteCatalog\Model\Product\Indexer\Fulltext\Datasource\PriceData, Smile\ElasticsuiteCatalog\Model\Product\Indexer\Fulltext\Datasource\PriceData::__construct(): Argument #2 ($attributeResourceModel) must be of type Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\AttributeData, array given, called in /home/s/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121`

So right now in virtual categories by selecting Only discounted products we are not getting configurable products
