### ISSUE TITLE
Setting an attribute to used_for_sort_by removes it from layered navigation

### ISSUE THREAD

**Issue by rikwillems** [Smile-SA/elasticsuite#481] opened 2017-07-31 09:05 UTC
We want to sort our categories by an attribute called  cartridge_type. If I check the used_for_sort_by option on this attribute the attribute shows up to sort by. But, now the attribute isn't in the layered navigation anymore.

**Comment by romainruaud** [comment] 2017-08-01 13:42
Hello @rikwillems 

Could you give me more details about your installation ? Especially : 

- which version of Magento (exact version, and precise if CE or EE)

- which version of Elasticsuite (exact version)

- all configuration of your attribute (what you have in eav_attribute and catalog_eav_attribute tables for this attribute, or a screenshot of this attribute configuration if you are not able to see what you have in the DB tables).

I do not reproduce your issue on my instance, so for now I am unable to afford more help for your issue.

**Comment by rikwillems** [comment] 2017-08-01 13:57
Hi @romainruaud

Please find my details below. Please let me know if you need more information.

Magento CE 2.1.7
Elasticsuite 2.3.6

![schermafbeelding 2017-08-01 om 15 56 42](https://user-images.githubusercontent.com/5927342/28828770-14896ac0-76d2-11e7-8587-f032f892c67d.png)
![schermafbeelding 2017-08-01 om 15 56 58](https://user-images.githubusercontent.com/5927342/28828771-1489812c-76d2-11e7-9004-a9d34fbdb011.png)

**Comment by rikwillems** [comment] 2017-08-03 13:49
Dear @romainruaud it appears to be an indexing issue. After enabling all active products in the catalog grid (so no effective change) the layered navigation and sorting work together.

Now I find another strange thing, the totals in the filters don't match the products that are supposed to be there. They do match after the previous action. But don't match anymore after index from the command line.

**Comment by romainruaud** [comment] 2017-08-09 12:26
@rikwillems according to your last comment "enabling all active products fixes the problem", I'm pretty sure you have corrupted data.

Is it a migration from previous Magento 1.x store data ?

Which kind of products are you using ? configurables ? simple ? mix of both ?

Regards

**Comment by rikwillems** [comment] 2017-08-09 14:45
@romainruaud It is a fresh M2 installation. It is filled through import though, not manually. I already configured a new Elasticsearch index which didn't fix the issue.

To be short. Indexing through the console creates wrong count of products and filter options. Activating products in the backend grid (although already activated) solves the counts.

**Comment by romainruaud** [comment] 2017-08-09 14:52
Please give me more details like : 

- is it a multiple website/stores environment ?
- which kind of products you are using : simples and/or configurable, or even bundle or grouped products.

If you have a production website where I can see the bug occuring, please let me know.

If this is not possible, please attach several screenshots to detail the steps you are doing and what is "wrong" about the count of products you see. (Is it wrong against the value you see in the back office ? Is it wrong because you click on a filter showing "X" number of items and then you arrive on a page where only "Y" items are listed ?).

Regards

**Comment by rikwillems** [comment] 2017-08-09 15:03
It is single store and only simple products. 

This project is in development so not available publically. I can give you details, on what address can I PM you?

**Comment by romainruaud** [comment] 2017-08-29 09:16
I close this one since it seems to be strongly related to your data, and not due to Elasticsuite.

Feel free to reopen it if you have more details.

best regards

**Closed by romainruaud** 2017-08-29 09:16 UTC
Labels: needs update
