### ISSUE TITLE
Registry key "applied_virtual_root_category" already exists

### ISSUE THREAD

**Issue by duckchip** [Smile-SA/elasticsuite#2829] opened 2023-01-24 11:11 UTC
Hi guys,

We noticed the following run time exception in our logs. Nothing broken on the frontend but we do get the logs in our sentry setup

Thanks in advance!
### Preconditions

Magento Version : 2.4.5-p1

ElasticSuite Version : 2.10.12.1

Environment : production

Third party modules : /

### Steps to reproduce

1. Visit a product detail page

### Expected result

1. no errors in log

### Actual result

```
RuntimeException: Registry key "applied_virtual_root_category" already exists in /var/www/shop/magento2/releases/20230112T093756630340/vendor/magento/framework/Registry.php:60
Stack trace:
#0 /var/www/shop/magento2/releases/20230112T093756630340/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/VirtualCategory/Root.php(79): Magento\Framework\Registry->register()
#1 /var/www/shop/magento2/releases/20230112T093756630340/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Controller/Router.php(106): Smile\ElasticsuiteVirtualCategory\Model\VirtualCategory\Root->setAppliedRootCategory()
#2 /var/www/shop/magento2/releases/20230112T093756630340/vendor/magento/framework/App/FrontController.php(144): Smile\ElasticsuiteVirtualCategory\Controller\Router->match()
#3 /var/www/shop/magento2/releases/20230112T093756630340/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#4 /var/www/shop/magento2/releases/20230112T093756630340/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#5 /var/www/shop/magento2/releases/20230112T093756630340/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#6 /var/www/shop/magento2/releases/20230112T093756630340/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
#7 /var/www/shop/magento2/releases/20230112T093756630340/vendor/baldwin/magento2-module-recaptcha/Plugin/Predispatch.php(134): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#8 /var/www/shop/magento2/releases/20230112T093756630340/vendor/magento/framework/Interception/Interceptor.php(135): Baldwin\Recaptcha\Plugin\Predispatch->aroundDispatch()
#9 /var/www/shop/magento2/releases/20230112T093756630340/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(71): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#10 /var/www/shop/magento2/releases/20230112T093756630340/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch()
#11 /var/www/shop/magento2/releases/20230112T093756630340/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#12 /var/www/shop/magento2/releases/20230112T093756630340/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#13 /var/www/shop/magento2/releases/20230112T093756630340/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#14 /var/www/shop/magento2/releases/20230112T093756630340/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#15 /var/www/shop/magento2/releases/20230112T093756630340/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent()
#16 /var/www/shop/magento2/releases/20230112T093756630340/app/code/Lochting/Sentry/Plugin/GlobalExceptionCatcher.php(33): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#17 /var/www/shop/magento2/releases/20230112T093756630340/vendor/magento/framework/Interception/Interceptor.php(135): Lochting\Sentry\Plugin\GlobalExceptionCatcher->aroundLaunch()
#18 /var/www/shop/magento2/releases/20230112T093756630340/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#19 /var/www/shop/magento2/releases/20230112T093756630340/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http\Interceptor->___callPlugins()
#20 /var/www/shop/magento2/releases/20230112T093756630340/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#21 /var/www/shop/magento2/releases/20230112T093756630340/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
```

**Comment by vahonc** [comment] 2023-01-24 14:04
Hello @duckchip,

Your issue can be a duplicate of this [issue](https://github.com/Smile-SA/elasticsuite/issues/2817) or smth similar.

Have you use some crawlers (Bingbot, etc)? 

BR,
Vadym

**Comment by duckchip** [comment] 2023-01-24 16:33
hi @vahonc

Thanks for linking the issue, I wasn't sure whether it was already reported.

This error was not caused by a crawler, but by a valid user with user Agent `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.5304.87 Safari/537.36` and on a Mac OS operating system

**Comment by Nuranto** [comment] 2023-01-27 09:40
Hi,

Same thing here :

Magento 2.4.5-p1
ElasticSuite 2.10.12.1

**Comment by PaulEmich** [comment] 2023-02-07 20:49
Problem is caused since this commit:
https://github.com/Smile-SA/elasticsuite/commit/81a08217528fb73b8332248313b8fd31d359c4c2

In our case the router hits multiple times on a 404 page. `setAppliedRootCategory` is called even when no category is found.

**Comment by vahonc** [comment] 2023-02-15 12:04
Hello guys!

I was not able to reproduce this issue on my test environment: Magento 2.4.5-p1 EE with default sample data and ElasticSuite 2.10.12.1. From out of the box there're no errors in logs or during visiting a product detail page. Also, I've created a few test categories, some of them were virtual, but still didn't notice any errors. 

Probably the reasons that cause this issue are quite specific to your projects. In particular, for example: do you use virtual categories, how exactly do you use them, how are they configured, what rules or conditions do you use, etc? Therefore, in order to understand this problem, we need more information from you that can help us to reproduce it.

@PaulEmich, commit [81a0821](https://github.com/Smile-SA/elasticsuite/commit/81a08217528fb73b8332248313b8fd31d359c4c2) was a part of fixing of [carzy URLs begaviour](https://github.com/Smile-SA/elasticsuite/issues/2628) issue. And with your changes, which essentially dismiss our fixes, this bug will be relevant again, so we can't merge it as is.

BR,
Vadym

**Comment by PaulEmich** [comment] 2023-02-15 12:11
@vahonc visting a PDP doesn't cause any issues but visiting a 404 page does. Try to go to https://localhost/non-existing-page and you should see the error created.

I have not tested my changes for the #2628 issue, perhaps I could look into that issue someday. I'd say the problem is more in the `getCategoryRewrite` method than the actual match function. In the end we should return null anyway if no match found.

**Comment by vahonc** [comment] 2023-02-15 12:43
@PaulEmich, even if I go to https://localhost/non-existing-page, which leads to the No Route page as I expected, there are no errors on the page or in logs. But you're right in some specific cases the problem could be in the getCategoryRewrite. 

Anyway, we will be apricated if you will have time to look into your PR and testing [#2628](https://github.com/Smile-SA/elasticsuite/issues/2628l) issue on your environment. 

BR,
Vadym

**Comment by PierreGauthier** [comment] 2023-03-02 09:29
Hello @duckchip @PaulEmich,

I do not successfully reproduce this bug. But I think it can be linked to custom router configuration or some case where magento creates a forward request that might run this code twice.
As said @vahonc, we could not merge your PR as it is @PaulEmich because it can make another bug reappear.
In the PR https://github.com/Smile-SA/elasticsuite/pull/2860/files, I propose another way to handle the specific cases where we need to run this code twice.

**Closed** 2023-03-02 16:39 UTC

**Comment by vrajeshpatel4u** [comment] 2023-03-06 06:40
Hello, 

How to upgrade this extension with this fixation ? 

I have tried below commands but still getting same error. 

_composer require smile/elasticsuite ~2.10.13.3_

**Comment by Bashev** [comment] 2023-03-06 08:20
@vrajeshpatel4u it's not released as version yet. If you want you can get dev-2.10.x as version, but for production my suggestion is to wait for the release.

**Comment by vrajeshpatel4u** [comment] 2023-03-06 09:03
Thank you for update.
