### ISSUE TITLE
Pagination / Sorting not working

### ISSUE THREAD

**Issue by mounish** [Smile-SA/elasticsuite#268] opened 2016-12-29 12:40 UTC
Hello Team, 

I have installed the plugin on base magento 2.1.2 EE with sample data, and installed elasticsuite plugin and it worked perfectly.

Followed the same steps on my website which already has few customizations and theme design done. The plugin works well loading the search results and listing the category products. 

But while i try to go to page 2 : it shows no **We can't find products matching the selection.**

Also sorting doesnt work. 

No major customization except few design changes have been done to catalog part. 

Have even disabled Category / Product flat tables still no luck.

Unable to start debugging or not getting idea of how to sort it.

Can anyone help out sorting the issue ?

Regards
Mounish

**Comment by mounish** [comment] 2016-12-29 13:44
Seems issue at our custom design level. 

Found the working from one of the closed issues. And following link : https://github.com/magento/magento2/issues/7253 got to know that magento has few limitations in setting up the toolbar.

Thankyou.

**Comment by mounish** [comment] 2016-12-30 12:15
Hello Team,

Please if anyone can help on the same ?

**Comment by Koc** [comment] 2017-01-03 16:59
@mounish see #249, looks like this is same issue

**Comment by afoucret** [comment] 2017-01-04 09:08
Hi @mounish,

@koc is right, this is a duplicate of #249.
You need to pay attention about design update and especially about the toolbar block modifications.
You can read the full detail in #249 but it is not related with ElasticSuite but with Magento.

As being a duplicate and not related to ElasticSuite, I close this one.

**Closed by afoucret** 2017-01-04 09:08 UTC

**Comment by mounish** [comment] 2017-01-04 09:12
Hello Team,

Cracked the issue today in morning. 

We had done a small customization in 2column-left.xml to display the layered navigation on top instead of bottom. Which was the actual culprit. We reverted that from before to after and module started working fluently. 

Thanks for the help.

Regards
Mounish

**Comment by arulkec** [comment] 2020-02-06 10:31
I also have the same issue can you please update what changes need to do?

**Comment by mounish** [comment] 2020-02-06 11:12
@arulkec : 

We had done a small customisation in 2column-left.xml to display the layered navigation on top instead of bottom. Which was the actual culprit. We reverted that from before to after and module started working fluently. 

Try reverting the changes to base Magentos settings it should help you !

**Comment by arulkec** [comment] 2020-02-06 11:26
Thank you for reply 
This is my 2column-left.xml.I am struggling for pas 1week. Can you help me out what to chnage
```
<layout xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_layout.xsd">
    <container name="root">
        <container name="after.body.start" as="after.body.start" before="-" label="Page Top"/>
        <container name="page.wrapper" as="page_wrapper" htmlTag="div" htmlClass="page-wrapper">
            <container name="global.notices" as="global_notices" before="-"/>
            <container name="main.content" htmlTag="main" htmlId="maincontent" htmlClass="page-main container">
                <container name="columns.top" label="Before Main Columns"/>
                <container name="columns" htmlTag="div" htmlClass="columns layout layout-1-col row">
                    <container name="main" label="Main Content Container" htmlTag="div" htmlClass="col-main col-lg-9 col-md-9 col-sm-9 col-xs-12" after="-"/>
                </container>
            </container>
            <container name="page.bottom.container" as="page_bottom_container" label="Before Page Footer Container" after="main.content" htmlTag="div" htmlClass="page-bottom"/>
            <container name="before.body.end" as="before_body_end" after="-" label="Page Bottom"/>
        </container>
    </container>
    <referenceContainer name="page.wrapper">
        <container name="header.container" as="header_container" label="Page Header Container"  htmlTag="header" htmlClass="header-container header header-default" before="main.content"/>
        <container name="slideshow.container" as="slideshow_container" label="Slideshow Container" after="header.container"/>
        <container name="page.top" as="page_top" label="After Page Header" after="header.container"/>
        <container name="footer-container" as="footer" before="before.body.end" label="Page Footer Container" htmlTag="footer" htmlClass="page-footer footer default" />
    </referenceContainer>
    <referenceContainer name="columns">
		<container name="col.left.sidebar" label="Col Left Sidebar" htmlTag="div" htmlClass="col-lg-3 col-md-3 col-sm-3 col-xs-12">
			<container name="div.sidebar.main" htmlTag="div" htmlClass="sidebar sidebar-main-1" before="main">
				<container name="sidebar.main" as="sidebar_main" label="Sidebar Main"/>
			</container>
			<container name="div.sidebar.additional" htmlTag="div" htmlClass="sidebar sidebar-additional1 hidden-xs" after="div.sidebar.main">
				<container name="sidebar.additional" as="sidebar_additional" label="Sidebar Additional"/>
			</container>
        </container>
    </referenceContainer>
</layout>
```

**Comment by gaiterjones** [comment] 2020-08-11 15:23
@arulkec @mounish I am testing elasticsuite with Magento 2.3.3 and the porto theme. In search and product list pagination is not working, all products are displayed. Is this a known problem with custom themes? Does anyone have a solution to resolve it as elasticsuite is not useable for me like this.
