### ISSUE TITLE
Products empty on virtual category

### ISSUE THREAD

**Issue by tschirmer** [Smile-SA/elasticsuite#2301] opened 2021-10-15 04:51 UTC
### Preconditions

Magento Version : 2.4.3-p1

ElasticSuite Version : 2.10.6

Environment : production

Third party modules : Storebase custom developed modules

### Steps to reproduce

1. setup new category
2. enable virtual category
3. set category root as Products
4. set virtual rule (in this case we're using "Attribute Set"  = "OurCustomAttributeSet"

### Expected result

1. products should appear in virtual category

### Actual result

1.
Products dont show, and the following is presented:
 [Screenshot, logs]
[2021-10-14 22:03:42] main.CRITICAL: Warning: call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Helper/Rule.php on line 67 {"report_id":"403453dffe717ce26fd1ced14fe0a4cdffda7a22f9614388534f42cfab5ad43d","exception":"[object] (Exception(code: 0): Warning: call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Helper/Rule.php on line 67 at /var/www/html/vendor/magento/framework/App/ErrorHandler.php:61)"} []

**Comment by romainruaud** [comment] 2021-10-21 13:30
Seems to be a duplicate of #1985 

The usual suspect for this one was the fact that somewhere on the page a category gets loaded through a categoryFactory (which is bad) instead of being loaded through the categoryRepository.

**Comment by romainruaud** [comment] 2022-02-28 10:56
any news on this one @tschirmer ?

**Comment by tschirmer** [comment] 2022-03-21 08:22
We found this was caused by accidently using an older di.xml than what was packaged. I'll mark it as resolved with no action on your part.

**Closed** 2022-03-21 08:22 UTC
