### ISSUE TITLE
Wrong assignment on "is_discount" if configurable product has one child with a price increment

### ISSUE THREAD

**Issue by CRYX2** [Smile-SA/elasticsuite#1645] opened 2019-12-18 13:36 UTC
Magento Version : 2.3.3 CE
ElasticSuite Version : 2.4
Environment : Production

### Steps to reproduce
1. Create a new configurable product
2. Create two variations, one with a price increased
3. Create a new virtual category with a virtual rule: "Only discounted products"
4. Reindex

### Expected result
1. Category should NOT show the configurable product

### Actual result
1. Configurable product is displayed

The problem is in the PriceConfigurable class:

```
<?php
/**
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Smile ElasticSuite to newer
 * versions in the future.
 *
 * @category  Smile
 * @package   Smile\ElasticsuiteCatalog
 * @author    Aurelien FOUCRET <aurelien.foucret@smile.fr>
 * @copyright 2019 Smile
 * @license   Open Software License ("OSL") v. 3.0
 */

namespace Smile\ElasticsuiteCatalog\Model\Product\Indexer\Fulltext\Datasource\PriceData;

/**
 * Price data parser used for most configurable products.
 *
 * @category Smile
 * @package  Smile\ElasticsuiteCatalog
 * @author   Aurelien FOUCRET <aurelien.foucret@smile.fr>
 */
class PriceConfigurable implements PriceDataReaderInterface
{
    /**
     * {@inheritDoc}
     */
    public function getPrice($priceData)
    {
        return $priceData['min_price'];
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginalPrice($priceData)
    {
        return $priceData['max_price'];
    }
}
```

**Comment by romainruaud** [comment] 2020-01-08 10:39
Duplicate of #866 for me.

Unfortunately, there is not much we can do considering how the data is structured into the price index table in my opinion.

**Closed by romainruaud** 2020-01-08 10:39 UTC
