### ISSUE TITLE
Error when in Catalog > Catagories

### ISSUE THREAD

**Issue by crantron** [Smile-SA/elasticsuite#636] opened 2017-11-29 00:27 UTC
`A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.` Is the error that displays on the Catalog->Category Page

### Preconditions
 - Centos 7.5
 - Php 7.1
 - Mysql 5.6
 - Elastic search ^2.4
 - Magento CE 2.2.1

Environment : Developer

Third party modules :
 - FishPig Wordpress Magento 2 Integration

### Steps to reproduce

1. Fresh Install
2. Navigate to Catalog -> Categories
3. Click on `Default Category`

### Expected result
1. No error should display

### Actual result
1. `A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.` display

### Error.log

```
Wed Nov 29 00:12:07.923005 2017] [:error] [pid 15700] [client 10.10.10.1:50949] PHP Fatal error:  
Uncaught Error: Call to a member function getCategorySearchQuery() on null in /home/vagrant/public_html/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Preview.php:199
Stack trace:
#0 /home/vagrant/public_html/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Preview.php(107): Smile\\ElasticsuiteVirtualCategory\\Model\\Preview->getQueryFilter()
#1 /home/vagrant/public_html/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Preview.php(128): Smile\\ElasticsuiteVirtualCategory\\Model\\Preview->getProductCollection()
#2 /home/vagrant/public_html/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Preview.php(91): Smile\\ElasticsuiteVirtualCategory\\Model\\Preview->getUnsortedProductData()
#3 /home/vagrant/public_html/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Controller/Adminhtml/Category/Virtual/Preview.php(71): Smile\\ElasticsuiteVirtualCategory\\Model\\Preview->getData()
#4 /home/vagrant/public_html/generate in /home/vagrant/public_html/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Preview.php on line 199, referer: http://cremocompany.dev/cremo_admin/catalog/category/index/key/9d742fc8c5f9a57263ea002c7dc04545b33f121fab1e1d68f32f181f8486e7d9/

[Wed Nov 29 00:12:09.968010 2017] [:error] [pid 15701] [client 10.10.10.1:50954] PHP Fatal error:  
Uncaught Error: Call to a member function getCategorySearchQuery() on null in /home/vagrant/public_html/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Preview.php:199
Stack trace:
#0 /home/vagrant/public_html/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Preview.php(107): Smile\\ElasticsuiteVirtualCategory\\Model\\Preview->getQueryFilter()
#1 /home/vagrant/public_html/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Preview.php(128): Smile\\ElasticsuiteVirtualCategory\\Model\\Preview->getProductCollection()
#2 /home/vagrant/public_html/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Preview.php(91): Smile\\ElasticsuiteVirtualCategory\\Model\\Preview->getUnsortedProductData()
#3 /home/vagrant/public_html/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Controller/Adminhtml/Category/Virtual/Preview.php(71): Smile\\ElasticsuiteVirtualCategory\\Model\\Preview->getData()
#4 /home/vagrant/public_html/generate in /home/vagrant/public_html/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Preview.php on line 199, referer: http://cremocompany.dev/cremo_admin/catalog/category/index/key/9d742fc8c5f9a57263ea002c7dc04545b33f121fab1e1d68f32f181f8486e7d9/
```

**Comment by afoucret** [comment] 2017-11-30 08:48
Did you run the setup:upgrade process after you have clean your caches ?
Then you have to reindex everything ?

**Comment by crantron** [comment] 2017-12-08 18:43
Yup, I followed the instructions exactly. I just ended up uninstalling it.

**Comment by afoucret** [comment] 2017-12-11 07:45
It is sad that you uninstall it and can not enjoy benefits of ElasticSuite.
As you don't have an environment to test it anymore, we will not be able to see what happen and I have to close the issue.

Feel free to reopen if you want to give a try again at ElasticSuite and the issue is still present.

BR,

**Closed by afoucret** 2017-12-11 07:45 UTC
Labels: needs update
