### ISSUE TITLE
Catalogsearch product by name

### ISSUE THREAD

**Issue by ngocdb** [Smile-SA/elasticsuite#514] opened 2017-08-28 08:31 UTC
Hello,

I am using ElasticSuite with Magento 2 CE 2.1.8. 

I created a "Test Product" & when I search "test" (/catalogsearch/result/?q=test), no products is returned though you can see I have a matched product.

The query is something as below. The part I feel confused is about query multi match, where we have something likes
```
                                                            [multi_match] => Array
                                                                (
                                                                    [query] => test
                                                                    [fields] => Array
                                                                        (
                                                                            [0] => spelling.whitespace^10
                                                                        )
                                                                    [minimum_should_match] => 100%
                                                                    [tie_breaker] => 1
                                                                    [boost] => 1
                                                                    [type] => best_fields
                                                                    [cutoff_frequency] => 0.15
                                                                    [fuzziness] => AUTO
                                                                    [prefix_length] => 1
                                                                    [max_expansions] => 10
                                                                )

```

How can I know if the "name" of product is including in the search ?, or what settings I should do for the name ?, or may be description after.

```
Array
(
    [index] => magento2_default_catalog_product
    [type] => product
    [body] => Array
        (
            [from] => 0
            [size] => 0
            [sort] => Array
                (
                    [0] => Array
                        (
                            [_score] => Array
                                (
                                    [order] => desc
                                    [missing] => _first
                                    [unmapped_type] => string
                                )
                        )
                    [1] => Array
                        (
                            [] => Array
                                (
                                    [order] => desc
                                    [missing] => _first
                                    [unmapped_type] => string
                                )
                        )
                )
            [query] => Array
                (
                    [filtered] => Array
                        (
                            [filter] => Array
                                (
                                    [bool] => Array
                                        (
                                            [must] => Array
                                                (
                                                    [0] => Array
                                                        (
                                                            [terms] => Array
                                                                (
                                                                    [stock.is_in_stock] => Array
                                                                        (
                                                                            [0] => 1
                                                                        )
                                                                    [boost] => 1
                                                                )
                                                        )
                                                    [1] => Array
                                                        (
                                                            [terms] => Array
                                                                (
                                                                    [visibility] => Array
                                                                        (
                                                                            [0] => 3
                                                                            [1] => 4
                                                                        )
                                                                    [boost] => 1
                                                                )
                                                        )
                                                )
                                            [must_not] => Array
                                                (
                                                )
                                            [should] => Array
                                                (
                                                )
                                            [minimum_should_match] => 1
                                            [boost] => 1
                                        )
                                )
                            [query] => Array
                                (
                                    [bool] => Array
                                        (
                                            [must] => Array
                                                (
                                                )
                                            [must_not] => Array
                                                (
                                                )
                                            [should] => Array
                                                (
                                                    [0] => Array
                                                        (
                                                            [multi_match] => Array
                                                                (
                                                                    [query] => test
                                                                    [fields] => Array
                                                                        (
                                                                            [0] => spelling.whitespace^10
                                                                        )
                                                                    [minimum_should_match] => 100%
                                                                    [tie_breaker] => 1
                                                                    [boost] => 1
                                                                    [type] => best_fields
                                                                    [cutoff_frequency] => 0.15
                                                                    [fuzziness] => AUTO
                                                                    [prefix_length] => 1
                                                                    [max_expansions] => 10
                                                                )
                                                        )
                                                    [1] => Array
                                                        (
                                                            [multi_match] => Array
                                                                (
                                                                    [query] => test
                                                                    [fields] => Array
                                                                        (
                                                                            [0] => spelling.phonetic^1
                                                                        )
                                                                    [minimum_should_match] => 100%
                                                                    [tie_breaker] => 1
                                                                    [boost] => 1
                                                                    [type] => best_fields
                                                                    [cutoff_frequency] => 0.15
                                                                )
                                                        )
                                                )
                                            [minimum_should_match] => 1
                                            [boost] => 1
                                        )
                                )
                            [boost] => 1
                        )
                )
        )
)
```

**Comment by ngocdb** [comment] 2017-08-28 09:22
How can "spelling.whitespace^10" or "spelling.phonetic^1" is converted into real field name ?
For example if I change it to "name^10" or "name^1" then I can get the result (the "Test Product")

**Comment by romainruaud** [comment] 2017-08-29 09:27
Hello @ngocdb 

Is the "Name" attribute set to "Used in Search" in your Magento Back-Office ? If not, the value for this attribute will not be copied to "spelling" and "search" field during indexing.

Please let me know,

Best regards,

**Comment by afoucret** [comment] 2017-09-19 07:32
Hello @ngocdb,

Since this issue have not been updated since more than 20 day, I close it.
Feel free to re-popen if the issue is still present and give us more details.

**Closed by afoucret** 2017-09-19 07:32 UTC
Labels: needs update
