### ISSUE TITLE
503 Backend fetch failed with Varnish

### ISSUE THREAD

**Issue by rbostan** [Smile-SA/elasticsuite#320] opened 2017-02-01 10:34 UTC
<pre>/catalogsearch/result/?q=example</pre> page gives 503 erorr while varnish enabled.

**Comment by romainruaud** [comment] 2017-02-01 10:37
Hello @rbostan 

I'm afraid but we will need more details to investigate, since when testing with Varnish on our environments we do not face such an issue.

Could you please tell us if something appear on the apache (or nginx) logs ? You may see a 500 error in those.

Also, can you please detail your Magento and Elasticsuite exact versions ?

Best regards,

**Comment by rbostan** [comment] 2017-02-01 10:46
@romainruaud 
Magento version : 2.1.2
Module version : smile/elasticsuite 2.4.x-dev

I suspect about timeout issues, because search takes tooo much time.
You may see nginx & php-fpm timeouts :
<pre>
send_timeout 600;
client_body_timeout 120;
client_header_timeout 120;
fastcgi_connect_timeout 600s;
fastcgi_send_timeout 600s; 
fastcgi_read_timeout 600s; 
</pre>

**Comment by romainruaud** [comment] 2017-02-03 13:31
I close this one since it's duplicate of #321

**Closed by romainruaud** 2017-02-03 13:31 UTC
