### ISSUE TITLE
Order by admin position (adminSortIndex) doesn't works properly

### ISSUE THREAD

**Issue by Koc** [Smile-SA/elasticsuite#239] opened 2016-12-08 20:56 UTC
1. create attribute with 20 values
2. set order by admin position 
3. open page with facet - facets build order by _count=desc limit 10
4. after then they order by adminSortIndex inside `addOptionsData` method
5. some attribute values are incorrect because we should sort them by admin sort index before order by count (or retrieve they without limit)

**Comment by afoucret** [comment] 2016-12-09 08:47
This one should be fixed in release 2.3.0.
The code is already present on the 2.3.0 branch and on the master one.

**Comment by afoucret** [comment] 2016-12-09 08:55
@Koc : Can you give me a feedback on the 2.3.x branch ?

**Comment by Koc** [comment] 2016-12-09 10:29
@afoucret wow, try test this later today

**Comment by afoucret** [comment] 2016-12-09 10:34
@Koc : Warning : the attribute filter template have completely change. You may have to backport changes from our theme if you have a custom theme.

**Comment by Koc** [comment] 2016-12-09 12:02
I've updated by composer to `"smile/elasticsuite": "2.3.x-dev",`, run mage upgrade, and reindex all indexes. Have a problem when load more attribute options - response is empty array for some atributes. See attached screencast

http://youtu.be/4hHrBI-CLxU?hd=1

**Comment by afoucret** [comment] 2016-12-09 15:55
@Koc, the problem you are describing is a duplicate of #237 
It has been fixed minutes ago on the branch 2.3.x.

BR,

**Comment by afoucret** [comment] 2016-12-16 14:38
Hi @Koc

Any feedback on this one ?

**Comment by afoucret** [comment] 2017-01-03 16:35
Hi @koc,

Since we had no feedback since a while and the problem seems to be fixed, I close the issue. Feel free to reopen if the problem is still present.

**Closed by afoucret** 2017-01-03 16:35 UTC
