### ISSUE TITLE
magento install failed when elastic search is on a different server

### ISSUE THREAD

**Issue by spipu** [Smile-SA/elasticsuite#209] opened 2016-11-17 13:09 UTC
Hi,

when make a fresh install of Magento on a architecture where elastic search is on a different server, the magento install crash with this error: 

> Module 'Magento_CatalogSearch':
> Installing data... 
>                                                                                                                                       
>   [Exception]                                                                                                                          
>   Recoverable Error: Object of class Smile\ElasticsuiteCore\Indexer\GenericIndexerHandler could not be converted to string in /var/ww  
>   w/fbd/releases/master-20161117113314/vendor/magento/module-catalog-search/Model/Indexer/IndexerHandlerFactory.php on line 84     

This is because ElasticSuite is selected by default as search engine, and that the default "ElasticSearch severs list" is localhost:9200

=> Magento try to contact elastic search, but it does not work, and the install stop.

**Comment by romainruaud** [comment] 2016-11-17 13:18
Hello,

please follow this part of the documentation when running elasticsearch on a dedicated server which is not localhost : 

https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall#optional--installing-the-module-when-using-a-custom-elasticsearch-server-location

Regards

**Comment by afoucret** [comment] 2016-11-17 13:54
Duplicate of #180

**Comment by afoucret** [comment] 2016-11-17 13:55
Duplicate #180

**Closed by afoucret** 2016-11-17 13:55 UTC
Labels: duplicate

**Comment by Koc** [comment] 2016-12-06 13:30
@afoucret can you properly handle Recoverable Error and throw exception like `could not connect to localhost:9200, check configuration settiings`?
