### ISSUE TITLE
Category view contains out of stock products

### ISSUE THREAD

**Issue by Koc** [Smile-SA/elasticsuite#502] opened 2017-08-17 13:02 UTC
### Preconditions

Magento Version : 2.1.8

ElasticSuite Version : 2.3.x

Environment : PHP 7.0.21

Third party modules : -

### Steps to reproduce

1. Open stores-settings-catalog-inventory (/admin/system_config/edit/section/cataloginventory/) and set "display out of stock products = no"
2. open category
3.

### Expected result

1. Out of stock products not visible in list

### Actual result

1. Out of stock products are visible

**Comment by romainruaud** [comment] 2017-08-17 13:05
Hello @Koc 

which kind of products are visible in list ? Are they simple or composite (configurable, bundle, etc..) ?

**Comment by Koc** [comment] 2017-08-17 13:09
haven't checked all, but that what checked are configuable

have you any idea for quick workaround for this (like add plugin)?

**Comment by romainruaud** [comment] 2017-08-17 15:13
Could you please show me the ES query which is generated ?

**Comment by romainruaud** [comment] 2017-08-17 15:33
The query generated should contain a clause like this : 

```
            {
              "terms": {
                "stock.is_in_stock": [
                  true
                ]
              }
            },
```

If this is not the case, then something is broken around the Layer Plugin : https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php#L56

Please note that I am not able to reproduce your issue on my instance. Are you using a raw Magento2 installation ? I am using Magento 2.1.8 with latest elasticsuite 2.3.x

Regards

**Comment by Koc** [comment] 2017-08-17 15:46
> Are you using a raw Magento2 installation ?

no, migrated from 1.9.2.x :(.

see query

![default](https://user-images.githubusercontent.com/191082/29420989-563accc8-837c-11e7-8497-0b41b8db4cf1.png)

**Comment by Koc** [comment] 2017-08-17 15:49
Query contains stock filter. I've collapsed aggregations node. And as you see below on the screen: product are out of stock

**Comment by romainruaud** [comment] 2017-08-17 16:05
And what do you have in the response ? You should be able to see the "stock" field in response documents. Maybe some products are having "true" in the stock field inside Elasticsearch.

**Comment by Koc** [comment] 2017-08-17 16:32
Is in stock = true. This is configurable product - they are always in stock in our shop. We depends on stock availability of simple products inside configurables. As I understand it can be done on indexation phase: check stock availability of child simple products.

![default](https://user-images.githubusercontent.com/191082/29422763-eaaa52f2-8381-11e7-8a8c-5b960cafd2ba.png)

**Comment by romainruaud** [comment] 2017-08-18 09:35
Hello @Koc 

`is_in_stock` is set here : https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/InventoryData.php#L53

and retrieven from the DB here : https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/InventoryData.php#L82

This is basic read from the "cataloginventory_stock_status" table, which should be correctly populated by Magento's stock indexer.

On a standard instance, Magento is turning a configurable product Out of Stock if none of it's children are In Stock.

Maybe you have something which is collisioning here.

Please ensure the value of "stock_status" field in this table for your products.

Since the issue does not seem to be related to Elasticsuite, I close it for now.

Feel free to reopen it if you have any clues that the problem is related to elasticsuite.

Best regards,

**Closed by romainruaud** 2017-08-18 09:35 UTC

**Comment by Koc** [comment] 2017-08-18 09:52
Heh, I have fears that this bug comes from Magento and not by Elasticsuite plugin.

> Magento is turning a configurable product Out of Stock if none of it's children are In Stock.

Have you idea how can I trigger refresh of stock status for all configurable products across database? Like write command which load and saves all configurable products.

**Comment by romainruaud** [comment] 2017-08-18 09:56
Imho the easiest way would be to process a full reindex for the catalog inventory indexer, or if you are using "update on schedule", process a dummy update on the catalog_product_entity table for all products having "type_id=configurable" could do the trick and put all of these products into the changelog table.

Regards

**Comment by Koc** [comment] 2017-08-18 12:05
> Imho the easiest way would be to process a full reindex for the catalog inventory indexer

oh, I've runed it many times, it doesn't help.

Thank very much you for investiganting my issue.
