### ISSUE TITLE
call_user_func_array(): Argument #1 ($callback) must be a valid callback

### ISSUE THREAD

**Issue by davidandersson1** [Smile-SA/elasticsuite#2722] opened 2022-09-28 12:10 UTC
Hello,

We are using magento version 2.4.4 with elastisuite version 2.10.11

### Preconditions

Magento Version : 2.4.4

ElasticSuite Version : 2.10.11

Environment :Production

Third party modules :

We have noticed in critical logs in system.log as below but somehow we do not know how to reproduce below critical log

[2022-09-28T12:04:30.982703+00:00] main.CRITICAL: TypeError: call_user_func_array(): Argument 1 ($callback) must be a valid callback, first array member is not a valid class name or object in vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Helper/Rule.php:76

if possible, Can you please help here to get rid of this issue.

Thanks,
David Andersson

**Comment by romainruaud** [comment] 2022-09-28 16:48
Duplicate of #1985 

Please check on this one if the scenario to reproduce and the provided fix is okay for you.

Regards

**Closed by romainruaud** 2022-09-28 16:48 UTC

**Comment by davidandersson1** [comment] 2022-09-29 04:03
@romainruaud thanks for your reply! 
Sorry but i can't found there exact fix so if possible can you plesae send me link of "provided fix" here.
