### ISSUE TITLE
Catalog Search indexer process unknown error:

### ISSUE THREAD

**Issue by sandymu123** [Smile-SA/elasticsuite#1012] opened 2018-07-19 09:47 UTC
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The [string] type is removed in 5.0. You should now use either a [text] or [keyword] field instead for field [sku]"}],"type":"illegal_argument_exception","reason":"The [string] type is removed in 5.0. You should now use either a [text] or [keyword] field instead for field [sku]"},"status":400}

I am using elastic suite 2.5.0 and elastic search 5.0 Magento EE 2.3

**Comment by romainruaud** [comment] 2018-07-19 09:49
Hello @sandymu123 ,

could you please post the output of the following commands : 

`composer info | grep elasticsearch`

`composer info | grep smile`

`curl localhost:9200` (if your ES server is installed locally).

**Comment by afoucret** [comment] 2018-07-23 13:04
I think you are not using ElasticSearch 5.x but ElasticSearch 6.x instead.

If confirmed this issue is fully expected because ElasticSuite 2.5.x does not support ElasticSearch 6.x. This will come with ElasticSuite 2.6.0 (currently the master branch).

BR,

**Comment by afoucret** [comment] 2018-07-24 13:19
Can you confirm ?

**Comment by afoucret** [comment] 2018-07-31 06:53
Hi @sandymu123,

I close this bug because we do not have any feedback from you and I suspect that you were using an unsupported ElasticSearch version.

**Closed by afoucret** 2018-07-31 06:53 UTC
Labels: needs update
