### ISSUE TITLE
I can not edit virtual rules

### ISSUE THREAD

**Issue by jamematen** [Smile-SA/elasticsuite#848] opened 2018-04-05 17:29 UTC
Some of the javascript code appears on the page and the controls do not respond
### Preconditions
After update from magento 2.1.8

Ubuntu 16.04 nginx php 7.0.28 elasticsearch 2.4.6 magento 2.1.12

Magento Version : CE 2.1.12

ElasticSuite Version : smile/elasticsuite ^2.3.0

Environment :
developer mode

Third party modules :

### Steps to reproduce

1.
![captura de pantalla de 2018-04-05 19 21 54](https://user-images.githubusercontent.com/4154820/38381520-4f237c1e-3907-11e8-8ddd-43381867ac59.png)
2.
3.

### Expected result

1.

### Actual result

1. [Screenshot, logs]

**Comment by romainruaud** [comment] 2018-04-06 09:42
Hello,

this seems like a duplicate of #806 

However, as @afoucret stated, the 2.3.x version is now unmaintained.

Are you able to update to a newer version ? I know it would imply to also migrate your store to Magento 2.2

**Closed** 2018-04-16 09:59 UTC
Labels: bug, duplicate
