### ISSUE TITLE
Visual merchandiser not workable on large catalogs and categories

### ISSUE THREAD

**Issue by rikwillems** [Smile-SA/elasticsuite#1177] opened 2018-11-12 07:35 UTC
The visual merchandiser allows a user to drag and drop products to a manual sorting. It shows a limited set of products after which you can click 'show more'. This is not workable on larger catalogs or categories. You will never get to the product you want to select.

**Comment by romainruaud** [comment] 2018-11-12 10:16
Hello @rikwillems 

You are right, it's actually complicated to get products if they are on deeper pages.

It's actually a duplicate of #157 where we were thinking about adding something to refine the selection better.

Regards

**Closed by romainruaud** 2018-11-12 10:16 UTC
Labels: duplicate
