### ISSUE TITLE
Autocomplete not clickable

### ISSUE THREAD

**Issue by isabelcelima** [Smile-SA/elasticsuite#1626] opened 2019-11-20 10:17 UTC
Hello,

I'm using elasticsuite for Magento 2.2.6 autocomplete works partially but the list of items are not clickable.
When I research something like 'ab' it shows me not all the items but only something like 'abetone' but it doesn't show me items like 'abete', is it possible to use partial search?

Thank you

**Comment by romainruaud** [comment] 2020-01-08 11:28
Sorry but I'll close this issue since it's lacking a lot of details.

Please reopen if and respect the issue template and describe the expected behavior and what you are facing, along with components versions and so on.

Regards

**Comment by nkajic** [comment] 2020-11-23 18:39
Hi @romainruaud and @isabelcelima 

We have encountered this problem. 

Steps to reproduce: Open shop on mobile device (Android) using Chrome. Search for something with many results. Scroll under elements that were shown *under virtual keyboard* and click on it. It will just tilt and scroll back to input field.

@isabelcelima Did you manage to resolve this problem by yourself?

![signal-2020-11-23-193423](https://user-images.githubusercontent.com/3989412/100001469-80efbd80-2dc3-11eb-8b52-a37bf4db3d07.jpg)

**Comment by rbayet** [comment] 2021-01-07 10:01
Hello @nkajic,

Could give us the exact version of Android 7 you are encountering this on ?
At this moment, I can't reproduce it on a 7.1.x device.

Regards,

**Comment by nkajic** [comment] 2021-01-07 11:29
Hi @rbayet thanks for support and your time. 

It is Android ver. 7.0

**Closed** 2021-01-08 14:25 UTC
Labels: bug

**Comment by rbayet** [comment] 2021-01-08 14:28
Hello @nkajic,

Thanks for your fix, I used a variation of your PR (explicit commit message) and it will be integrated in the upcoming 2.10.x and 2.9.x releases.

Regards,
