### ISSUE TITLE
Layered navigation filters: wrong configurable products found?

### ISSUE THREAD

**Issue by VincentMarmiesse** [Smile-SA/elasticsuite#854] opened 2018-04-09 15:10 UTC
Hello,

I'm having an issue when I use the layered navigation filters. When I filter by size for example, some configurable products are displayed even if their children of this size isn't in stock.

Here is my setup:

- My category has 9 configurable products

Product | Available sizes
---------- | --------------------
Product 1 | XS / S / M / L
Product 2 | XS / S / M / L / XL
Product 3 | XS / S / M / L / XL
Product 4 | XS / S / M / L / XL
Product 5 | XS / S / M / L / XL
Product 6 | XS / L / XL
Product 7 | XS / S
Product 8 | XL
Product 9 | XS / S / L / XL

Filter | Number of products | OK or KO
------ | --------------------------- | -------------
No filter | 9 | OK
XS | 8 | OK
S | 7 | OK
M | 5 | OK
L | 8 | KO : Product 8 is displayed, it should not
XL | 7 | OK

This issue seems to be random and can be repeated in all of our categories, with different products.

When I disable all ElasticSuite module and reindex, the default Magento filters are working fine.
When I disable the L size of Product 8 (which is out of stock), it works fine and Product 8 is no longer displayed when I filter on L. However it's displayed when I re-enable the L size.

Everything is reindexed, caches have been flushed.

Do you know what can cause this issue?

Thanks!

### Preconditions
Magento Version : 2.2.3

ElasticSuite Version : 2.5.6

Environment : Developer mode

Third party modules : Yes but should not be relevant

**Comment by VincentMarmiesse** [comment] 2018-04-09 16:16
I don't know if it's relevant but I'm using the size attribute as a swatch attribute.

**Comment by romainruaud** [comment] 2018-04-11 07:16
Hello,

it looks like a bug according to what you are describing.

I will try to reproduce this one and to investigate. Using Size as a swatch attribute should not matter, It's also the case on Magento2 sample data, and there are the one we are using for testing.

I keep you in touch.

Regards

**Comment by romainruaud** [comment] 2018-04-11 13:14
Hello,

I am actually investigating on this one.

Could you tell me if your "Product 8" (the parent one, not the childrens) does have something as value for "size" attribute ?

Also, are you able to check what is stored inside each product document in your Elasticsearch index ?

Regards

**Comment by VincentMarmiesse** [comment] 2018-04-11 13:39
Hi,
The configurable product has no value for the `size` attribute.

When I launch this request 
```
curl 172.17.0.2:9200/project_local_fr_ue_catalog_product_20180411_093050/_search?pretty -d '
{
  "query": { "match": { "sku": "PRODUCT8_CONFIGURABLE_SKU" } }
}'
```

I have the following result
```
{
  "took" : 36,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 12,
    "max_score" : 17.225546,
    "hits" : [
      {
        "_index" : "project_local_fr_ue_catalog_product_20180411_093050",
        "_type" : "product",
        "_id" : "82021",
        "_score" : 17.225546,
        "_source" : {
          "entity_id" : "82021",
          "attribute_set_id" : "4",
          "type_id" : "configurable",
          "sku" : [
            "PRODUCT8_CONFIGURABLE_SKU",
            "PRODUCT8_CONFIGURABLE_SKU_L",
            "PRODUCT8_CONFIGURABLE_SKU_XL"
          ],
          "has_options" : "1",
          "required_options" : "1",
          "created_at" : "2018-01-09 17:18:48",
          "updated_at" : "2018-04-09 15:17:19",
          "visibility" : "4",
          "price" : [
            {
              "price" : "70.0000",
              "original_price" : "70.0000",
              "is_discount" : false,
              "customer_group_id" : "0"
            },
            {
              "price" : "70.0000",
              "original_price" : "70.0000",
              "is_discount" : false,
              "customer_group_id" : "1"
            },
            {
              "price" : "70.0000",
              "original_price" : "70.0000",
              "is_discount" : false,
              "customer_group_id" : "2"
            },
            {
              "price" : "70.0000",
              "original_price" : "70.0000",
              "is_discount" : false,
              "customer_group_id" : "3"
            }
          ],
          "indexed_attributes" : [
            "price",
            "name",
            "image",
            "color",
            "status",
            "tax_class_id",
            "size"
          ],
          "category" : [
            {
              "category_id" : 2
            },
            {
              "category_id" : 105,
              "name" : "Femme"
            },
            {
              "category_id" : 109,
              "name" : "Soldes"
            },
            {
              "category_id" : 110,
              "name" : "Femme"
            },
            {
              "category_id" : 112,
              "is_parent" : true,
              "name" : "Toute la sélection"
            },
            {
              "category_id" : 114,
              "name" : "Maillots de bain"
            },
            {
              "category_id" : 115,
              "is_parent" : true,
              "name" : "Une pièce"
            },
            {
              "category_id" : 116,
              "is_parent" : true,
              "name" : "Tous les maillots de bain"
            },
            {
              "category_id" : 117,
              "is_parent" : true,
              "name" : "Nageurs"
            }
          ],
          "name" : [
            "Nageur femme"
          ],
          "image" : [
            "/b/a/xxxx.jpg"
          ],
          "color" : [
            55
          ],
          "option_text_color" : [
            "NOIR"
          ],
          "status" : [
            1
          ],
          "option_text_status" : [
            "Enabled"
          ],
          "tax_class_id" : [
            2
          ],
          "option_text_tax_class_id" : [
            "Taxable Goods"
          ],
          "children_ids" : [
            74995,
            74996
          ],
          "children_attributes" : [
            "size",
            "option_text_size",
            "indexed_attributes"
          ],
          "configurable_attributes" : [
            "size"
          ],
          "size" : [
            7,
            8
          ],
          "option_text_size" : [
            "L",
            "XL"
          ],
          "stock" : {
            "is_in_stock" : true,
            "qty" : 0
          }
        }
      },
    }
  }
}
```

(real skus have been changed).

So `PRODUCT8_CONFIGURABLE_SKU_L` in my example should not be here I think.

Do I launch the right request?

**Comment by romainruaud** [comment] 2018-04-11 13:50
Thank you, yes this request does fit my needs.

I'll investigate further.

Regards

**Comment by romainruaud** [comment] 2018-04-11 13:58
Ok I got it.

Two points here : 

- Disabling (setting `status` to `0`) the "L" child product should make it disappear from the results. It's the case on my dev environment when I reproduce your scenario.

- just setting it to `qty=0` and `is_in_stock=false` does not make it disappear. It's also the case on my dev env.

As stated by @afoucret on this issue, this is by design :  https://github.com/Smile-SA/elasticsuite/issues/809#issuecomment-371802537

@Koc gave a workaround in the same issue to exclude out-of-stock children products from indexing. Could you give it a try and tell me if it solves your issue ?

Regards

**Comment by VincentMarmiesse** [comment] 2018-04-11 15:01
> Disabling (setting status to 0) the "L" child product should make it disappear from the results. It's the case on my dev environment when I reproduce your scenario.

Indeed.

Thanks for the explanation, too bad Magento does not follow its own config and display out of stock configurable children. I have applied the plugin @Koc suggested and it works!

Thanks!

**Comment by romainruaud** [comment] 2018-04-11 15:03
Great,

I consider this issue resolved and close it for now.

Thank you for using our module and participating on our repository.

Regards

**Closed by romainruaud** 2018-04-11 15:03 UTC
Labels: duplicate, needs update
