### ISSUE TITLE
VirtualCategory not working on Magento 2.3.5

### ISSUE THREAD

**Issue by patruvlad** [Smile-SA/elasticsuite#1816] opened 2020-05-21 06:33 UTC
### Preconditions

Magento Version : Magento CE 2.3.5

ElasticSuite Version : 2.9.0

Environment : Developer

Third party modules : No, clean magento install

### Steps to reproduce

1. composer require smile/elasticsuite ( installing latest version 2.9.0 )
2. php bin/magento setup:upgrade
3. Go in admin area and click on Catalog -> Categories

### Expected result

1. Being able to create conditions for categories in admin

### Actual result

1. Error
{"0":"Invalid id field entity_id : field is not declared.","1":"#1 Smile\\ElasticsuiteCore\\Index\\Mapping\\Interceptor->__construct() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:121]\n#2 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:66]\n#3 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create() called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:56]\n#4 Magento\\Framework\\ObjectManager\\ObjectManager->create() called at [generated\/code\/Smile\/ElasticsuiteCore\/Api\/Index\/MappingInterfaceFactory.php:43]\n#5 Smile\\ElasticsuiteCore\\Api\\Index\\MappingInterfaceFactory->create() called at [vendor\/smile\/elasticsuite\/src\/module-elasticsuite-core\/Index\/Indices\/Config.php:145]\n#6 Smile\\ElasticsuiteCore\\Index\\Indices\\Config->initIndexConfig() called at [vendor\/smile\/elasticsuite\/src\/module-elasticsuite-core\/Index\/Indices\/Config.php:126]\n#7 Smile\\ElasticsuiteCore\\Index\\Indices\\Config->Smile\\ElasticsuiteCore\\Index\\Indices\\{closure}()\n#8 array_walk() called at [vendor\/smile\/elasticsuite\/src\/module-elasticsuite-core\/Index\/Indices\/Config.php:127]\n#9 Smile\\ElasticsuiteCore\\Index\\Indices\\Config->initData() called at [vendor\/magento\/framework\/Config\/Data.php:93]\n#10 Magento\\Framework\\Config\\Data->__construct() called at [vendor\/smile\/elasticsuite\/src\/module-elasticsuite-core\/Index\/Indices\/Config.php:105]\n#11 Smile\\ElasticsuiteCore\\Index\\Indices\\Config->__construct() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:121]\n#12 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:66]\n#13 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create() called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:70]\n#14 Magento\\Framework\\ObjectManager\\ObjectManager->get() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:167]\n#15 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:273]\n#16 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->getResolvedArgument() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:236]\n#17 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:34]\n#18 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:59]\n#19 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create() called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:70]\n#20 Magento\\Framework\\ObjectManager\\ObjectManager->get() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:167]\n#21 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:273]\n#22 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->getResolvedArgument() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:236]\n#23 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:34]\n#24 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:59]\n#25 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create() called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:70]\n#26 Magento\\Framework\\ObjectManager\\ObjectManager->get() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:167]\n#27 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:273]\n#28 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->getResolvedArgument() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:236]\n#29 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:34]\n#30 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:59]\n#31 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create() called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:70]\n#32 Magento\\Framework\\ObjectManager\\ObjectManager->get() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:167]\n#33 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:273]\n#34 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->getResolvedArgument() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:236]\n#35 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:34]\n#36 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:59]\n#37 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create() called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:70]\n#38 Magento\\Framework\\ObjectManager\\ObjectManager->get() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:167]\n#39 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:273]\n#40 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->getResolvedArgument() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:236]\n#41 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:34]\n#42 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:59]\n#43 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create() called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:56]\n#44 Magento\\Framework\\ObjectManager\\ObjectManager->create() called at [generated\/code\/Smile\/ElasticsuiteCatalogRule\/Model\/RuleFactory.php:43]\n#45 Smile\\ElasticsuiteCatalogRule\\Model\\RuleFactory->create() called at [vendor\/smile\/elasticsuite\/src\/module-elasticsuite-virtual-category\/Model\/Category\/Attribute\/VirtualRule\/ReadHandler.php:64]\n#46 Smile\\ElasticsuiteVirtualCategory\\Model\\Category\\Attribute\\VirtualRule\\ReadHandler->execute() called at [vendor\/magento\/framework\/EntityManager\/Operation\/Read\/ReadExtensions.php:48]\n#47 Magento\\Framework\\EntityManager\\Operation\\Read\\ReadExtensions->execute() called at [vendor\/magento\/framework\/EntityManager\/Operation\/Read.php:112]\n#48 Magento\\Framework\\EntityManager\\Operation\\Read->execute() called at [vendor\/magento\/framework\/EntityManager\/EntityManager.php:70]\n#49 Magento\\Framework\\EntityManager\\EntityManager->load() called at [vendor\/magento\/module-catalog\/Model\/ResourceModel\/Category.php:1094]\n#50 Magento\\Catalog\\Model\\ResourceModel\\Category->load() called at [generated\/code\/Magento\/Catalog\/Model\/ResourceModel\/Category\/Interceptor.php:336]\n#51 Magento\\Catalog\\Model\\ResourceModel\\Category\\Interceptor->load() called at [vendor\/magento\/framework\/Model\/AbstractModel.php:540]\n#52 Magento\\Framework\\Model\\AbstractModel->load() called at [generated\/code\/Magento\/Catalog\/Model\/Category\/Interceptor.php:1480]\n#53 Magento\\Catalog\\Model\\Category\\Interceptor->load() called at [vendor\/magento\/module-catalog\/Controller\/Adminhtml\/Category.php:100]\n#54 Magento\\Catalog\\Controller\\Adminhtml\\Category->_initCategory() called at [vendor\/magento\/module-catalog\/Controller\/Adminhtml\/Category\/Edit.php:85]\n#55 Magento\\Catalog\\Controller\\Adminhtml\\Category\\Edit->execute() called at [generated\/code\/Magento\/Catalog\/Controller\/Adminhtml\/Category\/Edit\/Interceptor.php:24]\n#56 Magento\\Catalog\\Controller\\Adminhtml\\Category\\Edit\\Interceptor->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:108]\n#57 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/module-backend\/App\/AbstractAction.php:231]\n#58 Magento\\Backend\\App\\AbstractAction->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#59 Magento\\Catalog\\Controller\\Adminhtml\\Category\\Edit\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#60 Magento\\Catalog\\Controller\\Adminhtml\\Category\\Edit\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:143]\n#61 Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#62 Magento\\Catalog\\Controller\\Adminhtml\\Category\\Edit\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#63 Magento\\Catalog\\Controller\\Adminhtml\\Category\\Edit\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Catalog\/Controller\/Adminhtml\/Category\/Edit\/Interceptor.php:39]\n#64 Magento\\Catalog\\Controller\\Adminhtml\\Category\\Edit\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:162]\n#65 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:99]\n#66 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#67 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#68 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#69 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#70 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:116]\n#71 Magento\\Framework\\App\\Http->launch() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:24]\n#72 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:261]\n#73 Magento\\Framework\\App\\Bootstrap->run() called at [index.php:39]\n","url":"\/admin\/catalog\/category\/index\/key\/88339ebe07fa3f11438e5d2b08c3de9b7b872d08d5760692079567585d7f840e\/","script_name":"\/index.php","report_id":"196560aef1cc3caf88f2d507c788534c7f3a1739599de3773999eb471477752a"}

**Comment by androshchuk** [comment] 2020-05-21 14:51
Hello @patruvlad 
Unfortunately, I could not reproduce this error in my environment (Magento ver. 2.3.5-p1 CE,
ElasticSuite v2.9.0)

If possible, provide more information.

Regards

**Comment by rbayet** [comment] 2020-06-05 12:56
Hello @patruvlad,

I also was not able either to reproduce the issue on a clean install.
If the Elasticsearch cannot be joined, the error message is usually `No alive nodes found in your cluster`.
If Elasticsearch is up and can be joined but there is absolutely no available index, the error message is `catalog_product index does not exist yet. Make sure everything is reindexed.`.

Usually it is better to complete the install with the full reindex, but setup:upgrade only will generately create the indices if none are there.

I'm closing this issue right now, but don't hesitate to re-open it if you are able to consistently reproduce the issue and can provide more context as @androshchuk suggested.

Regards

**Closed by rbayet** 2020-06-05 12:56 UTC
Labels: needs update
