### ISSUE TITLE
Search issue

### ISSUE THREAD

**Issue by bangln** [Smile-SA/elasticsuite#2622] opened 2022-07-04 10:34 UTC
I have an issue with search: 
when i search for swan, it have no exact ressults: https://sklep.yes2move.com/catalogsearch/result/?q=swan
but when i type 'swanson', it have 9 results: https://sklep.yes2move.com/catalogsearch/result/?q=swanson 
please help me!

**Comment by vahonc** [comment] 2022-07-04 10:45
Duplicate of #2600

@bangln, take some experience from the initial issue.

BR,
Vadym

**Comment by bangln** [comment] 2022-07-05 01:34
It's work! thanks very much!
Regard!

**Comment by vahonc** [comment] 2022-07-05 07:17
In this case, I'm closing this issue.

**Closed** 2022-07-05 07:17 UTC
Labels: duplicate
