### ISSUE TITLE
No alive nodes found in your cluster.

### ISSUE THREAD

**Issue by iRabi** [Smile-SA/elasticsuite#1002] opened 2018-07-07 21:14 UTC
**Preconditions**
After installing modules and enabling them, when I run `bin/magento setup:upgrade`, I get this error  _'Smile_ElasticsuiteCatalog': Installing data... No alive nodes found in your cluster_. When **_only_** 'Smile_ElasticsuiteCore' module is enabled, site is working but catalog is appearing blank.

Magento Version : 2.2.4, default Luma theme and demo products.
ElasticSuite Version : v5.3.2
Environment : Developer
Nginx, php 7.1.18

**### Steps to reproduce**
1. Installed ES modules with phonetic and UCI
2. Verified ES is running with "curl localhost:9200"
3. Followed instructions: https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall

**### Expected result**
1. Module should work as expected

**### Actual result**
1. CLI message: 
Module 'Smile_ElasticsuiteCore':
Module 'Smile_ElasticsuiteCatalog':
Installing data... No alive nodes found in your cluster

2. Log report: 
[2018-07-07 21:10:17] main.CRITICAL: No alive nodes found in your cluster {"exception":"[object] (Elasticsearch\\Common\\Exceptions\\NoNodesAvailableException(code: 0): No alive nodes found in your cluster at /var/www/html/espmagento/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:51)"} []

**Comment by romainruaud** [comment] 2018-07-09 09:36
Hello, thank you for giving our module a try.

Which instructions did you follow in module install ? In fact, they are all optional if your ES server is running on http://localhost:9200

Could you show me anything related to elasticsuite/elasticsearch as it appears on the core_config_data table during install or in the app/etc/env.php file ? 

Regards

**Comment by iRabi** [comment] 2018-07-10 17:07
Hi,
Followed this instruction: https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall
env.php:
```
<?php
return [
  'backend' => [
    'frontName' => 'admin_esp'
  ],
  'crypt' => [
    'key' => 'd1c386262377ac7ecee183b4ba2e7882'
  ],
  'db' => [
    'table_prefix' => '',
    'connection' => [
      'default' => [
        'host' => 'localhost',
        'dbname' => 'magentodb',
        'username' => 'magentouser',
        'password' => 'MagentoPWD123#',
        'active' => '1'
      ]
    ]
  ],
  'resource' => [
    'default_setup' => [
      'connection' => 'default'
    ]
  ],
  'x-frame-options' => 'SAMEORIGIN',
  'MAGE_MODE' => 'default',
  'session' => [
    'save' => 'files'
  ],
  'cache_types' => [
    'config' => 0,
    'layout' => 0,
    'block_html' => 0,
    'collections' => 0,
    'reflection' => 0,
    'db_ddl' => 0,
    'eav' => 0,
    'customer_notification' => 0,
    'config_integration' => 0,
    'config_integration_api' => 0,
    'full_page' => 0,
    'translate' => 0,
    'config_webservice' => 0
  ],
  'install' => [
    'date' => 'Mon, 02 Jul 2018 03:01:27 +0000'
  ],
  'system' => [
    'default' => [
      'smile_elasticsuite_core_base_settings' => [
        'es_client' => [
          'servers' => 'localhost:9200',
          'enable_https_mode' => 'false',
          'enable_http_auth' => 'false',
          'http_auth_user' => '',
          'http_auth_pwd' => ''
        ]
      ]
    ]
  ]
];
```
Also, there is not any row related to _elasticsuite/elasticsearch_ in _core_config_data_ .

Thanks.

**Comment by afoucret** [comment] 2018-07-24 13:21
Does the problem still occurs if you clean the cache before running the setup:upgrade script ?

**Comment by iRabi** [comment] 2018-07-29 15:48
Hi, I will give a try and let you know.
Thanks.

**Comment by afoucret** [comment] 2018-07-31 06:52
Hi @iRabi,

I close this one for having no feedback from you and not being able to reproduce the bug.

**Closed by afoucret** 2018-07-31 06:52 UTC
Labels: needs update

**Comment by izakarim** [comment] 2018-09-13 09:45
I faced the same issue. Is there any solution for this?

**Comment by alexpoletaev** [comment] 2018-10-05 13:11
the next config fixed the problem for me:
```
'smile_elasticsuite_core_base_settings' => [
                'es_client' => [
                    'servers' => '127.0.0.1:9200',
                    'enable_https_mode' => 0,
                    'enable_http_auth' => 0,
                    'http_auth_user' => '',
                    'http_auth_pwd' => '',
                    'scheme' => 'http'
                ]
            ]
```
the problem is that the 'false' is a **string**, it returns **true** during validation and Magento tries to connect over https.

**Comment by JohnMTrimbleIII** [comment] 2018-10-17 01:13
I'm having the same problem here is my config. 

 'system' => [
        'default' => [
            'smile_elasticsuite_core_base_settings' => [
                'es_client' => [
                    'servers' => 'https://*****************.us-west-2.es.amazonaws.com:443',
                    'enable_https_mode' => '0',
                    'enable_http_auth' => '0',
                ]
            ]
        ]
    ]

**Comment by andrewkett** [comment] 2019-01-18 08:39
I changed

` 'system' => [
        'default' => [
            'smile_elasticsuite_core_base_settings' => [
                'es_client' => [
                    'servers' => 'elasticsearch:9200',
                    'enable_https_mode' => '0',
                    'enable_http_auth' => '1',
                ]
            ]
        ]
    ] `

to 

` 'system' => [
        'default' => [
            'smile_elasticsuite_core_base_settings' => [
                'es_client' => [
                    'servers' => 'elasticsearch:9200',
                    'enable_https_mode' => 0,
                    'enable_http_auth' => 1,
                ]
            ]
        ]
    ] `

which resolved this issue for me.  It appears the 0 as a string was being evaluated as true as per alexpoletaevs suggestion

**Comment by Ahmed-Ayman** [comment] 2019-02-20 11:17
for anyone who is facing the same issue and coming from a docker-compose background!
just change the `'servers' value in `app/etc/env.php` to `<your elasticsearch image name>:<the port>` in my case it was `elasticsearch:9200` since my docker-compose was like 

```
 elasticsearch:
    build: images/elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

```

**Comment by LavanyaCS** [comment] 2019-03-20 07:43
i am also facing same issues

**Comment by LavanyaCS** [comment] 2019-03-20 07:43
I dono have idea 

May I know the proceduere

**Comment by LavanyaCS** [comment] 2019-03-20 07:44
Module 'Smile_ElasticsuiteCore':
Module 'Smile_ElasticsuiteCatalog':
Installing data... No alive nodes found in your cluster

**Comment by Ahmed-Ayman** [comment] 2019-03-20 13:49
check out the comments @LavanyaCS

**Comment by ryanisn** [comment] 2019-10-22 15:20
jeez, having protocol in the host url would break the installation, removing http(s) from url in config fixed it for me.

**Comment by mrtuvn** [comment] 2021-03-27 09:10
> the next config fixed the problem for me:
> 
> ```
> 'smile_elasticsuite_core_base_settings' => [
>                 'es_client' => [
>                     'servers' => '127.0.0.1:9200',
>                     'enable_https_mode' => 0,
>                     'enable_http_auth' => 0,
>                     'http_auth_user' => '',
>                     'http_auth_pwd' => '',
>                     'scheme' => 'http'
>                 ]
>             ]
> ```
> 
> the problem is that the 'false' is a **string**, it returns **true** during validation and Magento tries to connect over https.

works like a charm

**Comment by mamsincl** [comment] 2022-02-15 17:37
still an issue ..... can we enclose https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Setup/InstallData.php#L94 with a condition to check if `elasticsuite` is the actually used search engine .... that should eliminate the issue when you try to set up Elasticsuite details via a data patch 

it would be advisable to invalidate indexers instead of triggering a full reindex during setup upgrade - that also can prevent the reported error message

I think a site with empty product listing pages alongside an invalidated, but already running indexer triggered by cron is much better than a failed or time-consuming deployment ....

**Comment by hkvega01** [comment] 2022-10-27 08:10
> Hi, Followed this instruction: https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall env.php:
> 
> ```
> <?php
> return [
>   'backend' => [
>     'frontName' => 'admin_esp'
>   ],
>   'crypt' => [
>     'key' => 'd1c386262377ac7ecee183b4ba2e7882'
>   ],
>   'db' => [
>     'table_prefix' => '',
>     'connection' => [
>       'default' => [
>         'host' => 'localhost',
>         'dbname' => 'magentodb',
>         'username' => 'magentouser',
>         'password' => 'MagentoPWD123#',
>         'active' => '1'
>       ]
>     ]
>   ],
>   'resource' => [
>     'default_setup' => [
>       'connection' => 'default'
>     ]
>   ],
>   'x-frame-options' => 'SAMEORIGIN',
>   'MAGE_MODE' => 'default',
>   'session' => [
>     'save' => 'files'
>   ],
>   'cache_types' => [
>     'config' => 0,
>     'layout' => 0,
>     'block_html' => 0,
>     'collections' => 0,
>     'reflection' => 0,
>     'db_ddl' => 0,
>     'eav' => 0,
>     'customer_notification' => 0,
>     'config_integration' => 0,
>     'config_integration_api' => 0,
>     'full_page' => 0,
>     'translate' => 0,
>     'config_webservice' => 0
>   ],
>   'install' => [
>     'date' => 'Mon, 02 Jul 2018 03:01:27 +0000'
>   ],
>   'system' => [
>     'default' => [
>       'smile_elasticsuite_core_base_settings' => [
>         'es_client' => [
>           'servers' => 'localhost:9200',
>           'enable_https_mode' => 'false',
>           'enable_http_auth' => 'false',
>           'http_auth_user' => '',
>           'http_auth_pwd' => ''
>         ]
>       ]
>     ]
>   ]
> ];
> ```
> 
> Also, there is not any row related to _elasticsuite/elasticsearch_ in _core_config_data_ .
> 
> Thanks.

should be 

                'es_client' => [
                    'servers' => '172.18.0.120:9200',
                    'enable_https_mode' => 0,
                    'enable_http_auth' => 0,
                    'http_auth_user' => '',
                    'http_auth_pwd' => ''
                ]
