### ISSUE TITLE
Filter by Category on Virtual Category Page

### ISSUE THREAD

**Issue by OBog** [Smile-SA/elasticsuite#1174] opened 2018-11-08 12:23 UTC
### Preconditions

Magento Version : CE 2.2.2

ElasticSuite Version : 2.6.1

Environment : Production

Third party modules :

### Steps to reproduce

1. Create virtual category and set "Default Category" as a Root one.
2. Reindex and Clear FPC

### Expected result

1. Category filter is shown on Category page.

### Actual result

1. Category Filter is absent on Category Page.
 - Anchor is set to 1
 - In fact No Category filter is shown in case any category with subcategories is selected as " Virtual Category Root"

**Comment by romainruaud** [comment] 2018-11-09 11:32
It's due to #49 being still non-implemented for now.

**Comment by romainruaud** [comment] 2019-01-10 13:50
Closed as duplicate of #49

**Closed by romainruaud** 2019-01-10 13:50 UTC
Labels: duplicate, question
