### ISSUE TITLE
Add other query parameters when filtering for Category with URL rewrites

### ISSUE THREAD

**Issue by subbu1993** [Smile-SA/elasticsuite#1885] opened 2020-07-22 21:30 UTC
When URL rewrites are enabled, all query parameters are stripped in the layered navigation filter for Category filters. This is not okay

### Preconditions

Magento Version : 2.3.5-p1

ElasticSuite Version : 2.9.1

Environment : Production

Third party modules :

### Steps to reproduce

1. Enable Category URL rewrites
2. Go to a category page and filter by anything other than category
3. Click on the category filter

### Expected result

1. All filters before the category filter should be retained

### Actual result

1. All filters are removed

Doing a simple patch like the following should fix the issue https://github.com/Smile-SA/elasticsuite/pull/1884/commits/feb817b6efbdf202d3a3470e1d5d630d5b3fe5bc

**Comment by subbu1993** [comment] 2020-08-13 15:41
@romainruaud - thanks for acknowledging.
I opened a PR with this functionality #1884

**Comment by rbayet** [comment] 2021-01-07 15:51
Hello @subbu1993,

The issue is that this behavior of losing the attribute filters when jumping from a category to a child category in catalog navigation is consistent with the Magento one.

We offer the possibility of **not** losing all attribute filters and apply the category filter value "locally" by switching to "No" the admin settings "Store Configuration > Elasticsuite > Catalog Search > Use URL Rewrites for Category Filter in category navigation".
We cannot accept your PR as it is, as it would unilateraly impact too many people and change the default logic.

To introduce a third navigation mode where 
- the URL rewrites are used in catalog navigation for the category filter
- but the attribute filter values are kept

We would need an additional store configuration settings, dependent (ie shown on when) on "Store Configuration > Elasticsuite > Catalog Search > Use URL Rewrites for Category Filter in category navigation = Yes", named for instance
- "Keep current attribute filters when changing category" and valued by default to "No"
- or "Reset current attribute filters when changing category" and valued by default to "Yes"

Regards,

**Comment by romainruaud** [comment] 2021-02-17 08:12
I close this one since it has been answered.

**Closed by romainruaud** 2021-02-17 08:12 UTC
Labels: enhancement
