### ISSUE TITLE
Remove price slider?

### ISSUE THREAD

**Issue by blueflykeelo** [Smile-SA/elasticsuite#1025] opened 2018-08-05 16:34 UTC
I don't wish to use the price slider and would rather have clickable price ranges. I don't see anywhere to configure this, so how do I change it in the code?

Magento Version :
CE 2.2.5

ElasticSuite Version :
Latest

Environment :
test/prod

**Comment by romainruaud** [comment] 2018-08-09 09:19
Duplicate of #555.

**Closed by romainruaud** 2018-08-09 09:19 UTC
Labels: duplicate
