### ISSUE TITLE
Fatal error dependency injection on category overview backend (ES 2.5.1)

### ISSUE THREAD

**Issue by edwinbos** [Smile-SA/elasticsuite#760] opened 2018-02-16 08:29 UTC
When we installed the latest version of the ElasticSuite (2.5.1), everything works except the category overview in the backend. The following error is given:

```
Fatal error: Uncaught TypeError: Argument 1 passed to Smile\ElasticsuiteCatalog\Plugin\Ui\Category\Form\DataProviderPlugin::__construct() must be an instance of Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\FilterableAttribute\Category\CollectionFactory, instance of Magento\Catalog\Model\ResourceModel\Product\Attribute\CollectionFactory given, called in /var/www/releases/20180215151117/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 111 and defined in /var/www/releases/20180215151117/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/Ui/Category/Form/DataProviderPlugin.php:40 Stack trace: #0 /var/www/releases/20180215151117/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Smile\ElasticsuiteCatalog\Plugin\Ui\Category\Form\DataProviderPlugin->__construct(Object(Magento\Catalog\Model\ResourceModel\Product\Attribute\CollectionFactory)) #1 /var/www/releases/20180215151117/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ in /var/www/releases/20180215151117/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/Ui/Category/Form/DataProviderPlugin.php on line 40
```

By removing the following virtualType  in vendor/smile/elasticsuite/src/module-elasticsuite-catalog/etc/frontend/di.xml (line: 31) the error is gone:

```
<virtualType name="Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\FilterableAttribute\Category\CollectionFactory" type="Magento\Catalog\Model\ResourceModel\Product\Attribute\CollectionFactory">
    <arguments>
        <argument name="instanceName" xsi:type="string">Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\FilterableAttribute\Category\Collection</argument>
    </arguments>
</virtualType>
```

Is this virtualType needed, because the collectionFactory is still created.

### Preconditions
Magento Version : Magento CE 2.2.2
ElasticSuite Version : 2.5.1
Elastic Search Version: 5.6 
Environment : Developer & Production

**Comment by romainruaud** [comment] 2018-02-19 13:48
This one is really strange for several reasons : 

- **frontend** dependency injection causing issues in the **backend**
- The frontend should not continue to work if you remove this piece of DI.
- I am not able to reproduce your issue on my environment.

Did you process setup:upgrade and clean the di and the generated classes after installing the latest version of the module ?

**Comment by afoucret** [comment] 2018-02-20 16:14
As @romainruaud sait it is very unlikely that a frontend/di.xml modification will have any effect on the admin.

I close the issue for being not reproduced. Feel free to reopen if you can give us more detail.

**Closed by afoucret** 2018-02-20 16:14 UTC
Labels: needs update

**Comment by jruzafa** [comment] 2018-10-15 08:34
Hello,

I had the same error and it was because I had an own console command where in the constructor that set the area code frontend, the compilation was correct, but when entering the category management in the admin failed.
