### ISSUE TITLE
When a virtual category root is deleted, all products are shown

### ISSUE THREAD

**Issue by amenk** [Smile-SA/elasticsuite#1937] opened 2020-09-01 12:58 UTC
This is just for the record, don't really expect a fix, but want to have it documented in case others stumble upon it.

### Preconditions

* Create a category A and put no products into it
* Create a subcategory "B", parent A, and put some products into it
* Create a virtual category "V" below A with a the category "B" as root
* Delete the referenced category "B"

![image](https://user-images.githubusercontent.com/1087128/91854113-8aa1d300-ec63-11ea-981b-cb22328047bc.png)

In the backend it shows "entity with ID doesn't exist"

In the virtual category (another their parents, because of is_anchor) now unrelated products appear

* smile/elasticsuite 2.8.6 
* magento/product-community-edition                      2.3.4-p2   

## Expected Result

The virtual category V is empty, because it links to an invalid category

## Current Result

The virtual category V and also the parent categories seem to include all products from the catalog.

**Comment by vahonc** [comment] 2020-09-07 08:38
Hello @amenk, 

Could you please provide more details for your test case, maybe smth like a real detail example. Because from the current description it looks like a little bit blurry and not quite understood what you want to test and what you want to get or expect to see at the end result.

Best regards

**Comment by amenk** [comment] 2020-09-07 11:13
@vahonc  updated

**Comment by vahonc** [comment] 2020-09-08 13:01
Hi @amenk,

Well, now it is clearer what you have now and what you expect at the end.
But for me, your test case is still a little bit blurry. Therefore, could you please describe your preconditions step by step in more details, something like this:

> 1. Create category CategoryName1 as root (Notes: If I correctly understood it shouldn't be as a Subcategory under Default Category)
> 2. Create a virtual category CategoryName2 under CategoryName1

and so on...

This will really help us to more accurately understand your case and determine where we have a problem and offer you a solution as soon as possible.

Best regards

**Comment by amenk** [comment] 2020-09-08 13:31
@vahonc  edited

**Comment by vahonc** [comment] 2020-11-27 13:10
Hello @amenk,

Sorry for the long silence on your problem. I have added a PR with a solution that should fix it. Could you please check it out or share your thoughts on this.

Best regards,

**Comment by romainruaud** [comment] 2021-01-14 14:39
Hello @amenk 

unfortunately, we will not fix this particular case.

To be clear, "virtual root category", **with the actual behavior**, is just a short-hand to creating a condition on "category = X" on the rule section. It was supposed to do more (automatically generate category filters according to the childrens of the root category, etc....) but that's still not the case right now.

That being said, the "virtual root category" condition is added to the virtual rule query as a pre-filter, meaning that : 

- if you have "virtual root category = B" and "color = blue" condition. The generated query is a combination of both.
- if you delete the category B, the resulting category will feature "blue products" across all the catalog : the generated query only fetch blue products.

The same does apply in your case, except you only have a virtual root category, meaning that if you delete your root category, you end up with a query having no filter clause at all : this will fetch the entire catalog.

So despite being quite of an edge case, it's in our opinion working as intended.

Regards

**Comment by amenk** [comment] 2021-01-14 16:22
fair enough, makes sense.
@romainruaud thank you for your elaborate feedback, and keep up the great work at the module :)

**Comment by romainruaud** [comment] 2021-01-28 15:26
You're welcome, I close the issue then

**Closed by romainruaud** 2021-01-28 15:26 UTC

**Comment by amenk** [comment] 2021-03-30 07:49
We had the problem again and were wondering if there is SQL query to identify such problems, so we could at least add it to the monitoring.
