### ISSUE TITLE
Products in Virtual Categories are not displayed if sorting mode is 'automatic'

### ISSUE THREAD

**Issue by PauGNU** [Smile-SA/elasticsuite#456] opened 2017-06-21 09:46 UTC
### Preconditions

Magento Version : 2.1.4

ElasticSuite Version : 2.3

Environment : Production

Third party modules : 

### Steps to reproduce

1. Create a new category and select the type 'Virtual'
2. Add a condition (in my case, I created a condition to show all the products from type 'Default')
3. Save the category

### Expected result

1. All the products should be displayed on the category

### Actual result

1. No products are displayed in the category
2. However, if I edit the category in the backoffice and set the order to 'Manual Sort', the products are displayed in the category

**Comment by gewaechshaus** [comment] 2017-06-21 11:20
I can confirm that bug on MCE2.1.7. My condition is 

     If ANY  of these conditions are TRUE :
     Only discounted products 

**The Actual result:**
Even with manual sorting enabled on all products, I don't see any products in the frontend category. The backend product selection is correct, so the condition should be fine.

**Comment by romainruaud** [comment] 2017-06-21 13:49
I will take a look on this one.

Regards,

**Comment by romainruaud** [comment] 2017-06-27 13:08
For now, I am unfortunately unable to reproduce this issue on my testing environment.

@PauGNU since you are sitting next to me at Smile, I will ask you more informations :)

@gewaechshaus : do you specify a "Virtual Root Category" to your virtual category ? Are you using multiple stores instance ? If yes, in which store view are you previewing the category in the back office ? And also, how are your indexers configured ? On Update or Scheduled ?

Regards,

**Comment by gewaechshaus** [comment] 2017-06-27 13:45
@romainruaud 

1) Yes, the switch is active
2) Yes I do, but I didn't change the scope so I did set it in "View all stores" mode. I just did a quick check but can't notice any difference in backend when switching the store/storeview.
3) Currently running in sheduled mode...

Thanks!

**Comment by romainruaud** [comment] 2017-06-27 15:28
We fixed the issue of @PauGNU  by just updating ElasticSuite to the latest release.

@gewaechshaus which version are you using ? Versions prior to 2.3.5 contains this bug.

Regards

**Comment by gewaechshaus** [comment] 2017-06-27 16:03
@romainruaud 

I will have to look in detail, but my composer said
     "smile/elasticsuite": "^2.3",

**Comment by romainruaud** [comment] 2017-06-27 16:05
You can check by running this command : 

`composer show | grep elasticsuite`

**Comment by gewaechshaus** [comment] 2017-06-27 16:06
THX, that's good to know... Had a 2.3.5 and been actualy updating to 2.3.6.

**Comment by romainruaud** [comment] 2017-06-27 16:09
This bug should have been already fixed in the 2.3.5. That's strange.

Could you please attach a screenshot of how is configured your category in the BO ? So that I am able to reproduce it on my own.

Please also ensure that the cron is working properly to reindex all the fly all products data.

Regards,

**Comment by gewaechshaus** [comment] 2017-06-28 11:16
@romainruaud - for sure, sorry for the delay

https://www.awesomescreenshot.com/showImage?img_id=2618570

Cron is working, we got some tools to monitor this...

**Comment by romainruaud** [comment] 2017-07-05 11:56
Initial issue by @PauGNU has been fixed by upgrading the module.

I close the issue for our internal visibility processes. 

@gewaechshaus : I cannot see anything in your link to the screenshots. Please open a new issue with full details if you are still facing the problem.

Best regards,

**Closed by romainruaud** 2017-07-05 11:56 UTC
Labels: bug

**Comment by gewaechshaus** [comment] 2017-07-05 12:41
@romainruaud - it was on my todo list to post here ;) After deleting the category and creating a new one everything did work as is should. I somebody will stumble upon this...
