### ISSUE TITLE
Crazy URL path bug

### ISSUE THREAD

**Issue by gewaechshaus** [Smile-SA/elasticsuite#2724] opened 2022-09-30 07:47 UTC
Hello,
Hello @romainruaud, Hello @hostep 

### Preconditions
Magento Version : 2.4.4
ElasticSuite Version :2.10.11
Environment : Affects all modes

### Steps to reproduce
1. Enable Elasticsuite
2. Visit the frontend and hit a 2nd or 3rd level category (the level isn't really relevant). If your URL is something like https://www.example.com/foo/bar/baz.html (It depends on the setting: Store -> Configuration -> Catalog -> Catalog -> SEO -> Category URL Suffix) the URL would be reachable and routed to the category under:
- https://www.example.com/foo/bar/baz/
- https://www.example.com/foo/bar/scifi/url/baz.html
- ...
You can generate every URL as long as the /baz/ segment is kept. This has great potential to generate a lot of duplicate content on competitors running the same setup. Or duplicate content cause of internal typos. It is also affecting the routing of 3rd party modules which won't be able to render their content if there's a category URL for the last segment of the URL.
3. As I didn't inspect the code for now, I verified that this is caused by elastic by disabling all smile modules, bin/magento indexer:reindex and bin/magento c:f 

Cheers
Jan

**Comment by romainruaud** [comment] 2022-09-30 08:49
Duplicate of #2628 which is an ongoing fix.

Regards

**Closed by romainruaud** 2022-09-30 08:49 UTC
