### ISSUE TITLE
Facing issue when navigate the category page.

### ISSUE THREAD

**Issue by ezestrajesh** [Smile-SA/elasticsuite#556] opened 2017-10-09 11:33 UTC
1 exception(s):
Exception #0 (Exception): Warning: call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in /var/www/html/Similac/AbbottStore/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Layer/Filter/Category.php on line 153

**Comment by romainruaud** [comment] 2017-10-09 12:08
Hello @ezestrajesh 

Please follow the guidelines for submitting an issue : 


### Preconditions



Magento Version :


ElasticSuite Version :


Environment :


Third party modules :

### Steps to reproduce

1.
2.
3.

### Expected result

1.

### Actual result

1. [Screenshot, logs]

**Comment by ezestrajesh** [comment] 2017-10-11 06:56
Hello,


Please find below details


Preconditions

Magento Version : 2.1.9 (EE)

ElasticSuite Version : Latest , installed using composer 1.4.1

Environment : Test

Third party modules : No

Steps to reproduce

  1.   Installed using composer
  2.   navigate category page.
  3.   On category page that error has coming

Expected result

  1.  Product listing in category page should display

Actual result

     getting error :



1 exception(s):
Exception #0 (Exception): Warning: call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in /var/www/html/Similac/AbbottStore/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Layer/Filter/Category.php on line 153?


I am working with Magento default , Please let me know hot fix it.


Please let me know

Thanks & Regards
Rajesh Rathod
________________________________

**Comment by afoucret** [comment] 2017-10-17 13:26
Looks like you did'nt run setup:upgrade after you have installed ElasticSuite.

**Comment by afoucret** [comment] 2017-10-26 07:33
As this issue was not updated since more than 7 days and we do not have enough detail on what happen, I close the issue.

Feel free to reopen if not solved and you have more information.

**Closed by afoucret** 2017-10-26 07:33 UTC
Labels: needs update

**Comment by Hesoy** [comment] 2018-06-12 13:28
Same issue M2 v2.2.1. setup:upgrade was ran successfully.
