### ISSUE TITLE
Disable automatic engine selection and reindex on module install.

### ISSUE THREAD

**Issue by siimm** [Smile-SA/elasticsuite#780] opened 2018-02-22 11:47 UTC
[Patch_no_engine_select_and_no_reindex_on_setup.patch.txt](https://github.com/Smile-SA/elasticsuite/files/1747728/Patch_no_engine_select_and_no_reindex_on_setup.patch.txt)

### Preconditions
- any Build- or offline server e.g. jenkins or similar to build the project with Elasticsuite module. Basically any machine which is not having ElasticSearch server configured at the default location of localhost:9200, but is installing the module.

- Magento Version : 2.2.2 EE (irrelevant at this point)

- ElasticSuite Version : 2.5.1 (also present in master)

- Environment : Production mode and Developer mode

- Third party modules : irrelevant

### Steps to reproduce

1. Install the module without having any ES server available (or having it elsewhere than localhost:9200)
2. Encounter an error in setup scripts

### Expected result

1. Module should install without any errors and it would be up to admin/user to activate elasticsuite as the search engine

### Actual result

1. Error complaining about having no active EasticSearch nodes available

### Patch
Since there seems to be some kind of permissions problems while creating pull request, attaching patch to this issue.

**Comment by afoucret** [comment] 2018-02-22 14:23
This problematic have already been responded in many issues.

We consider that nobody is installing ElasticSuite in order to keep it disabled, so if you install ElasticSuite, you need an ElasticSearch server running at install time ... just as you need a MySQL server ...

If you are running a build process that install / upgrade Magento, I suppose you have MySQL available. Why would you want having a build system that reproduce only partially your target environment and test it with different indexer than thoose that will actually be used ? Since the response is in the question, you have to install an ElasticSearch server in your build system.

About using a different server than localhost:9200, you have several option documented here : https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall

This have been debated a lot with the community, so I close the issue.

BR,

**Closed by afoucret** 2018-02-22 14:23 UTC

**Comment by siimm** [comment] 2018-02-22 14:45
Thanks for the explanation. 
One more question if possible:
Why was it decided to index 2 indexes during the setup? (elasticsuite_categories_fulltext and elasticsuite_thesaurus)
Any particular reason why catalogsearch_fulltext was left out of the installation process ? As the functionality is overwritten on module install.

**Comment by afoucret** [comment] 2018-02-22 14:46
`catalogsearch_fulltext` indexing is already triggered by the Magento_CatalogSearch module.
We only trigger the ones we have created.
