### ISSUE TITLE
How to change catalog search reslut ordered?

### ISSUE THREAD

**Issue by ivankakurov** [Smile-SA/elasticsuite#1383] opened 2019-04-17 13:42 UTC
I need to sort result in catalog search by exact rules 
Example :  I search from "Pencil", result need to ordered:
1. If product name started whit exact search string . - first "name like  #"{string}" "
2. If product name contains exact search string.  - second "name like "{string} %" "
3. If product search string is start of another string in name. "name like "%{string} %"
4. If product search string is part of another string in name. "name like "%{string}%"
5. If product search string is end of another string in name. "name like "% {string}%"

In mysql my query like this: 
```php
 $scoreQuery_exact = '(search_index.attribute_id = '.(int)$attribute_id.' AND search_index.data_index like "'.$queryValue.' ") ';
                    $scoreQuery_start = '(search_index.attribute_id = '.(int)$attribute_id.' AND search_index.data_index like "'.$queryValue.' %") ';
                    $scoreQuery_where = '(search_index.attribute_id = '.(int)$attribute_id.' AND search_index.data_index like " %'.$queryValue.' %") ';
                    $scoreQuery_end = '(search_index.attribute_id = '.(int)$attribute_id.' AND search_index.data_index like "%'.$queryValue.'% ") ';
```

**Comment by romainruaud** [comment] 2019-04-17 14:07
Short answer : you can't.

I close this one for being a duplicate of #1294

**Closed by romainruaud** 2019-04-17 14:07 UTC
Labels: question
