### ISSUE TITLE
it looks like Smile-SA / Elasticsearch does not support configurable product

### ISSUE THREAD

**Issue by rugandroll** [Smile-SA/elasticsuite#641] opened 2017-11-30 07:33 UTC
i installed the module with no problem. when i go to a category with configurable products i get "We can't find products matching the selection." but when i go to a category with simple products everything is working fine. i have reindexed couple of time, but still doing the same.
configurable product category page: http://plain.rugandroll.com/new-rugs.html
simple product category page: http://plain.rugandroll.com/antique-rugs.html

on new rugs category my configurable  product are set to be visible only on catalog and for its child products to be visible in search.

on antique rugs category my simple products are set to be visible on both catalog/search and on this category there is no configurable product

### Preconditions

Magento Version : 2.2.1 CE

ElasticSuite Version : 2.4.6

Environment : Developer

Third party modules : NON

**Comment by afoucret** [comment] 2017-11-30 08:40
Configurable products are fully supported by ElasticSuite.
Looks like a bug or a misconfiguration.

@romainruaud : can you test this visibility combination ?

**Comment by romainruaud** [comment] 2017-11-30 08:41
Yes I will have a look on this one but it seems strange to me too.

**Comment by rugandroll** [comment] 2017-11-30 08:54
@afoucret  i have changed the visibility of the configurable product itself to be visible both on catalog/search and still the same

**Comment by afoucret** [comment] 2017-11-30 08:58
Since our dev dataset contains a lot of configurable products, I think there is a problem with your dataset.

As the PR #640 applies to configurable products, I suspect it can solved your problem. Especially if some simple products are assigned to several configurable products.

I merged it this morning in the branch 2.4.x. Can you test it by switching ypur project to this branch ?

**Comment by rugandroll** [comment] 2017-11-30 09:38
@afoucret i don't have any simple product assigned to several configurable product. if you want i can send you an export file of one of my configurable product with its simple products

**Comment by romainruaud** [comment] 2017-11-30 10:40
I did reproduce your exact test case : 

I had a category with : 

- 12 configurables products having "Visibility: Catalog / Search"
- all simple products having "Visibility : Not visible individually"

Everything was working properly.

I switched the products to : 

- all configurable products having **Visibility : Catalog**
- all the simple products associated to these configurable products are having **Visibility : Search**
- then I processed a full reindex (of all indexes)

The category is still showing my 12 products with all proper variations in swatches.

So for me, I am unable to reproduce your issue. 

Are you sure your simple products are activated properly ? The engine will discard configurable products that do not have at least one children activated. Do they show up in Search results ? They should, since they have "Visibility: Search"

Regards

**Comment by rugandroll** [comment] 2017-11-30 10:47
@romainruaud you can see it for yourself. here is my admin credential
http://plain.rugandroll.com/admin
user: admin
password:123123q

**Comment by romainruaud** [comment] 2017-11-30 11:09
The BO preview for this category is showing "Your product selection is empty for the selected Store View. If you are running a multi-store setup, please check this manual page for more informations."

So imho there is something wrong with scoping of categories. 

Preview in the BO for "Antique Rugs" is OK and showing products for the Default Store View, but not showing anything for the "All Store View" scope.

Preview in the BO for "New Rugs" is KO for both "All Store View" and "Default Store View".

How did you import your catalogs ? There might be a problem with the scoping of data, like the visibility not properly set for the "0" store.

Are you familiar with Magento Database ? You should check the product attributes data especially the values which are stored into the DB for the "visibility" and "status". 

Regards

**Comment by romainruaud** [comment] 2017-12-07 10:46
I close the issue for being non-answered for 7 days.

Also, since the problem strongly seems to be related with your environment, it cannot be part of the Open Source support we provide here on Github.

If you are interested in (paid) commercial support, you can contact both of us via aurelien.foucret@smile.fr and romain.ruaud@smile.fr and we'll be able to propose you a paid support plan.

Best regards,

**Closed by romainruaud** 2017-12-07 10:46 UTC

**Comment by caesarcxiv** [comment] 2018-03-08 20:11
Experiencing issue on 2.2.3
