### ISSUE TITLE
2.4.1 adds the contextinterface argument

### ISSUE THREAD

**Issue by davidtisn** [Smile-SA/elasticsuite#1973] opened 2020-10-23 00:24 UTC
https://github.com/Smile-SA/elasticsuite/blob/30fc0c43087d093ce5298beaf15e296cb22ce001/src/module-elasticsuite-catalog-graph-ql/Model/Resolver/Products/Query/Search.php#L85

**Comment by Quazz** [comment] 2020-10-23 11:25
Duplicate of https://github.com/Smile-SA/elasticsuite/issues/1961

**Closed** 2020-10-23 12:27 UTC
