### ISSUE TITLE
products without any categories shows up in virtual categories  with global root category as the root category and no rules set.

### ISSUE THREAD

**Issue by diadara** [Smile-SA/elasticsuite#679] opened 2018-01-04 07:46 UTC
![vr](https://user-images.githubusercontent.com/1678035/34554185-395d123c-f15e-11e7-83df-c85506cf3edf.png)

### Preconditions

Magento Version :2.1.9

ElasticSuite Version :2.3.0

Environment : Production

Third party modules :

### Steps to reproduce

1. create virtual category with root as the store category root
2. create product with catalog and search visibility which is not added to any category

![vr](https://user-images.githubusercontent.com/1678035/34554206-614e0c56-f15e-11e7-9c1d-e15fff8f4a1f.png)

### Expected result

1. product without category should not show up in any category

### Actual result

1.  product shows up in virtual category

**Comment by afoucret** [comment] 2018-01-04 08:12
Hi @diadara 

In Magento all visible (no matter if it is in search or in category) and enabled products are assigned to the root category. You can look at the native catalog_category_product_index table if you are not convinced.

Knowing this, the virtual category engine is just working as expected (as designed) and in your case the virtual category retrieve the products as it  :
* All product of the root category (all visible and enabled products)
* Apply no filter since no rule is set

This behavior will not be changed in the future.

**Closed by afoucret** 2018-01-04 08:12 UTC
