### ISSUE TITLE
Configuration for strict "contains".

### ISSUE THREAD

**Issue by Pierre-Adrien** [Smile-SA/elasticsuite#1707] opened 2020-02-11 16:33 UTC
**How can I configure Elastic Suite to search data with a strict "contains" condition ?**

I'm trying to configure Elastic Suite but I can't get what I'm looking for.
My objective is to get all the data containing strictly what the user wrote.
I want it to search on the product name and all the configured attributes too.

For example, with an attribute containing a text:
- Product A: ABCDEFG.
- Product B : EFGHIJK.

With that example, here is what I want to get:
- Search "CDEF" ==> Product A.
- Search "EFG" ==> Product A and Product B.
- Search "EFGH" ==> Product B.
- Search "ABCDEFGH" ==> NOTHING.

I cannot figure how to configure Elastic Suite to obtain such a result.

**Here is my actual configuration for the concerned attribute and for ES in general**

![attributeConf](https://user-images.githubusercontent.com/10037004/74256938-6f399f80-4cf4-11ea-9bc0-63a3c3e6c2da.PNG)
![ES_conf1](https://user-images.githubusercontent.com/10037004/74256985-7eb8e880-4cf4-11ea-879a-9bc761e1005f.PNG)
![ES_conf2](https://user-images.githubusercontent.com/10037004/74256991-8082ac00-4cf4-11ea-8659-60e8f2da4884.PNG)
![ES_conf3](https://user-images.githubusercontent.com/10037004/74256998-82e50600-4cf4-11ea-941a-cf7d1b52aac9.PNG)

Thank you in advance,
Pierre-Adrien Maison

**Comment by romainruaud** [comment] 2020-02-12 15:56
Hi @Pierre-Adrien 

I do not see a clear use case of this in real life : if you search "sta" on Amazon, there is no way you will find a play*sta*tion.

This is not how a fulltext search engine is working.

I closed this, as being a duplicate of #970

**Closed by romainruaud** 2020-02-12 15:56 UTC
Labels: question
