### ISSUE TITLE
Numeric sku not found

### ISSUE THREAD

**Issue by rikwillems** [Smile-SA/elasticsuite#524] opened 2017-09-05 08:38 UTC
We have some products that have a numeric sku (123456). These products are not found through search when querying for that sku. Products that have letters in the sku (abc123) are found when searching for the sku.

**Comment by IPeredero** [comment] 2017-09-05 10:33
https://github.com/Smile-SA/elasticsuite/issues/412

**Comment by rikwillems** [comment] 2017-09-05 11:04
Hi @IPeredero thanks for pointing me here. I must admit I have too little knowledge of Elasticsearch to make out what I need to do with all the output shown.

**Comment by southerncomputer** [comment] 2017-10-06 16:37
One option that you can do is place the ski into meta_keywords and make it searchable but break it down into its component - ie SKU 1122334455 as 1122334455,112233445,11223344,1122334,112233,11223,1122,112,11

Then make the field searchable - should do the trick, it is essentially what the reference method was doing automatically but didn't work out so hot! 

Try it!

**Comment by romainruaud** [comment] 2017-10-09 12:17
I close it since it's a duplicate of #412 which is the main topic about SKU based problematics.

Feel free to test also the attached PR #548 and tell me if it's better.

Regards

**Closed by romainruaud** 2017-10-09 12:17 UTC
Labels: duplicate
