### ISSUE TITLE
Unassigned products getting populated on category page

### ISSUE THREAD

**Issue by keyur-iksula** [Smile-SA/elasticsuite#487] opened 2017-08-05 15:43 UTC
I am have installed Magento 2.1.7 on nginx
Magento Version : 2.1.7 CE
ElasticSuite Version : 2.3.0 (even tried with 2.4.5)
Environment : Developer mode
Third party modules : No, i am not using any.

### Steps to reproduce
1. Reindex indexes successfully.
2. Flush the cache, setup:upgrade and deployed the static content, permission checked
3. Go to any category page some default products which are not assigned to that category getting populated on category page.

### Expected result

1. It should only populate assigned product. checkout attached screenshot. Bird control category having product assigned is only 2 and it is populating more than that.

### Actual result

1. [Screenshot, logs]
![screenshot from 2017-08-05 21 06 33](https://user-images.githubusercontent.com/8330275/28996641-3e2ffaa8-7a22-11e7-98d7-661c48075c4d.png)
![screenshot from 2017-08-05 21 06 15](https://user-images.githubusercontent.com/8330275/28996640-3e252862-7a22-11e7-9393-f90f7172005e.png)
![screenshot from 2017-08-05 21 17 43](https://user-images.githubusercontent.com/8330275/28996751-bdac0866-7a23-11e7-95e7-f326f007fe88.png)

**Comment by romainruaud** [comment] 2017-08-07 09:42
Hello @keyur-iksula 

How are your "Sparrow netting" and "Pigeon Netting" categories configured ? Do they have products attached ? Are they virtual categories ?

Since the module automatically set all categories to "is anchor", if there are products into child categories of "Bird Control", they will show up into the parent category.

Let me know,

regards,

**Comment by afoucret** [comment] 2017-08-10 07:42
Hi @keyur-iksula,

As explained by @romainruaud, this behavior is "by design" since all categories are anchor categories when using ElasticSuite. So, you will see all products assigned to the current category and all products assigned to it's children categories (recursively).

I close this issue since this behavior is expected when you are using ElasticSuite. Feel free to reopen if the behavior is different than the above explanation.

BR,

**Closed by afoucret** 2017-08-10 07:42 UTC

**Comment by soundararajanm1990** [comment] 2021-06-03 12:46
@romainruaud 
How to solve this issue "Unassigned products getting populated on category page"?
If any configuration or need to override in code?
Can you please advise?
