### ISSUE TITLE
Category rule "Attribute Set" not working

### ISSUE THREAD

**Issue by adyasa** [Smile-SA/elasticsuite#2582] opened 2022-06-02 05:10 UTC
When creating a virtual category, the rule "Attribute set is NOT"  doesn't have a correct impact on the displayed products. Many products that have the attribute set is still included.

### Preconditions
Create Catalog, set virtual rule to "Attribute Set is not (attribute set name)"
notice that the product that have the attribute set still appear:

![image](https://user-images.githubusercontent.com/16585826/171556387-94d096a2-a50a-4ffb-a959-a89a9b0e2d60.png)

![image](https://user-images.githubusercontent.com/16585826/171556520-29fc2750-8ffe-4b25-9968-d8dae8e3643f.png)

![image](https://user-images.githubusercontent.com/16585826/171556433-4274e560-6835-42fe-932a-f7ed0d98f969.png)

Magento Version : ver. 2.4.1

ElasticSuite Version : 3.0
![image](https://user-images.githubusercontent.com/16585826/171556779-8f72a309-66fd-44df-bef1-dd81de9d82ed.png)

Environment : Production / Staging / Development

Third party modules : -

### Steps to reproduce
1. Create Category
2. Assign Rule "Attribute Set is not Sofa Models"

![image](https://user-images.githubusercontent.com/16585826/171556967-9c1e581e-d201-4794-a69d-087c93684113.png)

4. Notice that Product that have "Sofa Models" attribute is still shown
![image](https://user-images.githubusercontent.com/16585826/171556520-29fc2750-8ffe-4b25-9968-d8dae8e3643f.png)
![image](https://user-images.githubusercontent.com/16585826/171556433-4274e560-6835-42fe-932a-f7ed0d98f969.png)

### Expected result
1. Product that have Sofa Models Attribute Set is not shown

### Actual result
![image](https://user-images.githubusercontent.com/16585826/171556387-94d096a2-a50a-4ffb-a959-a89a9b0e2d60.png)

![image](https://user-images.githubusercontent.com/16585826/171556520-29fc2750-8ffe-4b25-9968-d8dae8e3643f.png)

![image](https://user-images.githubusercontent.com/16585826/171556433-4274e560-6835-42fe-932a-f7ed0d98f969.png)

I'm hoping that you could help us with this. Thank you!

**Comment by vahonc** [comment] 2022-06-02 08:12
Hello @adyasa,

> ElasticSuite Version : 3.0
This is not correct info. To get the right version of ElasticSuite, use the following commands:
<pre>
$ composer info | grep elasticsuite
-or-
$ composer show smile/elasticsuite | grep "versions" | grep -o -E "\*\ .+" | cut -d" " -f2 | cut -d"," -f1
</pre>

Also, provide more details about the Promotion Type (promotion_type) attribute. As I understand it's a custom attribute and maybe you should check in which Attribute Sets it is included.

BR,
Vadym

**Comment by adyasa** [comment] 2022-06-03 01:56
i see, we got this
smile/elasticsuite 2.10.3
![image](https://user-images.githubusercontent.com/16585826/171771755-986c1e83-6bb0-4727-b9f9-821e1328bfec.png)

**Comment by vahonc** [comment] 2022-06-03 07:30
@adyasa,
>smile/elasticsuite 2.10.3

Thank you, this is correct info.

What about my other questions?

BR,
Vadym

**Comment by adyasa** [comment] 2022-06-07 02:22
>Also, provide more details about the Promotion Type (promotion_type) attribute. As I understand it's a custom attribute and maybe you should check in which Attribute Sets it is included.

Here the setting of Promotion Type (promotion_type) attribute:
![image](https://user-images.githubusercontent.com/16585826/172281325-29adcddd-b776-448f-855b-a5e241bbc69c.png)
![image](https://user-images.githubusercontent.com/16585826/172281344-70f1acfb-53e0-4b8d-a14f-d1a7b844081a.png)
![image](https://user-images.githubusercontent.com/16585826/172281362-8a483f36-1b0d-43b8-967a-8e97268b019c.png)
![image](https://user-images.githubusercontent.com/16585826/172281374-a4aa86bf-0897-4374-baef-dca40a97fa22.png)


>Provide more details about your virtual category root (Australia). Does this category have child categories and are there other virtual categories below it.
Yes the root category have virtual category, its only in Sale Category
![image](https://user-images.githubusercontent.com/16585826/172281653-1c631025-054a-4dad-b53c-3c8be963fe56.png)

>Also please provide an extract of the queries that are being sent to ES when you are browsing your virtual category. You can get it from the system.log file if you activate the Debug mode of Elasticsuite in: Stores -> Configuration -> Elasticsuite -> Base settings -> Elasticsearch Client -> Enable Debug Mode

here the system log
[system.log](https://github.com/Smile-SA/elasticsuite/files/8849581/system.log)

**Comment by romainruaud** [comment] 2022-06-09 13:49
For me it's a duplicate of https://github.com/Smile-SA/elasticsuite/issues/2299

The generated query has a "should" as the root clause, instead of a "must".

This is probably due to the fact that there are an imbrication of virtual categories inside virtual categories : Sofa Sales is under Sales.

A possible workardound would be to replace "Virtual Category Root : Australia" by a clause in the rule on "Category is one of : Australia".

**Comment by vahonc** [comment] 2022-06-09 14:13
@adyasa,

As I understand provided by you conditions (with Promo Type attribute and AtrributeSet is not Sofa Models) belong to the Sale category, which is a virtual category. And as I see on your screenshot this category has few child categories. Are they also virtual and have some rules? If so, please provide a list of rule conditions for them. We think that this issue could be linked to cases with complicated rule conditions.

BR,
Vadym

**Comment by adyasa** [comment] 2022-06-10 03:49
Yes, category inside Sale category is also virtual categories with each category has its own rule
![image](https://user-images.githubusercontent.com/16585826/172986588-5debbb82-2eb8-4cd0-81c5-98bd19c35473.png)
![image](https://user-images.githubusercontent.com/16585826/172986614-995f959c-5dca-4c1f-9ae8-0c41b31c0395.png)

**Comment by romainruaud** [comment] 2022-11-30 16:56
Short version : 

- You should not use Virtual Categories for doing your complete category tree.
- You should do this in a dedicated product management solution (Akeneo, etc...).
- Using Elasticsuite virtual categories to do this, especially with such complicated imbrications (virtual categories that have virtual childrens that are also referencing other categories elsewhere).

Long version : 

You have to keep in mind that when computing category/product association for a high-level category (or the search result page), the engine will build a complex query to assemble all the products belonging to the currently viewed category :

- products belonging to non-virtual children of the current category
- products matching one of any virtual children of the current category

The resulting query could end up being quite complex and adding pressure to the computation mechanism done by Elasticsearch. That’s why, due to the current situation, we strongly recommend to not using them for the whole category tree.

That's not the purpose behind virtual categories : they are designed to build ephemeral categories, such as dynamic corners : “special father day”, “actually discounted products”, “new products” and so on.

They are not a tool to automatically attach products to categories but a merchandising mechanism.

Let’s take a common misconception as an example : using some field that will never change to build virtual categories based on that. The most often occurring is the “create virtual categories based on brand”. A brand will never change, a Weber barbecue will alway be a Weber : if you want to define brand categories, it should be done either during the import process (with a brand/category mapping), or even earlier into the Product Management system.

Virtual categories are here to help the merchants to create either an ephemeral category, or a category based on something that will often change : discount, stock, total number of sales, etc…

And on top of that, since those categories are "virtual", the relationship between them and the products they contains is not materialized in the database, making them unable to be used for promotion rules, sitemap export, etc...

So for me, this usage could be worth a refinment on the catalog modelization.

**Closed by romainruaud** 2022-11-30 16:56 UTC
