### ISSUE TITLE
Indices and Product list not showing

### ISSUE THREAD

**Issue by joebassi** [Smile-SA/elasticsuite#2084] opened 2021-02-26 00:37 UTC
### Preconditions

Magento Version :  ver. 2.3.5-p2

ElasticSuite Version : 2.9.0

Environment : Both

Third party modules : Amasty - Custom Forms, Infortis-Ultimo Theme

### Steps to reproduce

1. We have 2 Magento Sites, on Site A, we're able to index and view products, but on Site B after indexing we get "We can't find products matching the selection" for the product list
2.  At beginning we only had 1 (ElasticSearch) node for both sites and both sites were indexing to that, now we added another node for Site B, but still get the issue
3.  Also on Admin menu, the Indices link (under Elasticsuite --> System)  is missing on Site B as well.

### Expected result

1.  Should see list of products on frontend
2. Should see Indices menu on admin and when clicked on, then should see list of Indices
![list](https://user-images.githubusercontent.com/3721939/109237971-81637000-7787-11eb-9292-d58fb9f438a7.png)
![indices](https://user-images.githubusercontent.com/3721939/109237972-81fc0680-7787-11eb-96ea-1302fb274ff1.png)

### Actual result

1. [Screenshot, logs]

**Comment by romainruaud** [comment] 2021-04-28 08:56
@joebassi any new elements on this one ?

To be honest it's impossible to reproduce this on any of our dev environment not projects.

**Comment by joebassi** [comment] 2021-04-28 14:31
Using command line for now, but if I have anything new, I will update.
Could be related to our data and/or theme (Ultimo), we did do a data sync from M1 on this site.

Thanks.

**Comment by romainruaud** [comment] 2021-04-30 07:39
Okay, I'll close this one since it does seem to be related to your specific website.

Best regards

**Closed by romainruaud** 2021-04-30 07:39 UTC
