### ISSUE TITLE
Product carousel widget sorting doesn't work

### ISSUE THREAD

**Issue by davidtabat** [Smile-SA/elasticsuite#3420] opened 2024-10-23 06:10 UTC
Product grid sorting works, but product carousel sorting not.

Adobe Commerce ver. 2.4.6-p3

[ElasticSuite](https://elasticsuite.io/) Premium ver. 2.11.5.3
bug, persists on both developer and production environments

### Steps to reproduce
1.create product grid in pagebuilder, like this: 
![image](https://github.com/user-attachments/assets/6e1ac5ae-0689-423a-b954-4e4698f43117)
2.Save and check sorting on frontend.
3.Resave same widget as carousel, now sorting on frontend will be different, (wrong)

This is request send to opensearch/elasticsearch for grid: {"size":5,"sort":[{"sku.sortable":{"order":"DESC","missing":"_first","unmapped_type":"keyword"}},{"_score":{"order":"desc"}},{"entity_id":{"order":"desc","missing":"_first","unmapped_type":"keyword"}}],"from":0,"query":{"constant_score":{"filter":{"bool":{"must":[{"bool":{"must":[{"bool":{"must":[],"must_not":[],"should":[{"match":{"sku.untouched":{"query":"101868-100-01","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"101872-293-01","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"102066-170-01","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"101866-293-01","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"101848-668-01","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"101910-612-01","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"101904-668-01","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"101898-105-01","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"101925-668-01","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"101831-293-01","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"101809-292-01","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"101921-292-01","minimum_should_match":"100%","boost":1}}}],"minimum_should_match":1,"boost":1}}],"must_not":[],"should":[],"boost":1}},{"terms":{"visibility":[2,4],"boost":1}},{"terms":{"visibility":[2,4],"boost":1}}],"must_not":[],"should":[{"term":{"stock.is_in_stock":{"value":true,"boost":1}}},{"term":{"out_of_stock_notify_enabled":{"value":true,"boost":1}}}],"minimum_should_match":1,"boost":1}},"boost":1}},"aggregations":{"attribute_set_id":{"terms":{"field":"attribute_set_id","size":10000,"order":{"_count":"desc"}}},"indexed_attributes":{"terms":{"field":"indexed_attributes","size":10000,"order":{"_count":"desc"}}}},"track_total_hits":true}

This is request sent for carousel, (as you can see sku sorting is missing):

{"size":10,"sort":[{"_score":{"order":"desc"}},{"entity_id":{"order":"desc","missing":"_first","unmapped_type":"keyword"}}],"from":0,"query":{"constant_score":{"filter":{"bool":{"must":[{"bool":{"must":[{"bool":{"must":[],"must_not":[],"should":[{"match":{"sku.untouched":{"query":"101868-100-01","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"101872-293-01","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"102066-170-01","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"101866-293-01","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"101848-668-01","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"101910-612-01","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"101904-668-01","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"101898-105-01","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"101925-668-01","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"101831-293-01","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"101809-292-01","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"101921-292-01","minimum_should_match":"100%","boost":1}}}],"minimum_should_match":1,"boost":1}}],"must_not":[],"should":[],"boost":1}},{"terms":{"visibility":[2,4],"boost":1}},{"terms":{"visibility":[2,4],"boost":1}}],"must_not":[],"should":[{"term":{"stock.is_in_stock":{"value":true,"boost":1}}},{"term":{"out_of_stock_notify_enabled":{"value":true,"boost":1}}}],"minimum_should_match":1,"boost":1}},"boost":1}},"aggregations":{"attribute_set_id":{"terms":{"field":"attribute_set_id","size":10000,"order":{"_count":"desc"}}},"indexed_attributes":{"terms":{"field":"indexed_attributes","size":10000,"order":{"_count":"desc"}}}},"track_total_hits":true}

**Comment by romainruaud** [comment] 2024-10-23 08:50
Duplicate of #3401

**Comment by romainruaud** [comment] 2024-10-28 14:12
Closed because #3401 was fixed

**Closed by romainruaud** 2024-10-28 14:12 UTC
Labels: duplicate
