### ISSUE TITLE
sorting is not applying for customer product attributes

### ISSUE THREAD

**Issue by i95devdivya** [Smile-SA/elasticsuite#935] opened 2018-06-04 13:53 UTC
Preconditions
1.	Magento EE 2.1.3
2.	PHP 7
3.     ElasticSuite 2.3.x 
Steps to reproduce

1. Product Attribute sku is set to "Used for Sorting in Product Listing"
2. Open Category Page and sort by sku

Expected result
1. Sorting should be applied properly based on SKU
Actual result
1. Sorting is not applying properly based on SKU

Note: In default Magento its working fine. After integrating elastic suite we are getting this issue.

**Comment by romainruaud** [comment] 2018-06-04 13:57
Hello @i95devdivya 

could you give us more insights ? Especially if you did process a reindex after setting the SKU as used for sorting, and also if your category pages is featuring composite products (configurables, bundles...).

Regards

**Comment by afoucret** [comment] 2018-06-04 14:01
@romainruaud : it is kind of duplicate of #920 

The SKU is a very special attribute and its settings (search weight, sortable, ...) can only be set by modifying elasticsuite_indices.xml.

Two options :
- avoid modification from admin since it can be dangerous
- have a proper merge of default settings (elasticsuite_indices.xml) and the db settings in the attribute datasource

BR,

**Comment by afoucret** [comment] 2018-06-04 14:06
@i95devdivya 

See my note bellow,

Additionally, for configurable product we are indexing all SKUs from all simple children under the configurable SKU. Result of sorting can become unpredictable ...

In your case and even if my previous point were fixed, I think you will have to duplicate the SKU value in another attribute (main_sku) and make it sortable.

**Comment by i95devdivya** [comment] 2018-06-04 14:10
Can you please explain clear what we have to do over here
**have a proper merge of default settings (elasticsuite_indices.xml) and the db settings in the attribute datasource**

And also we are displaying only parent items in the front end not an associated items.

**Comment by afoucret** [comment] 2018-06-04 14:14
Actually nothing ...
It is something that should be fixed in the ElasticSuite core (that why I have ping @romainruaud).

Even with this visibility children skus will be indexed into the parent.
It have been added since lot of users wanted to be able to search for configurable using children skus.

**Comment by i95devdivya** [comment] 2018-06-04 14:17
Ok Thanks for the information. But Can I know when the issue will be fixed?

Because one of our client required this feature to be implemented ASAP.

**Comment by afoucret** [comment] 2018-06-04 14:19
We do not provide such an SLA for the community project but only for our paid support client.
We try to be as fast as possible to give solution to our community member but that being said, we are very busy these days.

**Comment by i95devdivya** [comment] 2018-06-04 14:28
OK but try to provide solution ASAP.

**Comment by afoucret** [comment] 2018-06-07 07:43
A small update on this one.

In the latest versions of ElasticSuite, sku field have been made sortable by code as you can see in in `src/module-elasticsuite-catalog/etc/elasticsuite_indices.xml`:

```
<field name="sku" type="string">
    <isSearchable>1</isSearchable>
    <isUsedForSortBy>1</isUsedForSortBy>
    <isUsedInSpellcheck>1</isUsedInSpellcheck>
    <defaultSearchAnalyzer>whitespace</defaultSearchAnalyzer>
</field>
```

You should be able to sort by SKU if you update to branch 2.5.x.
You should be able to backport the `<isUsedForSortBy>1</isUsedForSortBy>` by overriding the config in a custom module but we do not have any idea of what impact it can have with branch 2.3.x.

We won't backport it by ourselves since it is now an outdated version which is not part of our community support anymore.

As explained before, if you are using composite products our advice is to duplicate the sku of the parent product (configurable in your case), in a new attribute (let call it main SKU) you can sort on.

I close because:
* Your issue is for an outdated version of ElasticSuite we don't support anymore
* The SKU have been made sortable in newer versions
* A workaround is proposed for composite products

**Closed by afoucret** 2018-06-07 07:43 UTC

**Comment by i95devdivya** [comment] 2018-10-03 15:05
Is elastic suite branch 2.5.x compatible with Magento EE 2.1.3?

If not which version of elastic suite compatible with Magento EE 2.1.3.
