### ISSUE TITLE
Product name not showing in autocomplete

### ISSUE THREAD

**Issue by surajiiitm** [Smile-SA/elasticsuite#652] opened 2017-12-07 11:46 UTC
Hi, I am trying to get the product related to terms in search bar as auto complete but it's not showing any product. 
Like I want to get suggestions for plywood but nothing is displayed but if there is any spelling mistake like plywoods or any thing like plywook, it give the correct suggestion but no suggestions for the exact product name.
So, It is not giving suggestion for exact product in auto complete but it suggest correct product for spelling mistakes in product name terms.

Please suggest what would be the possible solution.

**Comment by romainruaud** [comment] 2017-12-07 11:50
@surajiiitm I'm sorry but I have to close this issue since you are ignoring the issue template.

Please fill in another issue and complete the template properly, especially regarding the components versions.

Please also attach screenshots of your products data and a reproductible scenario for the bug.

Regards.

**Closed by romainruaud** 2017-12-07 11:50 UTC
