### ISSUE TITLE
trim(): Argument #1 ($string) must be of type string, array given

### ISSUE THREAD

**Issue by Nuranto** [Smile-SA/elasticsuite#2595] opened 2022-06-06 15:19 UTC
Hi there,

Here is bug I get when trying to reindex on a specific project : 
```
#1 /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Helper/AbstractAttribute.php(249): array_map('trim', Array)
```

M2.4.4
Smile latest

**Comment by vahonc** [comment] 2022-06-06 17:41
Hello @Nuranto,

Which version of the ElasticSuite you are using?

BR,
Vadym

**Comment by Nuranto** [comment] 2022-06-06 18:24
2.10.10

**Comment by vahonc** [comment] 2022-06-08 13:31
Hello @Nuranto,

Could you debug what you have in this [line](https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Helper/AbstractAttribute.php#L249) for `$optionTextValues` variable?

BR,
Vadym

**Comment by gewaechshaus** [comment] 2022-06-13 11:19
Hey,

we can confirm this issue.

Cheers,
Jan

**Comment by romainruaud** [comment] 2022-06-13 13:13
Hi @Nuranto 

Can you give us an exact way of reproducing the "change, for a random product, an attribute value that uses source, with a value that does not exists in source" ?

Regards

**Comment by Nuranto** [comment] 2022-06-13 14:20
Hi Romain,

Quicker way would be : `update catalog_product_entity_int set value = [unexisting_option_id] where entity_id = [existing_product_id] and attribute_id = [attribute_of_type_select_id]`, and then launch a catalogsearch_fulltext reindex

**Comment by romainruaud** [comment] 2022-06-21 13:26
This is fixed by https://github.com/Smile-SA/elasticsuite/commit/2a3bd1695d93fe2a8237b262ec862e2b44fc905d #2537 by @vsushkov 

It will be included in the next minor release. 

You can use the 2.10.x branch for now if you want to benefit from it.

**Comment by romainruaud** [comment] 2022-07-19 10:19
I close since this is fixed.

**Closed by romainruaud** 2022-07-19 10:19 UTC
Labels: bug
