### ISSUE TITLE
Maximum of 500 products per category in Magento 2.1.5 with Elasticsearch 2.3.1

### ISSUE THREAD

**Issue by diybook** [Smile-SA/elasticsuite#339] opened 2017-03-01 22:05 UTC
Maybe it is a stupid question. But after managing to run Magento 2.1.2 with Elasticsuite I've updated Magento to version 2.1.5 and Elasticsuite to Version 2.3.1.

Before updating Magento I've updated Elasticsuite first and did check the outcome. Everything worked as intended without any errors with magento 2.1.2 and Elasticsuite 2.3.1. 

But after updating Magento, it seems that eleastic search is somehow limited to display only 500 products per single category. 

For example - layered navigation shows the following: 
Antrieb 134
Abdeckungen 500 
Beleuchtung 23 
Gehäuse 500 
Sonstiges 808 
- Kleinteile 239
- Befestigung und Halterung 137 

All categories do not have any subcategory except Sonstiges. In the backend it looks like:
Antrieb 134
Abdeckungen 1773
Beleuchtung 23 
Gehäuse 1821 
Sonstiges 873
- Kleinteile 415
- Befestigung und Halterung 137

It seems a bit strange to me, beacause when disabling the elasticsuite magento shows the correct numbers. 

Any ideas on that issue? Any setting I've missed? Best regads and thanks for your help!

**Comment by romainruaud** [comment] 2017-03-02 08:23
Hello @diybook ,

thank you for submitting this issue.

Are you using any third-party modules except of ElasticSearch ?

**Comment by diybook** [comment] 2017-03-02 08:29
@romainruaud yes we do. E.g Amasty_Base Amasty_Stockstatus Apptrian_ImageOptimizer Fooman_PrintOrderPdf Fooman_EmailAttachments Magenerds_BasePrice and some own Modules. 

But I don't think that they are the issue because, deactivating elasticsearch bring up correct values. But I'll test deactivating all other modules.

**Comment by romainruaud** [comment] 2017-03-09 17:32
Hello @diybook 

I do have also very strange values in the Back-Office for the category tree. I am using Magento's sample datas.

In my case this is due to the case of there are several children of configurables which are directly assigned to categories.

When I view the categories in Front-Office, these simple products are not shown (they are "Not visible individually") which is implying that the number of products indicated in Front-Office is correct (it does only include products which are having "Visibility:Catalog").

Could you check that you are not facing the same problem ? If this is the case, this is not a bug, this is just meaning that you category does have XXX assigned products, but when viewing in Front-Office, the number shown correspond to the number of products which can be really displayed.

Best regards,

**Comment by diybook** [comment] 2017-03-09 18:24
HI @romainruaud, thanks for your input. I'm pretty sure that I'm not having this issue. Cause all my products are simple products with visibility Search and Catalog. 

Very strange is that with magento 2.1.2 the numbers are correct and with magento 2.1.5 they are not. I've first updated elasticsearch to magento 2.1.2 and then made an update of magento. 

After then the values are incorrect. When deactivating the elasticsearch module products are shown again. 

Any hint where I can start debugging that issue? Best regards!

**Comment by diwipl** [comment] 2017-03-18 13:41
@diybook This might be related to this Magento 2 bug: https://github.com/magento/magento2/issues/7968

**Comment by afoucret** [comment] 2017-03-20 09:32
Hi,

@diwipl is right. We rely on the catalog product categories index which is buggy.

Waiting for Magento to resolve the issue pointed out by @diwipl 

BR,

**Comment by diybook** [comment] 2017-03-20 19:47
Thanks @diwipl, you are right. After fixing that issue like stated on github, it seems to work. The quick fix is obviously not perfect, but is working. Hope magento will fix this bug soon. 
Thanks @afoucret for confirming that issue.

Best regards

**Comment by afoucret** [comment] 2017-03-21 06:48
As the big is not related with ElasticSuite but with Magento, I close it.

Thanks for reporting

**Closed by afoucret** 2017-03-21 06:48 UTC
