### ISSUE TITLE
trim(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by gewaechshaus** [Smile-SA/elasticsuite#2609] opened 2022-06-14 13:32 UTC
Hey

M2.4.4 + ES 2.10.10 + PHP 8.1.7

**While running**
`bin/magento indexer:reindex catalogsearch_fulltext`

**The following error is thrown:**
Catalog Search index process error during indexation process:

`trim(): Passing null to parameter #1 ($string) of type string is deprecated in /.../vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Helper/AbstractAttribute.php on line 249`

**Possible fix that doesn't work**
$optionTextValues    = array_diff(array_map('trim', $optionTextValues ?? ['']), ['', null, false]);

In our case it is related to the visibility attribute, it is getting triggered on the first product. 

Cheers,
Jan

**Comment by vahonc** [comment] 2022-06-14 14:11
Hello @gewaechshaus,

Please provide more details about the steps for reproducing your issue.

BR,
Vadym

**Comment by gewaechshaus** [comment] 2022-06-15 07:05
Helo @vahonc,

in our case we just need to reindex... It's a migrated m1 system, so maybe it's related to an unconventional visibility attribute. 
I will post all related stuff in a few minutes.

**Comment by gewaechshaus** [comment] 2022-06-15 08:26
We found the following entry in the product index mapping for the related store. Can you explain why @vahonc @hostep? We can't see this entry in another clients system. This can't be right as visibility is retrieving the mapping from the source model and using int as value...?

![Bildschirmfoto 2022-06-15 um 10 22 26](https://user-images.githubusercontent.com/7628545/173780124-d0164565-d4a7-4e78-9f7e-5cfd9983ca5d.png)

**Comment by gewaechshaus** [comment] 2022-06-15 08:49
We found it: it's related to the attributes flag is_used_for_promo_rules, we did set it to 0 and the indexer is running. We keep you updated. **Maybe you can try to set is_used_for_promo_rules to 1 to reproduce this...**

**Comment by romainruaud** [comment] 2022-06-16 13:15
The subsequent bug will be fixed as part of resolving #2595

**Comment by rbayet** [comment] 2022-06-16 14:50
Yes, in a default installation, visibility' is added to the index through the static fields (see https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/etc/elasticsuite_indices.xml#L39) of the catalog_product index definition.
Elasticsuite expects it to be indexed as in integer value, period.

But when migrating from M1, or when explicitely switching to 'true' from admin/database any property that dictates the fields to be indexed, the field will be both declared as a dynamic field and a static field.
Elasticsuite is **supposed** to handle that special case (see https://github.com/Smile-SA/elasticsuite/blob/85ebede062a9cce9f09b5b2630500c9c38dd59fe/src/module-elasticsuite-core/Index/Indices/Config.php#L183-L188) but I'm not sure it is actually the case as show by your screenshot above, @gewaechshaus.

The other issue is that 'visibility' has a specific source model (`\Magento\Catalog\Model\Product\Visibility`) which **does not** extends `\Magento\Eav\Model\Entity\Attribute\Source\AbstractSource` so it does not inherit the `\Magento\Eav\Model\Entity\Attribute\Source\AbstractSource::getIndexOptionText` method.
So this would logically pose some problems inside `\Smile\ElasticsuiteCatalog\Helper\AbstractAttribute` (for instance there: https://github.com/Smile-SA/elasticsuite/blob/85ebede062a9cce9f09b5b2630500c9c38dd59fe/src/module-elasticsuite-catalog/Helper/AbstractAttribute.php#L301).

So @romainruaud I'm not 100% fixing #2595 will also fully resolves this issue. It might just silence the behavior.

**Comment by romainruaud** [comment] 2022-06-21 13:25
This is fixed by https://github.com/Smile-SA/elasticsuite/commit/2a3bd1695d93fe2a8237b262ec862e2b44fc905d #2537 by @vsushkov 

It will be included in the next minor release. 

You can use the 2.10.x branch for now if you want to benefit from it.

**Comment by romainruaud** [comment] 2022-07-19 10:19
I close since this is fixed.

**Closed by romainruaud** 2022-07-19 10:19 UTC
Labels: bug, duplicate
