### ISSUE TITLE
Bad product reassembled in index

### ISSUE THREAD

**Issue by theozzz** [Smile-SA/elasticsuite#304] opened 2017-01-20 11:41 UTC
Hi,

We encounter a strange problem in the ES index.

In fact, when we search a bundle (query example :  _search/?q=sku:bundle-403114), an other product is returned as we can see in the name field (which is not one of children of the bundle).

[img of the ES index](http://nsa38.casimages.com/img/2017/01/20/170120125901748909.png)
[img of the Magento BO](http://nsa38.casimages.com/img/2017/01/20/170120125901866764.png)

The wrong product returned  by the query got the row_id field equals to **1568577** which is the entity_id of the researched bundle. It seems there is a confusion between the entity_id and the row_id.

Really thanks for your help.

Théo

**Comment by romainruaud** [comment] 2017-01-20 14:07
Hello @theozzz and thank you for submitting this issue.

From my first investigation, I tend to flag this one as **confirmed**.

I will look further by I suspect strongly a misuse between row_id and entity_id on the ```loadChildrens``` function.

For me this has been undiscovered previously because generally row_id and entity_id are the same at first time (this is especially true when using sample datas), but this is not the case on your project.

**Comment by theozzz** [comment] 2017-01-20 15:16
Hi @romainruaud,

Thanks for your investigation ;)

Théo

**Comment by romainruaud** [comment] 2017-01-20 15:24
This one could have an impact on configurable products too.

I am nearly sure this could explain the issue #204 which was never properly explained.

**Comment by afoucret** [comment] 2017-01-23 15:52
The PR is available on branch 2.2.x, 2.3.x, 2.4.x and master branches.
@romainruaud : let you manage the release of version 2.2.x and 2.3.x with appropriate release note (do not forget other small patches on autocomplete applied on 2.3.x).

**Comment by romainruaud** [comment] 2017-01-23 16:56
Issue has been fixed on 2.3.1

Feel free to upgrade to this version.

Best regards,

**Closed by romainruaud** 2017-01-23 16:56 UTC
Labels: bug
