### ISSUE TITLE
ES query error when virtual category enabled

### ISSUE THREAD

**Issue by jeroenkosse** [Smile-SA/elasticsuite#2389] opened 2021-12-13 12:42 UTC
### Preconditions

PHP 7.4.26
Elasticsearch: 7.9.3

Magento Version : 2.4.2 CE

ElasticSuite Version : 2.10.8.1

Environment : Developer mode

Third party modules :

### Steps to reproduce

1. When enabling a virtual category the product list in Magento admin part is correct
2. When visiting the category in the frontend no products are displayed

### Expected result

1. The products in the frontend should be visible

### Actual result

1. When the ES query is checked the following sort is in the query:

` {
      "category.position": {
        "order": "asc",
        "missing": "_last",
        "unmapped_type": "keyword",
        "nested": {
          "path": "category",
          "filter": {
            "terms": {
              "category.category_id": [
                null
              ],
              "boost": 1
            }
          }
        },
        "mode": "min"
      }
    }`

This results in the following error: `x_content_parse_exception`  [field_sort] failed to parse field [nested]

In the \Smile\ElasticsuiteVirtualCategory\Plugin\Collection\AddVirtualCategoryQuery::beforeAddCategoryFilter plugin the categoryId is unset. Then after this plugin the category \Smile\ElasticsuiteCatalog\Plugin\LayerPlugin::setSortParams layerPlugin is used and this is using the categoryId in the sort that is unset in a previous plugin.

**Comment by vahonc** [comment] 2021-12-13 14:21
Helllo @jeroenkosse

Could you provide more details with screenshots about configuration of your virtual category?

BR,
Vadym

**Comment by jeroenkosse** [comment] 2021-12-14 14:23
The settings for the virtual category are very simple. We just enable the virtual category, set the virtual category root to a specific category ( not virtual ) and use no virtual rule settings. In the product list preview in the admin the correct products will be displayed. In the front we get no products.

**Comment by romainruaud** [comment] 2021-12-15 14:46
Actually I'm not able to reproduce it.

I'm wondering why you are going through the \Smile\ElasticsuiteVirtualCategory\Plugin\Collection\AddVirtualCategoryQuery::beforeAddCategoryFilter 

I never pass inside it when browsing my category. Are you able to provide me the call stack leading to this piece of code ?

Do you have some particular widgets in this category ?

**Comment by romainruaud** [comment] 2021-12-15 15:23
Ok, I am able to reproduce it if I have a widget built on the same virtual category (maybe it's the same on another virtual category ?) on the same category page.

**Comment by romainruaud** [comment] 2021-12-15 15:35
PR #2392 contains a fix, are you able to test it ?

**Comment by jeroenkosse** [comment] 2021-12-15 17:17
I tested the fix and this is solving the issue. The products are now rendered normally and query looks okay.

**Comment by romainruaud** [comment] 2021-12-17 15:06
I close, this will be part of upcoming minor releases (beginning of january).

**Closed by romainruaud** 2021-12-17 15:06 UTC
