### ISSUE TITLE
Pagination / Page Size Not Working

### ISSUE THREAD

**Issue by brucemead** [Smile-SA/elasticsuite#1912] opened 2020-08-11 16:02 UTC
After 2.4.0 upgrade from 2.3.5-p1 pagination has stopped work and results in all products being returned. Issue relates to https://github.com/Smile-SA/elasticsuite/commit/207c5d93e730545c8e6e5829ea57a58673cff73e#diff-6a285666f9fbbc83496890ef4c186174 specifically:
```
    protected function _beforeLoad()
    {
        if ($this->_pageSize !== false) {
            $this->originalPageSize = $this->_pageSize;
            $this->_pageSize = false;
        }

        return parent::_beforeLoad();
    }
```
which once removed resolve my issue.

### Preconditions

Magento Version :  2.4.0 EE
ElasticSuite Version : 2.10.0
Environment : Developer & Production
Third party modules : N/A

### Steps to reproduce
1. Upgrade to Magento 2.4.0
2. Upgrade Smile Elasticsuite to 2.10.0

### Expected result
1. Pagination is presented based on admin configuration

### Actual result
1. All products are disabled with no pagination.

**Comment by Bashev** [comment] 2020-08-12 10:12
I create an quick fix for this #1914. Can you verify is this works for you?

**Comment by thampe** [comment] 2020-08-14 06:33
Hi,

we tested #1914. It works as expected. Thank you!

**Comment by romainruaud** [comment] 2020-08-24 07:15
I close for being a duplicate of #1903 

We'll try to release a version containing this fix very soon.

To be transparent, I was on vacations, so thank you @Bashev for taking care of this so quickly :)

**Closed by romainruaud** 2020-08-24 07:15 UTC

**Comment by romainruaud** [comment] 2020-08-24 14:10
Please upgrade to 2.10.1 which contains the fix

**Comment by jimuld** [comment] 2021-02-18 05:45
Same issue facing in latest version

**Preconditions**
Magento Version : 2.4.1 EE
ElasticSuite Version : 2.10.0
Environment : Developer & Production
Third party modules : N/A

**Comment by romainruaud** [comment] 2021-02-18 08:25
@jimuld please see my comment, you have to update to Elasticsuite 2.10.1

**Comment by jimuld** [comment] 2021-02-18 13:27
@romainruaud, sectio on "Which version should I use ?" says 2.10.1 no actively maintained, and mentioned as have to use 2.10.0 Mageno >=2.4.1

**Comment by romainruaud** [comment] 2021-02-18 14:13
You read it wrong.

Magento 2.4.0 => ElasticSuite 2.10.1 maximum, can't go higher.

Magento 2.4.1 and above => Elasticsuite 2.10.2

**Comment by jimuld** [comment] 2021-02-18 14:17
@romainruaud yes red wrong, thanks for the clarification

**Comment by jimuld** [comment] 2021-02-19 05:06
@romainruaud we upgraded to 2.10.3, still issue is there now its pagination working but showing all products on all page. For example there are 31 products in category and page size is 12, loading all 31 products on all pages

**Comment by diybook** [comment] 2021-06-16 07:40
@jimuld Could you resolve this issue. I'm having the same issue. I've updated to magento 2.4.2 and elasticsuite 2.10.4 and having the same problem you have described. All products are shown on all pages. Collection size is 38 and only 20 products should be shown per page. But all 38 products are listed. 
@romainruaud any ideas?
