### ISSUE TITLE
 bin/magento setup:static-content:deploy gives error

### ISSUE THREAD

**Issue by HRR1337** [Smile-SA/elasticsuite#76] opened 2016-07-05 13:05 UTC
Hi there. 

First: the extension looks VERY promising, and would defintly use it on live site when i'm ready with conversion to magento 2. 

I am on:

Ubuntu 16.04
Nginx 1.10
Php 7.0.7
latest elasticsearch
Magento 2.1 

I have followed the how-to to install. I am now at the point that i want to login. And beceause i didn't saw logo of login i cleared the cache and did command:  bin/magento setup:static-content:deploy .

I get the following error: 
![elastic-error](https://cloud.githubusercontent.com/assets/4428675/16585596/e962f9f0-42c1-11e6-9ae2-fa4d47222dee.jpg)

What am I doing wrong?

Thanks!

**Comment by afoucret** [comment] 2016-07-05 13:23
Hi,

I suppose you are using Magento >= 2.1.0.

This issue was documented on the homepage and you have to use the branch 2.2.x instead of the master one.

So the best things to do is to install the branch through :

```
composer require "smile/elasticsuite:^2.2@dev"
```

Then you have to run the setup again, redploy static content and reindex the fulltext.

Let me know if everything is OK once done.

**Comment by afoucret** [comment] 2016-07-05 13:23
Duplicate #69

**Comment by afoucret** [comment] 2016-07-05 13:25
Duplicate of #69

**Comment by afoucret** [comment] 2016-07-05 14:16
I close this one since it is a duplicate.
Feel free to ask for reopening it if things are not really fixed.

**Closed by afoucret** 2016-07-05 14:16 UTC
Labels: duplicate

**Comment by HRR1337** [comment] 2016-07-06 11:03
Hi there. After installing the 2.2 + clearing cache + deploy static + setting again permissions its working. Thanks.
