### ISSUE TITLE
Reindex throwing the error while executing the command from the terminal

### ISSUE THREAD

**Issue by sandipweb** [Smile-SA/elasticsuite#2656] opened 2022-07-27 09:56 UTC
### Preconditions

Magento Version: Magento 2.4.4 EE

ElasticSuite Version: 2.10.10

Environment: Production

### Steps to reproduce

1. Execute the reindex command using terminal

### Expected result

1. Should remove all errors while executing the reindex command

### Actual result

![image](https://user-images.githubusercontent.com/48554402/181218034-2aeb2f38-5039-4334-9570-4c28fc2ab8b0.png)

We have faced the issue while executing the reindex command so we have created the Magento support ticket.
Magento Support told me that the issue coming from the Smile Elasticsuite module.
Please check the screenshot 

![image](https://user-images.githubusercontent.com/48554402/181220525-87fda4be-2f31-4ad7-b9ba-075ae96dfd63.png)

Please look into this and share the solution

**Comment by romainruaud** [comment] 2022-07-27 12:21
Hi @sandipweb 

can you give us the output of the following commands : 

```composer info | grep elasticsuite```
```composer info | grep ezimuel```
```composer info | grep elasticsearch```

And also the exact version of PHP you are using.

Regards

**Comment by sandipweb** [comment] 2022-07-27 12:28
Hi @romainruaud 

We are using PHP 8.1.7 (cli) version.

![image](https://user-images.githubusercontent.com/48554402/181246320-ac02531e-c3e8-4237-b517-d099a297d0e5.png)

Regards

**Comment by sandipweb** [comment] 2022-07-27 12:41
I've checked both exception.log and system.log files

None of the entry available on the exception.log file but on the system.log file having log entries.

Please check the screenshot for your reference

![image](https://user-images.githubusercontent.com/48554402/181248850-ce7c6dc9-b5ff-46bd-a769-52de4643aab3.png)

**Comment by romainruaud** [comment] 2022-07-28 13:38
I see that @amenk already faced this issue : https://github.com/ezimuel/ringphp/pull/6

**Comment by amenk** [comment] 2022-07-28 13:51
@romainruaud Exactly. And we made a PR which is not yet merged in ringphp. We are currently using a composer patch.
Interesting enough to mention: The issue only surfaced on prod, not on our CI systems, which is pretty strange.

**Comment by romainruaud** [comment] 2022-07-28 15:57
That's not showing on our CI chain either, where everything is build on production mode and with PHP 8.1. So yes, this is a bit strange.

@sandipweb can you check if the patch from @amenk solves your issue ?

**Comment by sandipweb** [comment] 2022-07-29 05:53
Thanks @romainruaud

Yes, it works as expected.

Thanks, @amenk for sharing the solution 

[ Deprecated Functionality: curl_multi_exec():   vendor/ezimuel/ringphp/src/Client/CurlMultiHandler.php on line 133](https://github.com/ezimuel/ringphp/pull/6/commits/0b6c73b88b869bd8c2591213f54abbf0f7cdea37)

**Comment by romainruaud** [comment] 2022-08-01 13:11
I tag this as "wontfix" because the fix has to be made in ringphp library.

I let it open for now until the fix is made on ringphp so that anybody can grab the patch.

**Comment by dittertp** [comment] 2022-08-04 06:39
fyi: the error only occurs if newrelic is installed on the system.

**Comment by amenk** [comment] 2022-08-04 06:47
Oh wow, yes, I can confirm we also use newrelic. Did you dig deeper? Is it a newrelic bug?

**Comment by dittertp** [comment] 2022-08-04 06:58
no, i suspect that newrelic manipulates the errorhandler to get the logs, so a warning becomes an "Uncaught Exception".

**Comment by emirajbbd** [comment] 2022-08-12 20:10
Same issue on my cloud instance 
![image](https://user-images.githubusercontent.com/63784/184435183-dc387d9f-70af-4a73-9815-7979716b4a35.png)

**Comment by romainruaud** [comment] 2022-11-30 16:48
This has been fixed in the [ezimuel](https://github.com/ezimuel)/[ringphp](https://github.com/ezimuel/ringphp) package.

You can update this package to 1.2.1

Regards

**Closed by romainruaud** 2022-11-30 16:48 UTC
Labels: help wanted, wontfix
