### ISSUE TITLE
Error on category save

### ISSUE THREAD

**Issue by maky13** [Smile-SA/elasticsuite#328] opened 2017-02-09 11:06 UTC
Hi,

It's impossible to save a category from the BO or from the code.
We got the error `Exception' with message 'Asymmetric transaction rollback.'`
We already had this issue but I can't find any issue in github related to it.
In the error trace we have :
`#7 /var/www/avatacar/current/vendor/magento/framework/Interception/Interceptor.php(142): Smile\\ElasticsuiteVirtualCategory\\Plugin\\Catalog\\Category\\SaveProductsPositions->aroundSave(Object(Magento
\\Catalog\\Model\\ResourceModel\\Category\\Interceptor), Object(Closure), Object(Magento\\Catalog\\Model\\Category\\Interceptor))
#6 /var/www/avatacar/current/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Plugin/Catalog/Category/SaveProductsPositions.php(91): Magento\\Catalog\\Model\\ResourceModel\\Category\
\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Catalog\\Model\\Category\\Interceptor))
#5 /var/www/avatacar/current/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Framework\\Interception\\Chain\\Chain->invokeNext('Magento\\\\Catalog...', 'save', Object(Magento\\Cat
alog\\Model\\ResourceModel\\Category\\Interceptor), Array, 'smile_elasticsu...')
#4 /var/www/avatacar/current/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\\CatalogSearch\\Model\\Indexer\\Fulltext\\Plugin\\Category->aroundSave(Object(Magento\\Catalog\\Model\\R
esourceModel\\Category\\Interceptor), Object(Closure), Object(Magento\\Catalog\\Model\\Category\\Interceptor))
#3 /var/www/avatacar/current/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Category.php(29): Magento\\CatalogSearch\\Model\\Indexer\\Fulltext\\Plugin\\Category->addCommitCallback(
Object(Magento\\Catalog\\Model\\ResourceModel\\Category\\Interceptor), Object(Closure), Object(Magento\\Catalog\\Model\\Category\\Interceptor))
#2 /var/www/avatacar/current/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Category.php(67): Magento\\Catalog\\Model\\ResourceModel\\Category\\Interceptor->rollBack()
`
and then all the rollbacks methods.

I think there is some conflicts between the commit in the saveProductPositions.php (#7) file and the native magento plugin (#4).

ES : 2.3.0
Magento 2.1.2

adill from Smile

**Comment by romainruaud** [comment] 2017-02-09 11:14
Hello,

please investigate a bit more to find what is actually triggering the "Asymetric transaction rollback".

Maybe you should investigate the exception which is catched by the ```module-catalog-search/Model/Indexer/Fulltext/Plugin/Category.php``` before the line 52.

Regards

**Comment by afoucret** [comment] 2017-02-09 12:38
Hi @maky13,

I don't think the bug is linked to ElasticSuite but rather on Magento native code.
You can see ElasticSuite related classes but the bug is triggered while calling native code category save code (the `$proceed($category);` in `src/module-elasticsuite-virtual-category/Plugin/Catalog/Category/SaveProductsPositions.php(91)`). 

But as the code is using a commit callback we can be sure of anything. The best option we have to figure out what happened there would be to analyze exception raised in :

* `Magento\Framework\EntityManager\Operation\Create:l117`
* `Magento\Framework\EntityManager\Operation\Update:l116`

Make sure to dump the exception before `$connection->rollBack();`which thrown the exception.

**Comment by maky13** [comment] 2017-02-09 13:05
Unfortunately I ran a full reindex and I can't reproduce the issue anymore.
Due to the project timeline we don't have time to investigate more on this and so it will stay as is for now.
If we encounter the problem again I will come back to you with more data.

I was originally thinking of a dead lock between the commit made by ES and the one on magento side but as I said I can't reproduce it for new.

thanks for your support.

**Comment by romainruaud** [comment] 2017-02-13 11:22
If the issue is fixed at your side I close this one.

Feel free to reopen it if needed.

BR

**Closed by romainruaud** 2017-02-13 11:22 UTC
