### ISSUE TITLE
Get Virtual Categories IDs from product id(product which is filtered by product rule)

### ISSUE THREAD

**Issue by mhafizumer** [Smile-SA/elasticsuite#2076] opened 2021-02-15 10:17 UTC
**Get Virtual Categories IDs from product id(product which is filtered by product rule)**
I want to get all categories Ids from a product ID, product Id will be which we get product after applying the Virtual Rule.
let me explain you look at screenshot :

![image](https://user-images.githubusercontent.com/67052331/107932550-82361e00-6f9f-11eb-8848-617c86351e97.png)

I have applies virtual rule and products filter by colors, 3 products are filtered (sku 446745,4426,10,440150) now these 3 products are shown on frontend correctly.

Now I am trying to get category id from product id code is there
SKu **446745** has product id is **4441** so, 
```
$product = $this->product->load(4441);
        echo "<pre>";
        print_r($product->getCategoryIds());
```
**It not return the virtual category id** how can we get Category ids from a product id, this product will be get after applying virtual rule.

You have answer for this question  Product Count for a virtual category [https://github.com/Smile-SA/elasticsuite/issues/380](url)

Now can you guide me **how to  get Category count  from product id**(filtered product id by virtual rule)?

**Comment by romainruaud** [comment] 2021-02-15 13:26
Duplicate of #378

**Comment by mhafizumer** [comment] 2021-02-15 13:50
@romainruaud ticket [378](https://github.com/Smile-SA/elasticsuite/issues/378) is still open, mean there is not any method to fetch virtual categories from product?

**Comment by romainruaud** [comment] 2021-02-17 07:53
Right, there are no method to do this actually. And regarding the amount of work needed for #378, it's low priority for us right now.

Regards

**Comment by romainruaud** [comment] 2021-04-28 09:27
I close for being a duplicate.

#378 remains open but with low priority.

**Closed by romainruaud** 2021-04-28 09:27 UTC
Labels: duplicate, question
