### ISSUE TITLE
Search engine set to MySQL still call ElasticSuite

### ISSUE THREAD

**Issue by bmxmale** [Smile-SA/elasticsuite#509] opened 2017-08-23 08:58 UTC
When module is enabled and we change Catalog/Search/Engine back to MySQL, catalogsearch still call ElasticSuite and elasticsearch. 

![image](https://user-images.githubusercontent.com/23213308/29607427-7633880c-87f1-11e7-88fd-faf4576c3de7.png)
![image](https://user-images.githubusercontent.com/23213308/29607467-94e47388-87f1-11e7-8319-36d4a5b09fbb.png)

### Preconditions

Magento Version : 2.1.7

ElasticSuite Version : 2.3.6

Environment : developer

Third party modules :

### Steps to reproduce

1. Install plugin
2. Change Catalog/Search/Engine back to MySQL
3. Clean cache, DI Compile
4. On search query magento still call elasticsuite and try to connect elasticsearch node.

### Expected result

1. After change search engine to default, magento should back to mysql search.

**Comment by romainruaud** [comment] 2017-08-23 09:15
Hello @bmxmale 

This is due to the fact that many parts of the ElasticSuite module are retrieving informations from Elasticsearch (Product Collection is retrieving facets, count of products by attribute set, etc ....).

Also, there is no point using the module without setting the search engine to Smile Elasticsuite, since most of the module standard features just cannot work with MySQL engine, or with Solr or whatever.

You can consider this is by design. You have 2 choices here : 

- Use Elasticsuite with proper Elasticsuite search engine : Maybe we should set the configuration field as read-only when Elasticsuite is installed.

- Do not use Elasticsuite at all

I close this issue for now, you can reopen it if needed.

Best regards

**Closed by romainruaud** 2017-08-23 09:15 UTC

**Comment by bmxmale** [comment] 2017-08-23 10:13
When we set search engine to MySQL catalog_product indicies will not be recreated at reindex if we drop it before on elasticsearch.

https://github.com/Smile-SA/elasticsuite/issues/173#issuecomment-321014140
