### ISSUE TITLE
Error then trying to use Virtual Category for creating Page Block via PageBuilder

### ISSUE THREAD

**Issue by sergiirepin** [Smile-SA/elasticsuite#1807] opened 2020-05-12 09:15 UTC
Error then trying to use Virtual Category for creating Page Block via PageBuilder

Magento Version : Commerce 2.3.5

ElasticSuite Version : 2.9.0

Environment : develop

### Steps to reproduce

1. Select Content -> Blocks 
2. Click Add New Block
3. Drag and Drop Products from Side Bar under Add Content
4. Hover Over added Block
5. Select Edit 
6. Select Virtual Category as Category from Appearance Section
7. Click Save

### Expected result

1. Products should appear

### Actual result

1. Error appear: `Error filtering template: catalog_product index does not exist yet. Make sure everything is reindexed.` (https://i.imgur.com/ThqqUxf.png)

**Comment by romainruaud** [comment] 2020-05-13 09:06
@androshchuk can you have a look at this one ? You'll need Magento Commerce (EE) to be able to use PageBuilder module.

From what I can see, it's most likely a missing `setStoreId()` somewhere so that the category could be probably fetched for the current storeview : as seen in the screenshot, user can select "All Store Views".

**Comment by serhiirepin** [comment] 2020-05-15 07:41
Hey @androshchuk if you need any additional  info for debugging, feel free to ask.

**Comment by androshchuk** [comment] 2020-05-17 12:01
Hello @serhiirepin 
Thank you for your report.

I couldn't get the same error as you but it looks like our virtual categories don't work with PageBuilder.
my result: http://i.imgur.com/DbrJbM3.png .
For now, I'll work to fix this.
I will be grateful for any help.

Regards

**Comment by romainruaud** [comment] 2020-06-04 09:15
@rbayet can you provide some help to @androshchuk for this one ?

**Comment by rbayet** [comment] 2020-06-08 17:27
@romainruaud I was not able to reproduce the exact error of @serhiirepin but can confirm as @androshchuk that this will lead to a "No products found matching your selection".

This is basically linked to the fact that, while `Smile_ElasticsuiteVirtualCategory` depends on `Magento_CatalogWidget` since its inception, to my knowledge, Virtual Categories or Elasticsuite support has never been added into `Magento_CatalogWidget` widgets or specific rules engine.
And the PageBuilder relies upon `Magento_CatalogWidget`.

For instance, @serhiirepin's exemple generates an ajax call to admin controller `pagebuilder/stage/preview` with the following payload 
```
role | "products"
directive | "{{widget+type=\"Magento\\CatalogWidget\\Block\\Product\\ProductsList\"+template=\"Magento_PageBuilder::catalog/product/widget/content/carousel.phtml\"+anchor_text=\"\"+id_path=\"\"+show_pager=\"0\"+products_count=\"20\"+condition_option=\"category_ids\"+condition_option_value=\"3\"+type_name=\"Catalog+Products+Carousel\"+conditions_encoded=\"^[`1`:^[`aggregator`:`all`,`new_child`:``,`type`:`Magento\|\|CatalogWidget\|\|Model\|\|Rule\|\|Condition\|\|Combine`,`value`:`1`^],`1--1`:^[`operator`:`==`,`type`:`Magento\|\|CatalogWidget\|\|Model\|\|Rule\|\|Condition\|\|Product`,`attribute`:`category_ids`,`value`:`42`^]^]\"+sort_order=\"position\"+store_id=\"0\"}}"
form_key | "gbnUpTsQfPlEloX9"
```

A "Catalog Products List" widget on a Elasticsuite 2.6.x / M2 2.2.x, configured with a "Category" condition on a Virtual Category will not display anything either.

To address the situation, we could 
* either decide to make it so that Virtual Categories can no longer be selected in Widget rules engine and in the PageBuilder custom form (a "meh" solution)
* or decide to add support for Virtual Categories in the Widget rules engine (an ideal solution, but likely to significantly delay release 2.9.1)

Regards

**Comment by romainruaud** [comment] 2020-06-09 08:01
Then this one can go to next minor release (2.9.2).

**Comment by lbajsarowicz** [comment] 2021-06-23 18:05
@romainruaud Is there anything I can do to make it happen?

**Comment by romainruaud** [comment] 2021-06-24 07:24
Of course @lbajsarowicz you can propose a PR, I think the previous comments are self explanatory about what should be done here.

If you need more insights/supports I can also provide you what a proper entry point could be to add this fix.

**Comment by lbajsarowicz** [comment] 2021-10-03 21:51
After doing some thorough investigation, looks like it's way easier to build a new Content-Type for PageBuilder that loads products asynchronously on the Storefront using GraphQL / REST API, than trying to customize or adjust the existing Products Widget.

I'm willing to schedule a call with any of Smile's representatives, to find a better solution that would work for all our clients, without rebuilding the whole stuff from the scratch.

**Comment by romainruaud** [comment] 2021-11-18 14:12
This has been fixed in latest version.

Regards

**Closed by romainruaud** 2021-11-18 14:12 UTC
Labels: enhancement
