### ISSUE TITLE
Error on validate catgory virtual

### ISSUE THREAD

**Issue by Fdec** [Smile-SA/elasticsuite#71] opened 2016-06-30 13:44 UTC
Virtual rule
```
( ! ) Fatal error: Call to a member function getConditions() on array in /var/www/damartch/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-rule/Block/Product/Conditions.php on line 145
#	Time	Memory	Function	Location
1	0.0000	241848	{main}( )	../index.php:0
2	0.0385	4774504	Magento\Framework\App\Bootstrap->run( )	../index.php:39
3	0.0391	4821360	Magento\Framework\App\Http\Interceptor->launch( )	../Bootstrap.php:258
4	0.0414	5152840	Magento\Framework\App\Http\Interceptor->___callPlugins( )	../Interceptor.php:26
5	0.0415	5167824	Magento\Framework\App\Http->launch( )	../Interceptor.php:146
6	0.0769	8885976	Magento\Framework\App\FrontController\Interceptor->dispatch( )	../Http.php:135
7	0.0783	8813576	Magento\Framework\App\FrontController\Interceptor->___callPlugins( )	../Interceptor.php:26
8	0.0879	9492808	Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch( )	../Interceptor.php:142
9	0.0881	9492824	Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}( )	../DbStatusValidator.php:69
10	0.0881	9493296	Magento\Framework\Interception\Chain\Chain->invokeNext( )	../Interceptor.php:138
11	0.0881	9493504	Magento\Framework\App\FrontController\Interceptor->___callParent( )	../Chain.php:70
12	0.0881	9493768	Magento\Framework\App\FrontController->dispatch( )	../Interceptor.php:74
13	0.1458	14356456	Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->dispatch( )	../FrontController.php:55
14	0.1465	14406616	Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->___callPlugins( )	../Interceptor.php:39
15	0.2109	17418064	Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch( )	../Interceptor.php:142
16	0.2109	17418152	Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->Magento\Framework\Interception\{closure}( )	../MassactionKey.php:33
17	0.2109	17418456	Magento\Framework\Interception\Chain\Chain->invokeNext( )	../Interceptor.php:138
18	0.2132	17607072	Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch( )	../Chain.php:67
19	0.2199	17794944	Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}( )	../Authentication.php:143
20	0.2199	17795248	Magento\Framework\Interception\Chain\Chain->invokeNext( )	../Chain.php:63
21	0.2199	17795456	Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->___callParent( )	../Chain.php:70
22	0.2199	17795808	Magento\Backend\App\AbstractAction->dispatch( )	../Interceptor.php:74
23	0.2249	18239880	Magento\Framework\App\Action\Action->dispatch( )	../AbstractAction.php:226
24	0.2277	18382640	Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->execute( )	../Action.php:102
25	0.2277	18383376	Magento\Catalog\Controller\Adminhtml\Category\Edit->execute( )	../Interceptor.php:24
26	0.3273	26193920	Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu( )	../Edit.php:102
27	0.3273	26194128	Magento\Backend\Model\View\Result\Page->setActiveMenu( )	../Interceptor.php:24
28	0.3273	26194280	Magento\Framework\View\Layout\Interceptor->getBlock( )	../Page.php:59
29	0.3273	26194384	Magento\Framework\View\Layout->getBlock( )	../Interceptor.php:414
30	0.3273	26194432	Magento\Framework\View\Layout->build( )	../Layout.php:859
31	0.3273	26194536	Magento\Framework\View\Layout\Builder->build( )	../Layout.php:244
32	0.3283	26246392	Magento\Framework\View\Page\Builder->generateLayoutBlocks( )	../Builder.php:65
33	0.3324	26424616	Magento\Framework\View\Layout\Builder->generateLayoutBlocks( )	../Builder.php:55
34	0.3325	26428616	Magento\Framework\View\Layout\Interceptor->generateElements( )	../Builder.php:129
35	0.3325	26428992	Magento\Framework\View\Layout->generateElements( )	../Interceptor.php:89
36	0.3332	26628816	Magento\Framework\View\Layout\GeneratorPool->process( )	../Layout.php:327
37	0.3667	29392328	Magento\Framework\View\Layout\Generator\UiComponent->process( )	../GeneratorPool.php:86
38	0.3667	29393032	Magento\Framework\View\Layout\Generator\UiComponent->generateComponent( )	../UiComponent.php:93
39	0.4797	33516656	Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent( )	../UiComponent.php:126
40	0.5009	34701896	Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent( )	../UiComponent.php:145
41	0.5296	37370184	Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent( )	../UiComponent.php:145
42	0.5371	37405848	Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent( )	../UiComponent.php:145
43	0.5371	37405848	Magento\Ui\Component\HtmlContent->prepare( )	../UiComponent.php:148
44	0.5371	37406752	Magento\Framework\View\Element\AbstractBlock->toHtml( )	../HtmlContent.php:50
45	0.5372	37407616	Smile\ElasticsuiteVirtualCategory\Block\Adminhtml\Catalog\Category\VirtualRule->_toHtml( )	../AbstractBlock.php:659
46	0.5384	37519640	Magento\Framework\Data\Form->toHtml( )	../VirtualRule.php:62
47	0.5384	37522712	Magento\Framework\Data\Form\Element\AbstractElement->toHtml( )	../Form.php:322
48	0.5384	37522760	Magento\Framework\Data\Form\Element\Text->getHtml( )	../AbstractElement.php:467
49	0.5384	37523328	Magento\Framework\Data\Form\Element\AbstractElement->getHtml( )	../Text.php:43
50	0.5385	37523560	Smile\ElasticsuiteCatalogRule\Block\Product\Conditions->render( )	../AbstractElement.php:453
51	0.5385	37523840	Magento\Framework\View\Element\AbstractBlock->toHtml( )	../Conditions.php:93
52	0.5386	37526104	Magento\Backend\Block\Template->_toHtml( )	../AbstractBlock.php:659
53	0.5386	37527616	Magento\Framework\View\Element\Template->_toHtml( )	../Template.php:104
54	0.5388	37528368	Magento\Framework\View\Element\Template->fetchView( )	../Template.php:279
55	0.5390	37531600	Magento\Framework\View\TemplateEngine\Php->render( )	../Template.php:255
56	0.5390	37549392	include( '/var/www/damartch/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-rule/view/adminhtml/templates/product/conditions.phtml' )	../Php.php:59
57	0.5391	37551368	Smile\ElasticsuiteCatalogRule\Block\Product\Conditions->getInputHtml( )	../conditions.phtml:35
```

**Comment by afoucret** [comment] 2016-07-05 14:30
The issue is only present when updating from a previous version 2.1.0.

Something have been changed in Magento 2.1.0 that cause the bug.

Can you contribute the SQL query you have run to fix it (the one related to the is_anchor attribute) please.

We will try to find a more elegant solution.

**Comment by afoucret** [comment] 2016-07-12 14:43
This will be part of the migration process to 2.2.0.

I close the issue.

**Closed by afoucret** 2016-07-12 14:43 UTC
