### ISSUE TITLE
Error on Category view when 1,006,757 products in a category after update from 2.9.1 to 2.9.2

### ISSUE THREAD

**Issue by zjevik** [Smile-SA/elasticsuite#1911] opened 2020-08-11 13:47 UTC
### Preconditions

Magento Version : 2.3.5-p2

ElasticSuite Version : 2.9.2

Environment : Production mode

Third party modules : N/A

### Steps to reproduce

1. Update from 2.9.1 to 2.9.2
2. Category view won't display any products.

### Expected result

1. Category view should display products.

### Actual result

1. system.log:
`main.ERROR: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Result window is too large, from + size must be less than or equal to: [400000] but was [1006757]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"magento2_default_catalog_product_2020_08_11__05_50_00","node":"GHA2E089Q4qgTaRq5XRvDg","reason":{"type":"illegal_argument_exception","reason":"Result window is too large, from + size must be less than or equal to: [400000] but was [1006757]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."}}],"caused_by":{"type":"illegal_argument_exception","reason":"Result window is too large, from + size must be less than or equal to: [400000] but was [1006757]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.","caused_by":{"type":"illegal_argument_exception","reason":"Result window is too large, from + size must be less than or equal to: [400000] but was [1006757]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."}}},"status":400} [] []`

I already had to increase my result window to accomodate for my number of products. Increasing the window further is not a solution though. The result window now has to be as big as the number of products in a category which is very wasteful.
All the issues associated with this would be gone if the scroll API was implemented.

**Comment by ProxiBlue** [comment] 2020-08-15 10:55
>All the issues associated with this would be gone if the scroll API was implemented.

I think the issue is deeper than just increasing the limits. Seems to be affecting other parts.
I had two sites flapping for past 2 days (since an update) with ES service crashing multiple times.

Issue is multiple (massive) autocomplete queries pulling service down.

**Comment by zjevik** [comment] 2020-08-15 18:37
> > All the issues associated with this would be gone if the scroll API was implemented.
> 
> I think the issue is deeper than just increasing the limits. Seems to be affecting other parts.
> I had two sites flapping for past 2 days (since an update) with ES service crashing multiple times.
> 
> Issue is multiple (massive) autocomplete queries pulling service down.

I just looked over your bug report and agree with you. Although, there is something going on with the result window anyway even before 2.9.1. Try to set your result window in ES to let's say 200 (which should be totally enough for catalog browsing) and the catalog browsing won't work if you have 1000+ products in a category.

Let's hope someone will look into this. I would like to update Magento to 2.4.X

**Comment by Bashev** [comment] 2020-08-15 19:25
@zjevik I think, I already fix it with PR #1914 waiting for review and merge.

**Comment by romainruaud** [comment] 2020-08-24 07:13
Closed as being a duplicate of #1903 #1912 #1917

**Closed by romainruaud** 2020-08-24 07:13 UTC
Labels: duplicate

**Comment by romainruaud** [comment] 2020-08-24 14:09
Please upgrade to 2.9.3 which contains the fix
