### ISSUE TITLE
The facets management disturbs the display of the list of products on category pages

### ISSUE THREAD

**Issue by PierreLeMaguer** [Smile-SA/elasticsuite#484] opened 2017-08-02 11:46 UTC
### Summary
With a set of parameter for a product attribute on the table catalog_eav_attribute, my list of products on category pages is empty.

### Magento Version
Magento EE
Magento Version : 2.1.5

ElasticSuite Version : 2.3.4

Environment : Developer mode

### Steps to reproduce
1. Have a category with products
2. Update one of the attribute of these products (size, bag_volume, color for example) with that set of parameters :

(catalog_eav_attribute)

frontend_input_renderer: NULL
                    is_global: 1
                   is_visible: 1
                is_searchable: 0
                is_filterable: 1
                is_comparable: 0
          is_visible_on_front: 1
     is_html_allowed_on_front: 0
      is_used_for_price_rules: 0
      is_filterable_in_search: 1
      used_in_product_listing: 0
             used_for_sort_by: 0
                     apply_to: NULL
is_visible_in_advanced_search: 0
                     position: 3
           is_wysiwyg_enabled: 0
      is_used_for_promo_rules: 0
   is_required_in_admin_store: 0
              is_used_in_grid: 0
           is_visible_in_grid: 0
        is_filterable_in_grid: 0
                search_weight: 1
              additional_data: NULL
      is_used_in_autocomplete: 1
 is_displayed_in_autocomplete: 0
        is_used_in_spellcheck: 1
      facet_min_coverage_rate: 10
               facet_max_size: 10
             facet_sort_order: _score
              display_pattern: NULL
            display_precision: 0

### Expected result
The category page must show a list of products.

### Actual result
There is no product.

### Comments
If I change the **facet_min_coverage_rate** to 90 or if I change the **facet_sort_order**, it works and I have a list with product. My surprise is that I believed these datas didn't have an influence on the products showed but only on facets showed.
![category_without_products](https://user-images.githubusercontent.com/19976778/28872263-b7c064ee-7788-11e7-9eb7-855c8706e905.png)
![category_with_products](https://user-images.githubusercontent.com/19976778/28872264-b7c39394-7788-11e7-8597-3de935312849.png)

**Comment by romainruaud** [comment] 2017-08-02 12:06
Hello,

could you please update to the latest Elasticsuite version and check if this behavior is still present ?

Regards

**Comment by romainruaud** [comment] 2017-08-07 09:43
I close this one since it is an internal Smile issue which I was not able to reproduce, even with the specific project code. This is also working as expected in other environments.

Feel free to reopen it if you have more details about it.

Best regards

**Closed by romainruaud** 2017-08-07 09:43 UTC
