### ISSUE TITLE
poor matching with accented and capital/lower greek characters and different autocomplete results to search results

### ISSUE THREAD

**Issue by ioweb-gr** [Smile-SA/elasticsuite#2630] opened 2022-07-09 08:45 UTC
### Preconditions

Elastic Search 7.6.2

Magento Version : 2.4.1 CE

ElasticSuite Version :"2.10.10"

Environment : Developer

Third party modules :
List of enabled modules:
Amasty_Base
Amasty_CronScheduleList
Amasty_Geoip
Amasty_GdprCookie
Amasty_Gdpr
Ced_VivaPayments
Codazon_AjaxCartPro
Codazon_Core
Codazon_GoogleAmpManager
Codazon_ImproveBundle
Codazon_Lookbookpro
Codazon_MegaMenu
Codazon_ProductFilter
Codazon_ThemeOptions
Codazon_QuickShop
Codazon_ShippingCostCalculator
Codazon_Shopbybrandpro
Codazon_Slideshow
Codazon_ProductLabel
Codazon_Utility
Dotdigitalgroup_Email
Dotdigitalgroup_Chat
Dotdigitalgroup_Sms
Flurrybox_EnhancedPrivacy
Fooman_PrintOrderPdf
Harrigo_EverCrumbs
Ho_Templatehints
Ioweb_AmastyGdprAddon
Ioweb_Base
Ioweb_CspWhitelist
Ioweb_Customizer
Ioweb_Label
Ioweb_MariaDbHotfix
Ioweb_OrderComments
Ioweb_RestrictPayment
Ioweb_RestrictShipping
Ioweb_TaxDisplay
Ioweb_Widgets
MagePal_Core
MagePal_EditOrderEmail
Magefan_Community
Magefan_Blog
Magefan_WysiwygAdvanced
Mageplaza_Core
Mageplaza_GoogleRecaptcha
Mageplaza_Multiflatrates
Mageplaza_Smtp
Mageplaza_SocialLogin
Mageprince_Paymentfee
Magonex_DateTime
Nwdthemes_Base
Nwdthemes_Revslider
Plumrocket_Base
Plumrocket_SocialLoginFree
Smile_ElasticsuiteAdminNotification
Smile_ElasticsuiteCore
Smile_ElasticsuiteCatalog
Smile_ElasticsuiteCatalogGraphQl
Smile_ElasticsuiteCatalogRule
Smile_ElasticsuiteCatalogOptimizer
Smile_ElasticsuiteTracker
Smile_ElasticsuiteThesaurus
Smile_ElasticsuiteSwatches
Smile_ElasticsuiteIndices
Smile_ElasticsuiteAnalytics
Smile_ElasticsuiteVirtualCategory
Yosto_AddressAttribute
Yosto_AttributeRelation
Yosto_CustomerAddress
Yosto_CustomerAttribute
Yosto_OrderAttribute
Yotpo_Yotpo

### Steps to reproduce
1. Create a few products with Greek names with accented characters e.g. `κοριτσίστικο, κορίτσι, κοριτσάκι` etc etc
2. Search non-accented version `κοριτσι`

### Expected result

1. Caps or LowerCase should bring similar results
2. Accent / No Accent should be treated the same
3. The autocomplete results are the same as the actual search 

### Actual result

1. The autocomplete results, do not match the word pretty well 
4. The search results are different than the autocomplete results
5. The products found in search are much less than what exists in the system 

On the contrary the phonetic analysis is extremely good so typing `koritsi` will find the single product matching perfectly 

Let me present some screens of searches 

![image](https://user-images.githubusercontent.com/20220341/178098494-118a0ef9-7c85-438a-84e9-e0bc93dff317.png)
---
---
---
---

![image](https://user-images.githubusercontent.com/20220341/178098500-6c73e487-930e-4a4d-a533-5c5169ad208a.png)
---
---
---
---

![image](https://user-images.githubusercontent.com/20220341/178098518-40f10e2c-b1e6-4002-a7e5-b46cb1796876.png)
---
---
---
---

![image](https://user-images.githubusercontent.com/20220341/178098527-ad3c1f4f-c888-4efb-9a07-b54347d51af4.png)
---
---
---
---
![image](https://user-images.githubusercontent.com/20220341/178098537-890cc262-16c1-4d45-8bf8-6a7104affd6e.png)

---
---
---
---

Partial works better

![image](https://user-images.githubusercontent.com/20220341/178098567-83b67216-fcac-4c05-9e69-6ebf29eecb8f.png)

Autocomplete is a mess compared to search page

![image](https://user-images.githubusercontent.com/20220341/178098675-61cdfc73-0189-46b9-ac32-f67c33877f57.png)

**Comment by romainruaud** [comment] 2022-07-11 13:14
Hi @ioweb-gr 

about the last point where "Autocomplete is a mess compared to search page" : 

you are typing "κορίτσι" in the autocomplete, right ?

this leads the engine to suggest two particular search terms in the autocomplete box. What you need to know here is the fact that products displayed in the autocomplete are displayed according to the suggested search terms.

**Comment by ioweb-gr** [comment] 2022-07-11 13:23
I see, this is counter intuitive. I would have never guessed it and I imagine the customers wouldn't either.

I would expect the autocomplete to fetch results based on the typed query along with listing the suggested terms in case the user wants to pick those.

Because as you can see here, the actual requested products are not listed and instead irrelevant products to what the user typed are listed, autocomplete seems broken.

**Comment by cptX** [comment] 2022-09-01 06:28
I can verify all the above. I have exactly the same issues in Greek and I'm searching for solutions. I'm focusing on modifying the elasticsearch analyzer but my knowledge at the moment in elasticsearch system is very poor...
Important is that magento and elasticsearch at the moment is not a good solution out-of-the-box for Greek language. I'm curious what all other Greek magento eshops do on the subject. They haven't realized the problem yet?

**Comment by cptX** [comment] 2022-10-19 13:48
Any progress on this? I'm facing the same issue Magento ver. 2.4.5, Elasticsuite ver. 2.10.11
When I search for the word "κόρνα" it gives result, when I search for "κορνα" without accent it doesn't return any result. Also the phonetic search works ok, eg. "korna", returns the correct result!
I'm really lost, I cannot understand the cause of the issue. What I know is that in one of my installations after a lot of experimentation I managed to make it work but I have no clue how and why, so I cannot replicate it in a new installation.

**Comment by cptX** [comment] 2022-10-24 08:18
Hi @romainruaud ,

at the moment searching is useless in Greek language and this is critical!!!
Can you please help us what can we modify in order to make it work? For example for a product named "κόρνα" (with accent) when searching for the word "κορνα" (without accent) Ι get no results. Usually 99% of customers are typing without accents so you understand how important this issue is!!! 

I want to modify some filters, and in other discussions I saw that this filter ICUTransformFilter should be ok, but as I'm new in magento and elasticsearch/elasticsuite I don't know where to see if this filter is used and included if not!

**Comment by romainruaud** [comment] 2022-10-24 08:47
Hi @cptX 

I'll try to investigate more on this.

Actually we don't even have a default stemmer implemented for greek : https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-core/etc/elasticsuite_analysis.xml

I'll try first to add one and see if this helps.

Regards

**Comment by cptX** [comment] 2022-10-24 09:01
Hi @romainruaud ,

I really appreciate your help and focus on this. I have found several references on the proble since 2017 if I'm not wrong, and no solution yet. So I think it's time to work on it!

Here is an example on the current problem:

Look this picture
![image](https://user-images.githubusercontent.com/9040042/197487296-cf23ac98-22fa-4403-849f-b0b326b868b3.png)

Autosuggest successfully finds the word "κόρνα" (with accent) but at the same moment seach can't find it , gives a message that "No exact results found for: 'κόρνα'." but still shows it succesfully in search results!

Now if I search for the word "κορνα" (without accent)
autosuggest gives nothing at all!
search gives again the message "No exact results found for: 'κορνα'. The displayed items are the closest matches."
but shows the corresponding item!

![image](https://user-images.githubusercontent.com/9040042/197487840-a57cfa0a-a09c-45f9-b983-a1d78db970f2.png)

Really confusing situation and critical too!

**Comment by romainruaud** [comment] 2022-10-24 09:24
Hi @ioweb-gr ,

I created a store view, configured it with greek language in the back-office, created two products : 

- κόρνα
- κόρνα παιδιά

In the autocompletion I have this : 

- with accent : 

![image](https://user-images.githubusercontent.com/15340849/197493177-2b85269c-d159-403a-98e8-e0b25366b803.png)

- without accent : 

![image](https://user-images.githubusercontent.com/15340849/197493379-5d2ebe99-8da5-4d6b-8961-95213e41f248.png)

And the search results gives me : 

- with accent : 

![image](https://user-images.githubusercontent.com/15340849/197493519-32174915-cef2-440e-85ad-902c6dd4a5b2.png)


- without accent : 

![image](https://user-images.githubusercontent.com/15340849/197493753-45383beb-3df8-4e44-94e5-28a4f6663ecb.png)


So I can confirm that, despite having something different than you, there is a problem with matching between accentuated / non-accentuated characters.

I'll have a look.

Regards

**Comment by romainruaud** [comment] 2022-10-24 09:36
I have now the same results for κόρνα and κορνα when using the fix I provided in this PR : https://github.com/Smile-SA/elasticsuite/pull/2756/files

Can you check that it improves results on your side as well ? Beware, this require a cache clean + reindex after applying.

Regards

**Comment by cptX** [comment] 2022-10-24 12:13
Hi @romainruaud,
did the change but nothing changed.
Restarted the elasticsearch server and ran the following commands:
bin/magento cache:clean
bin/magento indexer:reindex

but nothing changed. Do I need to do something more to apply the change?

**Comment by cptX** [comment] 2022-10-24 12:22
Yes, that finally fixed everything, both autocomplete and search results!! Thanks!!!
What do you suggest? Should I use the patch from now on, or do you plan to include it in a future update? Is there any update planned where this could be included?

**Comment by romainruaud** [comment] 2022-10-24 12:49
Hi, the fuzzy search (used in case of misspelling) works fine locally for me in search results : 

![image](https://user-images.githubusercontent.com/15340849/197528732-70a2518a-1346-47f2-9b8c-625208dd6e41.png)

Fuzzy is never applied in autocomplete however.

That being said, if the provided PR is fixing your issue, I'll merge this and tag a 2.10.12.1 release because we have another issue that should not wait to get release.

I let you upgrade to 2.10.12.1 then.

I'll close this issue as well because I consider that the initial issue is fixed by my PR, but feel free to open a new one to follow greek-language related issues, especially if it seems to still be some problems with the fuzzy search.

Regards

**Closed** 2022-10-24 12:49 UTC

**Comment by cptX** [comment] 2022-10-24 13:06
"Κώρνα" returns nothing to me here!
This is my spellchecking configuration (default as far as I know)
![image](https://user-images.githubusercontent.com/9040042/197532096-3743a894-b5f5-4791-8441-d614a7521ca7.png)
Can you please tell me if my configuration is normal and if it's different than yours? If it's the same I'll open another issue!
Thanks in advance!

**Comment by romainruaud** [comment] 2022-10-24 13:31
Yes this is default configuration.

But it's also tied to which attributes are used for spellchecking.

By my side, κόρνα is contained in the "name" attribute, and this attribute is "used for spellcheck" according to the attribute configuration.

Can you please check if that's also the case for you, and if this problem is still occuring, please feel free to open a new issue.

Regards

**Comment by cptX** [comment] 2022-10-24 14:19
Yes Name attribute, has "Used in spellcheck" enabled in my configuration too!
The name I have set up for this product is "Ηλεκτρική κόρνα 120dB με φόρτιση USB", so the word "κόρνα" is the second word of the name and not the first! Could this be the issue? Should spellchecking work for the complete name?

**Comment by romainruaud** [comment] 2022-10-24 14:52
![image](https://user-images.githubusercontent.com/15340849/197556524-85b912f6-b259-459b-9093-98dc4d4a114b.png)

This just works for me with the fix provided this morning.

Please open another ticket if you are still having the issue when using the 2.10.12.1 version of Elasticsuite.

Regards
