### ISSUE TITLE
Difference in search suggestions and actual results

### ISSUE THREAD

**Issue by OvalMedia** [Smile-SA/elasticsuite#2394] opened 2021-12-16 10:36 UTC
I have a major discrepancy between search suggestions on a partial search term (which works great) and an actual result using this partial term.

In the screenshot you can see I was typing the incomplete term "paci" (intending to go for "pacific") and the store comes up with proper suggestions.

![quicksearch](https://user-images.githubusercontent.com/1006378/146355244-fff13d66-0897-4b1d-8400-977c5f3677d8.png)

But when I actually submit a search using "paci" I get no results at all.

Am I missing something or is there a remedy for this somehow?
Any insight welcome.

Thank you

**Comment by romainruaud** [comment] 2021-12-16 14:06
Duplicate of #1277

Please see this detailed comment for answers : https://github.com/Smile-SA/elasticsuite/issues/1277#issuecomment-456385530

Regards

**Closed by romainruaud** 2021-12-16 14:06 UTC
Labels: duplicate, invalid, wontfix

**Comment by OvalMedia** [comment] 2021-12-17 09:35
So there is no way to do a partial search?
