### ISSUE TITLE
Find a product with name "Simple Product 331" by query "Product 33"

### ISSUE THREAD

**Issue by Neos2007** [Smile-SA/elasticsuite#1655] opened 2020-01-03 19:51 UTC
Environment:
Magento 2.3.3 Commerce edition
ElasticSuite v 2.8.3

I'm configuring elastic suite on a new environment with test data.
Using Search query "Product 33" magento now returns products with names: "Configurable Product 33"," Simple product 33" and "Configurable Product Attribute Set 3 3".
Question: is it possible to configure elasticsuite extension that search using query like "Product 33" will return also products with names like Simple product 331, Simple product 332?...
Now to get for example the product with name "Simple product 331" in search I have to enter a query either "Product" (which will return also lot of other products) or "Product 331" (which will return exactly the product "Simple product 331")

![image](https://user-images.githubusercontent.com/17883826/71745511-03e9eb80-2e73-11ea-902c-4189151284f8.png)
![image](https://user-images.githubusercontent.com/17883826/71745565-22e87d80-2e73-11ea-8cfd-076a42fc2ada.png)

**Comment by androshchuk** [comment] 2020-01-06 13:26
Hello @Neos2007 

You can try changing the settings. For example ElasticSuite -> Search Relevance -> Relevance Configuration -> Fulltext Base Settings -> Minimum Should Match http://joxi.ru/ZrJ0V44iMk3Q82
But it'll impair search results (result for minimum_should_match = 99% - http://joxi.ru/v29nQDDHzjdQzA)

Regards

**Comment by romainruaud** [comment] 2020-02-27 07:29
I close since it's a duplicate of #797 #1536 #970 

Please give a try to the solution provided by @androshchuk which could be a workaround for you, but as he stated, this could also impair results.

Regards

**Closed by romainruaud** 2020-02-27 07:29 UTC
Labels: question
