### ISSUE TITLE
Undefined index: adminSortIndex

### ISSUE THREAD

**Issue by jeroenkosse** [Smile-SA/elasticsuite#677] opened 2018-01-03 15:25 UTC
Exception #0 (Exception): Notice: Undefined index: adminSortIndex in /vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Layer/Filter/Attribute.php on line 271

### Preconditions

Magento Version : 2.2.1

ElasticSuite Version : 2.4.6

### Steps to reproduce
When there is a space after the label for a specific attribute the module is trying to find the value with the space. The label from the item from the variable $items that is passed to the array is not containing the space.

### Possible solution

$optionLabel = trim((string)$option['label']);

**Comment by romainruaud** [comment] 2018-01-03 15:33
Hello @jeroenkosse and thank you for using our module.

I just reproduced your bug on my testing environment, so it's confirmed.

Will try to provide a fix for this one.

**Comment by afoucret** [comment] 2018-01-03 15:39
Agree with triming like proposed by

**Comment by romainruaud** [comment] 2018-01-03 15:43
Yes this is due to the fact that we trim the option label when indexing, so when re-sorting them in the attribute model, we have in entry the trimmed option label, and we try to sort on the "raw" one which is not trimmed.

I tested this solution and proposed PR #678

**Comment by jeroenkosse** [comment] 2018-01-03 15:48
Thnx for the quick response and hope to fetch a new release soon

**Comment by afoucret** [comment] 2018-01-03 16:05
PR merged.

**Closed by afoucret** 2018-01-03 16:05 UTC
Labels: bug
