### ISSUE TITLE
Layered Navigation Filter contains configurable product's associated out of stock products 

### ISSUE THREAD

**Issue by i95devdivya** [Smile-SA/elasticsuite#934] opened 2018-06-04 11:29 UTC
Preconditions
1.	Magento EE 2.1.3
2.	PHP 7
3.     ElasticSuite 2.3.x

Steps to reproduce
1.	Create configurable products (for example: Shoes)
2.	Create Category
3.	Enable layered navigation for the category
4.	Assign product to category
5.	Create linked simple products for sizes (sizes 5.5, 6, 6.5, 7 and so on)
6.	Set any one of the size (lets say 5.5) to out of stock, others are in-stock
7.	Set Show out of Stock Products: No
8.	Set Backorder: No
9.	Run full indexing, flush cache and static content deploy etc.
10.	Navigate to category view page on Front end
11.	Use layered navigation to filter by size attribute choose (5.5 or the size which was set to out of stock)
12.	The product will be shown even when the filtered by size attribute is out of stock

Expected result
1.	Although configurable products are considered out of stock only when all the simple products linked to configurable attribute are Out of Stock, it should consider the condition that when product listing page is filtered by a particular attribute value and the admin setting dictates that Out of stock product should not be shown, then in such cases it should do a stock check against the particular filtered value with the product's configurable attribute instead of checking the stocks of all the simple products linked to it

Actual result
1.	Shows the product in the filtered listing page even when the attribute value used to filter the product is Out Of Stock

**Note:** Initially the same issue we faced in default Magento. We posted ticket to Magento and they provided some patch to us, we applied. Now according to default Magento it is working fine. But after integrating elastic suite again its not working.

**Comment by i95devdivya** [comment] 2018-06-04 11:30
#502

**Comment by i95devdivya** [comment] 2018-06-04 11:31
Reference issue is #502

**Comment by afoucret** [comment] 2018-06-04 11:32
Hi @i95devdivya,

Your issue is a duplicate of #809 that have been responded for a while now.
I close since duplicated.

BR,

**Closed by afoucret** 2018-06-04 11:32 UTC
