### ISSUE TITLE
Displaying virtual categories on front

### ISSUE THREAD

**Issue by madonzy** [Smile-SA/elasticsuite#367] opened 2017-03-23 09:19 UTC
How to display products of virtual category

### Preconditions
**OS**: Linux debian-8 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux
**Magento Version**: 2.1.4 CE
**ElasticSuite Version**: 2.3.3
**Environment**: developer

### Steps to reproduce
1. Add new category inside Root category.
2. Set it as virtual
3. Set rule "Color  is one of  Blue."
4. Save
4. Full reindex & cache clean

### Expected result
The storefront will show me results in my virtual category page.

### Actual result
Now in the admin panel, I can see all products that really have attribute color with value Blue. But storefront don't show me any products in this category

**Comment by DogSports** [comment] 2017-03-23 09:25
Same issue #366

**Comment by madonzy** [comment] 2017-03-23 09:31
@DogSports I see that you are able to see products with some like "manual sort", what does it mean? I can't see any products at all.

**Comment by romainruaud** [comment] 2017-03-23 09:36
Confirmed.

We'll try to provide a fix for this one quickly.

Regards

**Comment by romainruaud** [comment] 2017-03-23 10:14
When enforcing the catalogsearch layer to be used on catalog navigation, we introduced a biasis causing to always apply the addCategoryFilter method on the product collection.

This causes all categories to include a "must category_id=XXX" which indeed works for standard categories but produces conditions like "must color=blue AND category_id=XXX" on virtual categories which is not reliable.

It also causes a double appliance of "category_id=XXX" on standard category but does not fail since it does not change anything to the result.

**Comment by madonzy** [comment] 2017-03-23 10:25
@romainruaud sorry, but I'm not sure I understand you correct. Please provide any steps to make virtual category show products on the storefront. Does your response mean that it's problem on my side or on the side of elasticsuit?

**Comment by romainruaud** [comment] 2017-03-23 10:27
Sorry if you did misunderstood my answer : the problem is clearly on our side and due to the latest release. You can consider downgrading to 2.3.2 till we fix the issue and provide a new release.

We are working on it and expect to provide a fix soon.

Best regards,

**Comment by romainruaud** [comment] 2017-03-23 13:27
Fixed by PR #368 , please migrate to 2.3.4 version and process cache clean and compile.

**Closed by romainruaud** 2017-03-23 13:27 UTC
Labels: bug
