### ISSUE TITLE
Css Error

### ISSUE THREAD

**Issue by rimmeh** [Smile-SA/elasticsuite#2580] opened 2022-05-31 13:10 UTC
### Preconditions

Magento Version : 2.4.2

ElasticSuite Version : 2.10.0

Environment : dev

Third party modules :

### Steps to reproduce

1. install elastic searuh suite
2. Load Frontend
3. Error in Fontend LEss Console
4. "variable @autocomplete-item__border is undefined in file /var/customers/webs/franksa/var/view_preprocessed/pub/static/frontend/Franksa/porto_child/de_DE/Smile_ElasticsuiteCore/css/source/_module.less in _module.less on line 32, column 38
30|                     border-bottom: 0;
31|                 }
32|                 .lib-css(border-top, @autocomplete-item__border);
33|                 cursor: default;
34|                 margin: 0;
35|                 padding: @indent__xs @indent__xl @indent__xs @indent__s;
<pre>#1 Magento\Framework\View\Asset\PreProcessor\AlternativeSource->processContent() called at [vendor/magento/framework/View/Asset/PreProcessor/AlternativeSource.php:114]
#2 Magento\Framework\View\Asset\PreProcessor\AlternativeSource->process() called at [vendor/magento/module-developer/Model/View/Asset/PreProcessor/PreprocessorStrategy.php:78]
#3 Magento\Developer\Model\View\Asset\PreProcessor\PreprocessorStrategy->process() called at [vendor/magento/framework/View/Asset/PreProcessor/Pool.php:77]
#4 Magento\Framework\View\Asset\PreProcessor\Pool->process() called at [vendor/magento/framework/View/Asset/Source.php:152]
#5 Magento\Framework\View\Asset\Source->preProcess() called at [vendor/magento/framework/View/Asset/Source.php:105]
#6 Magento\Framework\View\Asset\Source->getFile() called at [vendor/magento/framework/View/Asset/File.php:158]
#7 Magento\Framework\View\Asset\File->getSourceFile() called at [vendor/magento/framework/App/StaticResource.php:157]
#8 Magento\Framework\App\StaticResource->launch() called at [vendor/magento/framework/App/Bootstrap.php:263]
#9 Magento\Framework\App\Bootstrap->run() called at [pub/static.php:13]
</pre>"

### Expected result

1. No Less Error

### Actual result

1. Css in Frontend is broken

**Comment by vahonc** [comment] 2022-05-31 13:22
Duplicate of #2565

**Comment by romainruaud** [comment] 2022-06-08 13:15
I close since it's a duplicate.

Please see the workaround in https://github.com/Smile-SA/elasticsuite/issues/91

**Closed by romainruaud** 2022-06-08 13:15 UTC
Labels: duplicate, wontfix
