### ISSUE TITLE
Add rule for virtual category - only new products

### ISSUE THREAD

**Issue by Koc** [Smile-SA/elasticsuite#513] opened 2017-08-26 11:58 UTC
### Preconditions

Magento Version : 2.1.8

ElasticSuite Version : 2.3.x

Environment : PHP 7.0.21

Third party modules : -

### Steps to reproduce

1. Switch category to virtual
2. Rename it to "new products"
3. Start adding filters

### Expected result

1. Expected add rule "only new products" (products which filters by standard magento attributes for new products: `now() beteween product.is_new_from and product.is_new_to` )

### Actual result

1. This rule is missing

**Comment by romainruaud** [comment] 2017-08-29 09:12
Duplicate of #410 

I close this one.

Regards

**Closed by romainruaud** 2017-08-29 09:12 UTC
Labels: duplicate, feature

**Comment by Koc** [comment] 2017-08-29 10:50
oops, sorry for duplicate
