### ISSUE TITLE
Filter By quantity_and_stock_status not workig

### ISSUE THREAD

**Issue by ia-gaurav** [Smile-SA/elasticsuite#2202] opened 2021-07-11 08:11 UTC
**Preconditions**
Magento 2.4
Smile Elastic Latest Version
Select In Layered Navigation as yes for **quantity_and_stock_status**

![image](https://user-images.githubusercontent.com/63009790/125187493-849a5c80-e24d-11eb-90f8-aa8e9aab3dac.png)

**Issue :**
It must show in filter 

**Expected** 
Quantity should show in filter

**Comment by vahonc** [comment] 2021-07-12 06:34
Hello @ia-gaurav,

That's not possible, this is not a "real" attribute in Magento actually, having it displayed as a layered navigation filter would require more work since it would be needed to create a filter based on the stock.is_in_stock field.

BR,
Vadym

**Comment by romainruaud** [comment] 2021-07-15 13:14
Duplicate of #1924

**Comment by ia-gaurav** [comment] 2021-07-15 18:16
@romainruaud  can this be done with some workaround

**Comment by romainruaud** [comment] 2021-07-22 07:31
@ia-gaurav you can find an abandoned implementation of this feature in this (very old) PR : https://github.com/Smile-SA/elasticsuite/pull/133/files

It's probably not gonna work as a charm with recent Elasticsuite version but it should give you some guidelines about implementing it by yourself.

Best regards

**Closed by romainruaud** 2021-07-22 07:31 UTC

**Comment by ia-gaurav** [comment] 2021-07-22 07:42
@romainruaud  thanks can it be added in todo list for future
