### ISSUE TITLE
Multiple category filter

### ISSUE THREAD

**Issue by gihovani** [Smile-SA/elasticsuite#1982] opened 2020-10-31 20:19 UTC
Is it possible to show the category filter in the search, for multiple choice?

As with the ex: manufacturer attributes.

I haven't figured out how to set this up.

**Additional context**
Add any other context or screenshots about your question here.
![Captura](https://user-images.githubusercontent.com/2844128/97789194-36e93280-1b9d-11eb-8458-a8d55239bdc9.png)

**Comment by OvalMedia** [comment] 2021-02-11 13:39
Did you figure this one out?

**Comment by romainruaud** [comment] 2021-02-17 08:06
Woops I did not see this one.

Duplicate of #2071 : please see my response in the other issue.

regards

**Closed by romainruaud** 2021-02-17 08:06 UTC
Labels: question
