### ISSUE TITLE
Virtual Categories not working correct with bundle products

### ISSUE THREAD

**Issue by PHProDreamy** [Smile-SA/elasticsuite#2054] opened 2021-01-26 14:04 UTC
We have made a virtual category saying that this category can only contain products where "att_ismainproduct" = YES. We have then set up this value for several products and we see that ElasticSuite doesn't show the correct products in the front-end. 

### Preconditions
Magento Version : Magento ver. 2.4.1 - CE

ElasticSuite Version : 2.10.3

Environment : We are developing but using production mode

### Steps to reproduce

1. Create a virtual category with the following rules: https://filebin.net/o0ddm3zrt1n0egfq/Screenshot_2021-01-26_at_14.53.15.png?t=ui9s8syf
2. Create multiple bundle products. Set one bundle to att_ismainproduct = YES and the rest to NO: https://filebin.net/o0ddm3zrt1n0egfq/Screenshot_2021-01-26_at_14.46.27.png?t=e3blty6x
3. Look on the front-end: https://filebin.net/o0ddm3zrt1n0egfq/Screenshot_2021-01-26_at_14.46.49.png?t=oboazkxs

### Expected result
1. There should only be ONE product "Duo Priam 3 + nacelle légère Lite Cot" which is the SKU CYB00935-CYB00615-CYB00638

### Actual result
1. There are TWO, because he looks at the individual bundle products. He also shows the product with SKU "CYB00607-CYB00615-CYB00638" in the front-end, because one of the bundle items has an "att_ismainproduct" = YES. This makes no sense, he should look at the attribute "att_ismainproduct" of the real product, not of the values of the children in the bundle.

**Comment by vahonc** [comment] 2021-01-27 09:35
Hello @PHProDreamy,

Could you switch to the default Magento theme (Luma) and check if the problem you mentioned still exists?

Best regards

**Comment by romainruaud** [comment] 2021-01-28 15:19
Well, we do assemble all children data inside parent product data, yes. It's by design.

We do like this especially due to the fact that a parent product might not have proper data by itself, let's imagine a configurable : 

**T-shirt** : 

- price : 100
- description : a cool t-shirt

And his childrens : 

**Red T-Shirt, Small** : 

- size : S
- color : red

**Green T-Shirt, Small**  : 

- size : S
- color : green

... and so on.


We want the parent to have the combination of his childrens, because it's the parent that will be displayed on the website. So if someone filter on "color = green" we should display the parent. And most of time, child products are not even set to be visible individually.


So if you have a children that has "att_ismainproduct=yes", the parent will have the same value.

Actually, only some attributes are ignored for this process : https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php#L34

**Comment by PHProDreamy** [comment] 2021-01-28 16:27
Thanks for your feedback! That helps us a lot!

**Comment by romainruaud** [comment] 2021-02-09 13:30
Great, may I close this issue then ?

**Comment by PHProDreamy** [comment] 2021-02-09 13:41
We are working on it at the moment. I will update you tomorrow if that is good?

**Comment by PHProDreamy** [comment] 2021-02-11 16:36
We have changed here: https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php#L34

    private $forbidenChildrenAttributeCode = [
        'visibility',
        'status',
        'price',
        'tax_class_id',
        'name',
    ];
    
    to 
    
        private $forbidenChildrenAttributeCode = [
        'visibility',
        'status',
        'price',
        'tax_class_id',
        'name',
        'att_ismainproduct'
    ];

But it looks like nothing is happening. IS that normal? Did we do something wrong?

**Comment by PHProDreamy** [comment] 2021-02-16 16:43
Hi @romainruaud, Did you maybe have a change to take a look at this? :) I can always give you htcaccess / inlog details via mail to show you the issue.

Thank! With kind regards

**Comment by romainruaud** [comment] 2021-02-16 16:52
Hi @PHProDreamy 

We cannot provide support for your project as part of our (free) Open Source support policy here.

That's something we can do as part of our professional services (paid) policy if you feel the need to. If that's the case, you can contact us by mail at elasticsuite@smile.fr

Regards

**Closed** 2021-02-17 07:59 UTC
