### ISSUE TITLE
Service Temporarily Unavailable sometimes

### ISSUE THREAD

**Issue by sennin32** [Smile-SA/elasticsuite#844] opened 2018-04-02 13:53 UTC
### Preconditions

Magento Version : opensource 2.2

ElasticSuite Version : 2.5
Elasticsearch Version : 5.6

Environment : Production

Third party modules : Na

### Steps to reproduce

1. search rapidly within short time, around 5+ times per min

### Expected result

1. show result constantly

### Actual result

1. Site shows :
Service Temporarily Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

2. Log shows :
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:329) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:312) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:617) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:485) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:461) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:257) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:343) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:340) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:654) [elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:674) [elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.6.8.jar:5.6.8]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NumberFormatException: empty String
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842) ~[?:?]
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
        at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_161]
        at org.elasticsearch.index.mapper.NumberFieldMapper$NumberType.objectToDouble(NumberFieldMapper.java:918) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.index.mapper.NumberFieldMapper$NumberType.access$200(NumberFieldMapper.java:180) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.index.mapper.NumberFieldMapper$NumberType$3.parse(NumberFieldMapper.java:372) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.index.mapper.NumberFieldMapper$NumberType$3.rangeQuery(NumberFieldMapper.java:408) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.index.mapper.NumberFieldMapper$NumberFieldType.rangeQuery(NumberFieldMapper.java:978) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.index.query.RangeQueryBuilder.doToQuery(RangeQueryBuilder.java:517) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:96) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.index.query.NestedQueryBuilder.doToQuery(NestedQueryBuilder.java:306) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:96) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:444) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:418) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:96) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toFilter(AbstractQueryBuilder.java:118) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.index.query.ConstantScoreQueryBuilder.doToQuery(ConstantScoreQueryBuilder.java:146) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:96) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$1(QueryShardContext.java:313) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:325) ~[elasticsearch-5.6.8.jar:5.6.8]
        ... 14 more

I'm not really sure if this issue is cause by elasticsuite or elasticsearch.
Since I use it in magento 2, so I decide post here!

**Comment by romainruaud** [comment] 2018-04-03 08:35
Hello @sennin32 and thank you for testing our module.

Not sure this is purely related to Elasticsearch, since we can see a "NumberFormatException: empty String" that could be caused by erroneous data on the query which is sent to elasticsearch. But you did cut the first lines of elasticsearch error, could you show me what is the root cause of error on the Elasticsearch log file ?

Is it always happening on a specific query (or filtering on a given attribute) or is it purely random ?

**Comment by sennin32** [comment] 2018-04-03 08:49
org.elasticsearch.index.query.QueryShardException: failed to create query: {
  "constant_score" : {
    "filter" : {
      "bool" : {
        "must" : [
          {
            "nested" : {
              "query" : {
                "bool" : {
                  "must" : [
                    {
                      "bool" : {
                        "must_not" : [
                          {
                            "term" : {
                              "category.is_virtual" : {
                                "value" : true,
                                "boost" : 1.0
                              }
                            }
                          }
                        ],
                        "disable_coord" : false,
                        "adjust_pure_negative" : true,
                        "boost" : 1.0
                      }
                    },
                    {
                      "terms" : {
                        "category.category_id" : [
                          "23"
                        ],
                        "boost" : 1.0
                      }
                    }
                  ],
                  "disable_coord" : false,
                  "adjust_pure_negative" : true,
                  "boost" : 1.0
                }
              },
              "path" : "category",
              "ignore_unmapped" : false,
              "score_mode" : "none",
              "boost" : 1.0
            }
          },
          {
            "terms" : {
              "stock.is_in_stock" : [
                true
              ],
              "boost" : 1.0
            }
},
          {
            "terms" : {
              "option_text_color.untouched" : [
                "57,73"
              ],
              "boost" : 1.0
            }
          },
          {
            "terms" : {
              "option_text_keycap_printing" : [
                "59"
              ],
              "boost" : 1.0
            }
          }
        ],
        "disable_coord" : false,
        "adjust_pure_negative" : true,
        "boost" : 1.0
      }
    },
    "boost" : 1.0
  }
}

**Comment by sennin32** [comment] 2018-04-03 08:49
Sure, I paste it above :)

**Comment by romainruaud** [comment] 2018-04-03 14:06
Well the query seems kinda strange for me.

How is built the query ? Do you have piece of specific code assembling it ? Or are you fully letting Elasticsuite do his job ? 

On which page is appearing this query ? Category navigation or elsewhere ?

How are built your attributes ? I mean, I was not expecting integer value for the "option_" fields, since they are here to handle the textual value of the attributes options. I was expecting something like : 

```
{"option_text_color":["Black","Blue"],"boost":1}
```

Also, the filter for your "option_text_color" is not a proper array since it contains a string imploded by commas, which led me to my initial question regarding the fact that you may forge the query by yourself.

Regards

**Comment by sennin32** [comment] 2018-04-03 17:07
@romainruaud Hi, I just simply install elasticsearch and elasticsuite.
Try to search in the front page (search dialog in main page).
And it will start filtering during loading.
You can check it in https://shopkey.doyustudio.com/
It is not totally random, only search multi times in short time.
If I refresh the page after maybe 1 min, it work.

I'm not sure if it is related with the custom theme?
I use porto for my site, and I have to edit some setting (related to css) to make it work.

**Comment by romainruaud** [comment] 2018-04-04 10:11
Hmm...

This one seems to be related to some specific code on your website. Probably due to some third party modules, or the custom theme you are using.

You may have some other issues because I am not able to see the layered navigation filters on the search result page (eg: they are missing when I search for "keyboard").

Additionaly we had several issue with third party themes that modify the layout in a way that is not compatible with the standard Luma theme. Debugging commercial extensions is not part of our Open Source community support but we can help as part of our commercial support.

Could this commercial support interest you ? If yes, you can contact me by mail at romain.ruaud@smile.fr and I will forward you to our sales peoples that will be able to help you out.

Best regards, and thank you for using our module.

**Comment by afoucret** [comment] 2018-04-16 11:50
As explained by @romainruaud, we were not able to reproduce your issue and on site debugging is part of our commercial support for the extension.

I close the issue for being not reproductible. Feel free to reopen if you can give us more detail on how to reproduce or to contact us if interested in commercial support.

BR,

**Closed by afoucret** 2018-04-16 11:50 UTC
Labels: needs update
