### ISSUE TITLE
2.2.x-dev main.ERROR: Bulk index operation failed 1 times in index magento2_default_catalog_product_20160711_144337 for type product Error (mapper_parsing_exception) : failed to parse [option_text_attribute_s_12420] Failed doc ids sample : 1585697

### ISSUE THREAD

**Issue by southerncomputer** [Smile-SA/elasticsuite#81] opened 2016-07-11 14:53 UTC
php -q bin/magento reindex:catalogsearch_fulltext

[2016-07-11 14:45:35] main.ERROR: Bulk index operation failed 1 times in index magento2_default_catalog_product_20160711_144337 for type product Error (mapper_parsing_exception) : failed to parse [option_text_attribute_s_12420] Failed doc ids sample : 1585697 [] []
 main.ERROR: Bulk index operation failed 2 times in index magento2_default_catalog_product_20160711_144337 for type product Error (mapper_parsing_exception) : failed to parse [option_text_attribute_s_12420] Failed doc ids sample : 1628343, 1628350 [] []

![capture0711a](https://cloud.githubusercontent.com/assets/6178967/16735058/a6c80dae-4755-11e6-8938-1b16a92ed578.PNG)
![capture0711b](https://cloud.githubusercontent.com/assets/6178967/16735060/aa0b63a8-4755-11e6-87e8-517c085538d2.PNG)

Any thoughts on why the indexer is failing this attribute and document?

**Comment by southerncomputer** [comment] 2016-07-11 15:07
[2016-07-11 10:44:16,272][DEBUG][action.bulk              ] [ossec_node1] [magento2_default_catalog_product_20160711_144337][0] failed to execute bulk item (index) index {[magento2_default_catalog_product_20160711_144337][product][1576721], source[{"entity_id":"1576721","attribute_set_id":"104","type_id":"simple","sku":"9999-342-1623","has_options":"0","required_options":"0","created_at":"2016-07-09 21:08:44","updated_at":"2016-07-09 21:48:22","etilize_product_id":"1025500659","visibility":"4","price":[{"price":"240.0600","original_price":"240.0600","is_discount":false,"customer_group_id":"0"},{"price":"240.0600","original_price":"240.0600","is_discount":false,"customer_group_id":"1"},{"price":"240.0600","original_price":"240.0600","is_discount":false,"customer_group_id":"2"},{"price":"240.0600","original_price":"240.0600","is_discount":false,"customer_group_id":"3"}],"category":[{"category_id":3},{"category_id":126,"name":"I\/O & Storage Controllers"},{"category_id":127,"is_parent":true,"name":"SCSI\/RAID Controllers"},{"category_id":206,"name":"Storage Components"},{"category_id":368,"name":"Information Technology"}],"name":["Dell-IMSourcing NEW F\/S PERC H700 SAS Controller 342-1623"],"mfgpartno":["342-1623"],"ean_sku_code":["0609527729021"],"gtin_sku_code":["0609527729021"],"ingram_micro_usa_sku_code":["TC2689,TC2688"],"unspsc_sku_code":["43201556"],"upc_sku_code":["609527729021"],"attribute_s_1100":["8752"],"option_text_attribute_s_1100":["SAS Controller"],"attribute_s_11506":["2500"],"option_text_attribute_s_11506":["Plug-in Card"],"attribute_s_188":["14740"],"option_text_attribute_s_188":["PCI Express 2.0 x8"],"attribute_s_12749":["17187"],"option_text_attribute_s_12749":["6Gb\/s SAS"],"attribute_s_12420":["5092","5094","5097","5100","9584","9586","9587"],

"option_text_attribute_s_12420":{"1":"1","2":"10","3":"5","4":"50","5":"6","6":"60"},
^^ Look here

"description":["Dell-IMSourcing NEW F\/S PERC H700 SAS Controller - 6Gb\/s SAS - PCI Express 2.0 x8 - Plug-in Card - RAID Supported - 0, 1, 10, 5, 50, 6, 60 RAID Level - 8 Total SAS Port(s) - 2 SAS Port(s) Internal"],"short_description":["Dell-IMSourcing NEW F\/S PERC H700 SAS Controller"],"manufacturer":[70],"option_text_manufacturer":["Dell-IMSourcing"],"status":[1],"option_text_status":["Enabled"],"tax_class_id":[2],"option_text_tax_class_id":["Taxable Goods"],"attribute_s_113319":[28151],"option_text_attribute_s_113319":["Dell-IMSourcing"],"attribute_s_111115654":[4879],"option_text_attribute_s_111115654":["Yes"],"attribute_s_111119653":[12657],"option_text_attribute_s_111119653":["8"],"stock":{"is_in_stock":false,"qty":0}}]}
MapperParsingException[failed to parse [option_text_attribute_s_12420]]; nested: IllegalArgumentException[unknown property [1]];
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:329)
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:309)
	at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:326)
	at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:252)
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:122)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:309)
	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:580)
	at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:559)
	at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOperationOnPrimary(TransportIndexAction.java:212)
	at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:224)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:327)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:120)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:68)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:639)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:271)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: unknown property [1]
	at org.elasticsearch.index.mapper.core.StringFieldMapper.parseCreateFieldForString(StringFieldMapper.java:362)
	at org.elasticsearch.index.mapper.core.StringFieldMapper.parseCreateField(StringFieldMapper.java:311)
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:321)
	... 22 more

**Comment by afoucret** [comment] 2016-07-11 15:21
Hi @southerncomputer,

We will see how we can secure such list containing commas.

On naive question : why are you not using multi-value attributes instead ?

**Comment by afoucret** [comment] 2016-07-11 15:21
Sorry I closed the issue by mistake.

My bad.

**Comment by southerncomputer** [comment] 2016-07-11 15:25
This is utilizing 3rd party import routine, which also imports one attribute with "dandh inc,._sku" as name which throws a fit as well due to having period in the attribute_code!. 

I am not sure how to modify the importer to behave!

Is there a list of illegal characters I can try to change the attributes to avoid or escape?

**Comment by southerncomputer** [comment] 2016-07-11 15:52
933 |           83 |        936 |      933 |       933 |        0 | Pathway Innovations & Technologies, Inc.,                                                                                                            |
|      1200 |           83 |        704 |     1200 |      1200 |        0 | Konexx, Unlimited Systems Corp., Inc                                                                                                                 |
|     23514 |          751 |         10 |    35727 |     23514 |        0 | 10,000,000:1                                                                                                                                         |
|     25391 |          751 |         69 |    39569 |     25391 |        0 | 50,000,000:1                                                                                                                                         |
|     26751 |          751 |         37 |    41432 |     26751 |        0 | 20,000,000:1                                                                                                                                         |
|     27895 |          751 |         12 |    42990 |     27895 |        0 | 100,000,000:1                                                                                                                                        |
|     32372 |          751 |         85 |    49910 |     32372 |        0 | 80,000,000:1                                                                                                                                         |
|     33827 |          782 |          0 |    51673 |     33827 |        0 | 1,000,000:1                                                                                                                                          |
|     34506 |          751 |         26 |    52790 |     34506 |        0 | 2,000,000:1                                                                                                                                          |
|     34507 |          751 |         50 |    52791 |     34507 |        0 | 30,000,000:1                                                                                                                                         |
|     35289 |          751 |         44 |    53839 |     35289 |        0 | 3,000,000:1                                                                                                                                          |
|     36175 |          751 |          0 |    55008 |     36175 |        0 | 1,000,000:1                                                                                                                                          |
|     38819 |          751 |         66 |    58119 |     38819 |        0 | 5,000,000:1                                                                                                                                          |
|     40302 |          751 |         15 |    60148 |     40302 |        0 | 12,000,000:1                                                                                                                                         |
|     43256 |          751 |         83 |    64031 |     43256 |        0 | 8,000,000:1                                                                                                                                          |
|     44128 |          782 |         13 |    64964 |     44128 |        0 | 5,000,000:1                                                                                                                                          |
|     46990 |          751 |         81 |    69269 |     46990 |        0 | 70,000,000:1                                                                                                                                         |
|     47793 |          176 |       1479 |    70917 |     47793 |        0 | CNFE100(X)(M,S)(1,2)A                                                                                                                                |
|     48181 |          751 |         17 |    71305 |     48181 |        0 | 120,000,000:1                                                                                                                                        |
|     48192 |          782 |          6 |    71316 |     48192 |        0 | 2,000,000:1                                                                                                                                          |
|     48798 |          176 |       1483 |    72700 |     48798 |        0 | CNFE200(X)POE(M,S)(1,2)[HO][/M]                                                                                                                      |
|     49747 |          782 |          7 |    73794 |     49747 |        0 | 20,000,000:1                                                                                                                                         |
|     49748 |          782 |         11 |    73795 |     49748 |        0 | 4,000,000:1                                                                                                                                          |
|     51114 |          176 |       1482 |    75841 |     51114 |        0 | CNFE200(X)(M,S)(1,2)[POE][HO][/M]                                                                                                                    |
|     55152 |          664 |          7 |    80822 |     55152 |        0 | RLFDX232(M,S)2/(24DC,48DC,HV)                                                                                                                        |
|     55153 |          664 |          8 |    80823 |     55153 |        0 | RLFDX485(M,S)2/(24DC,48DC,HV)                                                                                                                        |
|     56435 |          751 |         32 |    82838 |     56435 |        0 | 2,500,000:1                                                                                                                                          |
|     56436 |          751 |         58 |    82839 |     56436 |        0 | 4,000,000:1                                                                                                                                          |
|     56437 |          751 |         74 |    82840 |     56437 |        0 | 6,000,000:1                                                                                                                                          |
|     12639 |          587 |          4 |    83601 |     12639 |        0 | 0, 1+0, 5, 6                                                                                                                                         |
|     20367 |          587 |          5 |    83602 |     20367 |        0 | 0, 1, 0+1, 5                                                                                                                                         |
|     12640 |          587 |          6 |    83603 |     12640 |        0 | 0, 1, 1+0                                                                                                                                            |
|     30431 |          587 |          7 |    83604 |     30431 |        0 | 0, 1, 1+0, 1E                                                                                                                                        |
|     12641 |          587 |          8 |    83605 |     12641 |        0 | 0, 1, 1+0, 5                                                                                                                                         |
|     20368 |          587 |          9 |    83606 |     20368 |        0 | 0, 1, 1+0, 5, 5+0                                                                                                                                    |
|     22364 |          587 |         10 |    83607 |     22364 |        0 | 0, 1, 1+0, 5, 5+0, 6, 6+0                                                                                                                            |
|     17338 |          587 |         11 |    83608 |     17338 |        0 | 0, 1, 1+0, 5, 6                                                                                                                                      |
|     33126 |          587 |         12 |    83609 |     33126 |        0 | 0, 1, 10                                                                                                                                             |
|     46487 |          587 |         13 |    83610 |     46487 |        0 | 0, 1, 10, JBOD                                                                                                                                       |
|     18344 |          587 |         14 |    83611 |     18344 |        0 | 0, 1, 1E                                                                                                                                             |
|     12642 |          587 |         15 |    83612 |     12642 |        0 | 0, 1, 3, 5, 10                                                                                                                                       |
|     36105 |          587 |         16 |    83613 |     36105 |        0 | 0, 1, 3, 5, 10, 30, 50, 60, 0+1, 1E                                                                                                                  |
|     41579 |          587 |         17 |    83614 |     41579 |        0 | 0, 1, 3, 5, 10, Clone Mode (N-Way Mirror)                                                                                                            |
|     40741 |          587 |         18 |    83615 |     40741 |        0 | 0, 1, 3, 5, 10, Clone Mode (N-Way Mirror), Concatenation                                                                                             |
|     34463 |          587 |         19 |    83616 |     34463 |        0 | 0, 1, 3, 5, 10, Clone Mode (N-Way Mirror), Concatenation, JBOD                                                                                       |
|     30432 |          587 |         20 |    83617 |     30432 |        0 | 0, 1, 3, 5, 10, Clone Mode (N-Way Mirror), JBOD                                                                                                      |
|     33778 |          587 |         21 |    83618 |     33778 |        0 | 0, 1, 3, 5, 10, Concatenation                                                                                                                        |
|     29507 |          587 |         22 |    83619 |     29507 |        0 | 0, 1, 3, 5, 10, JBOD                                                                                                                                 |
|     17339 |          587 |         23 |    83620 |     17339 |        0 | 0, 1, 3, 5, 6, 0+1, JBOD                                                                                                                             |
|     22365 |          587 |         24 |    83621 |     22365 |        0 | 0, 1, 3, 5, 6, 10                                                                                                                                    |
|     29508 |          587 |         25 |    83622 |     29508 |        0 | 0, 1, 3, 5, 6, 10, 0+1, JBOD                                                                                                                         |
|     55870 |          587 |         26 |    83623 |     55870 |        0 | 0, 1, 3, 5, 6, 10, 30, 50, 60                                                                                                                        |
|     46961 |          587 |         27 |    83624 |     46961 |        0 | 0, 1, 3, 5, 6, 10, 30, 50, 60, 0+1                                                                                                                   |
|     46107 |          587 |         28 |    83625 |     46107 |        0 | 0, 1, 3, 5, 6, 10, 30, 50, 60, 0+1, 1E                                                                                                               |
|     36106 |          587 |         29 |    83626 |     36106 |        0 | 0, 1, 3, 5, 6, 10, 30, 50, 60, 0+1, 1E, JBOD                                                                                                         |
|     32278 |          587 |         30 |    83627 |     32278 |        0 | 0, 1, 3, 5, 6, 10, 30, 50, 60, 0+1, JBOD                                                                                                             |
|     38168 |          587 |         31 |    83628 |     38168 |        0 | 0, 1, 3, 5, 6, 10, 30, 50, 60, 1+Hot Spare, 3+Hot Spare, 5+Hot Spare, 6+Hot Spare, 10+Hot Spare, 30+Hot Spare, 50+Hot Spare, 60+Hot Spare, JBOD      |
|     38169 |          587 |         32 |    83629 |     38169 |        0 | 0, 1, 3, 5, 6, 10, 30, 50, 60, 1+Hot Spare, 5+Hot Spare, 6+Hot Spare, 10+Hot Spare, 50+Hot Spare, 60+Hot Spare, JBOD                                 |
|     43200 |          587 |         33 |    83630 |     43200 |        0 | 0, 1, 3, 5, 6, 10, 30, 50, 60, 100, 1E, JBOD                                                                                                         |
|     24420 |          587 |         34 |    83631 |     24420 |        0 | 0, 1, 3, 5, 6, 10, 30, 50, 60, 1E                                                                                                                    |
|     43201 |          587 |         35 |    83632 |     43201 |        0 | 0, 1, 3, 5, 6, 10, 30, 50, 60, 1E, JBOD                                                                                                              |
|     41580 |          587 |         36 |    83633 |     41580 |        0 | 0, 1, 3, 5, 6, 10, 30, 50, 60, JBOD                                                                                                                  |
|     49677 |          587 |         37 |    83634 |     49677 |        0 | 0, 1, 3, 5, 6, 10, 30, 60, 0+1, JBOD                                                                                                                 |
|     17340 |          587 |         38 |    83635 |     17340 |        0 | 0, 1, 3, 5, 6, 10, 50                                                                                                                                |
|     44069 |          587 |         39 |    83636 |     44069 |        0 | 0, 1, 3, 5, 6, 10, 50, 60, 1E, JBOD                                                                                                                  |
|     32279 |          587 |         40 |    83637 |     32279 |        0 | 0, 1, 3, 5, 6, 10, 50, JBOD                                                                                                                          |
|     32280 |          587 |         41 |    83638 |     32280 |        0 | 0, 1, 3, 5, 6, 10, JBOD                                                                                                                              |
|     46962 |          587 |         42 |    83639 |     46962 |        0 | 0, 1, 3, 5, 6, 30, 50, 60, 0+1                                                                                                                       |
|     33779 |          587 |         43 |    83640 |     33779 |        0 | 0, 1, 3, 5, 6, 30, 50, 60, 0+1, 1E, 1+Hot Spare, 3+Hot Spare, 5+Hot Spare, 6+Hot Spare, 10+Hot Spare, 30+Hot Spare, 50+Hot Spare, 60+Hot Spare, JBOD |
|     33780 |          587 |         44 |    83641 |     33780 |        0 | 0, 1, 3, 5, 6, 30, 50, 60, 0+1, 1E, 3+Hot Spare, 5+Hot Spare, 6+Hot Spare, 30+Hot Spare, 50+Hot Spare, 60+Hot Spare, JBOD                            |
|     46963 |          587 |         45 |    83642 |     46963 |        0 | 0, 1, 3, 5, 6, 30, 50, 60, 0+1, 1E, JBOD                                                                                                             |
|     33781 |          587 |         46 |    83643 |     33781 |        0 | 0, 1, 3, 5, 6, 30, 50, 60, 0+1, 3+Hot Spare, 5+Hot Spare, 6+Hot Spare, 30+Hot Spare, 50+Hot Spare, 60+Hot Spare, JBOD                                |
|     17341 |          587 |         47 |    83644 |     17341 |        0 | 0, 1, 3, 5, 6, 30, 50, 60, 0+1, JBOD                                                                                                                 |
|     55871 |          587 |         48 |    83645 |     55871 |        0 | 0, 1, 3, 5, 6, 50, 60, 0+1, JBOD                                                                                                                     |
|     26072 |          587 |         49 |    83646 |     26072 |        0 | 0, 1, 4, 5, 6, 10                                                                                                                                    |
|     21442 |          587 |         50 |    83647 |     21442 |        0 | 0, 1, 4, 5, 6, 10, 40, 50, 60, DVRAID, JBOD                                                                                                          |
|     24421 |          587 |         51 |    83648 |     24421 |        0 | 0, 1, 4, 5, 6, 10, JBOD                                                                                                                              |
|     21443 |          587 |         52 |    83649 |     21443 |        0 | 0, 1, 4, 5, 6, 50, 60, 10, JBOD                                                                                                                      |
|     21444 |          587 |         53 |    83650 |     21444 |        0 | 0, 1, 5                                                                                                                                              |
|     19567 |          587 |         54 |    83651 |     19567 |        0 | 0, 1, 5, 0+1                                                                                                                                         |
|      7985 |          587 |         55 |    83652 |      7985 |        0 | 0, 1, 5, 10                                                                                                                                          |
|     19568 |          587 |         56 |    83653 |     19568 |        0 | 0, 1, 5, 10, 5+Hot Spare                                                                                                                             |
|     36107 |          587 |         57 |    83654 |     36107 |        0 | 0, 1, 5, 10, 5+Spare, Clone Mode (N-Way Mirror), Concatenation, JBOD                                                                                 |
|     26073 |          587 |         58 |    83655 |     26073 |        0 | 0, 1, 5, 10, 5+Spare, Concatenation, JBOD                                                                                                            |
|     55116 |          587 |         59 |    83656 |     55116 |        0 | 0, 1, 5, 10, 5+Spare, JBOD                                                                                                                           |
|     22366 |          587 |         60 |    83657 |     22366 |        0 | 0, 1, 5, 10, 50                                                                                                                                      |
|     34464 |          587 |         61 |    83658 |     34464 |        0 | 0, 1, 5, 10, 50, JBOD                                                                                                                                |
|     47629 |          587 |         62 |    83659 |     47629 |        0 | 0, 1, 5, 10, Clone Mode (N-Way Mirror), Concatenation, JBOD                                                                                          |
|     36108 |          587 |         63 |    83660 |     36108 |        0 | 0, 1, 5, 10, Clone Mode (N-Way Mirror), JBOD                                                                                                         |
|     32281 |          587 |         64 |    83661 |     32281 |        0 | 0, 1, 5, 10, JBOD                                                                                                                                    |
|     27803 |          587 |         65 |    83662 |     27803 |        0 | 0, 1, 5, 10, JBOD, S                                                                                                                                 |
|     51720 |          587 |         66 |    83663 |     51720 |        0 | 0, 1, 5, 6                                                                                                                                           |
|     55872 |          587 |         67 |    83664 |     55872 |        0 | 0, 1, 5, 6, 0+1, 0+5                                                                                                                                 |
|     16160 |          587 |         68 |    83665 |     16160 |        0 | 0, 1, 5, 6, 10                                                                                                                                       |
|     40742 |          587 |         69 |    83666 |     40742 |        0 | 0, 1, 5, 6, 10, 10+1, 10+2                                                                                                                           |
|     39713 |          587 |         70 |    83667 |     39713 |        0 | 0, 1, 5, 6, 10, 50                                                                                                                                   |
|     13971 |          587 |         71 |    83668 |     13971 |        0 | 0, 1, 5, 6, 10, 50, 1E                                                                                                                               |
|     33127 |          587 |         72 |    83669 |     33127 |        0 | 0, 1, 5, 6, 10, 50, 60                                                                                                                               |
|     13972 |          587 |         73 |    83670 |     13972 |        0 | 0, 1, 5, 6, 10, 50, 60, 1E                                                                                                                           |
|     41581 |          587 |         74 |    83671 |     41581 |        0 | 0, 1, 5, 6, 10, 50, 60, 1E, JBOD                                                                                                                     |
|     25334 |          587 |         75 |    83672 |     25334 |        0 | 0, 1, 5, 6, 10, 50, 60, JBOD                                                                                                                         |
|     47630 |          587 |         76 |    83673 |     47630 |        0 | 0, 1, 5, 6, 10, 50, JBOD                                                                                                                             |
|     33782 |          587 |         77 |    83674 |     33782 |        0 | 0, 1, 5, 6, 10, Concatenation, JBOD                                                                                                                  |
|     21445 |          587 |         78 |    83675 |     21445 |        0 | 0, 1, 5, 6, 10, JBOD                                                                                                                                 |
|     36109 |          587 |         79 |    83676 |     36109 |        0 | 0, 1, 5, 6, 10, X-RAID2                                                                                                                              |
|     27804 |          587 |         80 |    83677 |     27804 |        0 | 0, 1, 5, JBOD                                                                                                                                        |
|     33783 |          587 |         81 |    83678 |     33783 |        0 | 0, 1, Concatenation, JBOD                                                                                                                            |
|     20369 |          587 |         82 |    83679 |     20369 |        0 | 0, 1, JBOD                                                                                                                                           |
|     50848 |          587 |         83 |    83680 |     50848 |        0 | 0, 1, JBOD, NOR                                                                                                                                      |
|     56391 |          587 |         85 |    83682 |     56391 |        0 | 0, 3, 5, 10                                                                                                                                          |
|     39714 |          587 |         86 |    83683 |     39714 |        0 | 0, 3, 5, 10, LARGE                                                                                                                                   |
|     33784 |          587 |         87 |    83684 |     33784 |        0 | 0, 30, 50, JBOD                                                                                                                                      |
|     51721 |          587 |         89 |    83686 |     51721 |        0 | 0, 5, 10, 5+Spare                                                                                                                                    |
|     35251 |          587 |         90 |    83687 |     35251 |        0 | 0, 5, 10, Clone Mode (N-Way Mirror), Concatenation, JBOD                                                                                             |
|     42286 |          587 |         91 |    83688 |     42286 |        0 | 0, 5, 10, Concatenation, JBOD                                                                                                                        |
|     51722 |          587 |         92 |    83689 |     51722 |        0 | 0, 5, 6                                                                                                                                              |
|     35252 |          587 |         93 |    83690 |     35252 |        0 | 0, 5, 6, 10, 10+1, 10+2                                                                                                                              |
|     35253 |          587 |         94 |    83691 |     35253 |        0 | 0, 5, 6, 10, 10+2                                                                                                                                    |
|     22367 |          587 |         95 |    83692 |     22367 |        0 | 0, 5, 6, 5+Hot Spare                                                                                                                                 |
|     20370 |          587 |        102 |    83699 |     20370 |        0 | 1, 5, 0+1                                                                                                                                            |
|     35254 |          587 |        103 |    83700 |     35254 |        0 | 1, 5, 10, 5+Spare, Concatenation, JBOD                                                                                                               |
|     40276 |          587 |        104 |    83701 |     40276 |        0 | 1, 5, 6                                                                                                                                              |
|     52420 |          587 |        105 |    83702 |     52420 |        0 | 1, 5, 6, 0+1                                                                                                                                         |
|     37814 |          587 |        106 |    83703 |     37814 |        0 | 1, 5, 6, 10, Concatenation, JBOD                                                                                                                     |
|     37815 |          587 |        107 |    83704 |     37815 |        0 | 1, 5, 6, 10, JBOD                                                                                                                                    |
|     28865 |          587 |        108 |    83705 |     28865 |        0 | 1, 5, 6, JBOD                                                                                                                                        |
|     23424 |          587 |        122 |    83719 |     23424 |        0 | 5, 6, 10                                                                                                                                             |
+-----------+--------------+------------+----------+-----------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------+
127 rows in set (0.03 sec)

is a result of all eav_attribute_option_value where like '%,%,%';

Do you think the $ values with two commas will get thrown out? What about MFR names with multiple comma's?

**Comment by afoucret** [comment] 2016-07-11 15:56
Can you try the following :

1. Locate class `Smile\ElasticsuiteCatalog\Helper\Attribute`

2. Replace the code of the `getIndexOptionsText` method (l. 194) with the following :
```
   public function getIndexOptionsText(AttributeInterface $attribute, $storeId, array $optionIds)
    {
        $mapper = function ($optionId) use ($attribute, $storeId) {
            return $this->getIndexOptionText($attribute, $storeId, $optionId);
        };
        $optionValues = array_map($mapper, $optionIds);

        return array_values($optionValues);
    }
```

If the indexer is working again we will evaluate the opportunity to merge the code.

(Not sure about multiple faceting code but we will see it once indexing will be fixed).

BR,

**Comment by afoucret** [comment] 2016-07-11 15:59
Note : My point about multiple select was about the fact you have the same option (let say JBOD) in several values. It makes hard to select all device with the JBOD option (you have many value to select.

I think the value should be exploded at import time.

**Comment by southerncomputer** [comment] 2016-07-11 16:42
Before patch:
,"attribute_s_12420":["5092","5094","5097","5100","9584","9586","9587"],
"option_text_attribute_s_12420":{"1":"1","2":"10","3":"5","4":"50","5":"6","6":"60"}

after patch: (i selected one more option)
,"attribute_s_12420":"5092","33779","5094","5097","5100","9584","9586","9587"],
"option_text_attribute_s_12420":{"1":"0, 1, 3, 5, 6, 30, 50, 60, 0+1, 1E, 1+Hot Spare, 3+Hot Spare, 5+Hot Spare, 6+Hot Spare, 10+Hot Spare, 30+Hot Spare, 50+Hot Spare, 60+Hot Spare, JBOD","2":"1","3":"10","4":"5","5":"50","6":"6","7":"60"},

Need to strip off "1" "2" "3" "4" "5" "6" "7" of array ?

MapperParsingException[failed to parse [option_text_attribute_s_12420]]; nested: IllegalArgumentException[unknown property [1]];

I noticed on prior attribute:
"attribute_s_12749":["7729","4617"],
"option_text_attribute_s_12749":["Serial ATA\/300","Serial ATA\/600"],

I believe it is multi-select but it does not have array_key (1...7)?

**Comment by southerncomputer** [comment] 2016-07-11 22:36
I replaced(value,',','*') on that attribute and it still fails with no comma's present anymore?
How come this attribute is surrounded by { } braes instead of [ ] braces like others?

**Comment by afoucret** [comment] 2016-07-12 04:17
I think the following commit 9862a8a may fix this issue.
It is present into the 2.2.x branch.
As I was not able to reproduce your bug, I will let you test it and report me if it works as expected.

BR,

**Comment by afoucret** [comment] 2016-07-12 13:17
@southerncomputer : did you manage to test the proposed solution ?

**Comment by southerncomputer** [comment] 2016-07-12 13:53
Yes and no. I thought with UPDATE on SAVE - saving the malformed product would upsert the data into the current index. It did make its call to elasticsearch without error.

but now I am forced to do a catalogsearch_fulltext full reindex from command line which will take a bit of time, so far no errors on either post method which is definitely better than before!

**Comment by afoucret** [comment] 2016-07-12 14:00
Correct me if I am wrong but what I understand with your last message is that the full reindex is only required once (to fix the products that are missing) but once done, everything works has expected.

If so, can we consider the bug closed ?

**Comment by southerncomputer** [comment] 2016-07-12 14:13
You can close the ticket, the error has not showed up yet and reindex takes about 3-4 hours to verify - but i would have seen the debug log throw errors by now! thanks!

**Comment by afoucret** [comment] 2016-07-12 14:22
You're welcome.

Thx for reporting.

**Closed** 2016-07-12 14:22 UTC
