### ISSUE TITLE
Category filter is incorrect after a first filter appliance

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/elasticsuite#132] opened 2016-09-22 11:17 UTC
Steps to reproduce : 

- Go to http://demo.magento-elastic-suite.io/

- Search for 'hoodie' 

- Select a filter containing only one value : a good example is  'Hemp' value for 'Material'

Expected result : 

- The Category filter should display accordingly to the 'Material' facet.

What happens : 

- The Category filter still show all values of the raw 'hoodie' search. 'Women' category has 19 products.
- Clicking on the 'Women' category leads to a 'Your search returned no results' page.

**Comment by romainruaud** [comment] 2016-09-23 16:09
We go through this "silenced exception" piece of code in this case : 

https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-core/Search/Request/Aggregation/AggregationBuilder.php#L87

Exception message is : Field categories does not exists in mapping

**Comment by afoucret** [comment] 2016-09-26 08:30
The exception is managed.

The issue is more a functionnal inconsitent behavior there.
- When used in categories navigation, filters are reseted when changing of categories
- It is not the case when using fulltext search

**Comment by afoucret** [comment] 2016-09-26 09:32
PR #139 have been merged and fix the inconsistent behavior of filters in fulltext searches.

**Closed by afoucret** 2016-09-26 09:32 UTC
Labels: bug
