### ISSUE TITLE
The size attribute does not appear in the filters.

### ISSUE THREAD

**Issue by elisei** [Smile-SA/elasticsuite#1921] opened 2020-08-13 13:31 UTC
The size attribute does not appear in the filters, even "pinned" or set to "always visible".

### Preconditions
Magento CE 2.4
ES 7.8.1
ElasticSuite 2.10.0

### Steps to reproduce
Categorie -> Display -> Settings -> Atribute Size set "Always displayed" and "Pinned"

Visit the category on the store frontend and the attribute is not available.

### Expected result
See the attribute for filtering.

### Actual result
Currently only in the category Women -> Tops the attribute is visible, any other is not displayed.

### Additional information
When you remove ElasticSuite, you can see the attribute in all categories.

In the ElasticSuite demo the same possible problem occurs:
http://demo.magento-elastic-suite.io/index.php/men/tops-men.html
http://demo.magento-elastic-suite.io/index.php/women/tops-women/hoodies-and-sweatshirts-women.html
http://demo.magento-elastic-suite.io/index.php/women/tops-women/tees-women.html
http://demo.magento-elastic-suite.io/index.php/women/tops-women/tanks-women.html
...
In any category you can see the filter if you manually insert it in your url:
?size=L
http://demo.magento-elastic-suite.io/index.php/men/tops-men.html?size=L

**Comment by romainruaud** [comment] 2020-08-24 06:58
Hi @elisei 

Most probably, it does not appear because all products are sharing the exactly same values for the Size attribute on the sample data catalog, which means this filter would not be relevant for filtering, according to this commit : https://github.com/Smile-SA/elasticsuite/commit/443f739b5c24a63c76e4506f1e8b2cbab839d5fc

Try to remove one children product (put a variant children as unavailable or disabled), and this should allow the filter to appear.

Please also take into account that on a "real" catalog this is way more unlikely to happen.

But I agree that setting the filter to "always visible" should probably override this feature.

Regards

**Comment by elisei** [comment] 2020-08-24 13:10
@romainruaud 

Thank you very much for the guidance! <3

**Comment by PascalBrouwers** [comment] 2020-09-11 14:16
Does not work:
![Screenshot 2020-09-11 at 16 15 23](https://user-images.githubusercontent.com/17834386/92936199-1aa50100-f44a-11ea-9c0c-0dcefc8eee6d.png)

Removed the XL simple from the configurable. Size attribute still does not show up.

**Comment by rbayet** [comment] 2020-11-02 09:49
Re-opening to check @PascalBrouwers 's return.

**Comment by PascalBrouwers** [comment] 2020-11-02 09:57
Oh, is this fixed in the latest version?

**Comment by rbayet** [comment] 2020-11-19 15:17
@PascalBrouwers nope :) 

@romainruaud had put the flag "enhancement" to look at the possibility to enforce the "always visible", but @elisei closed the issue, so it was flagged as "done".
The issue has just been moved from one release to the next for the time being.

**Comment by rbayet** [comment] 2020-11-19 16:02
> Does not work:
> [...]
> 
> Removed the XL-black simple from the configurable. Size attribute still does not show up.
> 
> Only works if you remove ALL XL sizes from 1 configurable.

**Confirmed**.
That's because we merge at the parent product level the values of all the simple. So if at least one child-simple product has a given size, then the configurable has it.

Keeping this issue open to address the enhancement request as described in Romain's [comment above](https://github.com/Smile-SA/elasticsuite/issues/1921#issuecomment-678944192).

**Comment by romainruaud** [comment] 2020-12-16 09:57
@vahonc can you add a clause to check `$attribute->getFacetDisplayMode() == FilterDisplayMode::ALWAYS_DISPLAYED` in this line helps fixing the issue ? https://github.com/Smile-SA/elasticsuite/blob/443f739b5c24a63c76e4506f1e8b2cbab839d5fc/src/module-elasticsuite-catalog/Model/Layer/Filter/Attribute.php#L156

**Comment by vahonc** [comment] 2020-12-16 10:07
@romainruaud, ok I will check it.

**Closed** 2021-01-07 18:16 UTC
Labels: enhancement
