### ISSUE TITLE
Incompatible with Porto theme

### ISSUE THREAD

**Issue by vaggelisk** [Smile-SA/elasticsuite#933] opened 2018-05-31 15:55 UTC
### Preconditions

CentOS 7.4

Magento Version :  2.2.0
php 7.0.30

ElasticSuite Version : latest stable

Environment :  default

Third party modules : Porto Theme

### Steps to reproduce

1. composer require smile/elasticsuite
2. php bin/magento module:enable Smile_ElasticsuiteCore
3. php bin/magento setup:upgrade
4. php bin/magento setup:di:compile
5. php bin/magento setup:static-content:deploy -f

### Expected result

1. To have smoothie deploy

### Actual result

Compilation from source: /var/www/vhosts/sth.gr/httpdocs/vendor/magento/theme-frontend-blank/web/css/styles-m.less
variable @autocomplete-item__border is undefined in file /var/www/vhosts/sth.gr/httpdocs/var/view_preprocessed/pub/static/frontend/Smartwave/porto/en_US/Smile_ElasticsuiteCore/css/source/_module.less in _module.less on line 30, column 34
28|                 border-bottom: 0;
29|             }
30|             .lib-css(border-top, @autocomplete-item__border);
31|             cursor: default;
32|             margin: 0;
33|             padding: @indent__xs @indent__xl @indent__xs @indent__s;
Compilation from source: /var/www/vhosts/sth.gr/httpdocs/vendor/magento/theme-frontend-blank/web/css/styles-l.less
variable @autocomplete-item__border is undefined in file /var/www/vhosts/sth.gr/httpdocs/var/view_preprocessed/pub/static/frontend/Smartwave/porto/en_US/Smile_ElasticsuiteCore/css/source/_module.less in _module.less on line 30, column 34
28|                 border-bottom: 0;
29|             }
30|             .lib-css(border-top, @autocomplete-item__border);
31|             cursor: default;
32|             margin: 0;
33|             padding: @indent__xs @indent__xl @indent__xs @indent__s;

                                                                                                
  [Magento\Framework\Exception\FileSystemException]                                             
  Cannot read contents from file "/var/www/vhosts/sth.gr/httpdocs/pub/static/frontend/S  
  martwave/porto/en_US/css/styles-m.css" Warning!file_get_contents(/var/www/vhosts/sth.  
  gr/httpdocs/pub/static/frontend/Smartwave/porto/en_US/css/styles-m.css): failed to open stre  
  am: No such file or directory   

### Comment

I get the same results, even if I enable all of the five modules.

**Comment by romainruaud** [comment] 2018-06-04 08:56
Duplicate of #91 & #222 

Please see the workaround described in these issues.

regards

**Closed by romainruaud** 2018-06-04 08:56 UTC
Labels: duplicate

**Comment by orbitrod** [comment] 2018-06-07 19:41
I am having the same problem with the Porto theme as well.
