### ISSUE TITLE
I cannot figure how to add additional data to autocomplete product 

### ISSUE THREAD

**Issue by DevRiffs** [Smile-SA/elasticsuite#2009] opened 2020-12-02 09:32 UTC
vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Autocomplete/Product/ItemFactory.php here it is private function addProductData. I need to add additional data to product result, for example 'data_from_somewhere' (not attribute). But I can't find any good way to do it. Do not want to overwrite it completely, but also can't use any plugin. So how to add additional data?

**Comment by romainruaud** [comment] 2020-12-11 14:46
Probably a duplicate of #1416 

Please have a look at the comment describing the solution : https://github.com/Smile-SA/elasticsuite/issues/1416#issuecomment-499768974

**Comment by romainruaud** [comment] 2020-12-11 14:48
Or maybe, if your data is not a Magento2 attribute, just inject a custom collection PreProcessor here : 

https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/etc/frontend/di.xml#L130

**Closed** 2020-12-26 15:14 UTC
Labels: needs update, question
