### ISSUE TITLE
Dev environment install

### ISSUE THREAD

**Issue by husseycoding** [Smile-SA/elasticsuite#1219] opened 2018-12-06 12:53 UTC
### Preconditions

Magento Version : 2.2.6

ElasticSuite Version : 2.6.0

Environment : Developer

Third party modules : None that are relevant

### Steps to reproduce

1. Install extension in environment without elasticsearch installed on the server
2. Run any Magento tool from the command line 

### Expected result

1. The command runs successfully

### Actual result

1. You get the error 'Source class "\boolQuery" for "boolQueryFactory" generation does not exist.'

You see the error above because elasticsearch isn't installed in the server environment - not seeing this where it is installed so this ticket is more to explore possibilities around allowing this extension to be installed in development environments where the elasticsearch is not installed on the server.  Currently as it errors when running any command line tool it essentially blocks development as you can't run any upgrade scripts, import config etc.  So installing the extension appears to be introducing the requirement to have elasticsearch installed on all environments working on the project, even for developers who never do any work on elasticsearch.

Is there any workaround to remove the requirement for elasticsearch being installed in a dev environment where it's not required?

**Comment by rbayet** [comment] 2018-12-06 14:22
Hello @husseycoding,

I would not advise anyone to have a development environment which an architecture or a collection of active modules different than what is deployed in the staging or production environment, it's just asking for karma to hit you hard in the face.

Anyway, the extension assumes that it is there to be used, so installing ElasticSearch beforehand is indeed a requirement (as indicated in the wiki/documentation).
So, in essence, your first "step to reproduce" is a no-no.

But granted, there could be some situations where you are stuck with an ElasticSearch instance/architecture that is down.
If you really need to remove the requirement for ElasticSearch, then the only workaround (other than  removing it completely) is to disable all the extension modules with `php bin/magento module:disable` (*) (and the extra cache/DI cleaning commands after that).
For instance `php bin/magento module:disable Smile_ElasticsuiteCatalogRule Smile_ElasticsuiteCatalogOptimizer Smile_ElasticsuiteSwatches Smile_ElasticsuiteThesaurus Smile_ElasticsuiteTracker Smile_ElasticsuiteVirtualCategory`.

(*) Not _all_ Magento tools or `bin/magento` commands will actually fail...

Regards,

**Comment by husseycoding** [comment] 2018-12-06 14:33
Thanks for the reply @rbayet , ideally don't want to introduce the requirement to have elasticsearch installed in all local dev environments as there are quite a few most of which never need search functionality.  Also some of the environments are pretty locked down in terms of what can and can't be installed, might be that it's just not possible to have elasticsearch installed any time soon, or at all!  Either way it doesn't sound like there is any other option as disabling the extensions would make it's way into the global config and be deployed to all environments.

I'll pass the info on to the relevant people.

**Comment by romainruaud** [comment] 2018-12-06 14:55
Hello,

good practice is to have dev environments which are ISO to your prod environments, otherwise you will not be able to anticipate issues and will be blind about what you are delivering to the next step of your pipeline. It's just an advice but you should think about it. Especially since Elasticsearch is used for all frontend rendering (product list & search result pages).

That being said, yes, it's not possible to install and deploy the module if you are not having a running Elasticsearch. It's the same thing that if you were installing a Magento without an SQL database, it's impossible.

I close the issue since your question has been answered.

Regards

**Closed by romainruaud** 2018-12-06 14:55 UTC

**Comment by husseycoding** [comment] 2018-12-06 15:09
Hi @romainruaud, don't worry we have 2 staging environments in front of production and a dedicated testing team who tests only in these environments (where elasticsearch is installed).  This is in reference to local dev environments only where the only testing that is needed is on the feature currently being worked on which regularly will have nothing to do with elasticsearch/category listings etc at all.  It's a shame that you have been so quick to close the ticket as I feel like the requirement is valid and one that will be found by many other people as well.  Particularly also as the core elasticsearch logic doesn't basically break the store even if elasticsearch is selected as the search engine.

Outside of that, great extension that's likely to save a lot of work down the line.
