### ISSUE TITLE
Backend categories. Products preview not working

### ISSUE THREAD

**Issue by webcreative24** [Smile-SA/elasticsuite#3302] opened 2024-06-20 21:38 UTC
Hello. I have a multi-store setup with two stores and two store views. Each store has its own root category:

En store -> Root category: Default category. This one is set as the default store for the instance.
Am store -> Root category: Default am.
I've imported 1,000 products for each store. When I navigate to categories and switch to the En store, I am able to visually sort products. However, when I switch to the Am store, I see this message:
Your product selection is empty for the selected Store View. If you are running a multi-store setup, please check this [manual page](https://github.com/Smile-SA/elasticsuite/wiki/VirtualCategories#previewing-virtual-categories-on-a-multi-store-setup) for more information.

I tried to debug the issue and found that in the En category, the AJAX request (https://magento.loc/admin/virtualcategory/category_virtual/preview/ajax/1/store/1/key/bcdb....) returned an array of products, but the Am store returned an empty result:
{"products":[],"size":56}

There are no virtual categories or custom settings on ElasticSuite.

Can you please help me identify where to debug this issue, or have you faced something similar before?

Preconditions

Magento Version: 2.4.6-p4
ElasticSuite Version: 2.11.7
ElasticSearch Version: 7.17.9
Environment: Developer or Production
Categores structure:
![image](https://github.com/Smile-SA/elasticsuite/assets/13699502/aba81d9d-2e4b-4be8-b4f1-e3f03e868cbe)
En store switch:
![image](https://github.com/Smile-SA/elasticsuite/assets/13699502/0e04a7bd-154e-4ba1-be79-ba87467c4971)

Am store swtich:
![image](https://github.com/Smile-SA/elasticsuite/assets/13699502/8d217a01-1412-411e-a9f4-6b99a4c9397d)

**Comment by vahonc** [comment] 2024-06-24 14:03
Hello @webcreative24,

At the moment it is difficult to say exactly what is wrong, but maybe something is wrong with your import or his configurations, maybe during the import the products were not correctly assigned to the categories belonging to your second store (Armenian).

Take a look at these screenshots:

![ScreenShot Tool -20240624163909](https://github.com/Smile-SA/elasticsuite/assets/67791361/330261df-d662-4e59-adf2-b69510bff3d3)

![ScreenShot Tool -20240624163714](https://github.com/Smile-SA/elasticsuite/assets/67791361/3dd40643-f55b-4a69-9712-343676001904)

Check some products that belong to another store and ensure everything is configured correctly.

BR,
Vadym

**Comment by webcreative24** [comment] 2024-06-24 22:24
@vahonc I'll check. thanks

**Comment by ssx** [comment] 2024-06-25 07:24
@vahonc: Also having the same issue on 2.4.7-p1 as well. First store, lists and sorts fine. Second store doesn't.

**Comment by ssx** [comment] 2024-06-26 07:49
Hi @Vadym, I'll try to get that over to you shortly. 

In our case: two sites, one with 3 store/store views, one with 2 store/store views.

**Comment by Jerome-Garbocom** [comment] 2024-06-26 08:42
Patch for that

```
--- ./vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Preview.php.orig	    2024-05-02 15:52:52.000000000 +0200
+++ ./vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Preview.php          2024-06-18 17:32:02.148590600 +0200
@@ -121,7 +121,7 @@
         $directionFallback = $sortBy !== 'position' ? Collection::SORT_ORDER_ASC : Collection::SORT_ORDER_DESC;
 
         $collection->setOrder($sortBy, $this->request->getParam('sort_direction', $directionFallback));
-        $collection->addPriceData(self::DEFAULT_CUSTOMER_GROUP_ID, $this->category->getStoreId());
+        $collection->addPriceData(self::DEFAULT_CUSTOMER_GROUP_ID, $this->category->getStore()->getWebsiteId());
 
         return $collection;
     }

```

**Comment by webcreative24** [comment] 2024-06-26 09:53
> $collection->addPriceData(self::DEFAULT_CUSTOMER_GROUP_ID, $this->category->getStore()->getWebsiteId());

Thanks!

**Comment by ssx** [comment] 2024-06-27 14:32
I can confirm that patch has sorted it for us.

**Comment by webcreative24** [comment] 2024-06-27 14:47
@ssx yes, for us too. but we lost the previous sorted positions

**Comment by rbayet** [comment] 2024-07-01 13:41
Hello @webcreative24 

Could you clarify your last comment ?
Which sorted positions did you lose ? 
Are those the positions manually set at the "default store view" level ?
Or positions you intended to import through the product import ?

Regards,

**Comment by ssx** [comment] 2024-07-05 11:03
@rbayet the patch fixed products displaying for us. I'm not sure about ordering as I don't know what order they were in beforehand.

**Closed** 2024-07-10 14:41 UTC
Labels: bug, needs update
