### ISSUE TITLE
Issues with new Magento/Elasticsearch8, existing install - No commands defined after composer install of smile/elasticsuite

### ISSUE THREAD

**Issue by aramsdale** [Smile-SA/elasticsuite#3068] opened 2023-10-02 17:21 UTC
### Preconditions
Using Magento 2.4.6-p2, elasticsearch 8. All is working, indexes running, etc. Just trying to install elasticsuite, and then set up the modules, per the install guide.

Magento Version :2.4.6-p2 CE

ElasticSuite Version : 8.4

Environment : Production

Third party modules :

### Steps to reproduce

1. Installed Magento, Elasticsearch 8.4, base template and demo products
2. ran 'composer require smile/elasticsuite ~2.11.0' in magento_home directory
3. Attempted to enable elasticsuite modules, per 'bin/magento module:enable Smile_ElasticsuiteCore Smile_ElasticsuiteCatalog Smile_ElasticsuiteSwatches Smile_ElasticsuiteCatalogRule Smile_ElasticsuiteVirtualCategory Smile_ElasticsuiteThesaurus Smile_ElasticsuiteCatalogOptimizer Smile_ElasticsuiteTracker Smile_ElasticsuiteAnalytics Smile_ElasticsuiteAdminNotification'

### Expected result

1. Modules should process/enable

### Actual result

1. the addition of Elasticsuite in the composer file breaks the module namespace: " There are no commands defined in the "module" namespace."
2. Additionally, it seems to break all of the other commands also. trying to run a 'bin/magento list' command produces the following results:

Magento CLI 2.4.6-p2

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display help for the given command. When no command is given display help for the list command
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi|--no-ansi  Force (or disable --no-ansi) ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  completion  Dump the shell completion script
  help        Display help for a command
  list        List commands

In ServiceManager.php line 649:

  Service with name "Magento\Setup\Console\Command\ConfigSetCommand" could not be created. Reason: Impossible to process constructor argument Parameter #0 [ <required> Elasticsearch\ClientBuilder $clientBuilder ] of Smile\ElasticsuiteCore\Client\ClientBuilder class

In ClassReader.php line 57:

  Impossible to process constructor argument Parameter #0 [ <required> Elasticsearch\ClientBuilder $clientBuilder ] of Smile\ElasticsuiteCore\Client\ClientBuilder class

In GetParameterClassTrait.php line 34:

  Class "Elasticsearch\ClientBuilder" does not exist

**Comment by aramsdale** [comment] 2023-10-02 17:25
May be a continuation or additional context/related to [https://github.com/Smile-SA/elasticsuite/issues/2880](https://github.com/Smile-SA/elasticsuite/issues/2880)

**Comment by aramsdale** [comment] 2023-10-02 19:45
Redoing everything, I'm able to install all the way through... as soon as I add the elasticsesarch 8 magento modules, I hit the same issue.

**Comment by romainruaud** [comment] 2023-10-02 20:17
Duplicate of #2880 for me yep.

As said in the comment, do not install ``magento/module-elasticsearch-8`` : https://github.com/Smile-SA/elasticsuite/issues/2880#issuecomment-1483108798

Most probably, running ``composer remove magento/module-elasticsearch-8`` will make you rollback to ``elasticsearch/elasticsearch`` on version 7.x

**Comment by romainruaud** [comment] 2023-10-18 12:45
Closed for being a duplicate.

**Closed by romainruaud** 2023-10-18 12:45 UTC
Labels: duplicate
