### ISSUE TITLE
similar word instead of exact word in 2.3

### ISSUE THREAD

**Issue by rparentO2web** [Smile-SA/elasticsuite#1068] opened 2018-09-10 15:33 UTC
### Preconditions

Magento Version : 2.1.11 CE

ElasticSuite Version : 2.3.11

Environment : Production

### Steps to reproduce

1. Search the word "sound" 

### Expected result

1. Get products with the exact word  "sound" and the products with similar words to "sound" (example: Search: "sound" -> Get: "soundtouch")

### Actual result

1. Get only products with the exact word.

**Comment by romainruaud** [comment] 2018-10-03 14:19
Duplicate of #970 and #1036 (read detailed comment in these issues please)

TLDR : it's working as intended.

**Closed by romainruaud** 2018-10-03 14:19 UTC
