### ISSUE TITLE
Category filter is not working due to smile layered navigation

### ISSUE THREAD

**Issue by ezest-rajesh** [Smile-SA/elasticsuite#1449] opened 2019-06-27 07:43 UTC
### Preconditions

Hi Team,

Hope you are doing great!

I want to disable price slider from the layered navigation only, could you please help me.

And also, Smile Elastic search layered navigation is breaking category filter, It is directly redirecting to the category page and not doing the filter.
URL generates by smile for category filter: http://demo.magento-elastic-suite.io/index.php/men/tops-men/jackets-men.html
URL generates by Magento category filter:
http://local.m2ee.com/men/tops-men.html?cat=15

I want to disable price slider in layered navigation. Enable default Magento price filter by range.
I want to enable the category filter in Magento OOTB.
Please see attached screenshot for more details.

Magento Version : Magento Commerce 2.1.9

ElasticSuite Version : ~2.3.0

Environment : Dev 

Third party modules : No

### Steps to reproduce

1. Go to category/search result page
2. click on the category filter
3. redirecting category page instead of filter category by id

### Expected result

1. The product should filter by a category id

### Actual result

1. [Screenshot, logs]

**Comment by romainruaud** [comment] 2019-06-27 15:12
Hello @ezest-rajesh 

The category filter has been fixed in ElasticSuite 2.8.0 : https://github.com/Smile-SA/elasticsuite/releases/tag/2.8.0

You should update (I know, this would also imply upgrading your Magento Store to 2.3.x)

Additionnaly, you are using a very old version of ElasticSuite which is not part of our Open Source support commitment here on Github.

Rest of your question is a duplicate of #555 .

Regards

**Comment by ezest-rajesh** [comment] 2019-06-28 07:19
Hi @romainruaud,

Thanks for your quick reply,

We are using Magento Commerce 2.1.9 hance could not integrate Smile Elastic 2.8.0 as compatibility issues, could you please provide the patch which fixes the category issue?


Thanks,
Rajesh

**Comment by romainruaud** [comment] 2019-07-08 07:26
The PR for the category filter was this one, as stated in the changelog : https://github.com/Smile-SA/elasticsuite/pull/1388

Feel free to backport it to your version if you need it.

However, you should upgrade to latest Magento version since 2.1.9 is not supported anymore and 2.2 is scheduled for end of support on december.

Regards

**Closed by romainruaud** 2019-07-08 07:26 UTC
Labels: duplicate, wontfix
