### ISSUE TITLE
Multiselect attribute filter list changes on applying .

### ISSUE THREAD

**Issue by rahul-bhandary** [Smile-SA/elasticsuite#812] opened 2018-03-09 13:24 UTC
###Preconditions

Magento Version: 2.1.8 CE
ElasticSuite Version : 2.3.0
Environment: Developer mode
Third party modules: No

### Steps to reproduce
1. Go to category page, apply any of the multiselect filter
2. After applying any one of the multiselect filter, the no of multiselect values changes

### Expected result
1. Multiselect filter values should not change

### Actual result

1. Before applying filter

![screen shot 2018-03-09 at 6 46 18 pm](https://user-images.githubusercontent.com/15210758/37209344-02e98ea2-23cb-11e8-9814-a9604d7dd702.png)

2. Apply applying filter

![screen shot 2018-03-09 at 6 46 39 pm](https://user-images.githubusercontent.com/15210758/37209352-0923b6da-23cb-11e8-9126-24ce75838728.png)

**Comment by romainruaud** [comment] 2018-03-09 15:12
First of all, if you are really using Elasticsuite 2.3.**0** please consider upgrading to the 2.3.**11* version, since the 2.3.0 is now quite old, and many bugs were fixed by the subsequent minor version updates.

Once this is done, or when you are sure that you are using latest 2.3 version, could you please post your attribute configuration ? Especially the value of the fields used by Elasticsuite and listed here : https://github.com/Smile-SA/elasticsuite/wiki/Attribute-configuration#faceting-configuration

Regards

**Comment by romainruaud** [comment] 2018-03-09 15:36
Pretty sure you have overriden the default filter template, didn't you ?

Because otherwise you should see a "Show more" button and a text input on your first screen (where the list is capped).

So I strongly supposed this is a templating issue caused by a template override on your project.

regards

**Comment by afoucret** [comment] 2018-03-09 16:09
I would close this issue since as explained by @romainruaud it is a design issue.
Our template include a "Show more/Show Less" feature that is not present in your design.
You still can use a very high max value per facet if you don't want to use this feature.

I close for being "by design".

**Closed by afoucret** 2018-03-09 16:09 UTC
Labels: needs update
