### ISSUE TITLE
Loading more filter options produces non working urls

### ISSUE THREAD

**Issue by caesarcxiv** [Smile-SA/elasticsuite#930] opened 2018-05-27 15:05 UTC
### Preconditions

Magento Version : 2.2.4 ce

ElasticSuite Version : 2.5.9

Environment : Production

Third party modules :

### Steps to reproduce

1.perform search
2. Click show more options on filter
3. When the filter is loaded by clicking view more filter options the url is Ajax instead of https://demo.com?manufacturer=Smile 

Incorrect url that results in json being displayed https://url.com/catalog/navigation_filter/ajax/id/200/?_=1527432892434&cat=1&filterName=manufacturer

The first 5 filter options are correct.

### Expected result

1. All filter options generate the same url

### Actual result

1. Json displayed to end user

**Comment by romainruaud** [comment] 2018-05-29 08:13
Hello @caesarcxiv 

Since this is not occuring on the luma theme on our demo website (check http://demo.magento-elastic-suite.io/index.php/men/tops-men.html ) I strongly suspect there is something wrong with your theme or template for filters.

Your issue is an exact duplicate of #686 which was caused by the Mirasvit_Seo module. Are you using this module too ?

Are you using a custom theme ? Or maybe an other custom third party module ?

**Comment by afoucret** [comment] 2018-06-04 10:03
Hi @caesarcxiv,

The most probable cause for this bug is a JS error in a third party module.
Feel free to reopen if you can provide us more detail that can confirm an ElasticSuite bug.

**Closed by afoucret** 2018-06-04 10:03 UTC
Labels: bug, duplicate
