### ISSUE TITLE
Configurable products, missing attributes

### ISSUE THREAD

**Issue by gewaechshaus** [Smile-SA/elasticsuite#792] opened 2018-02-28 12:35 UTC
@afoucret - we noticed that all configurable attributes on configurable products are missing in frontend... Customers are calling in cause they can't buy the products :)
It this also related to the 2.5.3 update?

**Comment by afoucret** [comment] 2018-02-28 12:38
My testing dataset contains a lot of configurable (80%) and I can't reproduce the issue.
I will need more information to see if it is related to ElasticSuite or not.

If the problem occurs on the product page, I don't think it is related to ElasticSuite (since it is not used there).

BR,

**Comment by gewaechshaus** [comment] 2018-02-28 12:41
@afoucret - yes only in product single view

**Comment by afoucret** [comment] 2018-02-28 12:43
So I don't think it is related to ElasticSuite !!!

Let me know if you find something new but as it is unlikely that it is an ElasticSuite bug, I close the issue.

**Closed by afoucret** 2018-02-28 12:43 UTC
