### ISSUE TITLE
Autocomplete error with attribute displayed in autocomplete and not filterable

### ISSUE THREAD

**Issue by chrey** [Smile-SA/elasticsuite#307] opened 2017-01-23 11:26 UTC
Our customer modified in backend the atribute "name" to display it in the autocomplete results. This is not necessary because it is already selected by default in the collection but possible to do in Magento backend. 
This configuration leads to a weird error : 

<pre>
http://catanoma-prod.groupement.systeme-u.fr/au-rayon/cuisine-et-table.html?code_fournisseur%5B0%5D=HL+DISPLAY&code_fournisseur%5B1%5D=SITOUR
</pre>

It should not be possible to save an attribute displayed in autocomplete + not filterable

Charlotte

**Comment by romainruaud** [comment] 2017-01-23 16:34
Even if this is not the same error, this is a duplicate of #294 regarding a misconfiguration of attributes.

Will be fixed by c44af9d1b8c4b879bb580c5f474d18624c49bf98

**Comment by romainruaud** [comment] 2017-01-23 16:55
This has been fixed in release 2.3.1.

Feel free to upgrade to this version.

Best regards

**Closed by romainruaud** 2017-01-23 16:55 UTC
Labels: bug, duplicate
