### ISSUE TITLE
Admin Category Page - Form Key not being sent

### ISSUE THREAD

**Issue by lucasjor-summa** [Smile-SA/elasticsuite#836] opened 2018-03-22 13:33 UTC
When entering any Category page in Admin there's one ajax request that's throwing a JS error. This ends up with the page loading infinitely.
Further debugging showed up that the JS error is caused by an "Invalid Form Key" exception.

### Preconditions

1000+ product attributes

Magento Version : 2.2.2 EE

ElasticSuite Version : 5.6.8

Environment : Developer mode

Third party modules : none

### Steps to reproduce

1. Create 1000+ attributes, backend_type = varchar, frontend_input = select, filterable = true
2. Create one product, visible, with stock, and assign it to any category.
3. In Admin go to Catalog -> Categories
4. Wait for page to finish loading

### Expected result

1. Categories page should load fine.

### Actual result

An AJAX request is throwing error.
![js_error](https://user-images.githubusercontent.com/7723883/37773248-df65e9f8-2dbb-11e8-8a46-c0504d738e53.png)

Further debugging showed that the form key is not being sent in POST params. I attach screenshots to see the difference between POST params in Magento vanilla and in Magento with Smile.
![params_without_smile](https://user-images.githubusercontent.com/7723883/37773260-e854e3e8-2dbb-11e8-9f29-ffc21452544b.png)
![params_with_smile](https://user-images.githubusercontent.com/7723883/37773275-ee282bd6-2dbb-11e8-899b-357c009a8fc6.png)

**Comment by afoucret** [comment] 2018-03-22 13:37
The problem is in your PHP configuration (max_input_vars).
Read the last comment of issue #748 by @danrcoull since your issue is a duplicate of it.

**Closed** 2018-03-22 14:52 UTC

**Comment by afoucret** [comment] 2018-03-22 14:53
Supposed increase of the max_input_vars solved the problem.
We should be able to propose a patch to avoid changing the PHP conf.

I will post the PR for testing here when ready.
