### ISSUE TITLE
Category filter on a virtual category page

### ISSUE THREAD

**Issue by dyron** [Smile-SA/elasticsuite#865] opened 2018-04-13 12:03 UTC
Magento Version : 2.2.3

ElasticSuite Version : 2.5.3

Environment : Developer

Is it possible to show the category filters on virtual category pages?

**Comment by afoucret** [comment] 2018-04-16 11:48
The category filter is build using children categories of the current category page.
We have a pending RFC since a while to allow to rebuild a complete tree from another anchor point of the catalog (#49) ... but no planning to deliver it.

I close since it is a duplicate of RFC #49. You can upvote if you need it.

**Closed by afoucret** 2018-04-16 11:48 UTC

**Comment by dyron** [comment] 2018-04-16 12:59
Mind a contribution? Is #235 a good start?
