### ISSUE TITLE
ElasticSuite 2.2.5 - Error page category Frontend

### ISSUE THREAD

**Issue by DogSports** [Smile-SA/elasticsuite#256] opened 2016-12-16 16:24 UTC
Magnto 2.1.3
ElasticSuite 2.2.5

In the categories pages, I have this error message:

`
Fatal error: Uncaught Error: Call to a member function getCategorySearchQuery() on null in /var/www/vhosts/domain.com/httpdocs/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Layer/Filter/Category.php:96 Stack trace: #0 /var/www/vhosts/domain.com/httpdocs/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Layer/Filter/Category.php(98): Smile\ElasticsuiteVirtualCategory\Model\Layer\Filter\Category->applyCategoryFilterToCollection(Object(Magento\Catalog\Model\Category\Interceptor)) #1 /var/www/vhosts/domain.com/httpdocs/vendor/magento/module-layered-navigation/Block/Navigation.php(64): Smile\ElasticsuiteCatalog\Model\Layer\Filter\Category->apply(Object(Magento\Framework\App\Request\Http)) #2 /var/www/vhosts/domain.com/httpdocs/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Block/Navigation.php(98): Magento\LayeredNavigation\Block\Navigation->_prepareLayout() #3 /var/www/vhosts/domain.com/httpdocs/vendor/magento/framework/View/Element/AbstractBlock.php(264) in /var/www/vhosts/domain.com/httpdocs/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Layer/Filter/Category.php on line 96`

Thanks for your help.

**Comment by romainruaud** [comment] 2016-12-16 16:31
Hello @DogSports .

It seems to be a duplicate of #187 and #205 and due to the non-support of flat categories on the 2.2.X versions of ElasticSuite.

The support of flat categories has been added to the 2.3.x branch.

So you have the choice between shutting down flat categories and stay on stable 2.2.5 release, or switch to the 2.3.x branch .

Best regards,

I close the issue, feel free to reopen it if you have other questions.

**Closed by romainruaud** 2016-12-16 16:31 UTC
