### ISSUE TITLE
Remove requirement for Acitve Elastic Search Server on setup:install and setup:upgrade

### ISSUE THREAD

**Issue by tschirmer** [Smile-SA/elasticsuite#1627] opened 2019-11-25 08:07 UTC
**Is your feature request related to a problem? Please describe.**
When we're running this in development, we sometimes need to run setup:install, setup:upgrade, and  setup:config:set, and with your module installed, the setups halt if an elastic search connection isn't found. In development, we often don't have all services running to make development environments simpler to jump into an issue; especially if the development isn't related to the product search index.

**Describe the solution you'd like**
We'd like to see this requirement removed so that we can run setup:install,setup:upgrade without  and setup:config:set without an elastic search server running and active.

**Comment by romainruaud** [comment] 2020-01-08 11:26
Duplicate of #1639

**Closed by romainruaud** 2020-01-08 11:26 UTC
Labels: feature
