### ISSUE TITLE
Can't bulk add products to category

### ISSUE THREAD

**Issue by vseager** [Smile-SA/elasticsuite#2013] opened 2020-12-04 23:47 UTC
### Preconditions

This is a repeat of #414 which seems to be present in the latest release on Magento 2.4.1.

Magento Version : 2.4.1

ElasticSuite Version :2.10.3

Environment : Live / staging

Third party modules : None

### Steps to reproduce

1. Go to Products->Categories
2. Open tab "Products in Category"
3. Search for some products
4. Select all using "select all checkbox" in the top left corner of the table
5. Hit "Save"

### Expected result

1. Category saves with new product selection

### Actual result

1. An error occurs: Something went wrong while saving the category.

```
 SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`xxxxxx`.`catalog_category_product`, CONSTRAINT `CAT_CTGR_PRD_PRD_ID_CAT_PRD_ENTT_ENTT_ID` FOREIGN KEY (`product_id`) REFERENCES `catalog_product_entity` (`entity_id`) ON DELETE CAS), query was: INSERT  INTO `catalog_category_product` (`category_id`,`product_id`,`position`) VALUES (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?)
```

Note that it works fine if you select the products individually before saving, it only happens when selecting a

**Comment by vahonc** [comment] 2020-12-07 16:20
Hello @vseager,

I also reproduce this bug on my local environment. I'm not sure if this is exactly repeat of #414 issue, but I'll take a look and try to fix it.

Best regards,

**Comment by vahonc** [comment] 2020-12-09 16:02
Hello @vseager,

I've update solution from PR https://github.com/Smile-SA/elasticsuite/pull/418/files
<pre>
} else if (element.value && element.id) {
      // Override is here. Add the product to categoryProducts even if it does not have position field
      if (element.value !== 'on') {
          categoryProducts.set(element.value, 0);
      }
}
</pre>

Could you please check this quick fix on your side?

I'll add a PR a little bit later.

Best regards,

**Comment by duffner** [comment] 2020-12-21 01:29
@romainruaud, have you reviewed the above fix for this issue?

**Comment by rbayet** [comment] 2021-01-06 17:04
Hello @vahonc, 

I tested locally your approach it is the correct fix, but I would simplify it since the condition on `element.id` is not needed anymore : 
```
} else if (element.value && (element.value !== 'on')) {
      // Override is here. Add the product to categoryProducts even if it does not have position field
      categoryProducts.set(element.value, 0);
}
```

In theory, since element.value is supposed to hold the productId, we could also go with 
```
} else if (parseInt(element.value, 10) > 0)) {
      // Override is here. Add the product to categoryProducts even if it does not have position field
      categoryProducts.set(element.value, 0);
}
```
because `parseInt('on', 10)` will result in a `Nan`. But I haven't checked all browsers will handle gracefully a `Nan > 0` comparison.

**Comment by vahonc** [comment] 2021-01-07 10:59
Hello @rbayet,

I agree with you that it's a good solution:

<pre>
} else if (parseInt(element.value, 10) > 0)) {
      // Override is here. Add the product to categoryProducts even if it does not have position field.
      categoryProducts.set(element.value, 0);
}
</pre>

I've tested it on Magento ver. 2.3.5-p1 and Magento ver. 2.4.1 in Chrome and Firefox browsers and looks everything is good and I didn't notice any errors during the saving category after mass adding products.

And according to this:

![Screenshot from 2021-01-07 12-54-23](https://user-images.githubusercontent.com/67791361/103884814-c48a5680-50e7-11eb-9c00-f7232285dd82.png)

I don't think that we could have any issues with browser compatibility.

**Comment by rbayet** [comment] 2021-01-07 12:46
Hi @vahonc,

I don't have any doubt about `parseInt` per se, but more about `NaN > 0`, so maybe using `isNan` (and not `Number.isNaN`) if we go this way is the better approach.
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN vs https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN

**Closed** 2021-01-07 15:58 UTC
Labels: bug

**Comment by OvalMedia** [comment] 2021-08-02 15:04
2.10.5 / magento 2.4.2-p1: problem persists.
