### ISSUE TITLE
Disable Product Preview and Sorting

### ISSUE THREAD

**Issue by JerrodDavenport** [Smile-SA/elasticsuite#1069] opened 2018-09-10 17:35 UTC
Is there anyway to disable the Product Preview and Sorting feature?  We send hundreds of hours sorting the products in the past.  But when we updated to this elasticsuite, its using the Product Preview and Sorting instead of what we had before.  I'm kind of disappointed it doesn't use the previous sorting (position) by default.

### Preconditions

Magento Version : Version 2.1.9 EE

ElasticSuite Version : ElasticSuite 2.6

Environment : Production 

Third party modules : 

### Steps to reproduce

1. We have previously sorted products
2. After the install, items are in a random order.
3. The order is whats in the new Product Preview and Sorting feature.

### Expected result

1.  I would think this Product Preview and Sorting could be disabled.  
2. Or have the option to use the previous sorting options.

### Actual result

1. See screenshot.

![capture](https://user-images.githubusercontent.com/28022699/45313953-fbd7a100-b4f5-11e8-989b-3e157dfa640b.JPG)

**Comment by romainruaud** [comment] 2018-10-03 14:39
Duplicate of #998

**Closed by romainruaud** 2018-10-03 14:39 UTC
Labels: duplicate

**Comment by rikwillems** [comment] 2018-11-07 13:58
@JerrodDavenport we had the same issue and solved it by copying all values from catalog_category_product to smile_virtualcategory_catalog_category_product_position. This doesn't solve future sorting though.
