### ISSUE TITLE
How to search products by tags?

### ISSUE THREAD

**Issue by madonzy** [Smile-SA/elasticsuite#515] opened 2017-08-29 07:46 UTC
Is it possible to search products by tags (assigned to product) using Elasticsuit for Magento 2. If not, how can implement this feature?

**Comment by romainruaud** [comment] 2017-08-29 12:40
Seems like a duplicate of #517 

Since I have answered in the other issue, I close this one.

**Closed by romainruaud** 2017-08-29 12:40 UTC
Labels: question
