### ISSUE TITLE
AJAX Price Slider

### ISSUE THREAD

**Issue by fleex0** [Smile-SA/elasticsuite#671] opened 2017-12-26 19:09 UTC
Would be great if Elastic search get's a AJAX on the price slider!

**Comment by romainruaud** [comment] 2018-01-03 15:07
This feature request is a duplicate of #228 regarding Ajax layered navigation.

Please upvote this feature request if you'd like to see it implemented.

Best regards, and thank you for using our module

**Closed by romainruaud** 2018-01-03 15:07 UTC
Labels: duplicate
