### ISSUE TITLE
elasticsearch was not working on magento2

### ISSUE THREAD

**Issue by goudas** [Smile-SA/elasticsuite#252] opened 2016-12-15 08:41 UTC
I was getting this error in exception log
CRITICAL: Magento\Framework\Exception\LocalizedException: The element 'category.product.type.details.renderers' already has a child with alias 
'configurable' in /var/www/html/magento2/lib/internal/Magento/Framework/Data/Structure.php:611
Stack trace:

**Comment by afoucret** [comment] 2016-12-15 08:47
Hi @goudas,

This bug seems to be a duplicate of #170 and have been fixed at least in latest 2.2.x release.
Updating your ElasticSuite stable version (2.2.4) should fix this one.

Feel free to repoen if the solution does not works for you.

BR,

**Closed by afoucret** 2016-12-15 08:47 UTC
