### ISSUE TITLE
Not sure about the spellcheck accuracy in autocomplete

### ISSUE THREAD

**Issue by PierrickOlivier** [Smile-SA/elasticsuite#75] opened 2016-07-04 14:22 UTC
I have some doubts (?) about the accuracy of the "spellcheck" feature in autocomplete.

For example on the store http://demo.magento-elastic-suite.io/
if you search "fytness", the autocomplete doesn't suggest any product, but the search engine suggest "fitness" products.

I did some tests with Magento 1 and it seems that the autocomplete engine was much more tolerant to mistakes during typing. On Magento 2 almost no mistakes are allowed.

Possible explanation: Maybe only the phonetic search is applied in autocomplete without fuzzy search ?
Example:
"messengeer" suggest products with "messenger"
but
"messengeZr" doesn't suggest any product

**Comment by romainruaud** [comment] 2016-09-14 16:31
Confirmed. Fuzziness and Phonetic are not applied in autocomplete.

Currently investigating.

**Comment by romainruaud** [comment] 2016-09-14 17:10
This is due to : 

- autocomplete queries having no proper container defined (so they will try to use the catalog_view_container relevance configuration). Ok, this is easy to fix.

- the Spellchecker does not analyze array queries : see https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-core/Search/Request/Builder.php#L182

see the PR #114 for a proposal of implementation

**Comment by romainruaud** [comment] 2016-09-15 08:21
Other idea, we could consider the Request Builder to process a fuzzy query by default, instead of an exact one, but that's not perfect either.

**Comment by romainruaud** [comment] 2016-09-20 15:23
@afoucret assigned for review of #114

**Comment by romainruaud** [comment] 2016-09-23 09:51
the PR has been merged.

**Closed by romainruaud** 2016-09-23 09:51 UTC
Labels: bug
