### ISSUE TITLE
Magento 2.4.5 compatibility.

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/elasticsuite#2663] opened 2022-07-28 08:40 UTC
Magento 2.4.5 will land on August 9th.

It's already added in our integration test suite for branch 2.10.x.

All tests are working actually which is a good start.

We need to check that all features are functioning as expected.

**Comment by vahonc** [comment] 2022-08-03 14:17
When clicking on the `Magento BO -> ElasticSuite -> Search Relevance` section we get an error:

<pre>
[2022-08-03T13:47:34.670004+00:00] report.CRITICAL: Error: Call to a member function getEuCountryList() on null in /home/vahonc/Projects/m245ee/vendor/magento/module-config/view/adminhtml/templates/system/config/js.phtml:81
Stack trace:
#0 /home/vahonc/Projects/m245ee/vendor/magento/framework/View/TemplateEngine/Php.php(71): include()
#1 /home/vahonc/Projects/m245ee/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php->render()
#2 /home/vahonc/Projects/m245ee/vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView()
#3 /home/vahonc/Projects/m245ee/vendor/magento/module-backend/Block/Template.php(141): Magento\Framework\View\Element\Template->_toHtml()
#4 /home/vahonc/Projects/m245ee/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Backend\Block\Template->_toHtml()
#5 /home/vahonc/Projects/m245ee/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#6 /home/vahonc/Projects/m245ee/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#7 /home/vahonc/Projects/m245ee/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#8 /home/vahonc/Projects/m245ee/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#9 /home/vahonc/Projects/m245ee/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#10 /home/vahonc/Projects/m245ee/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#11 /home/vahonc/Projects/m245ee/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#12 /home/vahonc/Projects/m245ee/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#13 /home/vahonc/Projects/m245ee/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#14 /home/vahonc/Projects/m245ee/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#15 /home/vahonc/Projects/m245ee/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#16 /home/vahonc/Projects/m245ee/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#17 /home/vahonc/Projects/m245ee/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#18 /home/vahonc/Projects/m245ee/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#19 /home/vahonc/Projects/m245ee/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#20 /home/vahonc/Projects/m245ee/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#21 /home/vahonc/Projects/m245ee/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#22 /home/vahonc/Projects/m245ee/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout->renderElement()
#23 /home/vahonc/Projects/m245ee/generated/code/Magento/Framework/View/Layout/Interceptor.php(50): Magento\Framework\View\Layout->getOutput()
#24 /home/vahonc/Projects/m245ee/vendor/magento/framework/View/Result/Page.php(260): Magento\Framework\View\Layout\Interceptor->getOutput()
#25 /home/vahonc/Projects/m245ee/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render()
#26 /home/vahonc/Projects/m245ee/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(32): Magento\Framework\View\Result\Layout->renderResult()
#27 /home/vahonc/Projects/m245ee/vendor/magento/framework/App/Http.php(120): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult()
#28 /home/vahonc/Projects/m245ee/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#29 /home/vahonc/Projects/m245ee/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#30 /home/vahonc/Projects/m245ee/phpserver/router.php(119): include('...')
#31 {main} [] []
</pre>

**Comment by vahonc** [comment] 2022-08-04 14:44
I found another issue related to counting items on the category page.

For example, if we go to the "Gear -> Watches" category, we will see that the number of items in this category is 9.

![Screenshot from 2022-08-04 17-33-33](https://user-images.githubusercontent.com/67791361/182874129-0395c088-8154-4012-8f4d-20903a4e8ca7.png)

Now if we add a filter e.g. "Material -> Plastic" (with 4 results) we should see the correct number of items, like 4 items, but it still shows 9 items.

![Screenshot from 2022-08-04 17-10-47](https://user-images.githubusercontent.com/67791361/182874501-68263c97-2d33-4f50-b57b-7566f53d36a0.png)

I will try to check on fresh M2.4.5 without ES, maybe it's a native bug of the new version.

**Comment by leonhelmus** [comment] 2022-08-10 16:14
Yes, we are also experiencing the same issue. See image:
![image](https://user-images.githubusercontent.com/18070887/183960481-983ae668-b517-46ec-8ffe-63bdbb6c5505.png)
Or for category:
![image](https://user-images.githubusercontent.com/18070887/183960650-7e5624b7-c186-4e7f-a88b-fb0f06afb8c3.png)

**Comment by leonhelmus** [comment] 2022-08-10 16:18
When i do a composer require smile/elasticsuite i also get this error:
![image](https://user-images.githubusercontent.com/18070887/183961361-8d51e6bb-d87c-4443-8e19-6df7675cdad7.png)
Not sure yet why it's happening.
This only happened to me for magento 2.4.5

**Comment by vahonc** [comment] 2022-08-11 12:53
Hello @leonhelmus,

The strange thing, after reinstalling ElasticSuite this issue is gone. And looks like now all is fine with counting items on the page no matter which filters I select.

So, try to re-install ES and then run these commands:
<pre>$ bin/magento setup:upgrade
$ bin/magento setup:di:compile
$ bin/magento setup:static-content:deploy -f
$ bin/magento cache:clean
$ bin/magento indexer:reindex</pre>

BR,
Vadym

**Comment by leonhelmus** [comment] 2022-08-11 13:49
@vahonc it was upgraded from a previous version 2.4.4. Those steps were also taken to see if it resolved it.

I will check the debug mode and see whats up.

**Comment by leonhelmus** [comment] 2022-08-15 09:27
@vahonc  I think i found the culprit in magento 2.4.5 they added a new plugin (class: \Magento\InventoryCatalog\Plugin\Catalog\Block\ProductList\UpdateToolbarCount) for out of stock products, see:
![image](https://user-images.githubusercontent.com/18070887/184610452-af919880-ccbf-4a1d-8a7b-fbd915a96c78.png)

They only did not take into account what the current filters are... So for out of stock products there is an issue, Not quite sure if this needs to be resolved by elasticsearch or magento themselfs....

**Comment by vahonc** [comment] 2022-08-15 10:49
Hi @leonhelmus!

I agree with you that this issue was caused by setting "Display products that are out of stock => Yes".

Thanks for your investigation and PR for Magento. 

BR,
Vadym

**Comment by leonhelmus** [comment] 2022-08-15 11:33
@vahonc I think i did not get any issues back from QA about categories and search so i think it's safe to say this module is compatible.

**Comment by nmarquev** [comment] 2022-08-18 22:30
Hello, when filtering by a swatches attribute (color) with an option that resulkts in only one result, we get this error:

![image](https://user-images.githubusercontent.com/20818155/185506357-d6d25290-e83f-4b1d-993d-1acb6d1d21b4.png)

`1 exception(s):
Exception #0 (Exception): Notice: Array to string conversion in /home/rollpixprod/public_html/sileo/vendor/magento/module-swatches/Helper/Data.php on line 199

Exception #0 (Exception): Notice: Array to string conversion in /home/rollpixprod/public_html/sileo/vendor/magento/module-swatches/Helper/Data.php on line 199
<pre>#1 array_diff_assoc() called at [vendor/magento/module-swatches/Helper/Data.php:199]
#2 Magento\Swatches\Helper\Data->loadFirstVariation() called at [vendor/magento/module-swatches/Helper/Data.php:231]
#3 Magento\Swatches\Helper\Data->loadFirstVariationWithImage() called at [vendor/smile/elasticsuite/src/module-elasticsuite-swatches/Model/Plugin/ProductImage.php:101]
#4 Smile\ElasticsuiteSwatches\Model\Plugin\ProductImage->loadSimpleVariation() called at [vendor/smile/elasticsuite/src/module-elasticsuite-swatches/Model/Plugin/ProductImage.php:47]
#5 Smile\ElasticsuiteSwatches\Model\Plugin\ProductImage->beforeGetImage() called at [vendor/magento/framework/Interception/Interceptor.php:121]
#6 Magento\Catalog\Block\Product\ListProduct\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#7 Magento\Catalog\Block\Product\ListProduct\Interceptor->___callPlugins() called at [generated/code/Magento/Catalog/Block/Product/ListProduct/Interceptor.php:329]
#8 Magento\Catalog\Block\Product\ListProduct\Interceptor->getImage() called at [app/design/frontend/Rollpix/sileo/Magento_Catalog/templates/product/list.phtml:66]
#9 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:71]
#10 Magento\Framework\View\TemplateEngine\Php->render() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#11 Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#12 Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#13 Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php:23]
#14 Magento\Framework\View\TemplateEngine\Php\Interceptor->render() called at [vendor/magento/framework/View/Element/Template.php:263]
#15 Magento\Framework\View\Element\Template->fetchView() called at [generated/code/Magento/Catalog/Block/Product/ListProduct/Interceptor.php:392]
#16 Magento\Catalog\Block\Product\ListProduct\Interceptor->fetchView() called at [vendor/magento/framework/View/Element/Template.php:293]
#17 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1095]
#18 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1099]
#19 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:660]
#20 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#21 Magento\Catalog\Block\Product\ListProduct\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#22 Magento\Catalog\Block\Product\ListProduct\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#23 Magento\Catalog\Block\Product\ListProduct\Interceptor->___callPlugins() called at [generated/code/Magento/Catalog/Block/Product/ListProduct/Interceptor.php:617]
#24 Magento\Catalog\Block\Product\ListProduct\Interceptor->toHtml() called at [vendor/magento/framework/View/Layout.php:578]
#25 Magento\Framework\View\Layout->_renderBlock() called at [vendor/magento/framework/View/Layout.php:555]
#26 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#27 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#28 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#29 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Element/AbstractBlock.php:507]
#30 Magento\Framework\View\Element\AbstractBlock->getChildHtml() called at [vendor/magento/module-catalog/Block/Category/View.php:100]
#31 Magento\Catalog\Block\Category\View->getProductListHtml() called at [vendor/magento/module-catalog/view/frontend/templates/category/products.phtml:15]
#32 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:71]
#33 Magento\Framework\View\TemplateEngine\Php->render() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#34 Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#35 Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#36 Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php:23]
#37 Magento\Framework\View\TemplateEngine\Php\Interceptor->render() called at [vendor/magento/framework/View/Element/Template.php:263]
#38 Magento\Framework\View\Element\Template->fetchView() called at [vendor/magento/framework/View/Element/Template.php:293]
#39 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1095]
#40 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1099]
#41 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:660]
#42 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:578]
#43 Magento\Framework\View\Layout->_renderBlock() called at [vendor/magento/framework/View/Layout.php:555]
#44 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#45 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#46 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#47 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#48 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#49 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#50 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#51 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#52 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#53 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#54 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#55 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#56 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#57 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#58 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#59 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#60 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#61 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#62 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#63 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#64 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#65 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#66 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#67 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#68 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#69 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#70 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#71 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#72 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#73 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#74 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#75 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#76 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#77 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:975]
#78 Magento\Framework\View\Layout->getOutput() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#79 Magento\Framework\View\Layout\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#80 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#81 Magento\Framework\View\Layout\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:347]
#82 Magento\Framework\View\Layout\Interceptor->getOutput() called at [vendor/magento/framework/View/Result/Page.php:260]
#83 Magento\Framework\View\Result\Page->render() called at [vendor/magento/framework/View/Result/Layout.php:171]
#84 Magento\Framework\View\Result\Layout->renderResult() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#85 Magento\Framework\View\Result\Page\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#86 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#87 Magento\Framework\View\Result\Page\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Result/Page/Interceptor.php:95]
#88 Magento\Framework\View\Result\Page\Interceptor->renderResult() called at [vendor/magento/framework/App/Http.php:120]
#89 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#90 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#91 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]`

**Comment by vahonc** [comment] 2022-08-19 09:03
Hello @nmarquev,

On my test environment (fresh M2.4.5 with default sample data + ES 2.10.11), it seems all is fine with this.

![Screenshot from 2022-08-19 11-57-56](https://user-images.githubusercontent.com/67791361/185584298-23003139-6d2d-45ab-a7a0-1134d7ab5c9b.png)

Which version of ElasticSuite and PHP you are using? Have you tried to check this bug without installed ElasticSuite? 

BR,
Vadym

**Comment by faranAware** [comment] 2022-08-22 09:46
@vahonc on sample data it works fine because Display Out-of-Stock products is set to use system default value, try setting this to Yes.

**Comment by vahonc** [comment] 2022-08-22 11:23
@faranAware,

Even with `Display Out-of-Stock products` set to **Yes**, I can't to reprodcue this bug.
![Screenshot from 2022-08-22 14-14-50](https://user-images.githubusercontent.com/67791361/185908896-ffce260e-8cb9-4f32-9a05-9e752a8fe01c.png)

![Screenshot from 2022-08-22 14-15-37](https://user-images.githubusercontent.com/67791361/185908936-405f4e89-71fa-4751-aa2a-01967e4ebe5e.png)

Are you shure that you don't change any other settings?

Also try to swith to the default Magento theme (Luma) and check if this bug is occurs.

BR,
Vadym

**Comment by nmarquev** [comment] 2022-08-22 13:49
@vahonc thank´s for replying. 
Yes, when disabling ElasticSuite, works fine

![image](https://user-images.githubusercontent.com/20818155/185931285-1762731e-0f72-4573-9848-7ce6b053e900.png)

I'm using Magento 2.4.5. with PHP 7.4 and ES 2.10.10 (i´m not using 2.10.11 due to search form display bug on mobile) but we also test it on PHP 8.1 and ES 2.10.11 with same results.

**Comment by vahonc** [comment] 2022-08-22 13:54
@nmarquev,

Have you tried switching to the default Luma theme?

BR,
Vadym

**Comment by nmarquev** [comment] 2022-08-22 14:51
@vahonc yes i did, same error. I'm guessing it's a data related issue so I'll debug it later and keep you updated

**Comment by vseager** [comment] 2022-08-23 19:58
The search button on Luma theme no longer reveals the search box in mobile mode on 2.4.5 but haven't verified if it's an Elasticsuite compatibility issue or a core issue.

**Comment by nmarquev** [comment] 2022-08-23 20:04
Hello @vahonc , search button It is working on Magento 2.4.5 and ES 2.10.10, but not with ES 2.10.11

**Comment by nmarquev** [comment] 2022-08-23 21:19
@vahonc this report https://github.com/Smile-SA/elasticsuite/issues/2619 looks same as we are getting now

**Comment by vahonc** [comment] 2022-08-24 06:20
@vseager,

> The search button on Luma theme no longer reveals the search box in mobile mode on 2.4.5 but haven't verified if it's an Elasticsuite compatibility issue or a core issue.

Your issue could be linked to this [#2668](https://github.com/Smile-SA/elasticsuite/issues/2668)

BR,
Vadym

**Comment by vahonc** [comment] 2022-08-24 06:25
@nmarquev,

> @vahonc this report https://github.com/Smile-SA/elasticsuite/issues/2619 looks same as we are getting now

Yes, it seems the same, but again it was not reproducible on my test environment with the default preconditions. So I think it's definitely some kind of data issue.

Have you tried to test it without ElasticSuite?

BR,
Vadym

**Closed** 2022-09-07 15:50 UTC
Labels: feature

**Comment by machrafemergento** [comment] 2022-09-13 16:39
I see that this is fixed in #2702 but it's not released yet. my question is how can I get the changes using composer? or I must wait for the release. Thanks a lot.

**Comment by vahonc** [comment] 2022-09-13 17:41
Hello @machrafemergento,

You could try smth like that:
<pre>
$ composer require smile/elasticsuite:dev-fix_relevance-config --ignore-platform-reqs
</pre>

BR,
Vadym

**Comment by machrafemergento** [comment] 2022-09-14 10:51
Hi @vahonc,

Thanks for the suggestion, though it didn't work.

![Screenshot from 2022-09-14 11-46-53](https://user-images.githubusercontent.com/107622851/190134690-863b0d97-c49e-49bb-af45-bb3b5e807997.png)

**Comment by romainruaud** [comment] 2022-09-14 13:18
Just use the 2.10.x branch directly : 

composer require smile/elasticsuite:2.10.x-dev

**Comment by machrafemergento** [comment] 2022-09-15 11:33
Thanks a lot @romainruaud
