### ISSUE TITLE
Hiding a product in a category doesn't hide the product in the parent category

### ISSUE THREAD

**Issue by PierrickOlivier** [Smile-SA/elasticsuite#1094] opened 2018-09-25 16:09 UTC
It's not a bug, it's an improvement suggestion.

### Preconditions
ElasticSuite Version : 2.6.1

### Steps to reproduce
1. I create a category "Sale" with a sub-category "T-shirt"
2. The sub-category "T-Shirt" is a virtual category with the rule "Sale is yes AND Category is Tshirt"
3. In the sub-category "T-shirt", I hide manually a product in the block "Products List Preview and Sorting"

### Actual result
The product is hidden in the category "Sale/T-Shirt" but is still displayed in the category "Sale".

### Expected result
I think that hiding a product in a virtual category is a nice feature because it allows you to do "an exception" on an automatic rule.
But the current behavior makes it difficult to use the feature because every time the admin wants to do an exception, the admin have to update the category + all the parent categories.

I think that in this situation it would be better to hide the product in all parent categories.

**Comment by romainruaud** [comment] 2018-10-02 10:52
Yep, you are right, it's working like this "by design".

We'll need to go further on this one because you also may want to hide the product in parent category but show it on the children :)

And in this case, I'm not sure how it could be rendered in the UX to be understood properly...

Thank you for reporting it.

**Comment by PierrickOlivier** [comment] 2018-10-03 10:01
> you also may want to hide the product in parent category but show it on the children

Well, I'm not sure that any merchant may have that need... I don't see any business case that may require such feature (?).

**Comment by romainruaud** [comment] 2021-04-30 07:56
after some years and a lot of customers, it appears that nearly nobody is using the blacklist mechanism, and I've never heard of such advanced needs regarding it.

So I close this feature request for not being popular among our users.

If I encounter it again, I'll file a new feature request.

Regards

**Closed by romainruaud** 2021-04-30 07:56 UTC
Labels: feature
