### ISSUE TITLE
Does ElasticSuite work with Magento 2.3?

### ISSUE THREAD

**Issue by deckside** [Smile-SA/elasticsuite#1243] opened 2018-12-22 03:05 UTC
Does ElasticSuite work with Magento 2.3?

**Comment by djenvert** [comment] 2018-12-22 07:35
Yes.
“If your project is based on Magento 2.3.x, you can start working with ElasticSuite today using the latest 2.7.x release”

**Comment by rbayet** [comment] 2018-12-22 08:18
Hello @deckside,

As confirmed by @djenvert and indicated in the README, ElasticSuite works with Magento 2.3 starting from the 2.7.0 release.
You can install the latest 2.7.x release with `composer require smile/elasticsuite ^2.7.0`.

Regards,

**Comment by andy17612** [comment] 2018-12-29 11:20
Hi @rbayet @djenvert but i getting this error when i php bin/magento setup:upgrade .how to fix it? thank you

Fatal error: Uncaught Error: Cannot instantiate interface Magento\InventorySalesApi\Api\StockResolverInterface in /home/XXX/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50 Stack trace:

**Comment by tmp2000** [comment] 2018-12-30 05:34
installed no problem for magento 2.3 with "composer require smile/elasticsuite ^2.7.0" .

**Comment by Swahjak** [comment] 2019-01-02 09:21
Duplicate of https://github.com/Smile-SA/elasticsuite/issues/1222 ?

**Comment by VincentJorge** [comment] 2019-01-07 11:41
Hello Guys,

Anyone have a news about this issue ?

Thank's

**Comment by joshmcoffman** [comment] 2019-01-09 00:38
@romainruaud Your hunch is correct.

Make sure you have the following enabled:

`php bin/magento module:enable Magento_Inventory Magento_InventoryApi Magento_InventoryCatalogApi Magento_InventorySalesApi Magento_InventoryConfigurationApi Magento_InventoryReservationsApi Magento_InventorySourceDeductionApi Magento_SalesInventory Magento_InventorySales Magento_InventoryMultiDimensionalIndexerApi Magento_InventoryIndexer Magento_InventoryConfiguration Magento_InventoryCatalog`

Then you should be able to run setup:upgrade

**Comment by AnatoleRozan** [comment] 2019-01-09 12:57
Hello,
Any news?

I have this issue:
Fatal error: Uncaught Error: Cannot instantiate interface Magento\InventorySalesApi\Api\StockResolverInterface in /home/XXX/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50 Stack trace:

Thank's

**Comment by romainruaud** [comment] 2019-01-16 16:33
According Magento : 

"MSI is enabled for all fresh installations, and gets disabled for upgrade from early Magento versions to 2.3 unless it’s switched on manually"

So yes, issue is confirmed. 

If you are upgrading, you should enable MSI modules manually. But this also require you to ensure to report any customization on CatalogInventory modules to MSI modules.

I'm afraid as an extension provider we'll have to deal with an ugly hybrid support between "Magento and MSI", and "Magento with MSI disabled" since the both versions can exists.

**Comment by gshail** [comment] 2019-01-23 17:40
I have all the modules copied from elasticsuite-master/src into /app/code/ but when I try to enable the module, I keep getting - Unknown module(s): 'Smile_ElasticsuiteCore'

I'm running the following command. 
 /usr/local/php71/bin/php-cli bin/magento module:enable --clear-static-content Smile_ElasticsuiteCore                           

What am I missing here?
![screen shot 2019-01-23 at 18 40 27](https://user-images.githubusercontent.com/7835136/51625811-6554cb00-1f3e-11e9-822e-063bcc05f424.png)

**Comment by pedrosousa13** [comment] 2019-03-12 12:57
Is there no way to have the MSI disabled and still have elasticsuite?

**Comment by romainruaud** [comment] 2019-03-20 09:39
@pedrosousa13 actually, there is no way to achieve such things. 

I'm considering it, but for me it's unclear what is the future of the legacy CatalogInventory module.

It's a lot of (ugly) code to write to support both "Magento with MSI" and "Magento without MSI" and we should nearly consider these instances as additional versions of Magento (we already have to consider both CE and EE versions).

To be honest, it's quite a pain for us they implemented it this way, even if I understand there could be issues with BC for merchants having already highly customized the CatalogInventory module...

**Comment by real34** [comment] 2019-04-16 05:29
From a quick benchmark, disabling MSI modules improves response times by 25% for headless REST API calls…

It would be great to see a path to support both implementations indeed.

**Comment by romainruaud** [comment] 2019-04-17 13:19
PR #1382 contains necessary deprecation mechanism to work without MSI modules.

Please everybody note the following two things : 

- We did not want to provide such things and intentionally discarded such a deprecation mechanism when we wrote MSI support.

- Legacy implementation of Magento_CatalogInventory **will be removed** by Magento. We don't know when, but all merchants and integrators should rather begin using MSI for now instead of relying on legacy CatalogInventory.

- Since our community has spoken, I reconsidered my position about this topic and provide this support for now.

Regards

**Closed by romainruaud** 2019-04-17 13:19 UTC
Labels: bug

**Comment by real34** [comment] 2019-04-17 20:38
Thanks for your openness! It will make the migration path much smoother.
