### ISSUE TITLE
Too many unjustified tracker get requests! Are they needed?

### ISSUE THREAD

**Issue by cptX** [Smile-SA/elasticsuite#2849] opened 2023-02-13 17:21 UTC
Can somebody please explain what tracker is doing and why so many tracker get requests are running in every page even in checkout??
Is this how the tracker should work? Makes sense to have dozens of extra get requests in places where to my eyes are not needed?

For example in a product page and in checkout I counted 22 tracker requests like the one below !!!! What is the usage of all these?

GET
	https://xxxxxxxx/elasticsuite/tracker/hit/image/h.png?page[store_id]=4&page[type][identifier]=catalog_product_view&page[type][label]=Catalog Product View (Any)&page[locale]=el_GR&page[domain]=xxxxxxx&page[category][id]=23&page[category][label]=Jackets&page[category][path]=1/2/20/21/23&page[category][breadcrumb]=Women|Tops&page[product][id]=1396&page[product][label]=Olivia 1/4 Zip Light Jacket&page[product][sku]=WJ12&session[uid]=50c1a30c-0d91-482c-1ab0-3b33d650fcd6&session[vid]=336c98b2-4b51-11b3-ada3-8f06cab7eabd&page[site]=xxxxxxxx&page[url]=/olivia-1-4-zip-light-jacket&page[title]=Olivia 1/4 Zip Light Jacket&page[referrer][domain]=xxxxxxxxx&page[referrer][page]=/women/tops-women/jackets-women&page[resolution][x]=364&page[resolution][y]=812

![elasticsuite_tracker](https://user-images.githubusercontent.com/9040042/218530039-44168fa4-199c-46d9-b260-1d644eb58048.png)

**Comment by romainruaud** [comment] 2023-02-13 21:38
yes, this is how it works.

We need to be able to track products views, add to cart and sales, to be able to compute the conversion rate of each search term for the analytics dashboard.

However, you should only have one call to the tracker per page, not more.

If you see 22 requests on a product page, something is not working as intended.

Are you using a custom theme ?

Regards

**Comment by cptX** [comment] 2023-02-14 09:20
I have installed porto theme but during my current tests I'm using the default luma. Though, I have noticed that even the other theme is not enabled it affects many things in the behavior even after doing all compilations, cache clears etc...
Do you want me to do some tests to detect the problem?
Actually you told me to enable tracker to use it with analytics. But because I'm afraid of the overhead I'm not planning to use it in my first publication of my website. So now I deactivated both tracker and analytics

**Comment by romainruaud** [comment] 2023-02-20 14:26
Hi,

we do not support anything for Porto Theme as part of our Open Source Policy here. 

To be honest, we've mostly seen bad reviews of this theme. And nowadays, you can probably do way better things with Hyvä.

I close this issue.

best regards

**Closed by romainruaud** 2023-02-20 14:26 UTC
Labels: question
