### ISSUE TITLE
Issues with simple products which has special price enabled

### ISSUE THREAD

**Issue by qsolutions-pl** [Smile-SA/elasticsuite#834] opened 2018-03-22 11:48 UTC
### Preconditions

Magento Version : 2.1.7

ElasticSuite Version :2.3.0

Environment : PHP 7.0, developer & production mode

Third party modules : none

### Steps to reproduce

1. setup a simple product special price 
2. save the product
3. in the autocomplete, there are 2 prices, but displayed as minimal price, not as a special price

### Expected result

1. special price should be shown and correct HTML classes set, not minimal price

### Actual result

https://screencast.com/t/U12EWHagyVQr
https://screencast.com/t/EkiClS7cW9 - minimal price, not special price
It works fine for CONFIGURABLE products, but breaks for simple products.

It looks like the price template `final_price.phtml` for simple products has wrong data passed: 
method: 
`$block->hasSpecialPrice()`
return false, when it should return true when special price is set for a simple product

**Comment by afoucret** [comment] 2018-03-22 11:53
Hi,
The version you are using is outdated. The 2.3.x is not actively maintened. Our advice would be to migrate at least to the latest release of the 2.3 branch (2.3.11) or to upgrade both Magento and Elasticsuite.

**Comment by afoucret** [comment] 2018-03-22 12:40
Seems also it is a duplicate of #682 that was fixed in release 2.4.4 with PR #685.
I close for being a duplicate of a closed issue.

**Closed by afoucret** 2018-03-22 12:40 UTC
