### ISSUE TITLE
Value of 0 for attribute does not show in layered navigation

### ISSUE THREAD

**Issue by mcyrulik** [Smile-SA/elasticsuite#402] opened 2017-04-24 14:33 UTC
### Preconditions

Magento Version : 2.1.5

ElasticSuite Version : 2.3.0

Environment : Occurs in both.

Third party modules : Ves_Blog, BoostMyShop RMA, Barcode Label, Order Prep.

### Steps to reproduce

1. add a new attribute, or edit an existing one
2. make one of the attribute options 0
3. add simple products with that option. 

### Expected result

1. option with value of 0 shows in layered navigation with product count

### Actual result

1. Between x-large and 2, there should be 0 with a count of 190. 
<img width="214" alt="screen shot 2017-04-24 at 9 27 05 am" src="https://cloud.githubusercontent.com/assets/2649671/25342157/bb1826b0-28d0-11e7-89f1-d240e9817f58.png">

If I change the verbiage on the attribute value to 'zero' instead of '0' that shows up correctly.

**Comment by romainruaud** [comment] 2017-04-25 14:12
Confirmed.

**Comment by romainruaud** [comment] 2017-04-28 08:00
PR has been merged.

Please wait for the next stable release or use the 2.3.x branch for now.

Best regards

**Closed by romainruaud** 2017-04-28 08:00 UTC
Labels: bug

**Comment by mcyrulik** [comment] 2017-05-03 01:32
Thanks for pushing a fix - after upgrading to 2.3.5, I'm now getting this error:

1 exception(s):
Exception #0 (Exception): Notice: Undefined index: adminSortIndex in /Users/markcyrulik/Documents/WebProjects/goodwilltest/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Layer/Filter/Attribute.php on line 275

Same as above - changing the value to zero instead of 0 takes care of the error.

**Comment by espradley** [comment] 2017-08-15 17:28
@mcyrulik I don't think your issue is going to be addressed since this task is closed.  I had the same issue and created a new issue (with the fix):
https://github.com/Smile-SA/elasticsuite/issues/498
