### ISSUE TITLE
Product with disabled color is visible in virtual category

### ISSUE THREAD

**Issue by delyriand** [Smile-SA/elasticsuite#459] opened 2017-06-26 16:03 UTC
### Preconditions

Magento Version :  2.1.7

ElasticSuite Version : 2.3.5

Environment : developer

Third party modules :

### Steps to reproduce

1. Disable all products of the same color of a configurable product (with sample data, disable black color for prodcut M
2. Create a virtual category with rules: 
2.1. Product Name contains **Kangeroo**
2.2. Color is one of **Black**

### Expected result

1. Empty category

### Actual result

1. "Chaz Kangeroo Hoodie" product is display without the black color
2. "Black" is in the color filter.
![test_category_back](https://user-images.githubusercontent.com/465524/27548588-a98b9670-5a99-11e7-96df-221e917c84d9.png)
![test_category_front](https://user-images.githubusercontent.com/465524/27548583-a5247b06-5a99-11e7-9c7a-17b6fed354de.png)

**Comment by romainruaud** [comment] 2017-06-27 14:22
Hello,

I can confirm the behavior.

However, I am wondering if it could not be like this by design... Since a composite product is populated by all his children informations... even if they are disabled or not.

I will ask @afoucret about this one to ensure how we should fix it.

Thank you for submitting it.

**Comment by afoucret** [comment] 2017-07-27 07:49
Hi @delyriand,

The PR #480 is an attempt to fix this one.
Can you please give a try at this one and confirm that everything is OK with this one.

BR,

**Comment by romainruaud** [comment] 2017-08-04 09:22
@afoucret 

One of our project has a linked problem, but this time it is not due to the "status" being 0, but the children product being out of stock.

Seems that "we need to go deeper" on this topic.

**Comment by afoucret** [comment] 2017-08-09 07:33
@romainruaud : Your issue is linked but we will not address it. Standard Magento display swatches for out of stock products. So not indexing it / hiding it into the layered navigation would made the display inconsistent. Project can still customize the module if needed.

@delyriand : PR #480 have been merged and the issue is considered as fixed.

**Closed by afoucret** 2017-08-09 07:33 UTC
Labels: bug, help wanted
