### ISSUE TITLE
2.8.9 with magento 2.3.3 - Autocomplete not adhering to limits set in admin. Result window is too large errors.

### ISSUE THREAD

**Issue by ProxiBlue** [Smile-SA/elasticsuite#1922] opened 2020-08-15 10:27 UTC
Since upgrading form 2.8.8, to 2.8.9, using magento 2.3.3, the autocomplete function is no longer setting limits to the dropdown list.

There is also an error in logs, depending on size of results, from a search. 

```
[2020-08-14 23:54:11] main.ERROR: {"error":{"root_cause":[{"type":"query_phase_execution_exception","reason":"Result window is too large, from + size must be less than or equal to: [100000] but was [119032]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":
```

From observation, it appears autocomplete (per lookup) is pulling all products in a collection that matches. This can place a huge load on ES service.

locking the install to 2.8.8 prevents the issue.

This was tested in base LUMA theme 

### Preconditions
Magento 2.3.3, PHP 7.3, ElasticSuite 2.8.9, ElasticSearch 6.5

Magento Version : CE

ElasticSuite Version :2.8.9

Environment : Production

Third party modules : 

### Steps to reproduce

1. Install via composer 2.8.9 on m2.3.3
2. Enable autocomplete, and search for an item, which will result in over 10000 products 
3. Notice the autocomplete menu has no products if the noted error is triggered
4. Notice the autocomplete lists more than the number of products as set in admin for limits

### Expected result

1. The limits, as set in admin, shoudl be used for the autocomplete

### Actual result

1. It looks like no limits are used, and each autocomplete search pulls a complete collection of products. This ads a tremendious load on the ES server.

**Comment by ProxiBlue** [comment] 2020-08-15 10:48
Screenshots of test using 2.8.8

![Tooltip_813](https://user-images.githubusercontent.com/4994260/90310813-c892bd80-df27-11ea-894a-ba3130b523c6.png)
![Tooltip_812](https://user-images.githubusercontent.com/4994260/90310819-cc264480-df27-11ea-85ee-3777b98e5101.png)

Same using 2.8.9

![Tooltip_811](https://user-images.githubusercontent.com/4994260/90310830-d2b4bc00-df27-11ea-820f-195567e40c6f.png)
![Tooltip_810](https://user-images.githubusercontent.com/4994260/90310835-d7797000-df27-11ea-9934-e14b9bbc7ba3.png)

**Comment by ProxiBlue** [comment] 2020-08-15 10:50
Related to same issue in: https://github.com/Smile-SA/elasticsuite/issues/1911

**Comment by Bashev** [comment] 2020-08-15 18:33
@ProxiBlue solution can be found in #1914

**Comment by ProxiBlue** [comment] 2020-08-16 01:54
I can confirm the patch supplied by @Bashev works on this version to fix.
I applied the patch manually to 2.8.9, and autocomplete dropdown works as expected.

There was a patch rejection...

```
01:49 $ cat Collection.php.rej 
--- a/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php
+++ b/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php
@@ -590,8 +607,8 @@ private function prepareRequest()
         $searchRequestName = $this->searchRequestName;
 
         // Pagination params.
-        $size = ($this->_pageSize !== false) ? $this->_pageSize : $this->getSize();
-        $from = $size * (max(1, $this->getCurPage()) - 1);
+        $size = $this->getPageSize();
+        $from = $size * (max(1, $this->_curPage) - 1);
 
         // Setup sort orders.
         $sortOrders = $this->prepareSortOrders();

```

Below is a slighly adjusted version that works for me.

```
01:53 $ cat test.patch 
*** ./Collection.php.orig	2020-08-04 14:38:44.000000000 +0000
--- ./Collection.php	2020-08-16 01:48:02.829819228 +0000
***************
*** 408,413 ****
--- 408,431 ----
      }
  
      /**
+      * Get actual page size if is defined or return all results.
+      *
+      * @return integer|false
+      */
+     public function getPageSize()
+     {
+         if ($this->_pageSize !== false) {
+             return $this->_pageSize;
+         }
+ 
+         if ($this->originalPageSize !== false) {
+             return $this->originalPageSize;
+         }
+ 
+         return $this->getSize();
+     }
+ 
+     /**
       * @SuppressWarnings(PHPMD.CamelCaseMethodName)
       *
       * {@inheritdoc}
***************
*** 439,445 ****
          $this->getSelect()->order(new \Zend_Db_Expr("FIELD(e.entity_id,$orderList)"));
  
          $this->originalPageSize = $this->_pageSize;
-         $this->_pageSize = false;
  
          $this->isSpellchecked = $searchRequest->isSpellchecked();
  
--- 457,462 ----
***************
*** 573,579 ****
          $searchRequestName = $this->searchRequestName;
  
          // Pagination params.
!         $size = ($this->_pageSize !== false) ? $this->_pageSize : $this->getSize();
          $from = $size * (max(1, $this->_curPage) - 1);
  
          // Setup sort orders.
--- 590,596 ----
          $searchRequestName = $this->searchRequestName;
  
          // Pagination params.
!         $size = $this->getPageSize();
          $from = $size * (max(1, $this->_curPage) - 1);
  
          // Setup sort orders.

```

**Comment by Bashev** [comment] 2020-08-16 06:24
@ProxiBlue thank you for feedback!

**Comment by romainruaud** [comment] 2020-08-24 07:11
I close this one since it's a duplicate of #1917 and #1912 and #1903

**Closed by romainruaud** 2020-08-24 07:11 UTC

**Comment by romainruaud** [comment] 2020-08-24 14:10
Please upgrade to 2.8.10 which contains the fix
