### ISSUE TITLE
Smile\ElasticsuiteCatalogGraphQl\Model\Resolver\Products\Query\Search::getResult() not compatible with interface

### ISSUE THREAD

**Issue by maximgubar** [Smile-SA/elasticsuite#1969] opened 2020-10-16 12:17 UTC
https://github.com/Smile-SA/elasticsuite/blob/30fc0c43087d093ce5298beaf15e296cb22ce001/src/module-elasticsuite-catalog-graph-ql/Model/Resolver/Products/Query/Search.php#L85

in Magento 2.4.1 when you try to execute `bin/magento setup:di:compile` following error will appear:

```
$ bin/magento setup:di:compile 
Compilation was started.
Repositories code generation... 1/9 [===>------------------------]  11% 3 secs 50.0 MiB
PHP Fatal error:  Declaration of Smile\ElasticsuiteCatalogGraphQl\Model\Resolver\Products\Query\Search::getResult(array $args, Magento\Framework\GraphQl\Schema\Type\ResolveInfo $info): Magento\CatalogGraphQl\Model\Resolver\Products\SearchResult 
must be compatible with Magento\CatalogGraphQl\Model\Resolver\Products\Query\ProductQueryInterface::getResult(array $args, Magento\Framework\GraphQl\Schema\Type\ResolveInfo $info, Magento\GraphQl\Model\Query\ContextInterface $context): Magento\CatalogGraphQl\Model\Resolver\Products\SearchResult 
in /vagrant/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-graph-ql/Model/Resolver/Products/Query/Search.php on line 85
```

**Comment by OvalMedia** [comment] 2020-10-16 14:27
Quick fix: \vendor\smile\elasticsuite\src\module-elasticsuite-catalog-graph-ql\Model\Resolver\Products\Query\Search.php

Change...

`public function getResult(array $args, ResolveInfo $info/*, ContextInterface $context*/): SearchResult`

... to ...

`public function getResult(array $args, ResolveInfo $info, ContextInterface $context): SearchResult`

Basically uncomment the last parameter. Looks like somebody anticipated this change.

**Comment by refueledinc** [comment] 2020-10-22 15:12
Duplicate of #1961

**Closed** 2020-10-30 18:09 UTC
