### ISSUE TITLE
Virtual Categories ignore manual sorting

### ISSUE THREAD

**Issue by MarcusSchwarz** [Smile-SA/elasticsuite#2255] opened 2021-09-09 12:37 UTC
### Preconditions

1. Magento Enterprise Cloud Edition 2.4.x
2. No additional modules beside smile/elasticsuite

Magento Version : 2.4.3

ElasticSuite Version : 2.10.6

Environment : Production

Third party modules :
n/a

### Steps to reproduce

1. create a fresh magento-installation with sample data, ce or ee doesn't matter
2. install the smile/elasticsuite module
3. *go to the database and set the auto_increment for row_id in catalog_category_entity to some higher number like 500*
4. Create a virtual category with any rule you like
5. Switch to another storeview (not default)
6. manual sort some of the items
7. check in frontend if the sorting has been applied

### Expected result

1. the sorting has been applied

### Actual result

1. the sorting is ignored

So, to reproduce this, you will need some more preparation. Important is step 3. Fields row_id and entity_id have to be out of sync. I don't know how this happens in the real world, I could not force it by simply deleting categories or something like that. But fact is, it does happen.

The problem is the index aggregation in `vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/CategoryData.php`
In method `joinStorePosition()` there is a join-criteria defined: ``` "p.category_id = use_store_positions.{$linkField}", ```

This tries to map the category_id in smile_virtualcategory... table to the row_id of the catalog_category_entity_int-table. But that row_id is not equal to the category-id as described above. So if in catalog_category_entity the fields row_id and entity_id are out of sync, this join fails. This leads to missing data for the categories which have no sync ids.

**Comment by romainruaud** [comment] 2021-09-15 09:17
Duplicate of #2005 I think, but we have to solve this.

**Closed** 2021-09-27 15:30 UTC
Labels: bug
