### ISSUE TITLE
Installing data... Syntax error

### ISSUE THREAD

**Issue by Joshua-Ye** [Smile-SA/elasticsuite#1971] opened 2020-10-19 09:26 UTC
I have installed magento of version 2.4.1.
Elasticsearch version:7.9.2.
PHP version:7.4.11
I tried to install elasticsuite 2.10.0

Next i worked via SSH.
I followed this article:https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall step by step.
But when ran bin/magento setup:upgrade,came an error:
********************************
**Module 'Smile_ElasticsuiteCore':
Module 'Smile_ElasticsuiteCatalog':
Installing data... Syntax error**
********************************
when ran php bin/magento indexer:reindex
********************************
**ElasticSuite Category Indexing index process unknown error:
Syntax error
ElasticSuite Thesaurus Indexing index process unknown error:
Syntax error**
********************************

Can you please take a look?
Thank you.

**Comment by Joshua-Ye** [comment] 2020-10-19 09:29
'smile_elasticsuite_core_base_settings' => [
'es_client' => [
'servers' => 'https://9b*b.eastus2.azure.elastic-cloud.com:9**3',
'enable_https_mode' => 0,
'enable_http_auth' => 1,
'http_auth_user' => 'myuser',
'http_auth_pwd' => 'mypwd'
]
]

**Comment by dambrogia** [comment] 2020-10-21 23:43
You need to provide more information. What PHP version are you using? What other modules do you have installed? Have you tried using the verbose flag? What is in your error logs?

**Comment by Joshua-Ye** [comment] 2020-10-22 06:10
PHP version:7.4.11

**Comment by vahonc** [comment] 2020-10-22 13:49
Hello @Joshua-Ye,

I work around your problem.

For this I used:
- Clean Magento 2.4.1 EE without any additional third-party modules
- Elasticsearch version: 7.9.2
- ElasticSuite: 2.10.0
- PHP: 7.3.19

I didn't notice any errors during the running of the next commands:
- bin/magento setup:upgrade
- bin/magento indexer:reindex

Perhaps, your problem is linked to the version of PHP, namely 7.4. To be sure and check out your test case I need to re-configure my test environment.

Best regards

**Comment by vahonc** [comment] 2020-10-23 11:12
Hi @Joshua-Ye,

I went back, so I reconfigured my test environment and now it matches yours completely:

- Clean Magento 2.4.1 EE without any additional third-party modules
- PHP: 7.4.11
- Elasticsearch version: 7.9.2
- ElasticSuite: 2.10.0

Unfortunately as before I didn't notice any errors during the running of the next commands:

- bin/magento setup:upgrade
- bin/magento indexer:reindex

After clear installation of Magento and running the commands that I mentioned above I try to install ElasticSuite 2.10.0 with this command:

`composer require smile/elasticsuite=2.10.0`

And after that again run `bin/magento setup:upgrade` and `bin/magento indexer:reindex` commands and again didn't notice any error in the output.

So I have a few questions for you:
- Have you successfully install the ElasticSuite module? Have you noticed any errors?
- Do you use Magento Sample Data or some real data from your project?
- Did you check elasticsearch logs in `/var/log/elasticsearch`

Also please check precisely your configuration according to our Wiki, maybe you something missed.

**Comment by Joshua-Ye** [comment] 2020-10-23 12:09
1. I didn't install ElasticSuite module successfully.when in progress, ran `php bin/magento setup:upgrade`,came an error:

Module 'Smile_ElasticsuiteCore':
Module 'Smile_ElasticsuiteCatalog':
Installing data... Syntax error

2. I just installed magento 2.4.1 without sample data,i did nothing in my site then i tried to install ElasticSuite module.
(**I tried to install ElasticSuite module immediately after installed magento 2.4.1**)

3. My elasticsearch is managed on cloud.I have no elasticsearch logs in `/var/log/elasticsearch`.I didn't installed elasticsearch on my localhost.

**Comment by rbayet** [comment] 2020-10-30 18:18
Hello @Joshua-Ye,

My first guess would be that the issue is that you do not have provided to Magento/Elasticsuite the location of your Elasticsearch server.
It defaults to localhost, so if it's any different, you will indeed have an error at the setup:upgrade step.

Please refer to [the online documentation](https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall#enable-the-module-and-run-elasticsuite-setup).

Regards,

**Comment by Joshua-Ye** [comment] 2020-10-31 01:32
**I'm sure I did provide the correct Elasticsearch server.**
Because at first i provided a wrong server,there came an error:No alive nodes found in your cluster.
Then i configured my ElasticSearch server correctly,and i think every thing will be ok,but unfortunately there came another error: 
Installing data... Syntax error

**Comment by rbayet** [comment] 2020-10-31 09:04
> I found a really bad mistake:`'enable_https_mode' => 0`,should be changed to `'enable_https_mode' => 1`.
> [...]
> I've looked up relevant articles and found these caused by plugins which are required by ElasticSuite.
indeed.

> But i found nothing how to install analysis-phonetic and analysis-icu **on Elastic Cloud**.
> May I please kindly ask you to provide me with steps and more information on it?

A streamline version is available [on this issue](https://github.com/Smile-SA/elasticsuite/issues/1482) and googling for "add plugins to elasticsearch elastic cloud" leads to https://www.elastic.co/guide/en/cloud-enterprise/current/ece-add-plugins.html with indeed the following steps mentionned in the issue 
> 
> **To add plugins to an existing deployment:**
> 
>     **Log into the Cloud UI**.
> 
>     **On the Deployments page, select your deployment**.
> 
>     Narrow the list by name, ID, or choose from several other filters. To further define the list, use a combination of filters.
>     **From your deployment menu, go to the Edit page.**
>     Beneath the Elasticsearch master node, expand the **Manage plugins and settings caret.**
>     Select the plugins that you want.
>     Click Save changes.

Parallel to that, I had created an optimized deployment on an Elastic Cloud trial account, so I can confirm the steps : 
**Edit your deployment**
![image](https://user-images.githubusercontent.com/2353374/97775281-ba842e80-1b5f-11eb-81be-2558ebc817a8.png)

**Scroll until you see the options about the plugins** 
![image](https://user-images.githubusercontent.com/2353374/97775297-d982c080-1b5f-11eb-83c1-f0d91d1fafb6.png)

**Select the two required plugins (icu and phonetic)**
![image](https://user-images.githubusercontent.com/2353374/97775306-e30c2880-1b5f-11eb-9c96-85a19b841410.png)

**Save**
![image](https://user-images.githubusercontent.com/2353374/97775312-eacbcd00-1b5f-11eb-90a0-fb9cc1f22698.png)

**Wait for the changes to be propagated**
![image](https://user-images.githubusercontent.com/2353374/97775360-41d1a200-1b60-11eb-99cb-1940f0709d68.png)

**Profit ? :)**

**Comment by rbayet** [comment] 2020-10-31 09:56
Can confirm that :

> php bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/servers [your-deployment-host]:[port]
> php bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/enable_https_mode 1
> php bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/enable_http_auth 1
> php bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/http_auth_user elastic
> php bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/http_auth_pwd [your-elastic-cloud-password]

works as expected (ie no setup:configure error) : 
- after Magento 2 install
- after having composer require'd smile/elasticsuite 
- after having enabled the Elasticsuite modules

Regards,

**Comment by Joshua-Ye** [comment] 2020-10-31 11:28
Everything goes well now.
Thanks a million.
You guys are very much appreciated!!!

**Comment by romainruaud** [comment] 2020-11-10 08:31
Great ! I close this issue then.

Regards

**Closed by romainruaud** 2020-11-10 08:31 UTC
Labels: question
