### ISSUE TITLE
errors during compilation

### ISSUE THREAD

**Issue by roman204** [Smile-SA/elasticsuite#616] opened 2017-11-11 10:44 UTC
setup:di:compile don't work after installation of the suite

### Preconditions

no special preconditions

Magento Version : 2.2.0

ElasticSuite Version : 2.4.0

Environment : developer mode

Third party modules : nothing installed

### Steps to reproduce

1. install elastic suite 
2. enable the modules as described in wiki
3. try to setup:di:compile

### Expected result

1. the classes get generated

### Actual result

1. the classes are not generated cause an exception is thrown
[Screenshot, logs]
![auswahl_477](https://user-images.githubusercontent.com/584168/32688651-89f62516-c6d5-11e7-93e3-0ab8cd16b4a6.jpg)

**Comment by romainruaud** [comment] 2017-11-11 12:12
Duplicate of #614 that has been fixed in dev-master.

Please wait for 2.4.1 release or switch to dev-master branch.

Regards

**Closed by romainruaud** 2017-11-11 12:12 UTC
Labels: duplicate
