### ISSUE TITLE
The product searched by SKU is shown last in the list

### ISSUE THREAD

**Issue by OvidiuCalugar** [Smile-SA/elasticsuite#2684] opened 2022-08-12 15:18 UTC
Magento 2.4.2
smile/elasticsuite 2.10.9     Magento 2 merchandising and search engine built on ElasticSearch

If I search in the search bar a product by SKU it is shown the first one in the dropdown list.
In the search page with the results the products are shown the other way.
Enclosed you can see print screens with the 2 situations.

How can I set the correct order in search result page?

![search](https://user-images.githubusercontent.com/111138406/184386954-823da9da-dd1a-4ba3-b7ea-5df6ab8bdbdd.png)
![result](https://user-images.githubusercontent.com/111138406/184386949-99bdb1c8-0631-48b4-960c-bfb95e7f1cab.PNG)
![image_2022_08_18T14_14_44_648Z](https://user-images.githubusercontent.com/111138406/185422546-0e034b05-20d8-4819-b449-c6580326e29d.png)

**Comment by vahonc** [comment] 2022-08-12 15:27
Hello @OvidiuCalugar

First of all, provide information about your environment (version of Magento, ElasticSuite, third-party extension, etc)

BR,
Vadym

**Comment by OvidiuCalugar** [comment] 2022-08-12 16:06
Sorry about that.
It's Magento 2.4.2
Smile-SA elasticsuite

**Comment by vahonc** [comment] 2022-08-12 16:35
@OvidiuCalugar, thanks for the Magento version, but regarding ElasticSuite, the "Smile-SA elasticsuite" you specified is not enough for us, we need to specify the exact version, for example 2.10.11 (currently the latest version).

You can get this from the output of this command: 
`$ composer info | grep elasticsuite`

BR,
Vadym

**Comment by rbayet** [comment] 2022-08-16 13:48
Hello @OvidiuCalugar,

While waiting for your answer to @vahonc's question, have you changed any settings in admin under "Elasticsuite > Search Engine > Search Relevance" ?
What is the search weight of the "sku" attribute ?

You could have different results also if you created an Optimizer but only made it applied to "Catalog Product Autocomplete" requests and not both "Catalog Product Autocomplete" and "Catalog Product Search".

Regards,

**Comment by OvidiuCalugar** [comment] 2022-08-18 14:35
Hi, 
I just received the elastic suite versions. I updated the post.
Regarding your questions:
Relevance Configuration
- Fulltext base setting: 100% with Tie Breaker 1
- Enable boost on Phrase match is set to yes
- Phrase Match Boost Value is 10
- Cutoff Frequency is 0.15
Spellchecking Configuration:
- Fuzziness is enabled with Automatic value, 1 for Prefix Lenght and 10 for Max expansion
- Phonetic search is enabled
Thesaurus Configuration
- Max allowed rewrites is 2
- synonims search is enabled with 10 weight divider
- query Search Expansions is enabled with Concepts weight divider 10

Search weight for SKU I set to 6.
Name has search weight 2 and all other attributes have search weight 1.

There is an Optimizer that sends my out of stock products to the end of the category page. (In stock products have a 99 Boost value)
At Request type are set all 3 options: Catalog Product Search, Catalog Product Autocomplete and Category Product View

**Comment by vahonc** [comment] 2022-08-18 16:26
Hello @OvidiuCalugar,

The update for the version of the ElasticSuite that you specified is again not correct.

I assume that you are using 2.10.x version (or 2.9.x, which is unlikely). I have given you clear instructions on how to easily find out exactly which version you are using. So just run the below command in your environment:
`$ composer info | grep elasticsuite`

You should get the next output:
`smile/elasticsuite              2.10.11   Magento 2 merchandising and search engine built on ElasticSearch `

Perhaps you do not have the ability or access to the command line?

BR,
Vadym

**Comment by OvidiuCalugar** [comment] 2022-08-25 07:38
Hi. I don't have the ability to access the command line but I received form my colleagues the answer :)
The version is:
smile/elasticsuite 2.10.9     Magento 2 merchandising and search engine built on ElasticSearch

**Comment by vahonc** [comment] 2022-08-25 13:46
Hello @OvidiuCalugar,

Thanks for your clarifications. We will try to check the changelog of this version.

Have you tried to check the behavior of product search by SKU and your Optimizer on the default Magento theme (Luma)? 
Maybe your theme has some specific settings for search results sorting or smth like that.

BR,
Vadym

**Comment by OvidiuCalugar** [comment] 2022-08-25 14:32
Hello @vahonc,

I didn't try on Luma. I don't have an instance only with Luma but I have a staging version of the website with full settings.
I deactivated now the optimizer on staging and I tried to search but the result is the same like on live with optimizer on.

**Comment by vahonc** [comment] 2022-08-29 12:50
@OvidiuCalugar,

I tried to reproduce your issue according to your conditions on my test environment, but without success.
I got the results that I expected.

For this I use:
- M2.4.2-p1 EE with default sample data + Luma theme
- ElasticSuite 2.10.9

Below you can find my detailed explanation with screenshots.

Firstly, I created three test products with similar SKUs like **25-MG0**x.

![Screenshot from 2022-08-29 14-56-14](https://user-images.githubusercontent.com/67791361/187195778-8b7ca4c4-d310-4499-a298-57b0d5fecead.png)

As you can see one of them, namely **Dash Digital Watch II (SKU: 25-MG02)** is **Out of Stock**

Then I created an Optimizer for moving Out of Stock products to the end of the list.

![Screenshot from 2022-08-29 15-05-44](https://user-images.githubusercontent.com/67791361/187197380-730c2e27-d064-452a-84d4-e58d8e3d3a62.png)

![Screenshot from 2022-08-29 15-14-18](https://user-images.githubusercontent.com/67791361/187198755-f6b0c80a-930a-446d-8ddd-b922734d568c.png)

And now, if we go to the `Gear` => `Watches` category we will see at the end of the products listing there are two products that are **Out of Stock** (Dash Digital Watch II and Luma Analog Watch). The latest doesn't belong to this issue ;-)

![Screenshot from 2022-08-29 15-08-41](https://user-images.githubusercontent.com/67791361/187198246-11f495dd-b59d-428b-ab7a-bef519a7e9aa.png)

Finally, I tried to search these products by SKU mask.

Autocomplete results:

![Screenshot from 2022-08-29 15-20-36](https://user-images.githubusercontent.com/67791361/187200109-69c7cfac-b7d2-4e8f-bb3a-7337a265e563.png)

Search results:

![Screenshot from 2022-08-29 15-21-56](https://user-images.githubusercontent.com/67791361/187200131-a7a564d7-7a73-407e-9fb5-2765350acf29.png)

As you can see the result is the same in both cases, and the Out of Stock product, namely **Dash Digital Watch II (SKU: 25-MG02)** is displayed at the end of the list because my Optimizer is working. And if I update the `Boost value (%)` from `-99` to `99` in the configuration of my optimizer I moving Out of stock products at the top of the list in both cases (as for autocomplete suggestions and as for search results).

![Screenshot from 2022-08-29 15-47-06](https://user-images.githubusercontent.com/67791361/187204689-555b9ca7-4e4c-4660-a52a-9a4ef22cf227.png)

![Screenshot from 2022-08-29 15-47-16](https://user-images.githubusercontent.com/67791361/187204707-a9e4c919-6636-411b-af3e-a6d053ec3eda.png)

Therefore I believe that your issue is linked to your custom theme. If it's so, there is not much we can do for your issue, because compatibility with third-party modules or themes is out of the scope of our Open Source support policy provided here.

BR,
Vadym

**Comment by OvidiuCalugar** [comment] 2022-08-29 13:13
Thank you @vahonc for the time and for the detailed explanation. We will do more tests on the staging version to find out the compatibility problem.

**Comment by vahonc** [comment] 2022-09-28 11:35
@OvidiuCalugar,

Can we consider your problem solved and close this ticket?

BR,
Vadym

**Comment by OvidiuCalugar** [comment] 2022-09-28 11:42
Yes. Thank you!

**Closed** 2022-09-29 07:07 UTC
Labels: question
