### ISSUE TITLE
Category pages are refreshing after use filters in layerd navigation

### ISSUE THREAD

**Issue by Alizeinalzadeh** [Smile-SA/elasticsuite#950] opened 2018-06-13 06:47 UTC
Category pages are refreshing after use filters in layered navigation

### Preconditions
Magento Version : Magento CE, Version 2.2.2

ElasticSuite Version: 2.5.10

Environment: Production Mode

Third party modules: Magento Codazon Fastest Theme

### Expected result
1. After using filters in layered navigation, the category page is refreshing and then the filters are applying.

### Actual result
1. After using filters in layered navigation, filters should work with Ajax, not with page refresh.

**Comment by afoucret** [comment] 2018-06-13 10:30
Hi @Alizeinalzadeh,

I will close this issue for being a duplicate of #228.

**Closed by afoucret** 2018-06-13 10:30 UTC
