### ISSUE TITLE
ElasticSuite Indexer on Install/Upgrade Data

### ISSUE THREAD

**Issue by thomas-kl1** [Smile-SA/elasticsuite#1711] opened 2020-02-13 15:49 UTC
ElasticSUite reindex the data in install/upgrade data setup. It results in exception if elasticsearch is not setup correctly first. Anyway the reindex should be manual, as the default behavior after magento installation.

**Comment by rbayet** [comment] 2020-02-25 10:47
Hello @thomas-kl1,

I guess we'll have [to agree to disagree](https://github.com/Smile-SA/elasticsuite/issues/1639#issuecomment-572005637).

Regards,

**Comment by rbayet** [comment] 2020-02-25 10:48
Duplicate of #1639

**Closed by rbayet** 2020-02-25 10:48 UTC
