### ISSUE TITLE
Error when we save an optimizer with from date and/or to date values

### ISSUE THREAD

**Issue by PierreLeMaguer** [Smile-SA/elasticsuite#917] opened 2018-05-17 14:16 UTC
### Preconditions

The problem occurs when we try to create/update an optimizer with non null fromdate AND todate. The back office is configure to use French date format.

Magento Version : 2.1.12

ElasticSuite Version : 2.3.11

Environment : Dev and Prod

### Steps to reproduce

1. Go to the Back office
2. Create an optimizer with from date and to date.

### Expected result

1. Optimizer Saved with right values on the fields from_date and to_date

### Actual result

Optimizer not saved and error :  DateTime::__construct(): Failed to parse time string (23/05/2018) at position 0 (2): Unexpected character
Exception #0 (Exception): DateTime::__construct(): Failed to parse time string (23/05/2018) at position 0 (2): Unexpected character
#0 /var/www/algam/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-optimizer/Model/Optimizer.php(289): DateTime->__construct('23/05/2018')
#1 /var/www/algam/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-optimizer/Controller/Adminhtml/Optimizer/Save.php(55): Smile\ElasticsuiteCatalogOptimizer\Model\Optimizer->validateData(Object(Magento\Framework\DataObject))
#2 /var/www/algam/var/generation/Smile/ElasticsuiteCatalogOptimizer/Controller/Adminhtml/Optimizer/Save/Interceptor.php(24): Smile\ElasticsuiteCatalogOptimizer\Controller\Adminhtml\Optimizer\Save->execute()
#3 /var/www/algam/vendor/magento/framework/App/Action/Action.php(102): Smile\ElasticsuiteCatalogOptimizer\Controller\Adminhtml\Optimizer\Save\Interceptor->execute()
#4 /var/www/algam/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#5 /var/www/algam/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#6 /var/www/algam/vendor/magento/framework/Interception/Chain/Chain.php(70): Smile\ElasticsuiteCatalogOptimizer\Controller\Adminhtml\Optimizer\Save\Interceptor->___callParent('dispatch', Array)
#7 /var/www/algam/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Smile\\Elasticsu...', 'dispatch', Object(Smile\ElasticsuiteCatalogOptimizer\Controller\Adminhtml\Optimizer\Save\Interceptor), Array, 'adminAuthentica...')
1. [Screenshot, logs]

One solution I found: /home/pilem/Travail/SmileProject/algam/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-optimizer/Model/Optimizer.php:l288-289 -> replace new \DateTime() by $this->dateFilter->filter()

**Comment by afoucret** [comment] 2018-05-17 14:29
> But since the issue is occuring on a public method, you should be able to fix it on your project with an "around" plugin.

Would prefer a PR that fix the bug in the project !!!

**Comment by afoucret** [comment] 2018-06-11 11:39
@romainruaud : Can you have a look at this one ?

**Comment by romainruaud** [comment] 2018-06-11 11:49
I don't understand, it's fixed by PR #918

**Comment by afoucret** [comment] 2018-06-11 11:51
I want you to test the PR carefully.

**Comment by djenvert** [comment] 2018-06-11 11:51
Or write acceptance test 😀 #troll

**Comment by afoucret** [comment] 2018-06-11 11:52
That would be fine !!!

**Comment by romainruaud** [comment] 2018-06-11 13:17
PR is working as intended.

Tested on an english Back-Office, and also with a french one. No issue, date is properly saved and displayed with both locales.

**Comment by romainruaud** [comment] 2018-06-11 13:18
Just one thing, the commit could be cherry picked to 2.5.x instead of master.

**Comment by afoucret** [comment] 2018-06-11 13:19
PR merged

**Closed by afoucret** 2018-06-11 13:19 UTC
Labels: bug
