### ISSUE TITLE
Error on css compilation with themes that not inherit from luma 

### ISSUE THREAD

**Issue by Garde85** [Smile-SA/elasticsuite#1391] opened 2019-04-24 10:58 UTC
If applies to frontend a theme that not has as parent theme luma, static content compilation goes wrong.

### Preconditions
Magento Version : Magento CE 2.3.1
ElasticSuite Version : 2.7.6
Environment : Developer mode

Third party modules : Porto theme 

### Steps to reproduce

1. Install smile-SA suite to magento 2
2. Install porto theme or every other child theme that not has luma as parent
3. Apply this theme to frontend
4. Visit one page on frontend

### Expected result
Page displayed well.

### Actual result
Page is broken beacuse css is generated with errors. This is the error present in:

static/version1556099033/frontend/Smartwave/porto/it_IT/css/styles-m.css

`variable @autocomplete-item__border is undefined in file /var/www/html/var/view_preprocessed/pub/static/frontend/Smartwave/porto/it_IT/Smile_ElasticsuiteCore/css/source/_module.less in _module.less on line 32, column 38
30|                     border-bottom: 0;
31|                 }
32|                 .lib-css(border-top, @autocomplete-item__border);
33|                 cursor: default;
34|                 margin: 0;
35|                 padding: @indent__xs @indent__xl @indent__xs @indent__s;
<pre>#1 Magento\Framework\View\Asset\PreProcessor\AlternativeSource->processContent() called at [vendor/magento/framework/View/Asset/PreProcessor/AlternativeSource.php:114]
#2 Magento\Framework\View\Asset\PreProcessor\AlternativeSource->process() called at [vendor/magento/module-developer/Model/View/Asset/PreProcessor/PreprocessorStrategy.php:76]
#3 Magento\Developer\Model\View\Asset\PreProcessor\PreprocessorStrategy->process() called at [vendor/magento/framework/View/Asset/PreProcessor/Pool.php:77]
#4 Magento\Framework\View\Asset\PreProcessor\Pool->process() called at [vendor/magento/framework/View/Asset/Source.php:152]
#5 Magento\Framework\View\Asset\Source->preProcess() called at [vendor/magento/framework/View/Asset/Source.php:105]
#6 Magento\Framework\View\Asset\Source->getFile() called at [vendor/magento/framework/View/Asset/File.php:158]
#7 Magento\Framework\View\Asset\File->getSourceFile() called at [vendor/magento/framework/App/StaticResource.php:135]
#8 Magento\Framework\App\StaticResource->launch() called at [vendor/magento/framework/App/Bootstrap.php:258]
#9 Magento\Framework\App\Bootstrap->run() called at [pub/static.php:13]
</pre>`

This less variable:

@autocomplete-item__border

is present only in luma and not in blank theme. (Porto's parent theme is Magento blank)

**Comment by romainruaud** [comment] 2019-04-25 13:05
`@autocomplete-item__border` is part of blank theme.

Please see : https://github.com/magento/magento2/blob/2.3-develop/app/design/frontend/Magento/blank/Magento_CatalogSearch/web/css/source/_module.less#L12

Closed as being duplicate of #91 #222 #933

**Closed by romainruaud** 2019-04-25 13:05 UTC

**Comment by evagabond** [comment] 2019-05-01 20:40
@romainruaud - I've installed the latest version of ElasticSuite and still getting the similar error, in spite of applying the solutions at [#91](https://github.com/Smile-SA/elasticsuite/issues/91) [#222](https://github.com/Smile-SA/elasticsuite/issues/222) [#933](https://github.com/Smile-SA/elasticsuite/issues/933)

I am using **Magento 2.3.1** & **Porto Theme 3.1.8**

**I am getting the following error:**

Compilation from source: /vendor/magento/theme-frontend-blank/web/css/styles-m.less
variable @autocomplete-item__border is undefined in file /var/view_preprocessed/pub/static/frontend/Smartwave/porto/en_US/Smile_ElasticsuiteCore/css/source/_module.less in _module.less on line 32, column 38
30|                     border-bottom: 0;
31|                 }
32|                 .lib-css(border-top, @autocomplete-item__border);
33|                 cursor: default;
34|                 margin: 0;
35|                 padding: @indent__xs @indent__xl @indent__xs @indent__s;

In File.php line 151:
                                                                                                                                                     
The contents from the "/pub/static/frontend/Smartwave/porto/en_US/css/styles-m.css" file can't be read. Warning!file_get_contents(/pub/static/frontend/Smartwave/porto/en_US/css/styles-m.css): failed to open stream: No such file or directory file

**Comment by mbuchert** [comment] 2019-05-02 07:58
I've edited the file`app/design/frontend/<vendor>/<theme>/Magento_CatalogSearch/web/css/source/_module.less` and added
```
@autocomplete__background-color: @color-white;
@autocomplete__border: 1px solid @form-element-input__border-color;
@autocomplete-item__border: 1px solid @color-gray90;
@autocomplete-item__hover__color: @color-gray91;
@autocomplete-item-amount__color: @color-gray60;
```
Then I ran command `rm -rf var/di/* var/generation/* var/cache/* var/log/* var/page_cache/* var/session/* var/view_preprocessed/* generated/* && php bin/magento cache:clean &&php bin/magento cache:flush && php bin/magento setup:upgrade && php bin/magentosetup:di:compile && php bin/magento setup:static-content:deploy -f` and all gone fine

**Comment by evagabond** [comment] 2019-05-02 11:25
@mbuchert - Yes tried all that, but still not working. Even contacted Porto support, but they said that this issue doesn't fall within their theme-support, and that I contact extension developer for any support. 
:-(

**Comment by elfeffe** [comment] 2019-09-11 14:22
I'm having the same problem with Hebes theme
