### ISSUE TITLE
Fail To Create Products Index Due To Data Type In The ElasticSearch

### ISSUE THREAD

**Issue by liangsuilong** [Smile-SA/elasticsuite#673] opened 2017-12-29 08:29 UTC
### Preconditions

Magento Version : CE 2.2.2

ElasticSuite Version : 2.4.6

Environment : Default Mode

We add a customized attribute for our product. It is named as spu. The data type is varchar in MySQL. 

MySQL [dcshop]> select * from eav_attribute where attribute_code = 'spu'\G;
*************************** 1. row ***************************
   attribute_id: 145
 entity_type_id: 4
 attribute_code: spu
attribute_model: NULL
  backend_model: NULL
   backend_type: varchar
  backend_table: NULL
 frontend_model: NULL
 frontend_input: text
 frontend_label: SPU
 frontend_class: validate-digits
   source_model: NULL
    is_required: 1
is_user_defined: 1
  default_value: NULL
      is_unique: 0
           note: NULL
1 row in set (0.00 sec)

After installing  smile_elasticsuite, I run bin/magento indexer:reindex command. There is no error. However, I click the menu on my website and search something, I cannot see any product in the category page and search result page.  I check elasticsearch's log. It shows NumberFormatException.

Dec 29 11:52:10 elasticsearch elasticsearch[2081]: [2017-12-29 11:52:09,156][DEBUG][action.bulk              ] [Ajak] [magento2_default_catalog_product_20171229_035201][0] failed to execute bulk item (index) index {[magento2_default_catalog_product_20171229_035201][product][7617], source[{"entity_id":"7617","attribute_set_id":"9","type_id":"simple","sku":"60043151980838","has_options":"0","required_options":"0","created_at":"2017-12-06 07:16:23","updated_at":"2017-12-06 07:17:00","visibility":"4","price":[{"price":"56.0000","original_price":"56.0000","is_discount":false,"customer_group_id":"0"},{"price":"56.0000","original_price":"56.0000","is_discount":false,"customer_group_id":"1"},{"price":"56.0000","original_price":"56.0000","is_discount":false,"customer_group_id":"2"},{"price":"56.0000","original_price":"56.0000","is_discount":false,"customer_group_id":"3"},{"price":"56.0000","original_price":"56.0000","is_discount":false,"customer_group_id":"4"}],"category":[{"category_id":2},{"category_id":87,"is_parent":true,"name":"Home & Lights & Construction"},{"category_id":94,"is_parent":true,"name":"Lights & Lighting"},{"category_id":98,"is_parent":true,"name":"LED Lighting"}],"color":[245],"option_text_color":["Multicolor Red"],"status":[1],"option_text_status":["Enabled"],"tax_class_id":[4],"option_text_tax_class_id":["None"],"size":[305],"option_text_size":["N\/A"],"description":["<p>LED lights. Illuminated garland with lamps. 140 LED lights. Length: 10m. Indoor use only<\/p>"],"short_description":["<p>LED Lights-Multicoloured<\/p>\n<p>- Illuminated garland with lamps<br \/>\n- 140 LED lights<br \/>\n- Voltage: 220V<br \/>\n- Colour: Multicoloured<br \/>\n- Length: 10meters<br \/>\n- Indoor use only<\/p>"],"name":["LED Lights-Multicoloured"],"image":["\/6\/0\/60043151980838-1.jpg"],"spu":["60043151980838"],"stock":{"is_in_stock":true,"qty":9999}}]}
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: MapperParsingException[failed to parse [spu]]; nested: NumberFormatException[For input string: "60043151980838"];
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:329)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:311)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:438)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.index.mapper.DocumentParser.parseNonDynamicArray(DocumentParser.java:426)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.index.mapper.DocumentParser.parseArray(DocumentParser.java:381)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:256)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:124)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:309)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:584)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:563)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOperationOnPrimary(TransportIndexAction.java:211)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:223)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:327)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:120)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:68)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:657)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:287)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:378)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at java.lang.Thread.run(Thread.java:748)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: Caused by: java.lang.NumberFormatException: For input string: "60043151980838"
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at java.lang.Integer.parseInt(Integer.java:583)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at java.lang.Integer.parseInt(Integer.java:615)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.common.xcontent.support.AbstractXContentParser.intValue(AbstractXContentParser.java:127)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.index.mapper.core.IntegerFieldMapper.innerParseCreateField(IntegerFieldMapper.java:293)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:241)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:321)
Dec 29 11:52:10 elasticsearch elasticsearch[2081]: #011... 24 more

And I check elasticsearch's indices. There is no document put into the products index.

root@elasticsearch:~# curl 'localhost:9200/_cat/indices?v'
health status index                                             pri rep docs.count docs.deleted store.size pri.store.size 
green  open   magento2_default_catalog_product_20171229_035201    1   0          0            0       159b           159b 
green  open   magento2_default_catalog_category_20171229_035209   1   0        128            0    152.6kb        152.6kb 
green  open   magento2_default_thesaurus_20171229_035210          1   0          0            0       159b           159b 

Later, I check mapping of product index. Here is response from elasticsearch 
root@elasticsearch:~# curl 'localhost:9200/magento2_default_catalog_product_20171229_035201/_mapping?pretty=true'
{
  "magento2_default_catalog_product_20171229_035201" : {
    "mappings" : {
      "product" : {
        "_all" : {
          "enabled" : false
        },
        "properties" : {
          "attribute_set_id" : {
            "type" : "integer"
          },
          "autocomplete" : {
            "type" : "string",
            "fields" : {
              "shingle" : {
                "type" : "string",
                "analyzer" : "shingle"
              },
              "whitespace" : {
                "type" : "string",
                "analyzer" : "whitespace"
              }
            },
            "analyzer" : "standard"
          },
          "brand" : {
            "type" : "integer"
          },
          "category" : {
            "type" : "nested",
            "properties" : {
              "category_id" : {
                "type" : "integer"
              },
              "is_parent" : {
                "type" : "boolean"
              },
              "is_virtual" : {
                "type" : "boolean"
              },
              "name" : {
                "type" : "string",
                "norms" : {
                  "enabled" : false
                },
                "fielddata" : {
                  "format" : "disabled"
                },
                "copy_to" : [ "search", "spelling" ],
                "analyzer" : "standard"
              },
              "position" : {
                "type" : "integer"
              }
            }
          },
          "children_ids" : {
            "type" : "integer"
          },
          "color" : {
            "type" : "integer"
          },
          "configurable_attributes" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "created_at" : {
            "type" : "date",
            "format" : "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd"
          },
          "description" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling" ],
            "analyzer" : "standard"
          },
          "entity_id" : {
            "type" : "integer"
          },
          "has_options" : {
            "type" : "boolean"
          },
          "image" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling" ],
            "analyzer" : "standard"
          },
          "manufacturer" : {
            "type" : "integer"
          },
          "mixed_match_group" : {
            "type" : "integer"
          },
          "mixed_price" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "fields" : {
              "sortable" : {
                "type" : "string",
                "norms" : {
                  "enabled" : false
                },
                "index_options" : "docs",
                "analyzer" : "sortable"
              }
            },
            "copy_to" : [ "spelling" ],
            "analyzer" : "standard"
          },
          "name" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "fields" : {
              "shingle" : {
                "type" : "string",
                "norms" : {
                  "enabled" : false
                },
                "index_options" : "docs",
                "fielddata" : {
                  "format" : "disabled"
                },
                "analyzer" : "shingle"
              },
              "sortable" : {
                "type" : "string",
                "norms" : {
                  "enabled" : false
                },
                "index_options" : "docs",
                "analyzer" : "sortable"
              },
              "whitespace" : {
                "type" : "string",
                "norms" : {
                  "enabled" : false
                },
                "fielddata" : {
                  "format" : "disabled"
                },
                "analyzer" : "whitespace"
              }
            },
            "copy_to" : [ "search", "spelling" ],
            "analyzer" : "standard"
          },
          "option_text_brand" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling" ],
            "analyzer" : "standard"
          },
          "option_text_color" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "fields" : {
              "untouched" : {
                "type" : "string",
                "index" : "not_analyzed"
              }
            },
            "copy_to" : [ "search", "spelling" ],
            "analyzer" : "standard"
          },
          "option_text_manufacturer" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "fields" : {
              "untouched" : {
                "type" : "string",
                "index" : "not_analyzed"
              }
            },
            "copy_to" : [ "search", "spelling" ],
            "analyzer" : "standard"
          },
          "option_text_mixed_match_group" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling" ],
            "analyzer" : "standard"
          },
          "option_text_size" : {
            "type" : "string",
            "index" : "not_analyzed",
            "copy_to" : [ "spelling" ]
          },
          "option_text_status" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling" ],
            "analyzer" : "standard"
          },
          "option_text_tax_class_id" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling" ],
            "analyzer" : "standard"
          },
          "price" : {
            "type" : "nested",
            "properties" : {
              "customer_group_id" : {
                "type" : "integer"
              },
              "is_discount" : {
                "type" : "boolean"
              },
              "original_price" : {
                "type" : "double"
              },
              "price" : {
                "type" : "double"
              }
            }
          },
          "required_options" : {
            "type" : "boolean"
          },
          "search" : {
            "type" : "string",
            "fields" : {
              "shingle" : {
                "type" : "string",
                "analyzer" : "shingle"
              },
              "whitespace" : {
                "type" : "string",
                "analyzer" : "whitespace"
              }
            },
            "analyzer" : "standard"
          },
          "short_description" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling" ],
            "analyzer" : "standard"
          },
          "size" : {
            "type" : "integer"
          },
          "sku" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "fields" : {
              "untouched" : {
                "type" : "string",
                "index" : "not_analyzed"
              }
            },
            "copy_to" : [ "search", "spelling" ],
            "analyzer" : "whitespace"
          },
          "spelling" : {
            "type" : "string",
            "fields" : {
              "phonetic" : {
                "type" : "string",
                "analyzer" : "phonetic"
              },
              "shingle" : {
                "type" : "string",
                "analyzer" : "shingle"
              },
              "whitespace" : {
                "type" : "string",
                "analyzer" : "whitespace"
              }
            },
            "analyzer" : "standard"
          },
          "spu" : {
            "type" : "integer",
            "copy_to" : [ "spelling" ]
          },
          "status" : {
            "type" : "integer"
          },
          "stock" : {
            "properties" : {
              "is_in_stock" : {
                "type" : "boolean"
              },
              "qty" : {
                "type" : "integer"
              }
            }
          },
          "tax_class_id" : {
            "type" : "integer"
          },
          "type_id" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "updated_at" : {
            "type" : "date",
            "format" : "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd"
          },
          "vendor_sku" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling" ],
            "analyzer" : "standard"
          },
          "visibility" : {
            "type" : "integer"
          }
        }
      }
    }
  }
}

It shows the type of spu is integer in the elasticsearch's mapping. As we know, The maximum value of elasticsearch's integer is  2^31-1. In fact my spu is 14-bit digits, and it is bigger than 32bit integer. I think the issue is here. However, spu attribute is  varchar type in MySQL. Why is it put into elasticsearch as integer type? Is there any problem in transfer data type in the plugin?

**Comment by liangsuilong** [comment] 2017-12-29 10:38
I update some information. 

I click into Magento admin console, and go into product attribute page. I switch input validation for store owner from integer number to none. Then I check the eav attribute in MySQL. Here is some change.

![screencapture-192-168-122-156-admin-catalog-product_attribute-edit-attribute_id-145-key-7c83c71c1b1a4086da075f9ade018ae37f3256187f7c80151ba49cec8f2e9d80-1514543184963](https://user-images.githubusercontent.com/152888/34435190-ab4daeb6-ecc6-11e7-91cf-885bf6333ef8.png)

MySQL [dcshop]> select * from eav_attribute where attribute_code = 'spu'\G
*************************** 1. row ***************************
   attribute_id: 145
 entity_type_id: 4
 attribute_code: spu
attribute_model: NULL
  backend_model: NULL
   backend_type: varchar
  backend_table: NULL
 frontend_model: NULL
 frontend_input: text
 frontend_label: SPU
 frontend_class: NULL
   source_model: NULL
    is_required: 1
is_user_defined: 1
  default_value: NULL
      is_unique: 0
           note: NULL
1 row in set (0.00 sec)

And I reindex all index. There is no error in Magento command line. And there is no error in elasticsearch , either. It looks OK. I check the mapping of elasticsearch. I found the data type of spu changes to string. 

root@elasticsearch:/var/log# curl 'localhost:9200/magento2_default_catalog_product_20171229_093352/_mapping?pretty=true'
{
  "magento2_default_catalog_product_20171229_093352" : {
    "mappings" : {
      "product" : {
        "_all" : {
          "enabled" : false
        },
        "properties" : {
          "attribute_set_id" : {
            "type" : "integer"
          },
          "autocomplete" : {
            "type" : "string",
            "fields" : {
              "shingle" : {
                "type" : "string",
                "analyzer" : "shingle"
              },
              "whitespace" : {
                "type" : "string",
                "analyzer" : "whitespace"
              }
            },
            "analyzer" : "standard"
          },
          "brand" : {
            "type" : "integer"
          },
          "category" : {
            "type" : "nested",
            "properties" : {
              "category_id" : {
                "type" : "integer"
              },
              "is_parent" : {
                "type" : "boolean"
              },
              "is_virtual" : {
                "type" : "boolean"
              },
              "name" : {
                "type" : "string",
                "norms" : {
                  "enabled" : false
                },
                "fielddata" : {
                  "format" : "disabled"
                },
                "copy_to" : [ "search", "spelling" ],
                "analyzer" : "standard"
              },
              "position" : {
                "type" : "integer"
              }
            }
          },
          "children_attributes" : {
            "type" : "string"
          },
          "children_ids" : {
            "type" : "integer"
          },
          "color" : {
            "type" : "integer"
          },
          "configurable_attributes" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "created_at" : {
            "type" : "date",
            "format" : "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd"
          },
          "description" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling" ],
            "analyzer" : "standard"
          },
          "entity_id" : {
            "type" : "integer"
          },
          "has_options" : {
            "type" : "boolean"
          },
          "image" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling" ],
            "analyzer" : "standard"
          },
          "manufacturer" : {
            "type" : "integer"
          },
          "mixed_match_group" : {
            "type" : "integer"
          },
          "mixed_price" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "fields" : {
              "sortable" : {
                "type" : "string",
                "norms" : {
                  "enabled" : false
                },
                "index_options" : "docs",
                "analyzer" : "sortable"
              }
            },
            "copy_to" : [ "spelling" ],
            "analyzer" : "standard"
          },
          "name" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "fields" : {
              "shingle" : {
                "type" : "string",
                "norms" : {
                  "enabled" : false
                },
                "index_options" : "docs",
                "fielddata" : {
                  "format" : "disabled"
                },
                "analyzer" : "shingle"
              },
              "sortable" : {
                "type" : "string",
                "norms" : {
                  "enabled" : false
                },
                "index_options" : "docs",
                "analyzer" : "sortable"
              },
              "whitespace" : {
                "type" : "string",
                "norms" : {
                  "enabled" : false
                },
                "fielddata" : {
                  "format" : "disabled"
                },
                "analyzer" : "whitespace"
              }
            },
            "copy_to" : [ "search", "spelling" ],
            "analyzer" : "standard"
          },
          "option_text_brand" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling" ],
            "analyzer" : "standard"
          },
          "option_text_color" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "fields" : {
              "untouched" : {
                "type" : "string",
                "index" : "not_analyzed"
              }
            },
            "copy_to" : [ "search", "spelling" ],
            "analyzer" : "standard"
          },
          "option_text_manufacturer" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "fields" : {
              "untouched" : {
                "type" : "string",
                "index" : "not_analyzed"
              }
            },
            "copy_to" : [ "search", "spelling" ],
            "analyzer" : "standard"
          },
          "option_text_mixed_match_group" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling" ],
            "analyzer" : "standard"
          },
          "option_text_size" : {
            "type" : "string",
            "index" : "not_analyzed",
            "copy_to" : [ "spelling" ]
          },
          "option_text_status" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling" ],
            "analyzer" : "standard"
          },
          "option_text_tax_class_id" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling" ],
            "analyzer" : "standard"
          },
          "price" : {
            "type" : "nested",
            "properties" : {
              "customer_group_id" : {
                "type" : "integer"
              },
              "is_discount" : {
                "type" : "boolean"
              },
              "original_price" : {
                "type" : "double"
              },
              "price" : {
                "type" : "double"
              }
            }
          },
          "required_options" : {
            "type" : "boolean"
          },
          "search" : {
            "type" : "string",
            "fields" : {
              "shingle" : {
                "type" : "string",
                "analyzer" : "shingle"
              },
              "whitespace" : {
                "type" : "string",
                "analyzer" : "whitespace"
              }
            },
            "analyzer" : "standard"
          },
          "short_description" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling" ],
            "analyzer" : "standard"
          },
          "size" : {
            "type" : "integer"
          },
          "sku" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "fields" : {
              "untouched" : {
                "type" : "string",
                "index" : "not_analyzed"
              }
            },
            "copy_to" : [ "search", "spelling" ],
            "analyzer" : "whitespace"
          },
          "spelling" : {
            "type" : "string",
            "fields" : {
              "phonetic" : {
                "type" : "string",
                "analyzer" : "phonetic"
              },
              "shingle" : {
                "type" : "string",
                "analyzer" : "shingle"
              },
              "whitespace" : {
                "type" : "string",
                "analyzer" : "whitespace"
              }
            },
            "analyzer" : "standard"
          },
          "spu" : {
            "type" : "string",
            "index" : "not_analyzed",
            "copy_to" : [ "spelling" ]
          },
          "status" : {
            "type" : "integer"
          },
          "stock" : {
            "properties" : {
              "is_in_stock" : {
                "type" : "boolean"
              },
              "qty" : {
                "type" : "integer"
              }
            }
          },
          "tax_class_id" : {
            "type" : "integer"
          },
          "type_id" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "updated_at" : {
            "type" : "date",
            "format" : "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd"
          },
          "vendor_sku" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling" ],
            "analyzer" : "standard"
          },
          "visibility" : {
            "type" : "integer"
          }
        }
      }
    }
  }
}

At last, I try to search some product from search box. It can show some products to me. So I think it is a bug that elasticsuite use wrong data type to fetch data from MySQL and put into elasticsearch. It occurs that elasticsearch cannot create and update index normally.

**Comment by afoucret** [comment] 2018-01-04 11:06
Hi @liangsuilong 

We choose to store the field with a numeric frontend class as integer in order to fulfill some functional requirements :
* Ability to create slider facets for this fields
* Ability to sort using the numeric order instead of the lexicographic one (1, 2, 10 instead of 1, 10, 2)
* Ability to create numeric filters (gt, lt, ...) in rules (virtual category, optimizers, ...)

Having integer is a functionnal requirement and it will not change in the future.
I patch the code to use long for such kind of fields instead of integer. So you can have longer fields and it will solve the issue at least if you have less than 18 digits.

We may also append an additional control on the length for this fields in the future.
I considered the issue as close since it is by design and the situation is improved by using long (#PR #680 that have been merged and will be part of the next stable release).

**Closed by afoucret** 2018-01-04 11:06 UTC
