### ISSUE TITLE
Not Optimum Search: Search for "jack" doesnt find "jacket"

### ISSUE THREAD

**Issue by samc2810** [Smile-SA/elasticsuite#355] opened 2017-03-15 16:59 UTC
### Preconditions

M2.1.4 CE
PHP 7.1
ES 2.4.0

Environment : Developer

### Steps to reproduce

1. Search for "jack"

### Expected result

1. It should find Product containing the word "jack" eg jack, jacket, jackets

### Actual result

1. Search for "jacket" delivers more results than search for "jack"
![image](https://cloud.githubusercontent.com/assets/1092318/23960543/92f0817e-09a8-11e7-9472-5918018dda5c.png)

![image](https://cloud.githubusercontent.com/assets/1092318/23960565/a218ec68-09a8-11e7-9d47-29998bc2f5dc.png)

Is this a configuration or a bug in the extension? As you can the autocomplete shows more results than the actual search. It can be reproduced on your demo site too

Thanks for a reply and a fix
Cheers Sam

**Comment by romainruaud** [comment] 2017-03-15 18:09
Hello @samc2810 and thank your for submitting this issue.

I agree with you, this is a bit confusing. Let's see what happens here.

The autocomplete box is "auto learning" : when you type "jack", it finds previously typed search terms, like "jacket" in your example.

It then runs a query searching for "jack" AND "jacket"  (and eventually other synonyms stuff) => bingo, many products are matching "jacket" and are showed up here.

This is mainly to obtain a "search as you type" feature and being able to have results even if you just began to type a word (you have results for "ja" because the engine is automatically expanding it to "jacket").

But once you hit enter and land on the search result page, we are now processing a search query only for "jack" and do not expand to "jacket".

ElasticSearch himself could do some stemming part here, but "jack" and "jacket" are not enough close on its stemming engine to make them matching.

If you tweak a bit the fuzziness configuration (see https://github.com/Smile-SA/elasticsuite/wiki/FulltextSearchEngineBasicConfiguration#fuzziness-configuration ), you'll be able to obtain matching between "jack" and "jacket" but I am not sure you do want especially do such a thing, but are rather wondering about the behavior you are observing.

So it's not a bug, it's just different behavior between autocomplete box and concrete search results page. Thank you for submitting this one, it points out a good one to think about internally with @afoucret .

Best regards, and again, thank you for asking this.

**Comment by samc2810** [comment] 2017-03-17 10:44
Hi Romain

Thanks for your quick reply
Fuzziness seems to be the answer

**Comment by romainruaud** [comment] 2017-03-20 16:11
Hello,

we will not provide a fix for this one, since most of users will not just hit Enter when they have typed "jac" and are seeing the autocomplete results : they will just click on the proposed "jacket" term.

That's fine for us if the fuzziness does help you managing this case.

Best regards, and do not hesitate to reopen if needed.

**Closed by romainruaud** 2017-03-20 16:11 UTC
Labels: question
