### ISSUE TITLE
Attributes Not Searched With Spellchecking Turn Off

### ISSUE THREAD

**Issue by paulpartington-cti** [Smile-SA/elasticsuite#1455] opened 2019-07-03 11:13 UTC
### Preconditions

Magento Version : Magento EE 2.3.0

ElasticSuite Version : 2.8.0

Environment : Production

### Steps to reproduce
1. Create a text attribute for ISBN10 and ISBN13
2. Set the attributes to be searchable but disable spellchecking. Give the attributes a weighting of 10.
3. Enable Search Fuzziness
4. Run a seach reindex
5. Search for a product using an ISBN10 or ISBN13

### Expected result
1. As only a single result matches, the customer is taken directly to the product page.

### Actual result
1. The ISBN10 and ISBN13 attributes are not included in the search request
2. The customer is taken to a blank search result page

I've logged the search request's `must` values with the spellcheck settings toggled on/off.

*Spellcheck Enabled*
```
"must": {
              "bool": {
                "must": [],
                "must_not": [],
                "should": [
                  {
                    "multi_match": {
                      "query": "9780070265141",
                      "fields": [
                        "spelling.whitespace^10",
                        "name.whitespace^100",
                        "sku.whitespace^60",
                        "isbn10.whitespace^100",
                        "isbn13.whitespace^50",
                        "authors.whitespace^40"
                      ],
                      "minimum_should_match": "100%",
                      "tie_breaker": 1,
                      "boost": 1,
                      "type": "best_fields",
                      "cutoff_frequency": 0.15,
                      "fuzziness": "AUTO",
                      "prefix_length": 1,
                      "max_expansions": 10
                    }
                  },
                  {
                    "multi_match": {
                      "query": "9780070265141",
                      "fields": [
                        "spelling.phonetic^1"
                      ],
                      "minimum_should_match": "100%",
                      "tie_breaker": 1,
                      "boost": 1,
                      "type": "best_fields",
                      "cutoff_frequency": 0.15
                    }
                  }
                ],
                "minimum_should_match": 1,
                "boost": 1
              }
            },
            "boost": 1
          }
```

*Spellcheck Disabled*
```
"must": {
              "bool": {
                "must": [],
                "must_not": [],
                "should": [
                  {
                    "multi_match": {
                      "query": "9780070265141",
                      "fields": [
                        "spelling.whitespace^10",
                        "name.whitespace^100",
                        "sku.whitespace^60",
                        "authors.whitespace^40"
                      ],
                      "minimum_should_match": "100%",
                      "tie_breaker": 1,
                      "boost": 1,
                      "type": "best_fields",
                      "cutoff_frequency": 0.15,
                      "fuzziness": "AUTO",
                      "prefix_length": 1,
                      "max_expansions": 10
                    }
                  },
                  {
                    "multi_match": {
                      "query": "9780070265141",
                      "fields": [
                        "spelling.phonetic^1"
                      ],
                      "minimum_should_match": "100%",
                      "tie_breaker": 1,
                      "boost": 1,
                      "type": "best_fields",
                      "cutoff_frequency": 0.15
                    }
                  }
                ],
                "minimum_should_match": 1,
                "boost": 1
              }
            },
```

As some background our client sells books and therefore uses ISBNs as a unique identifier. We have two attributes: ISBN10 and ISBN13. The SKU contains the ISBN10 but also some other characters.

As ISBNs contain a string of digits, we don't want to apply any spellchecking to them otherwise non-related products are sometimes returned.

**Comment by romainruaud** [comment] 2019-07-08 07:32
Well for me this is the broken case I was describing in #1266 if I read it properly.

@rbayet I suggest you have a look on this one, maybe the first step is to find a workaround, prior to refactoring the spellchecking feature.

Regards

**Comment by romainruaud** [comment] 2020-02-27 07:36
I close since it's duplicate of #1266

**Closed by romainruaud** 2020-02-27 07:36 UTC
Labels: bug
