### ISSUE TITLE
ElasticSuite 2.3 Magento 2.1.7 autocomplete _getSectionTitle — form-mini.min.js:5:305TypeError: undefined is not an object (evaluating 'this.options.templates[type].title')

### ISSUE THREAD

**Issue by mjamato714** [Smile-SA/elasticsuite#477] opened 2017-07-25 19:46 UTC
I have attempted to include the elasticsuite autocomplete block in a custom theme layout file like this: 
` <referenceContainer name="porto_header">
            <block class="Smile\ElasticsuiteCore\Block\Search\Form\Autocomplete" name="top.search" as="topSearch" template="Smile_ElasticsuiteCore::search/form.mini.phtml">
                <arguments>
                    <argument name="rendererList" xsi:type="array">
                        <item name="term" xsi:type="array">
                            <item name="title" xsi:type="string" translate="true">Search terms</item>
                            <item name="template" xsi:type="string">Smile_ElasticsuiteCore/autocomplete/term</item>
                        </item>
                    </argument>
                </arguments>
            </block>
        </referenceContainer>`

This results in a browser console javascript error like this: 
`[Error] TypeError: undefined is not an object (evaluating 'this.options.templates[type].title')
	_getSectionTitle (form-mini.min.js:5:305)
	(anonymous function) (jquery-ui.min.js:27:340)
	_getSectionHeader (form-mini.min.js:4:304)
	(anonymous function) (jquery-ui.min.js:27:340)
	(anonymous function) (form-mini.min.js:6:804)
	(anonymous function)
	each (9a913ab56d195c28441d18bc89341610.min.js:176:562)
	(anonymous function) (form-mini.min.js:6:671)
	proxy (9a913ab56d195c28441d18bc89341610.min.js:186)
	fire (9a913ab56d195c28441d18bc89341610.min.js:360:229)
	fireWith (9a913ab56d195c28441d18bc89341610.min.js:366:186)
	done (9a913ab56d195c28441d18bc89341610.min.js:776:107)
	callback (9a913ab56d195c28441d18bc89341610.min.js:803)`

The search autocomplete box is not loaded at all. 
### Preconditions

Centos 7, magento 2.1.7 php 7.x elasticsuite 2.3

Magento Version : CE 2.1.7

ElasticSuite Version :2.3

Environment :Production

Third party modules : Smartwave porto theme which includes Smartwave Megamenu module. no other modules. 

### Steps to reproduce

1. include the elasticsuite autocomplete block in a custom theme layout file like this: 
` <referenceContainer name="porto_header">
            <block class="Smile\ElasticsuiteCore\Block\Search\Form\Autocomplete" name="top.search" as="topSearch" template="Smile_ElasticsuiteCore::search/form.mini.phtml">
                <arguments>
                    <argument name="rendererList" xsi:type="array">
                        <item name="term" xsi:type="array">
                            <item name="title" xsi:type="string" translate="true">Search terms</item>
                            <item name="template" xsi:type="string">Smile_ElasticsuiteCore/autocomplete/term</item>
                        </item>
                    </argument>
                </arguments>
            </block>
        </referenceContainer>`
### Expected result

1. The search autocomplete box should show on frontend and there should not be a javascript error. 

### Actual result

1. autocomplete box is not shown and browser console shows javascript [Error] TypeError: undefined is not an object (evaluating 'this.options.templates[type].title')

**Comment by romainruaud** [comment] 2017-07-27 09:59
Hello,

I'm afraid that we cannot propose support for custom themes, especially since this one is not free (99$), leading me unable to test to reproduce your issue.

I am guessing that something is wrong on layouting. Please first ensure that you are using latest version of Elasticsuite (2.3.6).

Please also note that autocomplete renderers are injected into the autocomplete block in several pieces of layout : 

https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/view/frontend/layout/default.xml#L19

This one should continue to work since it references the block with "top.search" name, which should fit to your own block.

And here : 

https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-core/view/frontend/layout/default.xml#L20

Maybe this one is now missing since you re-declared the top.search block. I would suggest you dig more on this one, maybe just try to report it to your own block.


Best regards,

**Comment by mjamato714** [comment] 2017-07-27 17:44
Hi @romainruaud,

Thank you very much for your response! 

I suspect that you were correct that redeclaring the search block caused one of those two files to be missing. 

There may be an alternative way of solving this by addressing module load order, but I was able to solve it in my case by including **both** of the contents of the linked files in your answer in my custom theme layout/default.xml file (with only the referenceContainer name edit) like this: 

``` 
<referenceContainer name="porto_header">
	               <block class="Smile\ElasticsuiteCore\Block\Search\Form\Autocomplete" name="top.search" as="topSearch" template="Smile_ElasticsuiteCore::search/form.mini.phtml">
	                   <arguments>
	                       <argument name="rendererList" xsi:type="array">
	                           <item name="term" xsi:type="array">
	                               <item name="title" xsi:type="string" translate="true">Search terms</item>
	                               <item name="template" xsi:type="string">Smile_ElasticsuiteCore/autocomplete/term</item>
	                           </item>
	                       </argument>
	                   </arguments>
	               </block>
	           </referenceContainer>
		        <referenceBlock name="top.search">
		            <arguments>
		                <argument name="rendererList" xsi:type="array">
		                    <item name="product" xsi:type="array">
		                        <item name="title" xsi:type="string" translate="true">Products</item>
		                        <item name="template" xsi:type="string">Smile_ElasticsuiteCatalog/autocomplete/product</item>
		                    </item>
		                    <item name="category" xsi:type="array">
		                        <item name="title" xsi:type="string" translate="true">Categories</item>
		                        <item name="template" xsi:type="string">Smile_ElasticsuiteCatalog/autocomplete/category</item>
		                    </item>
		                    <item name="product_attribute" xsi:type="array">
		                        <item name="title" xsi:type="string" translate="true">Attributes</item>
		                        <item name="template" xsi:type="string">Smile_ElasticsuiteCore/autocomplete/term</item>
		                        <item name="titleRenderer" xsi:type="string">Smile_ElasticsuiteCatalog/js/autocomplete/product-attribute</item>
		                    </item>
		                </argument>
		            </arguments>
		        </referenceBlock>
```
This should work with porto theme and should be similar for other themes that are hiding/replacing the header-wrapper container. 

Thanks again @romainruaud and the Smile team for a great extension!

**Comment by romainruaud** [comment] 2017-07-28 06:47
Hello @mjamato714 

Glad to see you managed to fix your instance !

You're welcome, thank you for using our extension,

I close the issue since it's solved, feel free to reopen it if needed,

Best regards

**Closed by romainruaud** 2017-07-28 06:47 UTC

**Comment by inelukipg** [comment] 2017-08-25 08:07
Hi @mjamato714 I'm using Porto and plan to install elasticsuite on my site.
Was that the only problem that you faced in the Porto-elasticsuite combination?

**Comment by mjamato714** [comment] 2017-08-28 17:13
@inelukipg 

Hi, 

Sorry for the wait, I was away the last few days. The issues I faced were:

1.   Error during static content deploy both the issue and solution is discussed in this thread:https://github.com/Smile-SA/elasticsuite/issues/91#issuecomment-325209166

2. Search autocomplete results not displaying correctly and unclickable as is discussed in this current thread. 

Let me know if you have any questions or issues getting elasticsuite up and running with porto. 

Good luck!

**Comment by inelukipg** [comment] 2017-08-29 07:32
@mjamato714 

Thank you!
Ok for (1) you mean this solution?
in file:
/var/www/html/magento2/app/design/frontend/Smartwave/porto/Magento_CatalogSearch/web/css/source/module.less

_Replace the lines 6-10 with the following:
@autocomplete__background-color: @color-white;
@autocomplete__border: 1px solid @form-element-input__border-color;
@autocomplete-item__border: 1px solid @color-gray90;
@autocomplete-item__hover__color: @color-gray91;
@autocomplete-item-amount__color: @color-gray60;

You then need to go through the file and replace the old classes with these new ones._

I don't want to override the core theme files, could I place this in my child theme?

**Comment by mjamato714** [comment] 2017-08-29 07:47
Hi @inelukipg,

Yes I am referring to that solution. You could include an edited version of the module.less file in your child theme which will override the core theme file. Just place the edited file in your custom theme directory within app/design like this: 

app/design/frontend/Custom/Theme/Magento_CatalogSearch/web/css/source/module.less

You may still get static content deploy errors for the themes where you have not updated the module.less file, but the child theme should deploy without errors. I have not extensively tested this as I have updated the module.less file in all themes currently to remove all static content deploy errors. I would be interested to hear whether or not you run into any major issues using porto and elasticsuite by overriding the module.less file with the edits in only your child theme.

**Comment by mjamato714** [comment] 2018-03-27 07:10
Hi @deckside,

What does your layout/default.xml look like?

**Comment by deckside** [comment] 2018-03-27 10:27
Hi @ mjamato714

I tried creating my own module, using your code.

Created Module 
------------
app/design/frontend/Deckside/searchfix/etc/module.xml

<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="Deckside_searchfix" setup_version="1.0.0">
    </module>
</config>

-----------
app/design/frontend/Deckside/searchfix/registration.php

<?php
\Magento\Framework\Component\ComponentRegistrar::register(
	\Magento\Framework\Component\ComponentRegistrar::MODULE,
	'Deckside_searchfix',
	__DIR__
);

----------------

app/design/frontend/Deckside/searchfix/Magento_Theme/layout/default.xml

<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="footer_links" remove="true" />
        <referenceContainer name="header-wrapper">
            <block class="Smile\ElasticsuiteCore\Block\Search\Form\Autocomplete" name="top.search" as="topSearch" template="Smile_ElasticsuiteCore::search/form.mini.phtml">
                <arguments>
                    <argument name="rendererList" xsi:type="array">
                        <item name="term" xsi:type="array">
                            <item name="title" xsi:type="string" translate="true">Search terms</item>
                            <item name="template" xsi:type="string">Smile_ElasticsuiteCore/autocomplete/term</item>
                        </item>
                    </argument>
                </arguments>
            </block>
        </referenceContainer>
        <referenceBlock name="top.search">
            <arguments>
                <argument name="rendererList" xsi:type="array">
                    <item name="product" xsi:type="array">
                        <item name="title" xsi:type="string" translate="true">Products</item>
                        <item name="template" xsi:type="string">Smile_ElasticsuiteCatalog/autocomplete/product</item>
                    </item>
                    <item name="category" xsi:type="array">
                        <item name="title" xsi:type="string" translate="true">Categories</item>
                        <item name="template" xsi:type="string">Smile_ElasticsuiteCatalog/autocomplete/category</item>
                    </item>
                    <item name="product_attribute" xsi:type="array">
                        <item name="title" xsi:type="string" translate="true">Attributes</item>
                        <item name="template" xsi:type="string">Smile_ElasticsuiteCore/autocomplete/term</item>
                        <item name="titleRenderer" xsi:type="string">Smile_ElasticsuiteCatalog/js/autocomplete/product-attribute</item>
                    </item>
                </argument>
            </arguments>
        </referenceBlock>
    </body>
</page>
----------

php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy en_US en_AU -f 
php bin/magento setup:di:compile
sudo chmod -R u+rwX,go+rX,go-w /var/www/magento
sudo chown -R www-data:www-data /var/www/magento
sudo php bin/magento cache:flush
---------

Result: Search box still missing
--------


I think my problem is that I do not really know what I'm doing when creating the module.

The module looks like it is working but no changes are visible (search box is still missing).

**Comment by deckside** [comment] 2018-03-27 10:39
Just added
app/design/frontend/Deckside/searchfix/Smile_ElasticsuiteCore/templates/search/form.mini.phtml
```
<?php
/**
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Smile Elastic Suite to newer
 * versions in the future.
 *
 *
 * @category  Smile
 * @package   Smile\ElasticsuiteCore
 * @author    Romain Ruaud <romain.ruaud@smile.fr>
 * @copyright 2016 Smile
 * @license   Open Software License ("OSL") v. 3.0
 */
/**
 * Template for quick search mini form.
 * Overriden to manage template injection for the rendering of autocomplete results.
 *
 * @var $block \Smile\ElasticsuiteCore\Block\Search\Form\Autocomplete
 */
?>

<?php
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div id="header-search" class="skip-content skip-content--style">
    <div class="block block-search">
        <div class="block block-title"><strong><?php /* @escapeNotVerified */
                echo __('Search'); ?></strong></div>
        <div class="block block-content">
            <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */
            echo $helper->getResultUrl() ?>" method="get">
                <div class="field search">
                    <label class="label" for="search" data-role="minisearch-label">
                        <span><?php /* @escapeNotVerified */
                            echo __('Search'); ?></span>
                    </label>
                    <div class="control">
                        <input id="search"
                               data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?php /* @escapeNotVerified */
                               echo $block->getUrl('search/ajax/suggest'); ?>",
                                "destinationSelector":"#search_autocomplete",
                                "templates": <?php /* @noEscape */
                               echo $block->getJsonSuggestRenderers(); ?>,
                                "priceFormat" : <?php /* @noEscape */
                               echo $block->getJsonPriceFormat(); ?>}
                            }'
                               type="text"
                               name="<?php /* @escapeNotVerified */
                               echo $helper->getQueryParamName() ?>"
                               value="<?php /* @escapeNotVerified */
                               echo $helper->getEscapedQueryText() ?>"
                               placeholder="<?php /* @escapeNotVerified */
                               echo __('Search entire store here...'); ?>"
                               class="input-text"
                               maxlength="<?php /* @escapeNotVerified */
                               echo $helper->getMaxQueryLength(); ?>"
                               role="combobox"
                               aria-haspopup="false"
                               aria-autocomplete="both"
                               autocomplete="off"
                               data-block="autocomplete-form"/>
                        <div id="search_autocomplete" class="search-autocomplete"></div>
                        <?php echo $block->getChildHtml() ?>
                    </div>
                </div>
                <div class="actions">
                    <button type="submit"
                            title="<?php echo $block->escapeHtml(__('Search')) ?>"
                            class="action search">
                        <span><?php /* @escapeNotVerified */
                            echo __('Search'); ?></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
```
Run commands
`php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy en_US en_AU -f 
php bin/magento setup:di:compile
sudo chmod -R u+rwX,go+rX,go-w /var/www/magento
sudo chown -R www-data:www-data /var/www/magento
sudo php bin/magento cache:flush`



Result: Search box still missing

**Comment by deckside** [comment] 2018-03-27 20:02
Have also tried changing the load sequence in module.xml to ensure my module runs last. After this change my module is listed last in app/etc/config.php

app/design/frontend/Deckside/searchfix/etc/module.xml

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="Deckside_searchfix" setup_version="1.0.0">
		    <sequence>
	    <!-- Deckside_searchfix will run last: -->
            <module name="Temando_Shipping" />
            </sequence>
    </module>
</config>
```

**Comment by deckside** [comment] 2018-03-27 21:35
Solved:
Create file app/design/frontend/Infortis/base/Smile_ElasticsuiteCore/templates/search/form.mini.phtml

Paste content below:
```
<?php
/**
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Smile Elastic Suite to newer
 * versions in the future.
 *
 *
 * @category  Smile
 * @package   Smile\ElasticsuiteCore
 * @author    Romain Ruaud <romain.ruaud@smile.fr>
 * @copyright 2016 Smile
 * @license   Open Software License ("OSL") v. 3.0
 */
/**
 * Template for quick search mini form.
 * Overriden to manage template injection for the rendering of autocomplete results.
 *
 * @var $block \Smile\ElasticsuiteCore\Block\Search\Form\Autocomplete
 * 
 * @modified by Darren Sutherland <darren@deckside.com> for use with Infortis Ultimo theme, only removed "Search" from echo as it did not fit well on screen.
 * Place this code in app/design/frontend/Infortis/base/Smile_ElasticsuiteCore/templates/search/form.mini.phtml
 *
 */
?>

<?php
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div id="header-search" class="skip-content skip-content--style">
    <div class="block block-search">
        <div class="block block-title"><strong><?php /* @escapeNotVerified */
                echo __(''); ?></strong></div>
        <div class="block block-content">
            <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */
            echo $helper->getResultUrl() ?>" method="get">
                <div class="field search">
                    <label class="label" for="search" data-role="minisearch-label">
                        <span><?php /* @escapeNotVerified */
                            echo __(''); ?></span>
                    </label>
                    <div class="control">
                        <input id="search"
                               data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?php /* @escapeNotVerified */
                               echo $block->getUrl('search/ajax/suggest'); ?>",
                                "destinationSelector":"#search_autocomplete",
                                "templates": <?php /* @noEscape */
                               echo $block->getJsonSuggestRenderers(); ?>,
                                "priceFormat" : <?php /* @noEscape */
                               echo $block->getJsonPriceFormat(); ?>}
                            }'
                               type="text"
                               name="<?php /* @escapeNotVerified */
                               echo $helper->getQueryParamName() ?>"
                               value="<?php /* @escapeNotVerified */
                               echo $helper->getEscapedQueryText() ?>"
                               placeholder="<?php /* @escapeNotVerified */
                               echo __('Search entire store here...'); ?>"
                               class="input-text"
                               maxlength="<?php /* @escapeNotVerified */
                               echo $helper->getMaxQueryLength(); ?>"
                               role="combobox"
                               aria-haspopup="false"
                               aria-autocomplete="both"
                               autocomplete="off"
                               data-block="autocomplete-form"/>
                        <div id="search_autocomplete" class="search-autocomplete"></div>
                        <?php echo $block->getChildHtml() ?>
                    </div>
                </div>
                <div class="actions">
                    <button type="submit"
                            title="<?php echo $block->escapeHtml(__('Search')) ?>"
                            class="action search">
                        <span><?php /* @escapeNotVerified */
                            echo __(''); ?></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

```
Set permission for file, flush cache

**Comment by ukomiljon** [comment] 2018-03-28 01:03
Hi guys, it works!.

After this: 
Create file app/design/frontend/Infortis/base/Smile_ElasticsuiteCore/templates/search/form.mini.phtml
and paste the content. flush cache.

thank you very much to all. :)

**Comment by o0mohd0o** [comment] 2023-06-07 18:09
Hi, I have 2.4.5 Magento 2 I had hard time to fix this.

this is the modification I have done in latest porto theme.

in this file app/design/frontend/Smartwave/porto/Smartwave_Porto/layout/default.xml

replace the follwoing:
`        <referenceContainer name="page.wrapper">
          <block class="Smartwave\Porto\Block\Template" name="porto_header" template="html/header.phtml" before="main.content">
              <block class="Magento\Framework\View\Element\Html\Links" name="header.links">
                  <arguments>
                      <argument name="css_class" xsi:type="string">header links</argument>
                  </arguments>
              </block>
              <block class="Smartwave\Porto\Block\Form\Login" name="header_customer_form_login" ifconfig="porto_settings/header/login_popup" template="Smartwave_Porto::html/login.phtml"/>
              <block class="Magento\Store\Block\Switcher" name="store_language" as="store_language" template="switch/languages.phtml"/>
              <block class="Magento\Framework\View\Element\Template" name="top.search" as="topSearch" template="Magento_Search::form.mini.phtml" />
              <block class="Smartwave\Porto\Block\Template" name="custom_block" template="html/header_custom_block.phtml" ifconfig="porto_settings/header/static_block" after="-"/>
              <block class="Smartwave\Porto\Block\Template" name="custom_block_top" template="html/top_custom_block.phtml" ifconfig="porto_settings/header/static_block_top" after="-"/>
              <block class="Smartwave\Porto\Block\Template" name="custom_block_menu" template="html/header_custom_block_menu.phtml" after="-"/>
              <block class="Smartwave\Porto\Block\Template" name="porto_custom_notice" template="html/custom_notice.phtml" after="-"/>
          </block>
        </referenceContainer>`

with this:

`        <referenceContainer name="page.wrapper">
          <block class="Smartwave\Porto\Block\Template" name="porto_header" template="html/header.phtml" before="main.content">
              <block class="Magento\Framework\View\Element\Html\Links" name="header.links">
                  <arguments>
                      <argument name="css_class" xsi:type="string">header links</argument>
                  </arguments>
              </block>
              <block class="Smartwave\Porto\Block\Form\Login" name="header_customer_form_login" ifconfig="porto_settings/header/login_popup" template="Smartwave_Porto::html/login.phtml"/>
              <block class="Magento\Store\Block\Switcher" name="store_language" as="store_language" template="switch/languages.phtml"/>
              <block class="Magento\Framework\View\Element\Template" name="top.search" as="topSearch" template="Magento_Search::form.mini.phtml" />
              <block class="Smartwave\Porto\Block\Template" name="custom_block" template="html/header_custom_block.phtml" ifconfig="porto_settings/header/static_block" after="-"/>
              <block class="Smartwave\Porto\Block\Template" name="custom_block_top" template="html/top_custom_block.phtml" ifconfig="porto_settings/header/static_block_top" after="-"/>
              <block class="Smartwave\Porto\Block\Template" name="custom_block_menu" template="html/header_custom_block_menu.phtml" after="-"/>
              <block class="Smartwave\Porto\Block\Template" name="porto_custom_notice" template="html/custom_notice.phtml" after="-"/>
              <block class="Smile\ElasticsuiteCore\Block\Search\Form\Autocomplete" name="top.search" as="topSearch" template="Smile_ElasticsuiteCore::search/form.mini.phtml">
                <arguments>
                    <argument name="rendererList" xsi:type="array">
                        <item name="term" xsi:type="array">
                            <item name="title" xsi:type="string" translate="true">Search terms</item>
                            <item name="template" xsi:type="string">Smile_ElasticsuiteCore/autocomplete/term</item>
                        </item>
                    </argument>
                </arguments>
              </block>
          </block>
        <referenceBlock name="top.search">
            <arguments>
                <argument name="rendererList" xsi:type="array">
                    <item name="product" xsi:type="array">
                        <item name="title" xsi:type="string" translate="true">Products</item>
                        <item name="template" xsi:type="string">Smile_ElasticsuiteCatalog/autocomplete/product</item>
                    </item>
                    <item name="category" xsi:type="array">
                        <item name="title" xsi:type="string" translate="true">Categories</item>
                        <item name="template" xsi:type="string">Smile_ElasticsuiteCatalog/autocomplete/category</item>
                    </item>
                    <item name="product_attribute" xsi:type="array">
                        <item name="title" xsi:type="string" translate="true">Attributes</item>
                        <item name="template" xsi:type="string">Smile_ElasticsuiteCore/autocomplete/term</item>
                        <item name="titleRenderer" xsi:type="string">Smile_ElasticsuiteCatalog/js/autocomplete/product-attribute</item>
                    </item>
                </argument>
            </arguments>
        </referenceBlock>`
