### ISSUE TITLE
Static content deploy error

### ISSUE THREAD

**Issue by davidandersson1** [Smile-SA/elasticsuite#1835] opened 2020-06-04 08:57 UTC
Hello,

We have found a Elastic suite module bug when we run static content deploy command. please check attached screenshot.

Magento community version: 2.3.5
Elastic suite version: 2.9.0
Deploy Mode: production
We have JS setting in backend as below as per recommended by Magento.
a) Merge JavaScript Files- No
b) Enable JavaScript Bundling - Yes
c) Minify JavaScript Files -Yes

Look like something wrong in file: vendor/smile/elasticsuite/src/module-elasticsuite-indices/view/adminhtml/web/js/jquery.json-viewer.js 

Can you please check and provide us some solution for it.

Thanks in advance,
David Andersson
![Screenshot from 2020-06-04 14-15-39](https://user-images.githubusercontent.com/49389320/83736539-6be56d80-a66f-11ea-8461-102f8f233dce.jpg)

**Comment by romainruaud** [comment] 2020-06-04 09:16
Probably a duplicate of #1793

**Comment by davidandersson1** [comment] 2020-06-04 09:28
Hi @romainruaud 

Thanks for your quick reply.

Yes its same and got solution. Thanks a lot.

Have a nice day ahead.

Thanks,
David

**Closed** 2020-06-04 09:31 UTC
Labels: duplicate
