### ISSUE TITLE
curl: (7) Failed to connect to localhost port 9200: Connection refused

### ISSUE THREAD

**Issue by Dayssam** [Smile-SA/elasticsuite#67] opened 2016-06-24 12:32 UTC
Hi

`curl localhost:9200`

i got this error

```
curl: (7) Failed to connect to localhost port 9200: Connection refused
```

ubuntu 15.10 32 bits

**Comment by afoucret** [comment] 2016-06-27 07:32
The issue is not in ElasticSuite but more likely in your ElasticSearch install.

Can you check you ran all steps described here : https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig

BR,

**Comment by Dayssam** [comment] 2016-06-27 09:14
@afoucret 
I followed all the steps

**Comment by afoucret** [comment] 2016-06-27 09:20
Are you using any virtualization or container stuff ? 

The problem is clearly related with your ElasticSearch setup and not in ElasticSuite. 
It seems that the service is not started.

I would start by checking this : https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-service.html#using-systemd

**Comment by Dayssam** [comment] 2016-06-27 09:32
@afoucret 
The service is not starting

```
root@sofisoft-OptiPlex-380:/var/www/html# java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) Server VM (build 25.91-b14, mixed mode)

```

```
root@sofisoft-OptiPlex-380:/var/www/html# /etc/init.d/elasticsearch stop
[ ok ] Stopping elasticsearch (via systemctl): elasticsearch.service.
root@sofisoft-OptiPlex-380:/var/www/html# /etc/init.d/elasticsearch start
[ ok ] Starting elasticsearch (via systemctl): elasticsearch.service.
root@sofisoft-OptiPlex-380:/var/www/html# 

```

**Comment by afoucret** [comment] 2016-06-27 09:48
Since this issue is purely related to running ElasticSearch on Ubuntu 15.10, it would be better to look for a solution into the ElasticSearch community (and start digging into the elasticsearch github repo https://github.com/elastic/elasticsearch).

IMHO it is not related to ElasticSuite at all and this issue should be closed.

**Comment by Dayssam** [comment] 2016-06-27 10:10
Where can i find any log of ElasticSearch ?

**Comment by afoucret** [comment] 2016-06-27 14:10
You will find log into `/var/log/elasticsearch`.
If the problem occurs during startup, useful information can sometines be found into the syslog (`/var/logsyslog` ?)

As explained in my previous response I close this issue which is not related directly with ElasticSuite.

Thx

**Closed by afoucret** 2016-06-27 14:10 UTC

**Comment by Dayssam** [comment] 2016-06-27 14:15
no log file in this folder
`tail -f /var/log/elasticsearch/`

no log related to elasticsearch in 
`/var/log/syslog`

**Comment by sravankumark** [comment] 2017-02-12 06:53
I am beginner for ElasticSearch and i would like to install ES in my AWS RHEL 7.2, Can you please share the steps for installation.
Thank you

**Comment by asabanovic** [comment] 2017-04-07 12:33
Here is a tutorial on how to install it and what issues to watch out for (Elasticsearch 5) on ubuntu/homestead
https://medium.com/@adnanxteam/how-to-install-elasticsearch-5-and-kibana-on-homestead-vagrant-60ea757ff8c7
