### ISSUE TITLE
Pagebuilder product widget category filter not working with anchored parent categories

### ISSUE THREAD

**Issue by chrey** [Smile-SA/elasticsuite#2958] opened 2023-06-01 08:24 UTC
When creating a CMS block with a PageBuilder Product carousel, I don't have any products displayed if I select a parent category. 
Same behaviour if : 
- I use  Select product by "Category" > select the parent category in the list
- I use Select product by  "Condition" > create a  rule based on category is one of  "a parent category"

It works fine if I use a child category that has products directly assigned. 
All my categories have is_anchor = 1  in database

### Preconditions
Magento Version : Adobe commerce 2.4.6 + B2B shared catalog activated
ElasticSuite Version : 2.11.1.1
Environment : Production mode

Third party modules : 
 "akeneo/magento2-connector-enterprise": "^103.4",
        "amasty/mega-menu": "^2.4",
        "amasty/mega-menu-page-builder": "^1.0",
        "amasty/module-hide-price": "^1.6",
        "amasty/module-request-a-quote-pro-subscription-package": "^1.0",
        "cweagans/composer-patches": "^1.7",
        "dompdf/dompdf": "^2.0",
        "magento/composer-dependency-version-audit-plugin": "~0.1",
        "magento/composer-root-update-plugin": "~2.0",
        "magento/extension-b2b": "^1.3",
        "magento/product-enterprise-edition": "2.4.6",
        "mageplaza/magento-2-french-language-pack": "^1.0",
        "markshust/magento2-module-disabletwofactorauth": "^2.0",
        "nesbot/carbon": "^2.66",
        "owebia/magento2-module-advanced-shipping": "^2.8",
        "smile/elasticsuite": "~2.11.0",
        "smile/module-cron": "^5.0",
        "smile/module-custom-entity": "^1.3",
        "smile/module-custom-entity-product-link": "^1.3",
        "smile/module-elasticsuite-quick-order": "^2.11",
        "smile/module-elasticsuite-shared-catalog": "~2.11",
        "smile/module-patch": "^1.0",
        "smile/module-reconfigure": "^5.0",
        "stripe/module-payments": "^3.4"

### Steps to reproduce
1. Create a CMS block in backend
2. Use pagebuilder to edit the block, add a row and a Product widget inside
3. Select Carousel  + Category + take a category in the list that has subcategories and no products directly assigned
4. Validate the widget

### Expected result
1. Products of subcategories should be displayed in carousel

### Actual result
No products displayed, empty block

![unnamed](https://github.com/Smile-SA/elasticsuite/assets/644773/8c7f6291-ea17-448a-9197-53b2fbf962de)

### Other comment :
It works on another project having more or less the same modules stack on Magento 2.4.3-93 + Elasticsuite 2.10.4

**Comment by vahonc** [comment] 2023-06-05 11:24
Hello @chrey, 

Are the categories from your screenshots real or virtual (based on some rules)?

Have you compared the assigned relations of the products in both your environment?

Also, please provide an extract of the queries that are being sent to ES when you validate the widget. You can get it from the `system.log` file if you activate the **Debug mode** of Elasticsuite in: `Stores -> Configuration -> Elasticsuite -> Base settings -> Elasticsearch Client -> Enable Debug Mode`.

BR,
Vadym

**Comment by romainruaud** [comment] 2023-06-20 13:53
Hi @chrey 

I close this issue since we were not able to reproduce it.

Please try to solve it internally for your project.

If in the end it's really an Elasticsuite issue, feel free to open another issue.

Regards

**Closed by romainruaud** 2023-06-20 13:53 UTC
