### ISSUE TITLE
Sorting of Virtual Categories

### ISSUE THREAD

**Issue by Judder** [Smile-SA/elasticsuite#796] opened 2018-03-05 16:01 UTC
Magento Version : 2.2.1

### Steps to reproduce
1. Create virtual category
2. Change Display Settings -> Default Product Listing Sort By to a different value
3. No change to results shown in category listing pages

### Expected result
1. Virtual category products, that are Auto Sorted, are sorted according to the selected value

### Actual result
1. Value appears to be ignored from reading module-elasticsuite-virtual-category

**Comment by afoucret** [comment] 2018-03-05 16:37
Hi @Judder,

What ElasticSuite version are you using ?
If using 2.5.3, there is a known bug on sorts that is fixed in the 2.5.4 version.

Please let me know if upgrading to version 2.5.4 fix the problem.

**Comment by afoucret** [comment] 2018-03-07 09:59
Hi @Judder,

Any feedback on this ?

**Comment by afoucret** [comment] 2018-03-08 08:00
As I get no response from you and I am not able to reproduce the bug in the last version, I close the issue. Feel free to reopen if needed

**Closed by afoucret** 2018-03-08 08:00 UTC
