### ISSUE TITLE
'is_discount' price data field wrong for dynamic price bundle products and discounted.

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/elasticsuite#290] opened 2017-01-12 14:29 UTC
Steps to reproduce : 

- Create a bundle with dynamic pricing
- Apply a 50% discount via the "Advanced Pricing" tab
- Check the catalog_product_index_price table : the discounted price is shown in min_price and max_price.
- Check the product on ES index : it will show like this : 

```
            {
              "price": "30.5000",
              "original_price": "30.5000",
              "is_discount": false,
              "customer_group_id": "0"
            }
```

This is due to this piece of code : https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/PriceData.php

Lines 65 & 66 : initialize the price and original price to min_price.

Line 68 : For composite products (bundles are catched), do nothing

Line 80 : 'is_discount' is true if final price is < original_price : this is always  false for the case we described above.

**Comment by metamasterplay** [comment] 2017-01-19 18:50
This bug also affects configurable products when pricing is directly done within the simple products. This can be reproduced by:
- Create a confugurable product without any price info.
- Create simple variations with each a price and a special price.

Expected result:
- is_discount should return 'true', especially if all the simple variants are discounted
Actual result:
- is_discount return false because no additionnal processing is done for composite products, the function 'isOriginalPriceReliable' completely jumps this case

Possible solution:

- I think that the table catalog_product_index_price is unreliable because it doesn't calculate the correct prices for composite products. Maybe using $_product->getPriceInfo()->getPrice('regular_price')->getAmount()->getValue() and $_product->getPriceInfo()->getPrice('final_price')->getAmount()->getValue() can do the trick.

**Comment by afoucret** [comment] 2017-02-06 15:44
Hi @metamasterplay 

We cannot use your patch since it will result in a dramatic performance loss during indexing. The problem is in the way Magento is indexing price (not indexing to be more exact) composite products prices. We have some discussion on this with the core team since Magento ES and SolR implementation have the same bug (for the same reason).

**Comment by afoucret** [comment] 2017-10-24 15:11
@romainruaud : I saw the configurable price index was fixed in Magento 2.2.0.
Can you test this one and close the issue if it have been fixed.

**Comment by romainruaud** [comment] 2017-10-24 15:15
@afoucret yep, I take a look at this one.

**Comment by CRYX2** [comment] 2018-01-15 11:53
Same problem, in elasticsearch all is set to false, but I've a simple product discounted and a catalog rule for other products who is not recognized in elastic

**Comment by afoucret** [comment] 2018-01-31 13:44
Hi @CRYX2,

I suspect the patch applied to solve #689 solve this one too.
Can you confirm ?

**Comment by CRYX2** [comment] 2018-01-31 13:53
Yes, #689 fixed even this problem

**Comment by afoucret** [comment] 2018-01-31 13:54
So I close.
Thx for helping.

**Closed by afoucret** 2018-01-31 13:54 UTC
Labels: bug

**Comment by themoonwatcher** [comment] 2020-05-15 16:36
Hello,
It seems the problem is still active in 2.9 version. Is there a fix to include discounted configurables in a virtual category?

**Comment by madnazz** [comment] 2021-03-29 10:59
the rule is not usable when all configurable products are displayed. an alternative solution would be to use 'special_price' is greather then instead of contains...how does this work?
