### ISSUE TITLE
Javascript hangs on Product Detail Page

### ISSUE THREAD

**Issue by EliasKotlyar** [Smile-SA/elasticsuite#1016] opened 2018-07-26 08:56 UTC
### Preconditions
1. Set "general/locale/code" to "Germany(Swiss)"

Magento Version :
I was using EE2.2.4, but it will apply on all Magento Versions.

ElasticSuite Version :
Any

Environment :
can be reproduced on Developer/Production

Third party modules :
No

### Steps to reproduce
1. Set "general/locale/code" to "Germany(Swiss)"
2. Go to Product Detail page

### Expected result
You will see the PDP without any errors

### Actual result
There is a JS Error on the PDP

## Technical Information:
The Value of Price "groupSymbol" on the locale is " ' ". This results in an error in "smile/elasticsuite/src/module-elasticsuite-core/view/frontend/templates/search/form.mini.phtml" because its surrounded with an "data-mage-init" and is not being escaped.

**Comment by afoucret** [comment] 2018-07-31 06:46
Seems that you have spotted the bug root cause.
Is it possible to you to provide a PR that fix ?

**Comment by afoucret** [comment] 2018-08-30 11:34
PR #1049 have been merged and will be part of release 2.5.15.

**Closed by afoucret** 2018-08-30 11:34 UTC
