### ISSUE TITLE
Search by exact request

### ISSUE THREAD

**Issue by anthonyherve** [Smile-SA/elasticsuite#1749] opened 2020-03-16 11:13 UTC
Hello,

I want to configure ElasticSuite to do following search.
I have a field contains shorts key words separated by space (example : SIM, SIM2B, M2B, 80B...).
When I search "M2B", I want results for exact search of "M2B" in key words.

How can I configure search and attribute to have theis result?

Thank you fro your help.

Regards,
Anthony

**Comment by rbayet** [comment] 2020-03-16 12:43
Hello @anthonyherve,

Is that field your SKU or an additional product attribute ?

Regards

**Comment by anthonyherve** [comment] 2020-03-16 13:01
Hello,

It's an additional product attribute.

Regards,
Anthony

**Comment by rbayet** [comment] 2020-03-16 13:45
Hello @anthonyherve,

Thanks for that quick response.
To better address your question, in the example you gave, that is searching for "M2B"
- what do you expect to have in search results if available values are "SIM", "SIM2B", "M2B", "80B"
- what do you expect to have in search results if available values are "SIM", "SIM2B", "80B" (ie nothing with the exact value "M2B")

Just to be sure the behavior you want to reach (to define "exact results OR ...").

Regards,

**Comment by anthonyherve** [comment] 2020-03-16 14:20
Hello,

Thank you also for your quick answer. :-)

- what do you expect to have in search results if available values are "SIM", "SIM2B", "M2B", "80B"
- what do you expect to have in search results if available values are "SIM", "SIM2B", "80B" (ie nothing with the exact value "M2B")

To explain your examples, I have two products in my database.
One with my specific attribute containing: "SIM SIM2B M2B 80B".
The other with my specific attribute containing: "SIM SIM2B 80B".
If I search "M2B", I want my 2 products in search results. If I search "SMI2B" or "08B", I want 0 result.

Thank you for your help.

Regards,

**Comment by rbayet** [comment] 2020-03-16 14:31
Hello @anthonyherve,

What is your current configuration for "minimum should match" and what are the current results in both examples you described ?
(Do we agree that "08B" is "zero eight B" ?)

Regards,

**Comment by anthonyherve** [comment] 2020-03-16 17:01
hello,

My "minimum should match" is 100%.
I agree that "08B" is "zero eight B".
I'm doing some tests because I have a lot of data and I want to do a small example as we discuss.

Meanwhile I want to explain clearly my problem:
- We have SKU formatted only with uppercase, numbers and dash (SIM2B80K...)
- We have two other attributes with product references containing uppercase, numbers and dash (01APP105-1A102Z, MBBN3495E...)

My client wants to have following search results:
- Search: "01APP" => 1 result
- Search: "01APQ" => no result
- Search: "005-1A1" => 1 result
- Search: "0051A1" => no result
- Search: "B80K" => 1 result

Is it possible to do that with ElasticSuite? If yes which configuration I need to do? If not, is there a solution with or without developement?

For the moment, I did not find a solution. So I have created my new specific attribute by cuting words in my SKU and attributes (example : "SIM2B80K" by "SIM SIM2 SIM2B SIM2B8 SIM2B80 SIM2B80K IM2 IM2B...")

I hope you understand what I want to explain.

Thank you for your help.

Regards,

**Comment by anthonyherve** [comment] 2020-03-17 08:00
Hello,

I have found an example on my test environment.
I have following request on my database (my specific attribute has ID 522 and I search for "2B80", I have 16 results)
![image](https://user-images.githubusercontent.com/1899492/76834177-fb2b7380-682c-11ea-9777-bc9777d79768.png)
If I search "2B80" in frontend, I have 17 results : https://qa.amphenol-airlb.fr/fr/catalogsearch/result/index/?q=2B80 (Have you access to this URL?)
![image](https://user-images.githubusercontent.com/1899492/76834296-32018980-682d-11ea-861c-5fc226ca8250.png)

The 17th product is one with SKU "SIM2S80B". I have checked value of specific attribute: "SIM IM2 M2S 2S8 S80 80B SIM2 IM2S M2S8 2S80 S80B SIM2S IM2S8 M2S80 2S80B SIM2S8 IM2S80 M2S80B SIM2S80 IM2S80B SIM2S80B" and I don't have string "2B80".

Thank you for your help.

Regards,

**Comment by romainruaud** [comment] 2020-03-18 08:59
Closed for being duplicate of #970 

Please have a look at the workaround proposed here : https://github.com/Smile-SA/elasticsuite/issues/970#issuecomment-594380109 

Otherwise, we cannot involve more deeply into your particural implementation as part of our Open Source policy here. Feel free to contact us by email directly at romain.ruaud@smile.fr if you are willing to get us involved through our professional services support policy. 

Best regards

**Closed by romainruaud** 2020-03-18 08:59 UTC
Labels: duplicate, question
