### ISSUE TITLE
Base64.encode is missing in analytics date_range_picker.phtml

### ISSUE THREAD

**Issue by southerncomputer** [Smile-SA/elasticsuite#1518] opened 2019-08-28 18:01 UTC
Base64.encode is missing in analytics date_range_picker.phtml
### Preconditions

Magento Version : 2.3.2 EE

ElasticSuite Version : 2.8

Environment : Dev

Third party modules :

### Steps to reproduce

1. Base64.encode is missing in date_range_picker.phtml in Analytics causing module to fail
2. I changed Base64.encode to btoa since that is built in to javascript.
3. Any thoughts on why the Base64.encode function in missing?

### Expected result

1.

### Actual result

1. [Screenshot, logs]

**Comment by androshchuk** [comment] 2019-09-09 14:50
Hello @southerncomputer.
I can't reproduce this problem.
elasticsuite module doesn't have a file named 'date_range_picker.phtml' (only with name date_range_switcher.phtml)  http://joxi.ru/D2P0jEEiqVbwR2
I checked the work of Base64 in file vendor/smile/elasticsuite/src/module-elasticsuite-analytics/view/adminhtml/templates/report/date_range_switcher.phtml. 
It works.

Please provide more information as I can reproduce this issue.

Regards

**Comment by southerncomputer** [comment] 2019-09-10 17:54
![image](https://user-images.githubusercontent.com/6178967/64637789-86d1cc80-d3d2-11e9-9bca-113b7a3b6486.png)

did you try with both yes and no to javascript calendar?

**Comment by androshchuk** [comment] 2019-09-11 08:41
Yes. I checked it. Elasticsuite module doesn't have a file named 'date_range_picker.phtml'. 
Maybe you are using some other third party modules? 
Unfortunately, I can't reproduce this bug.
Please provide more information and screenshots of the bug

**Comment by romainruaud** [comment] 2019-09-11 09:49
@androshchuk can you check the Datepicker in the Search Analytics Dashboard page is still working if you set the Configuration Option "Use Javascript Calendar" to both Yes, and No ?

If I understand properly, that's what is saying @southerncomputer

**Comment by androshchuk** [comment] 2019-09-11 10:31
I changed the configuration option "Use Javascript Calendar" from section  Configuration>Catalog>Catalog>Date & Time Custom Options  . cleared cache and checked page  Search Usage Analytics http://joxi.ru/xAeOGEEfRk3Gqm . 
In both cases everything works fine

**Comment by southerncomputer** [comment] 2019-09-11 10:53
Could be my javascript screwing up because the data picker just doesn't work as it should on these fields.. Sorry I will look into my patches to see what might be causing this strangeness!

**Comment by romainruaud** [comment] 2020-02-27 07:36
I close this one since it was stalled and non reproduce.

Thank you for reporting, do not hesitate to open again if you are facing any issues.

Regards

**Comment by HirokazuNishi** [comment] 2020-03-06 08:25
@romainruaud this issue can reproduce when you enable minify/bundle on production mode.
we can fix the issue to add

'mage/backend/validation', 'prototype'

into require def.

**Comment by androshchuk** [comment] 2020-03-30 08:00
Hello @HirokazuNishi , @southerncomputer 

I can't reproduce this bug.
I have no problem with Base64 in production mode with enabled minify css and js.

Please provide steps to reproduce this problem and your version of Magento and ElasticSuite.
Are you using any third-party modules? If yes, please attach the list

**Comment by HirokazuNishi** [comment] 2020-03-30 09:15
Hi @androshchuk ,

My procedure was,

1. Install M2.3.2-p2 with latest ElasticSuite.
2. Enable JS/CSS minify/merge/bundle.
3. Set Magento mode into production.
4. Deploy static content.
5. Access to admin panel.
6. Filter statistics with date.

Thanks,

**Closed** 2020-04-14 08:11 UTC
Labels: bug, needs update
