### ISSUE TITLE
Price slider displaying incorrect amount on products.

### ISSUE THREAD

**Issue by vortexunsworth** [Smile-SA/elasticsuite#539] opened 2017-09-21 13:01 UTC
The price slider is displaying incorrect product result count compared to actual results and result count when listing products by price excluding tax.

### Preconditions
Magento Version : CE 2.1.7

ElasticSuite Version : 2.3

Environment : Developer and Production

Third party modules : N/A

### Steps to reproduce

1. Set Sales > Tax > Calculation Settings > Catalog Prices = Excluding Tax
2. Go to product list page.
3. Filter products by price slider.

### Expected result
1. Price filter displayed expected results to be actual result count.

### Actual result

1. Price slider expected result count is incorrect to actual results.
![image](https://user-images.githubusercontent.com/30156430/30696860-f96ed5ba-9ed4-11e7-827c-f240eb6ca0df.png)

The problem "seems" to be that the slider carrier on filtering with VAT applied to products. Tried various solutions but none that worked including PR #381 .

**Comment by romainruaud** [comment] 2017-09-25 14:45
Hello @vortexunsworth and thank you for submitting this issue.

I am able to reproduce it on my local environment.

This is not especially due to the "Excluding tax" display configuration, but rather a duplicate of #376 and incorrect slider up and down limit.

The PR #381 is incomplete for now, as it does not resolve completely the bug (that's why the PR has not been merged for now).

We'll continue to work on this PR.

Best regards

**Comment by afoucret** [comment] 2018-02-23 08:36
Merged in branch 2.5.x and master.
Will be part of release 2.5.3.

**Closed by afoucret** 2018-02-23 08:36 UTC
Labels: bug
