### ISSUE TITLE
Banner for the 1st search displayed at the 2nd search

### ISSUE THREAD

**Issue by PierrickOlivier** [Smile-SA/elasticsuite#452] opened 2017-06-13 21:32 UTC
### Preconditions
Environment : http://demo.magento-elastic-suite.io/

### Steps to reproduce
1. Search for "tunic" -> the product http://demo.magento-elastic-suite.io/index.php/maya-tunic.html is displayed
2. Search for something else -> a banner "Maya Tunic is the only product matching your 'tunic' research." is displayed

### Expected result
This banner should be displayed at step 1, not at step 2.

**Comment by romainruaud** [comment] 2017-06-14 07:15
Hello Pierrick, 

Since this is a duplicate of #426 which is already fixed (but fixed not merged at the moment), I close this issue.

Regards

**Closed by romainruaud** 2017-06-14 07:15 UTC
