### ISSUE TITLE
Why indexers are deleting automatically?

### ISSUE THREAD

**Issue by interequipment** [Smile-SA/elasticsuite#2781] opened 2022-11-14 12:35 UTC
I have installed Smile ElasticSuite Open Source ver. 2.10.11 on Magento 2.4.4. why is that product indexer keep deleting after few days?
ElasticSearch version is 7.17.7

**Comment by vahonc** [comment] 2022-11-14 14:34
Hello @interequipment

At this moment your issue is a little bit blurry for us because we don't understand how we can reproduce it. We need more details about your environment, so provide screenshots with your indices and add steps on how it can be reproduced.

BR,
Vadym

**Comment by interequipment** [comment] 2022-11-15 05:03
Hello @vahonc , 

I am mot sure how to reproduce the issue. But in my case, indexed data get deleted after few hours (sometimes in few days). When I check indices in ElasticSuite > System > Indices I cannot see any indices So I have to reindex again

**Comment by romainruaud** [comment] 2022-11-15 07:27
Is this a local environment (Docker ?)

Is this a production/staging environment ? if yes, how is built the Elasticsearch cluster ?

Regards

**Comment by interequipment** [comment] 2022-11-15 07:29
no it is not docker. ElasticSearch installed on a seperetae server (https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig-7.x)

**Comment by romainruaud** [comment] 2022-11-15 07:34
can you share this server specifications ? who is the provider of the server and how the elasticsearch is installed on it ?

regards

**Comment by interequipment** [comment] 2022-11-15 09:51
It is an AWS t3.xlarge instance. Ubuntu 22.04. Installed ES  as per this documentation. https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig-7.x

**Comment by romainruaud** [comment] 2022-11-30 16:33
Hi @interequipment 

for me, this is purely a system/hosting issue and cannot be adressed here as part of our open source support policy.

We do not provide support here on maintaining an Elasticsearch infra.

I close this issue, regards

**Closed by romainruaud** 2022-11-30 16:33 UTC
Labels: question
