### ISSUE TITLE
disable tracking_log

### ISSUE THREAD

**Issue by grebbekevin** [Smile-SA/elasticsuite#1252] opened 2019-01-09 08:42 UTC
Magento Version : 2.2.5
ElasticSuite Version : 2.6.1
Environment : Production mode

### Steps to reproduce
1. Setup elastic suite.
2. Go to Stores -> Configuration -> Elasticsuite -> Tracking
    Set the option enabled to false.
3. Let people search
4. The table is filling up with tracking logs and I can't disable the log events.

### Expected result
1. No tracking logs were send to bonsai.io

### Actual result

![schermafbeelding 2019-01-09 om 09 40 17](https://user-images.githubusercontent.com/8779381/50887124-a0111c00-13f2-11e9-904c-b624b5e37a28.png)

1. The database is filling up with tracking logs of your module.

**Comment by rbayet** [comment] 2019-01-14 16:56
Hello @grebbekevin, 

Are you sure that with `smile_elasticsuite_tracker/general/enabled` set to false there is still new data added to the MySQL table elasticsuite_tracker_log_event ?
After clearing the config and FPC caches ?

I cannot reproduce it on a CE 2.2.7 in production mode with ElasticSuite 2.6.4 and the problem is that the code that ensures the boolean config param is taken into account is already there in 2.6.1...

Are you on a EE version or a CE ?

Regards,

**Comment by romainruaud** [comment] 2019-01-23 09:35
@grebbekevin any update on this one ?

**Comment by grebbekevin** [comment] 2019-01-23 09:54
Dear Rbayet,

We are still having this issue.
We don't use the module with MYSQL but with bonsai.io and these tables are still filling up with those tracking information.
What kind of steps can I give you guys so you can reproduce?

**Comment by romainruaud** [comment] 2019-01-23 10:33
Hello,

just to ensure you understand how the workflow is done.

When people navigate on the website, tracking data are stored (temporarily) on the MySQL table called `elasticsuite_tracker_log_event`. This should not be the case if the tracking is disabled.

@rbayet tested it, and on our instance, if the tracking is disabled in the back-office, this table does not get filled.

Then, the tracking data contained in this table are sent (by batch) regularly to the Elasticsearch storage (your bonsai.io) by a cronjob. This is done like this because Elasticsearch has poor performance with multiple (concurrent) writing and would suffer too much if we keep writing each event in Elasticsearch one by one. That's why this buffer table exists.

That being said,

Please provide us : 

- the result of the following MySQL query : 

`select * from core_config_data where path like "%elasticsuite%";`

- the result of this one : 

`select MAX(date) from elasticsuite_tracker_log_event`

- the result of the following command (on the Magento base dir) : 

`bin/magento config:show smile_elasticsuite_tracker/general/enabled`

- and another capture of all your bonsai.io "tables" which are in fact Elasticsearch indices. 

- if you can, please also paste the content of the indices existing in these bonsai.io "tables".

Regards

**Comment by grebbekevin** [comment] 2019-01-23 10:47
select * from core_config_data where path like "%elasticsuite%"
![query 1](https://user-images.githubusercontent.com/8779381/51601205-0b371400-1f04-11e9-83d7-7a98be4aa832.png)

select MAX(date) from elasticsuite_tracker_log_event
![query 2](https://user-images.githubusercontent.com/8779381/51601204-0a9e7d80-1f04-11e9-813e-f3b7e3c7e54c.png)

bin/magento config:show smile_elasticsuite_tracker/general/enabled
![query 3](https://user-images.githubusercontent.com/8779381/51601203-0a9e7d80-1f04-11e9-9313-8ec9737ed08f.png)

The indices in bonsai:
`green open owh_hyper_3_nl_tracking_log_event_20190106                        tFcncpLKREywnj2QlXEvHg 1 0    34     0  10.2kb  10.2kb
green open owh_hyper_3_default_tracking_log_event_20190118                   pEhbLQ_kQ9qrI4DDtbFI3w 1 0    17     0  24.1kb  24.1kb
green open owh_hyper_3_default_tracking_log_event_20190121                   j0uTyEbNTYuqHYxkhugViw 1 0    19     0  34.9kb  34.9kb
green open owh_hyper_3_default_tracking_log_event_20190105                   wxVmf__pQfKBgeJjcHqiVA 1 0    40     0  10.7kb  10.7kb
green open owh_hyper_3_default_tracking_log_event_20190112                   T6h7fp30SR-ay1ARPmjQpw 1 0    42     0  35.4kb  35.4kb
green open owh_hyper_3_uwcamerastore_com_gl_thesaurus_20181024_121941        i1rN3d8QQvagMK9Sn-Ygog 1 0     0     0    130b    130b
green open owh_hyper_3_default_tracking_log_event_20190109                   fiQqvjdkTAKnZESlzGJq9g 1 0    15     0   9.8kb   9.8kb
green open owh_hyper_3_nl_tracking_log_event_20190117                        9QxlUsRDSJGlTs5D0B7NkQ 1 0     8     0  29.4kb  29.4kb
green open owh_hyper_3_default_tracking_log_event_20190113                   nuX56sC-QsWBWUpdMyqomQ 1 0    34     0  16.6kb  16.6kb
green open owh_hyper_3_default_tracking_log_event_20190111                   vFpJIciMQw-2gwqInmVp0Q 1 0    10     0  33.2kb  33.2kb
green open owh_hyper_3_default_tracking_log_event_20190107                   ksE_1jUNTsm60ENpr_EIPw 1 0    23     0   8.4kb   8.4kb
green open owh_hyper_3_default_catalog_product_20181024_121813               KmD4F4nUT56GtImuNoOv3Q 1 0 50728 31405  43.7mb  43.7mb
green open owh_hyper_3_default_tracking_log_event_20190120                   _PHggcmSRgKpxuVh7KIIVw 1 0    24     0  14.9kb  14.9kb
green open owh_hyper_3_default_tracking_log_event_20190108                   F-JolLqTQf682IPOZGx4gw 1 0    21     0   7.5kb   7.5kb
green open owh_hyper_3_nl_tracking_log_event_20190121                        A0vA4rckRfazKp1Mle1W-A 1 0    31     0   9.6kb   9.6kb
green open owh_hyper_3_nl_tracking_log_event_20190107                        T-KuRLtCSviJZ3z6d9RCmw 1 0    26     0   8.3kb   8.3kb
green open owh_hyper_3_nl_tracking_log_event_20190105                        aYJr8T7ESTe2mC3LECGlkg 1 0    23     0   7.8kb   7.8kb
green open owh_hyper_3_default_tracking_log_event_20190116                   Cfzv3xJHQZiiPvBiN0YOuA 1 0    15     0  16.8kb  16.8kb
green open owh_hyper_3_nl_tracking_log_event_20190114                        EUhPN4u9RFOiERnFUFzZUg 1 0    26     0  36.1kb  36.1kb
green open owh_hyper_3_default_tracking_log_event_20190123                   ig7NCA4pRcu4CBrvhYruJQ 1 0     4     0  14.7kb  14.7kb
green open owh_hyper_3_default_tracking_log_event_20190110                   2P4n34uSRe-9S1FkxxaDKA 1 0    17     0  24.1kb  24.1kb
green open owh_hyper_3_de_thesaurus_20181024_121940                          u86Rg4jmRq-kn004QhDYMA 1 0     0     0    130b    130b
green open owh_hyper_3_default_catalog_category_20181024_121936              RMxCNtKETIaWxGiOJAkvFA 1 0   290     5 430.9kb 430.9kb
green open owh_hyper_3_uwcamerastore_com_gl_catalog_product_20181024_121931  rd9qxGhCTSmceMq7QLnHyw 1 0     0     0    159b    159b
green open owh_hyper_3_default_tracking_log_event_20190115                   61zHFAV9S0K6egL_K8Feew 1 0    16     0  16.9kb  16.9kb
green open owh_hyper_3_uwcamerastore_com_gl_catalog_category_20181024_121939 deoC-PmyTLWxKPfRhKNTqA 1 0   290     5 437.5kb 437.5kb
green open owh_hyper_3_nl_tracking_log_event_20190123                        abDcqVxaRmeA0TsTVuZWcA 1 0     9     0  26.1kb  26.1kb
green open owh_hyper_3_nl_thesaurus_20181024_121940                          VqSjfb7DSbyGDm5SLT5AHg 1 0     0     0    130b    130b
green open owh_hyper_3_nl_catalog_product_20181024_121838                    rObDV4dkRRCBsL91FUdFKg 1 0 50728 33921  45.6mb  45.6mb
green open owh_hyper_3_default_tracking_log_event_20190104                   4oF7n0DAQkmTFEnvJZT8Vg 1 0    29     0   8.8kb   8.8kb
green open owh_hyper_3_nl_tracking_log_event_20190112                        gZX9jkq4SEO3CZjWKPktIw 1 0    11     0   5.6kb   5.6kb
green open owh_hyper_3_default_tracking_log_event_20190117                   QOqJ0fR7RSSIpspNvnanfA 1 0     9     0    33kb    33kb
green open owh_hyper_3_nl_tracking_log_event_20190118                        QbnB74TYS0mMdo-MTlY0iw 1 0    31     0   9.1kb   9.1kb
green open owh_hyper_3_default_tracking_log_event_20190106                   tPBol3rISzu8CUwzDQgbqA 1 0    16     0   6.5kb   6.5kb
green open owh_hyper_3_nl_tracking_log_event_20190120                        bwZIR-JDQwCF_9RQbWedEA 1 0    20     0  10.7kb  10.7kb
green open owh_hyper_3_nl_tracking_log_event_20190116                        DulBmsu-S-2mdI2n6866_A 1 0    16     0  23.9kb  23.9kb
green open owh_hyper_3_nl_tracking_log_event_20190111                        ede7tnjuQzq2RPCkpqH81Q 1 0    28     0  26.1kb  26.1kb
green open owh_hyper_3_nl_tracking_log_event_20190103                        0N-QqjCnTHON4VwDgfv-iQ 1 0     6     0   4.7kb   4.7kb
green open owh_hyper_3_nl_tracking_log_event_20190109                        x-uYWW5GSHe-aJ4aOBdeSw 1 0     7     0  18.8kb  18.8kb
green open owh_hyper_3_nl_tracking_log_event_20190110                        g63mE0rbSMSeyVMAzczyow 1 0    17     0  17.2kb  17.2kb
green open owh_hyper_3_default_tracking_log_event_20190114                   Z9lg0Y2vSnm4Oxenu4XlEg 1 0    46     0  18.7kb  18.7kb
green open owh_hyper_3_default_tracking_log_event_20190119                   DuL0Mfu6RHOpEaoVlnV-vg 1 0    19     0  24.5kb  24.5kb
green open owh_hyper_3_nl_tracking_log_event_20190119                        0M2Y-tMIRkC_ICKDDqG2gQ 1 0    12     0  12.7kb  12.7kb
green open owh_hyper_3_de_catalog_category_20190109_082409                   RGJ4_OGzTISAUuqUYMdjOA 1 0     1     0   9.1kb   9.1kb
green open owh_hyper_3_nl_tracking_log_event_20190104                        rhRi8II6Qn-FrfPj_ZOLUw 1 0    24     0     8kb     8kb
green open owh_hyper_3_de_catalog_product_20181024_121904                    6MUxHvx_ThqpkQZW4lp_KQ 1 0 50708 27183  38.4mb  38.4mb
green open owh_hyper_3_nl_tracking_log_event_20190113                        kJpN6auTT7SDy9VvS2H5HA 1 0    56     0  17.7kb  17.7kb
green open owh_hyper_3_default_tracking_log_event_20190122                   n8E2yqYNSjmh_-Ot7aAErA 1 0    32     0  37.3kb  37.3kb
green open owh_hyper_3_nl_tracking_log_event_20190115                        Cw6qD3VXTGy5XiO2yK274A 1 0    31     0  37.1kb  37.1kb
green open owh_hyper_3_nl_tracking_log_event_20190108                        zYvz8pDzTMqSOrBoyvPIwg 1 0    13     0   6.5kb   6.5kb
green open owh_hyper_3_default_thesaurus_20181024_121940                     jE6P60gcRVC7ALttirjtVA 1 0     0     0    130b    130b
green open owh_hyper_3_nl_tracking_log_event_20190122                        2UobZ1yjQgWPNtEatjLjZQ 1 0    39     0    21kb    21kb
green open owh_hyper_3_nl_catalog_category_20181024_121937                   OHndzijNQaedQgBTaMZQTg 1 0   290     5 508.4kb 508.4kb
 `

Unfortunately i don't know how i can retrieve the information that is in a indice (shard)

**Comment by romainruaud** [comment] 2019-01-23 10:50
Ok, I think I have some insights, most probably, the only events that continue to get registered are the "add to cart", since all the frontend tracking part is properly disabled if the config says so.

But the "add to cart" tracking is done in PHP and does not seem to be conditioned by the tracking enabling... Any other event tracked in PHP directly could lead to the same symptom.

I'll push a PR to fix this one.

Regards

**Comment by romainruaud** [comment] 2019-01-23 11:19
#1279 will fix this issue.

**Comment by grebbekevin** [comment] 2019-01-23 11:31
Hi @romainruaud ,
Thank you for your quick response.
Can you tell me when you make a tag for this fix?

**Comment by romainruaud** [comment] 2019-01-23 11:35
Well I think we should release this 2.6.6 tag next week. 

If that's too slow for you, you can use the 2.6.x-dev branch for now, that contains already the fix.

regards

**Comment by rbayet** [comment] 2019-01-23 16:46
Fixed by 
- #1279 for M2 2.2.x
- #1280 for M2 2.3.x

**Closed by rbayet** 2019-01-23 16:46 UTC
Labels: bug, needs update
