### ISSUE TITLE
Category/search loading performance

### ISSUE THREAD

**Issue by refueledinc** [Smile-SA/elasticsuite#1915] opened 2020-08-12 11:58 UTC
### Preconditions

Magento Version : 2.4.0CE

ElasticSuite Version : 2.10.0

Environment : Developer

Third party modules : Anything related to category has been disabled

### Steps to reproduce

1. When we were on M2.3.3 and ES2.8.X we did not have any category load performance issues
2. We recently did an incremental update to M2.3.5 and ES2.9.x. We noticed category pages were taking a very long time to load.
3. We decided to update to M2.4.0 and ES2.10.0 and we still have the issue with categories.
4. On very small categories with, say, 260 products, we can get the category page to load in 6-8 seconds
5. On larger categories, say, 4,500 products, the page times out and won't load
6. If I disable ES, all categories and search pages load without issue.

### Expected result

1. Pages should load without timeout

### Actual result

1. I have searched, but I cannot find any information in the logs related to the issue
2. Disabling ES fixes the page load problems and allows categories and search pages to load without issue
3. This does not seem specific to M2.4.0 and ES2.10.0 as we noticed the problem with M2.3.5 and ES 2.9.x, but we decided to upgrade magento before really investigating the problem.
4. I searched through the other issues related to performance, but none seem to match the issue we're seeing

Any clue what might cause an issue like this or how to investigate further?

**Comment by Bashev** [comment] 2020-08-12 12:36
The problem is related to page size. Magento try to load all amount of products on one page and this reflect to loading time. You can see my fix #1914

**Comment by refueledinc** [comment] 2020-08-12 16:08
@Bashev Unfortunately I'm not seeing any performance improvement with the PR. I'm still seeing larger categories timeout and smaller categories take a long time to load.

**Comment by refueledinc** [comment] 2020-08-12 16:50
Now that I look more closely, the small category that loads (slowly) is actually loading every product in that category on the first page, despite having pagination set to 24 items. 

The page also has pagination showing and when I click the second page link, no items are returned.

I suspect that's why the larger categories are timing out. Every product is trying to load on the first page, rather than paginate.

**Comment by refueledinc** [comment] 2020-08-12 17:03
@Bashev Thanks for the help and the PR. It looks like my stupidity may have gotten the best of me. It looks like varnish was getting in my way after applying your PR. I've disabled varnish and now I see your PR has indeed helped with the issue.

**Comment by romainruaud** [comment] 2020-08-24 07:08
I close since it's related to the pagesize issue which is expected to be fixed on minor releases 2.10.1 and 2.9.3 very soon.

Regards

**Closed by romainruaud** 2020-08-24 07:08 UTC
