### ISSUE TITLE
How can I search by custom attribute?

### ISSUE THREAD

**Issue by madonzy** [Smile-SA/elasticsuite#517] opened 2017-08-29 10:47 UTC
How can I search products by custom attribute?

**Comment by romainruaud** [comment] 2017-08-29 11:49
Hello @madonzy 

Please provide more details. Your question is quite unclear.

From what I understand, you should create a new Product attribute and set is as "Used in search". This is enough to have it set as searchable and indexed into Elasticsearch.

Regards

**Comment by madonzy** [comment] 2017-08-29 11:55
@romainruaud ok, but what if my attribute is custom and depends on database? Example:
I have a place in my Admin panel where I define tags. Then I choose this tags for the product while creating/editing and data with selected tags savings in custom table. What steps should I do?

**Comment by madonzy** [comment] 2017-08-31 09:50
@romainruaud well, I added file elasticsuite_indices.xml in my module with the content
<img width="813" alt="screen shot 2017-08-31 at 11 45 49 am" src="https://user-images.githubusercontent.com/5281020/29917410-3a0d43de-8e42-11e7-8327-62d7ca0e9aa3.png">
And I created  class with method addData():
<img width="602" alt="screen shot 2017-08-31 at 11 46 31 am" src="https://user-images.githubusercontent.com/5281020/29917442-50c85794-8e42-11e7-89ad-a21481824d7d.png">
Then reindexed (successfull all indexes) but when I type "asdf" in search there is no autocomplete. Normaly I want product with ID: 2050 to be shown. What I'm doing wrong?

**Comment by romainruaud** [comment] 2017-08-31 09:52
Are you sure the data is in the Elasticsearch index ? 

Please check this

**Comment by madonzy** [comment] 2017-08-31 09:54
@romainruaud I added the file_put_contents('text.txt', 'test') as the first line of addData() method, and it created this file while reindexing...

**Comment by romainruaud** [comment] 2017-08-31 09:59
This does not prove anything... please check data inside your Elasticsearch index. 

This can be run by directly querying it via curl, or by using utility plugins like "kopf" plugin on your elasticsearch instance.

Regards

**Comment by madonzy** [comment] 2017-08-31 10:12
@romainruaud maybe you can give me example curl command to run? I can't configure kopf

**Comment by madonzy** [comment] 2017-08-31 11:25
@romainruaud and what about if I have many values (like tags) I should supply it like csv or maybe array?

**Comment by romainruaud** [comment] 2017-08-31 12:19
```curl -XGET 'localhost:9200/magento2*/product/_search?pretty'```

where "magento2" is the alias name defined in Elasticsuite configuration.

This leads to the search api.

You can add param like this : 

```curl -XGET 'localhost:9200/magento2*/product/_search?q=entity_id:2050&pretty'```

Or even post more complex queries by using POST method. Please check the Elasticsearch documentation about queries if you want to know more.

About your values, they can be added as array, this is already done for all attributes.

Regards

**Comment by madonzy** [comment] 2017-08-31 12:29
@romainruaud response is like that:
`test@debian-8:~/www/distripark.dev$ curl -XGET 'localhost:9200/magento2_default_catalog_product_20170831_110239/product/_search?q=entity_id:2050&pretty'
{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 9.893779,
    "hits" : [ {
      "_index" : "magento2_default_catalog_product_20170831_110239",
      "_type" : "product",
      "_id" : "2050",
      "_score" : 9.893779,
      "_source" : {
        "entity_id" : "2050",
        "attribute_set_id" : "4",
        "type_id" : "simple",
        "sku" : "NAN-0012",
        "has_options" : "0",
        "required_options" : "0",
        "created_at" : "2017-06-07 06:47:46",
        "updated_at" : "2017-06-13 09:18:09",
        "visibility" : "4",
        "tags" : [ "nanoauto", "chemia samochodowa" ],
        "price" : [ {
          "price" : "15.9000",
          "original_price" : "15.9000",
          "is_discount" : false,
          "customer_group_id" : "0"
        }, {
          "price" : "15.9000",
          "original_price" : "15.9000",
          "is_discount" : false,
          "customer_group_id" : "1"
        }, {
          "price" : "15.9000",
          "original_price" : "15.9000",
          "is_discount" : false,
          "customer_group_id" : "2"
        }, {
          "price" : "15.9000",
          "original_price" : "15.9000",
          "is_discount" : false,
          "customer_group_id" : "3"
        }, {
          "price" : "15.9000",
          "original_price" : "15.9000",
          "is_discount" : false,
          "customer_group_id" : "4"
        }, {
          "price" : "15.9000",
          "original_price" : "15.9000",
          "is_discount" : false,
          "customer_group_id" : "5"
        }, {
          "price" : "15.9000",
          "original_price" : "15.9000",
          "is_discount" : false,
          "customer_group_id" : "6"
        }, {
          "price" : "15.9000",
          "original_price" : "15.9000",
          "is_discount" : false,
          "customer_group_id" : "7"
        } ],
        "category" : [ {
          "category_id" : 11
        }, {
          "category_id" : 212,
          "name" : "Produkty dla domu"
        }, {
          "category_id" : 362,
          "name" : "Marki"
        }, {
          "category_id" : 431,
          "is_parent" : true,
          "name" : "Motoryzacja"
        }, {
          "category_id" : 432,
          "is_parent" : true,
          "name" : "Kosmetyki samochodowe"
        }, {
          "category_id" : 433,
          "is_parent" : true,
          "name" : "NANOAUTO"
        } ],
        "status" : [ 1 ],
        "option_text_status" : [ "Enabled" ],
        "tax_class_id" : [ 6 ],
        "option_text_tax_class_id" : [ "Polska (standard 23%)" ],
        "short_description" : [ "<p style=\"text-align: justify;\">Profesjonalny produkt do pielęgnacji, nabłyszczania i konserwacji opon samochodowych przeznaczony jest zar&oacute;wno do opon jak i do gumowych element&oacute;w samochod&oacute;w i uszczelek. Produkt pozostawia na aplikowanych elementach warstwę ochronno-pielęgnującą, dzięki kt&oacute;rej gumowe elementy i opony zachowują swoje właściwości elastyczne na dłużej.</p>" ],
        "description" : [ "<p style=\"text-align: justify;\">Profesjonalny produkt do pielęgnacji, konserwacji oraz nabłyszczania opon samochodowych przeznaczony jest zar&oacute;wno do opon jak i do uszczelek oraz gumowych element&oacute;w samochodu. Składniki zawarte w produkcie sprawiają, że elementy, na kt&oacute;rych preparat był stosowany, chronione są warstwą pielęgnującą. Warstwa ta sprawia, że zar&oacute;wno opony jak i gumowe elementy samochodu zachowują na dłużej swoje właściwości elastyczne. Stosowanie produktu zimą zapobiega przymarzaniu drzwi do uszczelek. Preparat nadaje oponom efekt nowości i pogłębia ich kolor co przekłada się na atrakcyjność samochodu. Czysty i zadbany samoch&oacute;d jest wizyt&oacute;wką każdego kierowcy. Produkt do konserwacji i nabłyszczania opon samochodowych pomoże Ci zadbać o Tw&oacute;j samoch&oacute;d.<br /><br /></p>" ],
        "name" : [ "Preparat do pielęgnacji oraz konserwacji opon " ],
        "stock" : {
          "is_in_stock" : true,
          "qty" : 2
        }
      }
    } ]
  }
}
`

**Comment by romainruaud** [comment] 2017-08-31 13:01
Then your tags are here.

What does ``` curl -XGET 'localhost:9200/magento2*/product/_mapping?pretty' ``` give as an output ?

**Comment by madonzy** [comment] 2017-08-31 13:03
@romainruaud 
```
test@debian-8:~/www/distripark.dev$ curl -XGET 'localhost:9200/magento2_default_catalog_product_20170831_110239/product/_mapping?pretty'
{
  "magento2_default_catalog_product_20170831_110239" : {
    "mappings" : {
      "product" : {
        "_all" : {
          "enabled" : false
        },
        "properties" : {
          "attribute_set_id" : {
            "type" : "integer"
          },
          "autocomplete" : {
            "type" : "string",
            "fields" : {
              "shingle" : {
                "type" : "string",
                "analyzer" : "shingle"
              },
              "whitespace" : {
                "type" : "string",
                "analyzer" : "whitespace"
              }
            },
            "analyzer" : "standard"
          },
          "brand" : {
            "type" : "integer"
          },
          "category" : {
            "type" : "nested",
            "properties" : {
              "category_id" : {
                "type" : "integer"
              },
              "is_parent" : {
                "type" : "boolean"
              },
              "is_virtual" : {
                "type" : "boolean"
              },
              "name" : {
                "type" : "string",
                "norms" : {
                  "enabled" : false
                },
                "fielddata" : {
                  "format" : "disabled"
                },
                "copy_to" : [ "search", "spelling" ],
                "analyzer" : "standard"
              },
              "position" : {
                "type" : "integer"
              }
            }
          },
          "children_attributes" : {
            "type" : "string"
          },
          "children_ids" : {
            "type" : "integer"
          },
          "color" : {
            "type" : "integer"
          },
          "configurable_attributes" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "created_at" : {
            "type" : "date",
            "format" : "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd"
          },
          "description" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling", "autocomplete" ],
            "analyzer" : "standard"
          },
          "entity_id" : {
            "type" : "integer"
          },
          "has_options" : {
            "type" : "boolean"
          },
          "image" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling", "autocomplete" ],
            "analyzer" : "standard"
          },
          "manufacturer" : {
            "type" : "integer"
          },
          "name" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "fields" : {
              "shingle" : {
                "type" : "string",
                "norms" : {
                  "enabled" : false
                },
                "index_options" : "docs",
                "fielddata" : {
                  "format" : "disabled"
                },
                "analyzer" : "shingle"
              },
              "sortable" : {
                "type" : "string",
                "norms" : {
                  "enabled" : false
                },
                "index_options" : "docs",
                "analyzer" : "sortable"
              },
              "whitespace" : {
                "type" : "string",
                "norms" : {
                  "enabled" : false
                },
                "fielddata" : {
                  "format" : "disabled"
                },
                "analyzer" : "whitespace"
              }
            },
            "copy_to" : [ "search", "spelling", "autocomplete" ],
            "analyzer" : "standard"
          },
          "option_text_brand" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "fields" : {
              "untouched" : {
                "type" : "string",
                "index" : "not_analyzed"
              }
            },
            "copy_to" : [ "search", "spelling", "autocomplete" ],
            "analyzer" : "standard"
          },
          "option_text_color" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling", "autocomplete" ],
            "analyzer" : "standard"
          },
          "option_text_manufacturer" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling", "autocomplete" ],
            "analyzer" : "standard"
          },
          "option_text_reaction" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling", "autocomplete" ],
            "analyzer" : "standard"
          },
          "option_text_rozmiar" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling", "autocomplete" ],
            "analyzer" : "standard"
          },
          "option_text_smell" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling", "autocomplete" ],
            "analyzer" : "standard"
          },
          "option_text_status" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling", "autocomplete" ],
            "analyzer" : "standard"
          },
          "option_text_tax_class_id" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling", "autocomplete" ],
            "analyzer" : "standard"
          },
          "price" : {
            "type" : "nested",
            "properties" : {
              "customer_group_id" : {
                "type" : "integer"
              },
              "is_discount" : {
                "type" : "boolean"
              },
              "original_price" : {
                "type" : "double"
              },
              "price" : {
                "type" : "double"
              }
            }
          },
          "reaction" : {
            "type" : "integer"
          },
          "required_options" : {
            "type" : "boolean"
          },
          "rozmiar" : {
            "type" : "integer"
          },
          "search" : {
            "type" : "string",
            "fields" : {
              "shingle" : {
                "type" : "string",
                "analyzer" : "shingle"
              },
              "whitespace" : {
                "type" : "string",
                "analyzer" : "whitespace"
              }
            },
            "analyzer" : "standard"
          },
          "short_description" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "copy_to" : [ "search", "spelling", "autocomplete" ],
            "analyzer" : "standard"
          },
          "sku" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "smell" : {
            "type" : "integer"
          },
          "spelling" : {
            "type" : "string",
            "fields" : {
              "phonetic" : {
                "type" : "string",
                "analyzer" : "phonetic"
              },
              "shingle" : {
                "type" : "string",
                "analyzer" : "shingle"
              },
              "whitespace" : {
                "type" : "string",
                "analyzer" : "whitespace"
              }
            },
            "analyzer" : "standard"
          },
          "status" : {
            "type" : "integer"
          },
          "stock" : {
            "properties" : {
              "is_in_stock" : {
                "type" : "boolean"
              },
              "qty" : {
                "type" : "integer"
              }
            }
          },
          "tags" : {
            "type" : "string",
            "norms" : {
              "enabled" : false
            },
            "fielddata" : {
              "format" : "disabled"
            },
            "fields" : {
              "untouched" : {
                "type" : "string",
                "index" : "not_analyzed"
              }
            },
            "copy_to" : [ "search" ],
            "analyzer" : "standard"
          },
          "tax_class_id" : {
            "type" : "integer"
          },
          "type_id" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "updated_at" : {
            "type" : "date",
            "format" : "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd"
          },
          "visibility" : {
            "type" : "integer"
          }
        }
      }
    }
  }
}
```

**Comment by romainruaud** [comment] 2017-08-31 13:06
Hmm everything seems ok...

You got no result when searching for "samochodowa" or anything else you put into the tags ?

**Comment by madonzy** [comment] 2017-08-31 13:09
@romainruaud exactly! nothing shows...

**Comment by madonzy** [comment] 2017-08-31 19:49
@romainruaud do you have any ideas why it's not working? =/

**Comment by romainruaud** [comment] 2017-09-01 14:20
I reproduced it on my instance. Just adding ```isUsedInSpellcheck``` made it works for me : 

```
                <field name="tags" type="string">
                    <isSearchable>1</isSearchable>
                    <isUsedInSpellcheck>1</isUsedInSpellcheck>
                </field>
```

**Comment by madonzy** [comment] 2017-09-01 14:36
@romainruaud thanks, now it works!!

**Comment by romainruaud** [comment] 2017-09-01 14:37
Fine, then I close the issue,

Obviously, you can use the same way to add as much as "external" (ie non-attributes data) data as you wish.

**Closed by romainruaud** 2017-09-01 14:37 UTC
Labels: needs update, question
