### ISSUE TITLE
Partial search terms not returning any results

### ISSUE THREAD

**Issue by viiter** [Smile-SA/elasticsuite#472] opened 2017-07-20 07:35 UTC
When making a query for example "termomeeter" i get all the right results, but when looking for "term" i get nothing, why is that? i do have disabled fuzziness cause that messes up the results like searching for "tartu" returns results that have nothing to do or  contain anything related to "tartu"

### Preconditions
Magento Version : 2.1.7 CE
ElasticSuite Version : 2.3.0
Environment : production mode
Third party modules : no third party modules

### Steps to reproduce
1. create a product named "termomeeter"
2. reindex all the things
3. do a search for "term"

### Expected result
1. you get a result for the newly created "termomeeter" product
![screen shot 2017-07-20 at 10 24 05](https://user-images.githubusercontent.com/1838955/28405941-1b92b4c4-6d37-11e7-8d87-5e67b8628455.png)

### Actual result
1. nothing is returned
![screen shot 2017-07-20 at 10 24 25](https://user-images.githubusercontent.com/1838955/28405931-1505f3e6-6d37-11e7-9d54-a3c97c195b62.png)

**Comment by romainruaud** [comment] 2017-07-28 09:24
Hello, and thank you for submitting this issue.

However, this is a duplicate of #355 

Please check the detailed answer I gave to this one : https://github.com/Smile-SA/elasticsuite/issues/355#issuecomment-286831041

This is by design. That's as true as you won't find "jackets" on amazon when typing "jack" and pressing Enter.

Also, an additional examples on estonian (I guess you are from Estonia, right ?) website : 

http://www.hinnavaatlus.ee/search/?Type=products&Query=term&minPrice=&maxPrice=

=> "term" does not give termomeeter

**Note :** 

If you are using this module with estonian language, it may show inconsistency since there is no stemmer for estonian by default in Elasticsearch (see https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-stemmer-tokenfilter.html )

You may benefit of using this elasticsearch plugin : https://github.com/vhyza/elasticsearch-analysis-lemmagen

Best regards

**Closed by romainruaud** 2017-07-28 09:24 UTC
Labels: duplicate, wontfix
