### ISSUE TITLE
Request: Partial match on one word

### ISSUE THREAD

**Issue by eddetollenaer** [Smile-SA/elasticsuite#1036] opened 2018-08-15 11:19 UTC
### Preconditions
Magento 2.2.3 with the latest Elastic Suite version

Magento Version : Magento 2.2.3 Commerce Edition

ElasticSuite Version : 2.5.11

Environment : Production Mode

Third party modules : not applicable

### Steps to reproduce

1. Search on "stofzuiger"
2. No results are shown while there are a lot of products that have the name "robotstofzuiger" in it.

### Expected result

1. We expect to find all products that have "robotstofzuiger" in the name WITHOUT USING THE THESAURUS

### Actual result

1. No results are shown

Information for development:

It would be nice to make an option where you can say that if a word in the productname contains x% of the searchterm it should also be found as a result.

For instance:
The setting is: if 50% of a single word in the name of a product matches the search query, then show this product in the search results.

So, when you search on "stofzuiger",  products with the name "robotstofzuiger" in them will be shown on the results.

**Comment by shochdoerfer** [comment] 2018-08-16 08:07
This seems to be related to #597.

**Comment by romainruaud** [comment] 2018-08-20 15:37
Sorry but I'm not sure this is as easy as it looks, and it's not how we want to deal with the engine relevance.

"50% of a single word in the name of a product matches the search query".

Sounds good with your example stofzuiger/robotstofzuiger but I can find as many counter-examples as I want : 

if I search for a "hoe", should the search engine display "shoes" ? or display "pants" when someone is searching for "pan" ? and so on ...

In my opinion, you should use a synonym between stofzuiger and robotstofzuiger if the most common term used to find "robotstofzuiger" is "stofzuiger". This is a proper use case for using synonyms with Elasticsuite.

Regards

**Comment by shochdoerfer** [comment] 2018-08-21 08:14
@romainruaud does the synonym look work automatically when calling \Smile\ElasticsuiteCore\Model\Search::search()? Last time I tried it, it did not seem to work, but I was not able to debug it in-depth. Maybe some mis-configuration on my side...

**Comment by romainruaud** [comment] 2018-08-21 15:05
@shochdoerfer synonyms are triggered when using directly the Search model. Please create another issue if it's not the case on your instance, since this question is not related to current topic.

Regards

**Comment by romainruaud** [comment] 2018-08-24 15:14
I close since it's also a duplicate of #970

**Closed by romainruaud** 2018-08-24 15:14 UTC
Labels: duplicate, question, wontfix
