### ISSUE TITLE
Multiselect attribute unable to add options

### ISSUE THREAD

**Issue by berwa** [Smile-SA/elasticsuite#1275] opened 2019-01-21 09:27 UTC
### Preconditions
Magento Version : Commerce 2.2.7
ElasticSuite Version : 2.6.5 (and 2.6.4)
Environment : 
- PHP7.1
- Elasticsearch-version: 5
- Magento-modes: reproducible both in default and production

Third party modules : none (reproducible in plain installation e.g. with sample data)

### Steps to reproduce
1. Open product attribute administration in Magento backend 
2. Add new product attribute of type "Multiple Select", add options for that attribute
3. Save that attribute
4. Open details of newly created product attribute

### Expected result
Previously created attribute options are displayed

### Actual result
Attribute options are not displayed, and are not present in database

(Additional information: no error-message was found in any Magento- or system-log, none is displayed in Magento)

**Comment by romainruaud** [comment] 2019-01-21 14:36
Duplicate of #1248

**Closed by romainruaud** 2019-01-21 14:36 UTC
Labels: bug, duplicate
