### ISSUE TITLE
Virtual category: products don't show up when not sorted

### ISSUE THREAD

**Issue by arnoudhgz** [Smile-SA/elasticsuite#1454] opened 2019-07-03 11:03 UTC
When using a virtual category the products don't show when they are not manually sorted.

### Preconditions
Magento Version : 2.3.2
ElasticSuite Version : 2.8.0
Environment : Production and Developer

### Steps to reproduce
1. Create a virtual category
2. Assign products according rules
3. Only manual sort one product
4. Reindex `catalogsearch_fulltext`
5. Go to your category page
6. See that only the manual sorted product is shown

### Expected result
1. All products should be shown

### Actual result
1. Only manual sorted product is shown

### Tech hints
The data in _vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/CategoryData.php_ does not give the same data as _vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Controller/Adminhtml/Category/Virtual/Preview.php_

**Comment by arnoudhgz** [comment] 2019-07-03 13:30
Found a workaround solution for me: disabling the Magento_Elasticsearch* modules. 

This ElasticSuite package should however complement the Magento packages instead of conflicting.

**Comment by romainruaud** [comment] 2019-07-08 07:38
Thanks for submitting it @arnoudhgz 

Most probably, there is something that remain to be fixed with Magento 2.3.2.

Did you have the same behavior on Magento 2.3.1 ?

Regards

**Comment by arnoudhgz** [comment] 2019-07-08 08:21
No only occurred when upgrading to Magento 2.3.2 (which also contained a lot off changes provided by Smile ;) concerning the ElasticSearch implementation).

**Comment by romainruaud** [comment] 2019-07-08 09:48
Hmm... afaik all changes I made to Magento_ElasticSearch have been already merged into Magento 2.3.1. If something changed between 2.3.1 and 2.3.2 Smile was not involved.

I'll have a look on it anyway.

Regards

**Comment by romainruaud** [comment] 2019-07-08 13:54
Actually, I'm not able to reproduce this issue on Magento 2.3.2 and Elasticsuite 2.8.x **dev branch**.

For now, i'll consider this one as being fixed as part of our commitment to fix properly compatibility with Magento 2.3.2.

Can you test the 2.8.x branch on your environment and let us know if the issue is still happening (even when letting the Magento_Elasticsearch module enabled).

Regards

**Closed** 2019-07-23 14:05 UTC
Labels: needs update
