### ISSUE TITLE
Products with no "saleable quantity" shown on front end

### ISSUE THREAD

**Issue by lingwooc** [Smile-SA/elasticsuite#1476] opened 2019-07-19 20:27 UTC
### Preconditions

Debian stretch
Php 7.2
Docker
elasticsearch 6.8.1

Magento Version : 2.3.2

ElasticSuite Version : 2.8.1

Environment : Developer

Third party modules : None that affect inventory

### Steps to reproduce

1. Single inventory source. Decrease Stock When Order is Placed: Yes, Display Out of Stock Products: No
2. Setup a simple product with a stock of 1, in stock
3. Sell your bundle product but don't ship it yet.

### Expected result

1. Can't see the product on the frontend.

### Actual result

1. _Can_ see the product on the frontend.
2. Product shows as "in stock" on backend, quantity is 1, _but_ Default Stock : 0
3. Ship the product and it goes out of stock and quantity is 0.

I've tried reindexing, clearing caches etc. I wonder if this is related to the new MSI. This is a huge blocker for us so I'll attempt to narrow this down a bit more over the weekend.

**Comment by romainruaud** [comment] 2019-07-22 09:20
@lingwooc thank you for submitting this issue.

Could you please try reproducing it on a raw Magento without ElasticSuite ? I'm curious to check if it's only MSI related or if it's more linked to how ElasticSuite is proceeding with MSI data during reindex.

regards

**Comment by alinalexandru** [comment] 2019-08-07 12:31
I was able to reproduce on a Magento default without ElasticSuite.
It seems that the issue is from Magento with MSI.

**Comment by romainruaud** [comment] 2019-08-07 14:12
Great, so I close this one, please open a new issue directly on Magento MSI repository.

Regards

**Closed by romainruaud** 2019-08-07 14:12 UTC
Labels: needs update
