### ISSUE TITLE
No results if not an exact match

### ISSUE THREAD

**Issue by cctorres** [Smile-SA/elasticsuite#2600] opened 2022-06-09 21:18 UTC
Magento Version : 2.4.4 

ElasticSuite Version : 2.10

Environment : Dev/Prod

### Expected result
1. Get a suggestion list of products that have partial match with the input text string

### Actual result
1. Not getting any suggestion if there is not an exact match

**Comment by romainruaud** [comment] 2022-06-13 13:05
Hi @cctorres 

can you give a bit more details ?

Especially, what is the input text string, and what are the products you expect to see ? 

Regards

**Comment by romainruaud** [comment] 2022-06-16 13:32
The autocomplete works like this :

For now, autocomplete is "self-learning", according exactly to the scenario you describe.

First type, you type "send", no results, because it's unable to expand "send" to a previously used search term (that could be "senderos").

Once someone has already searched for "senderos", this record will be put (it's legacy Magento code here) in the search terms table, allowing to expand an user typing "send" to "senderos" search term, and retrieving associated results inside the autocompletion bar.

**Comment by cctorres** [comment] 2022-06-16 16:57
@romainruaud Thanks for answer. 

And there is any configuration to enable this features?

I tried to search "send" after find "senderos" product and there is not autocomplete yet.
https://postimg.cc/TpVFjBzk

I checked in the admin dashboard and it does appear that the word "sendero" and "senderos" were searched for previously.
https://postimg.cc/Hc1P72SG

**Comment by vahonc** [comment] 2022-06-23 17:03
Hello @cctorres,

I tried to reproduce your issue and I can confirm that what **Romain** explained above works.

The autocomplete "self-learning" feature is working from out of the box. 

As for searching "send" and "senderos" look at my screenshots:

![Screenshot from 2022-06-23 19-51-07](https://user-images.githubusercontent.com/67791361/175353264-ce7d2f29-c92b-4eb0-8504-958be0da6360.png)

![Screenshot from 2022-06-23 19-29-56](https://user-images.githubusercontent.com/67791361/175353307-5ef30705-e2fe-4e5f-ada0-f387a7e31353.png)

![Screenshot from 2022-06-23 19-30-24](https://user-images.githubusercontent.com/67791361/175353345-5c72c001-e222-4fbf-b9e7-3a9f26625b82.png)

![Screenshot from 2022-06-23 19-30-31](https://user-images.githubusercontent.com/67791361/175353378-d69f0db5-31ba-44a7-8d56-48ed91085643.png)

![Screenshot from 2022-06-23 19-49-09](https://user-images.githubusercontent.com/67791361/175353423-6aea0a86-1eac-49f8-a696-edc91e015a7f.png)

So as you can see all is working as we expected.

As for your issue please check if all caches are cleared. Maybe you have some third-party modules that might affect this.

Also, check the `Search Terms` configuration in the `Magento BO -> Marketing -> Search Terms` or provide this info for us.

![Screenshot from 2022-06-23 19-31-30](https://user-images.githubusercontent.com/67791361/175354549-fefef2c1-a115-476a-b8fc-21c2be61143a.png)

BR,
Vadym

**Comment by vahonc** [comment] 2022-06-24 07:42
@cctorres,

My screenshots from the last version of ElasticSuite (2.10.10), and fresh Magento 2.4.4 with default sample data.

Have you checked the `Search Terms` configuration in the `Magento BO -> Marketing -> Search Terms`? Provide this info for us.

Are you sure that you don't have any third-party modules that might affect this?

Also please provide an extract of the queries that are being sent to ES when you are searching for something on your site. You can get it from the `system.log` file if you activate the Debug mode for Elasticsuite in: `Stores -> Configuration -> Elasticsuite -> Base settings -> Elasticsearch Client -> Enable Debug Mode`.

BR,
Vadym

**Comment by cctorres** [comment] 2022-06-24 13:43
@vahonc Thanks!

So, This is the config for Search Terms 
![Screen Shot 2022-06-24 at 8 12 58 AM](https://user-images.githubusercontent.com/25993793/175548269-09ec6811-cc8e-421d-9c6e-86faa35304f5.png)

And here is the log from the query:
```
[2022-06-24T13:14:46.423867+00:00] logger.INFO: Request Success: {"method":"POST","uri":"http://127.0.0.1:9200/magento2_corporate_site_enus_usd_catalog_product/_search","port":"9200","headers":{"Host":["127.0.0.1"],"Content-Type":["application/json"],"Accept":["application/json"],"User-Agent":["elasticsearch-php/7.16.0 (Darwin 20.6.0; PHP 7.4.29)"],"x-elastic-client-meta":["es=7.16.0,php=7.4.29,t=7.16.0,a=0,cu=7.82.0"]},"HTTP code":200,"duration":0.004286} []
[2022-06-24T13:14:46.430386+00:00] logger.INFO: curl -XPOST 'http://127.0.0.1:9200/magento2_corporate_site_enus_usd_catalog_product/_search?pretty=true' -d '{"size":5,"sort":[{"_score":{"order":"desc"}},{"entity_id":{"order":"desc","missing":"_first","unmapped_type":"keyword"}}],"from":0,"query":{"bool":{"filter":{"bool":{"must":[{"terms":{"visibility":[3,4],"boost":1}},{"bool":{"must_not":[{"nested":{"path":"search_query","score_mode":"none","query":{"bool":{"must":[{"term":{"search_query.query_id":{"value":5981671,"boost":1}}},{"term":{"search_query.is_blacklisted":{"value":true,"boost":1}}}],"must_not":[],"should":[],"boost":1}},"boost":1}}],"boost":1}},{"terms":{"type_id":["grouped"],"boost":1}}],"must_not":[],"should":[],"boost":1}},"must":{"bool":{"must":[],"must_not":[],"should":[{"bool":{"filter":{"multi_match":{"query":"Senderos","fields":["search^1","sku^1"],"minimum_should_match":"100%","tie_breaker":1,"boost":1,"type":"best_fields"}},"must":{"multi_match":{"query":"Senderos","fields":["search^1","name.standard^5","sku.reference^6","option_text_theme.standard^3","author.standard^4","country_of_origin.standard^2","subtitle.standard^3","option_text_book_type.standard^3","isbn_no_dashes.standard^10","search.whitespace^10","name.whitespace^50","sku.whitespace^60","option_text_theme.whitespace^30","author.whitespace^40","country_of_origin.whitespace^20","subtitle.whitespace^30","option_text_book_type.whitespace^30","isbn_no_dashes.whitespace^100","name.sortable^100","sku.sortable^120"],"minimum_should_match":1,"tie_breaker":1.0,"boost":1,"type":"best_fields"}},"boost":1}}],"minimum_should_match":1,"boost":1}},"boost":1}},"track_total_hits":0}' [] []
```

**Comment by romainruaud** [comment] 2022-06-27 12:34
@cctorres how much search terms are configured to be suggested by the autocompletion ?

You can find this configuration in **Stores > Configuration > Elasticsuite > Autocomplete > Search terms**.

This should be higher than 0 for the autocomplete to suggest terms properly.

Since the "Senderos" term is on the search terms and "Suggested Terms = Yes", this should be suggested by the engine.

**Comment by cctorres** [comment] 2022-06-28 12:34
> @cctorres how much search terms are configured to be suggested by the autocompletion ?
> 
> You can find this configuration in **Stores > Configuration > Elasticsuite > Autocomplete > Popular Terms**.
> 
> This should be higher than 0 for the autocomplete to suggest terms properly.
> 
> Since the "Senderos" term is on the search terms and "Suggested Terms = Yes", this should be suggested by the engine.

This Worked. Thanks for all your time!!!

**Comment by vahonc** [comment] 2022-06-29 17:28
@cctorres,

Now that all questions are resolved, I suppose we can close this issue?

BR,
Vadym

**Closed** 2022-06-30 07:09 UTC
