### ISSUE TITLE
Color attribute issue

### ISSUE THREAD

**Issue by gewaechshaus** [Smile-SA/elasticsuite#195] opened 2016-11-09 19:02 UTC
Hey there,

@afoucret  - do you have an idea what is causing the limitation on the color attribute in the layered navigation right here:
https://eu.makerdise.com/3d-druck/filament.html

I tested all combinations related to this https://github.com/Smile-SA/elasticsuite/wiki/Attribute%20configuration

Maybe some problem with indexation? I will have to install the head plugin...

Regards
Jan

**Comment by afoucret** [comment] 2016-11-09 20:33
I need a clarification on what you mean by "the limitation on the color attribute". 
Are some colors missing in the facets ? That is how I understand this. Am I right ?

**Comment by gewaechshaus** [comment] 2016-11-09 21:37
Yes - all colors you can see in the listing underneath the product "PolyMax™ PLA" - except orange and white...

**Comment by afoucret** [comment] 2016-11-10 05:28
I fear, I did not understand. When I go to the page you have pointed me out, I get all colors available in the left col.

Whereas, here are a little memo on how the value are made available into the filters. 

* First there should be at least one produt matching the value in the result (concept of faceting)

* The facet is display only if the related attribute is present in at least 90% of the attribute sets of the result products set (the 90% treshold is configurable attribute by attribute with the facet coverage rate params of the attribute).

* For all attributes, we chose to display only a subset of available values (10 by defaut). There is an WIP rfc to display a "show more" button which extends the display (already available in branch 2.3.x) and an embedded search engine into the facet (WIP). This limit can be configured with the facet max size param of each attribute. Not sure if swatches attribute respect this tuning ... To be verified ...

Hope it's help. Let me know if the issue can be close or if it remains valid.

**Comment by gewaechshaus** [comment] 2016-11-10 08:32
Hey @afoucret 

here's how it is looking in my case...

<a href="http://www.xup.in/dl,56806687/color_elasticsuite.png/" target="_blank"><img src="http://www0.xup.in/exec/ximg.php?fid=56806687" border="0"></a>

**Comment by southerncomputer** [comment] 2016-11-10 13:53
![capture](https://cloud.githubusercontent.com/assets/6178967/20179251/288fd2cc-a723-11e6-8038-4c8d66ead806.PNG)

this is what I see from your link!

**Comment by afoucret** [comment] 2016-11-10 13:57
The same than @southerncomputer 

Maybe a problem occurring on another environnement (dev, staging, testing) ?
Are you sure all swatches images are present on the environment you are testing on ?

**Comment by southerncomputer** [comment] 2016-11-10 13:59
@afoucret The facet is display only if the related attribute is present in at least 90% of the attribute sets of the result products set (the 90% treshold is configurable attribute by attribute with the facet coverage rate params of the attribute). 
^^ is flawed since it is not recomputed always on facet/category select. 

//$this->logger->debug( "$currentCoverageRate $attributeCountCandidates $facetCoverageRate $totalCount \r\n");
/*[2016-11-02 16:01:06] report.DEBUG: 0.784698191011 6059 40 772144
[2016-11-02 16:01:06] report.DEBUG: 1.0091381918399 7792 40 772144
[2016-11-02 16:01:06] report.DEBUG: 0.20812180111482 1607 40 772144
[2016-11-02 16:01:06] report.DEBUG: 0.061258003688431 473 40 772144
[2016-11-02 16:01:06] report.DEBUG: 0.060480946559191 467 40 772144
[2016-11-02 16:01:06] report.DEBUG: 0.024347790049524 188 40 772144
[2016-11-02 16:01:06] report.DEBUG: 0.018519861580223 143 40 772144

It may be due to caching?

**Comment by gewaechshaus** [comment] 2016-11-10 14:36
Hmmm. I did rm -rf on all related folders, cleaned every different testing clients cache, but can't see all colors. So maybe it's related to default and non-default website id's or due tue misconfiguration in one case...

It's the same environment for both domains...

**Comment by afoucret** [comment] 2016-11-10 15:24
@southerncomputer : I can see the coverage rate varying between 1% and 0.01% in your example. I have tested on my own environment and all variables show expected values ($currentCoverageRate $attributeCountCandidates $facetCoverageRate $totalCount).

Quite sure there is no bug there (and no caching !!!).

**Comment by southerncomputer** [comment] 2016-11-10 15:29
I would consider the cataloginventory scope as it provided problems for me:
  public function loadInventoryData($storeId, $productIds)
    {
        $websiteId = $this->getWebsiteId($storeId);
        $stockId   = $this->getStockId($websiteId);

        $select = $this->getConnection()->select()
            ->from(['ciss' => $this->getTable('cataloginventory_stock_status')], ['product_id', 'stock_status', 'qty'])
            ->where('ciss.stock_id = ?', $stockId)
//            ->where('ciss.website_id = ?', $this->stockConfiguration->getDefaultScopeId())
            ->where('ciss.product_id IN(?)', $productIds);

        return $this->getConnection()->fetchAll($select);
    }

notice I had to comment out : 
//            ->where('ciss.website_id = ?', $this->stockConfiguration->getDefaultScopeId())

Since stock is computed from another table and is equal for all of my websites, I found this caused problems with one of my configuration upgrade from 2.0.x versus fresh install - the scopes were not the same!

You can check other tables to verify your scope is applied consistently throughout the tables using mysql simple commands. I found my import utility didn't care about a certain index that Magento cares about in 2.1.2 only which further confused the situation!

**Comment by afoucret** [comment] 2016-11-10 15:32
@southerncomputer : I can see any relationship between your last response and this issue. A mistake ?

**Comment by southerncomputer** [comment] 2016-11-10 16:22
If cataloginventorystock_stock_status.website_id <> getDefaultScopeId()) - then you will skip indexing objects for the website, which can reduce the number of attributes indexed!

**Comment by gewaechshaus** [comment] 2016-11-12 12:18
Any news here?

**Comment by romainruaud** [comment] 2016-11-14 10:56
Hello @southerncomputer and @gewaechshaus , do you have any idea why the getDefaultScopeId would result a "wrong" scope Id ? Did you use a custom module to manage the inventory ? Or a custom configuration ?

Regards,

**Comment by southerncomputer** [comment] 2016-11-14 19:01
When I upgraded from Magento 2.0 to 2.1 - something caused the scope to reflect a different number but since Magento 2 cannot have separate inventory right now, does the query make any sense?

**Comment by gewaechshaus** [comment] 2016-11-15 11:04
@romainruaud 

> Did you use a custom module to manage the inventory ? 

No. But we got M2E running which affects it in theory.
https://github.com/m2epro/magento2-extension

> Or a custom configuration ?

It's just a multisite setup

**Comment by afoucret** [comment] 2016-11-15 13:29
@gewaechshaus : 
Yes M2E extension can have side effects on this.
As it is not a standard Magento setup we do not support it.

@southerncomputer :
I don't remember well why we append this filter but I think it is related to the ability to manage or not the stock on a website basis. Imagine, you have a product with two websites. On one website the stock is managed and on the other it is not. The index will be different ... I will confirm it when I will have more time to investigate on this one.

**Comment by southerncomputer** [comment] 2016-11-15 13:57
@afourcet https://github.com/magento/magento2/issues/7090
is what i reference.

**Comment by southerncomputer** [comment] 2016-11-21 15:01
select website_id,count(website_id) from cataloginventory_stock_status group by website_id;
+------------+-------------------+
| website_id | count(website_id) |
+------------+-------------------+
|          0 |            772147 |
+------------+-------------------+
1 row in set (0.18 sec)

 select website_id,count(website_id) from catalog_product_website group by website_id;
+------------+-------------------+
| website_id | count(website_id) |
+------------+-------------------+
|          1 |            772144 |
+------------+-------------------+
1 row in set (0.16 sec)

How does your mysql look?

**Comment by romainruaud** [comment] 2016-11-28 16:49
@southerncomputer is right : Something has changed into Magento between 2.0.x and 2.1.x

Magento 2.0 : 

```
mysql> select website_id,count(website_id) from cataloginventory_stock_status group by website_id;
+------------+-------------------+
| website_id | count(website_id) |
+------------+-------------------+
|          1 |              2046 |
+------------+-------------------+
```

Magento 2.1 : 

```
mysql> select website_id,count(website_id) from cataloginventory_stock_status group by website_id;
+------------+-------------------+
| website_id | count(website_id) |
+------------+-------------------+
|          0 |              2047 |
+------------+-------------------+

```

But I'm still not sure this could be related to this bug.

@gewaechshaus can you check how is looking your "PolyMax PLA" product into the Elasticsearch index and post it here ?

Regards,

**Comment by romainruaud** [comment] 2016-12-14 11:40
@gewaechshaus can you provide any update ? 

Since you are the only one to face this issue, and having not responding to this thread since 2 weeks, we may close this issue soon if we do not have new elements from your side.

Best regards

**Comment by gewaechshaus** [comment] 2016-12-19 12:46
@romainruaud - sorry for the delay, I was kind of busy. 

The issue finaly disappeared after a setup:static-content:deploy and a shell based reindex...

**Comment by afoucret** [comment] 2016-12-23 11:55
Good news. We are closing for now. Feel free to reopen if the problem is not really solved in the future.

**Closed by afoucret** 2016-12-23 11:55 UTC
