### ISSUE TITLE
Tracking turned off, tracking indices still being created

### ISSUE THREAD

**Issue by Thertor** [Smile-SA/elasticsuite#1691] opened 2020-02-05 09:36 UTC
### Preconditions

Magento Version : Magento 2.3.1 Communitry Edition and Magento 2.3.2 Enterprise

ElasticSuite Version : 2.8.2

Environment : Production mode

Elasticsearch: 6.8+

### Steps to reproduce

1. Setup elasticsuite
2. Set tracking in the module to false
3. Let people do search etc
4. Tracking indices are still created and updated

### Expected result

1. Tracking indices shouldn't be created and update

### Actual result
1. Tracking indices are created and updated

This has happened with several of our M2 customers now, on different versions of Magento, the two best examples are both running the same elasticsuite version.

**Comment by rbayet** [comment] 2020-02-06 14:44
Hello @Thertor,

Strange, this looks like #1252 (fixed in 2.6.6 and 2.7.4) is back ...
Are you sure that events dating from **after** the tracking is disabled end up in new Elasticsearch indices ?
This could be previous events clogging the DB storage table.

Regards,

**Comment by Thertor** [comment] 2020-02-07 06:42
Yes, the tracking was never enabled in the first place before I added these two to the ES cluster.

**Comment by rbayet** [comment] 2020-02-24 14:56
Hello @Thertor,

Sorry, I cannot reproduce your issue in 2.8.2 or 2.8.4.
**Once disabled**, the tracker does not collect any new event, ie no new record is added to table `elasticsuite_tracker_log_event`.

On the other hand, as stated, if you still had some events dating from right before disabling the tracker in Stores > Configuration > Elasticsuite > Tracking, then any cron:run execution will indeed index those remaining events in the Elasticsearch server.
Hence my remark about 
> This could be previous events clogging the DB storage table.

We could probably decide not to index them at all and let them be in the storage DB table.

Something that bothers me, you say 

> Yes, the tracking **was never enabled in the first place** before I added these two to the ES cluster.
The tracking is enabled by default when installing the module, so it does not need to be explicitely enabled.
Were you saying that **you had taken extra steps to make sure the tracking was disabled** before deploying ?

Regards,

**Closed** 2020-03-10 15:25 UTC
Labels: bug, needs update
