### ISSUE TITLE
Invalid category count while filtering

### ISSUE THREAD

**Issue by madonzy** [Smile-SA/elasticsuite#568] opened 2017-10-18 08:47 UTC
### Preconditions

Magento Version : 2.1.9

ElasticSuite Version : 2.3.8

Environment : Developer

Third party modules : -

### Steps to reproduce

1. Open catalog page
2. Filter by any attribute

### Expected result

1. Categories have the numbers near titles, and I expect this numbers to be really valid number amount of products if I choose this category.

### Actual result

1. The numbers don't change at all when I select different filters.
<img width="1210" alt="screen shot 2017-10-18 at 10 41 00 am" src="https://user-images.githubusercontent.com/5281020/31709233-b5a6c7de-b3f1-11e7-935d-6b0da9d1a712.png">
<img width="1354" alt="screen shot 2017-10-18 at 10 41 20 am" src="https://user-images.githubusercontent.com/5281020/31709235-b5c0d912-b3f1-11e7-8836-b55d35e2604f.png">
<img width="1320" alt="screen shot 2017-10-18 at 10 41 55 am" src="https://user-images.githubusercontent.com/5281020/31709236-b5e2d206-b3f1-11e7-8fe4-69b707e4143d.png">

**Comment by afoucret** [comment] 2017-10-18 09:05
IMHO, this is not really a bug but more how it is working by design.

When selecting a category filters are reset. So the number of product displayed is consistent with what will happen when clicking on the filter.

As explained in #263, we will not change this default behavior since there is a lot of website already using ElasticSuite and we do not want to break backward compatibility (changing the behavior when updating). Maybe we will add a config in the future ...

I close the issue as being a duplicate of #263.

**Closed by afoucret** 2017-10-18 09:05 UTC
