### ISSUE TITLE
Add support searching by product.id (aka product code)

### ISSUE THREAD

**Issue by Koc** [Smile-SA/elasticsuite#511] opened 2017-08-23 15:10 UTC
### Preconditions

Magento Version : 2.1.8

ElasticSuite Version : 2.3.x

Environment : PHP 7.0.21

Third party modules : -

### Steps to reproduce

1. add some products via admin
2. search `1234` (product id)
3.

### Expected result

1. expected got product with `entity_id=1234` on top of the list

### Actual result

1. no any products found

We are using "products codes" when talking with customers by phone. Product code is just product id separated with dash by 3 digit (`1-234`). I've tryed search `1-234` or `1234` and always got 0 results.

As I understand correctly - we can create new attribute `product_code` used in search, add observer on product save after and programatically update value of this attribute. And add optimizer for this attribute.

But what about providing sollution out of the box? Similar to #412

**Comment by afoucret** [comment] 2018-01-04 08:16
Hi @Koc 

Cleaning since you are saying duplicate of #412 that is now closed.

Feel free to reopen and give us more precision if needed.

**Closed by afoucret** 2018-01-04 08:16 UTC
Labels: enhancement, feature
