### ISSUE TITLE
[Suggestion] Add statement if no alive nodes found

### ISSUE THREAD

**Issue by bmxmale** [Smile-SA/elasticsuite#507] opened 2017-08-22 11:08 UTC
### Preconditions

When elasticsearch node is not available on search request we getting exception

1 exception(s):
Exception #0 (Elasticsearch\Common\Exceptions\NoNodesAvailableException): No alive nodes found in your cluster.

In my opinion in this case module should auto disable and back to MySQL search.

Magento Version : 2.1.7

ElasticSuite Version : 2.3.6

Environment : developer/production

Third party modules :

### Steps to reproduce

1. Disable elasticsearch node
2. Try to search any word

### Expected result

1. Search page work even node is dead.

### Actual result

1. [Screenshot, logs]

![image](https://user-images.githubusercontent.com/23213308/29562768-f613d5fc-873a-11e7-941d-69b234bdbfdf.png)

**Comment by romainruaud** [comment] 2017-08-22 13:23
Hello @bmxmale 

Unfortunately, this is not possible to auto-disable the module in such a case.

This is by design, ElasticSearch is a mandatory piece of the application, as MySQL is. Try to run Magento with MySQL server disabled, you will have a fatal error saying the database is not reachable.

We consider the search engine as a vital part of an Ecommerce website. Especially when using Elasticsearch, which is easy to make redundant and fault tolerant.

Also, please consider that auto-disabling the module would imply to do all the following things : 

- This would implie having a MySQL Fulltext index properly rebuilt and "ready to use" in case of failure, which would lead to rebuild this index at the same time we rebuild the Elasticsearch index. This is not suitable especially for large catalogs since the MySQL fulltext index is known to have poor performances.

- Additionnally, "auto disabling" the module would also imply that all layouts/templates are disabled, and also anything injected via the DI, meaning you had to process the compiling again when running on production. You may also loose anything you built on top of ElasticSuite blocks, models and templates.


I close this issue,

Best regards

**Closed by romainruaud** 2017-08-22 13:23 UTC
